### ISSUE TITLE
Can this be accomplished by NGXS.

### ISSUE THREAD

**Issue by daBishMan** [ngxs/store#100]
The use case i have assume I have history of the user interactions and I use the url to record the search params the user entered, for example

``http://localhost:4200/history;sortBy=dateViewed;sortByDirection=desc;page=1;pageSize=20;rated=0,1``

Assume the user, bookmarked the page and comes back again, I want to be able to populate my state search param from the url, and execute the search.

What is the appropriate way to handle this in ngxs?

**Comment by amcdnl** [comment]
I would call this a URL State Deserializer. I do this manually in a app I have that uses NGRX. 

Could easily create a event handler that watches route change and use this https://www.npmjs.com/package/query-string and then trigger a state change event.

**Comment by amcdnl** [comment]
Closing this. Let me know if you have other questions.
