### ISSUE TITLE
[Request] Enhance Documentation regarding Action Lifecycle

### ISSUE THREAD

**Issue by cuddlecake** [ngxs/store#1004]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

There is barely any information regarding the Action Lifecycle.

There is only mention about which phases are available (dispatched, successful, unsuccessful, completed, etc.), and some further documentation on how to cancel actions (but no mention that this affects the Action Lifecycle).

## What is the motivation / use case for changing the behavior?

I have only found out through trying out, that actions are errored when one of the reducers associated with the action either throw an Error or return an Error Observable.

**Comment by splincode** [comment]
it will be very cool if you send us a pull request

**Comment by cuddlecake** [comment]
I will try to, but I can't say when.

**Comment by splincode** [comment]
Released in 3.5.0
