### ISSUE TITLE
Incorrect Aria Attributes on Tabs

### ISSUE THREAD

**Issue by internalsystemerror** [ngxs/store#1012]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using the tabset, the ul has a role of tabset and the a elements within the li's have a role of tab.

## Expected behavior

No roles are assigned to lists.

## Minimal reproduction of the problem with instructions

* Create project using tabset

## What is the motivation / use case for changing the behavior?

This is incorrect Aria behaviour and fails a Google Lighthouse test. See documentation: https://getbootstrap.com/docs/4.3/components/navs/#regarding-accessibility as to why this should be removed.

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.13
- @ngxs/store version: 3.4.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.15.0  
- Platform:  Windows

Others:

</code></pre>

**Comment by splincode** [comment]
how is this related to NGXS?

**Comment by internalsystemerror** [comment]
... my sincere apologies ... too many open tabs :/
