### ISSUE TITLE
Karma errors

### ISSUE THREAD

**Issue by splincode** [ngxs/store#1014]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[x] Other... Please describe:
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/12021443/56467912-cef55000-642d-11e9-84d2-a0f1cac669ff.png)

**Comment by markwhitfeld** [comment]
Closed because we have moved to using `jest` (See PR #1068)
