### ISSUE TITLE
State operators: patch expected ';' error TS1005 

### ISSUE THREAD

**Issue by haacki47** [ngxs/store#1043]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
My console shows errors when `ng serve` application

```
ERROR in node_modules/@ngxs/store/operators/patch.d.ts(6,36): error TS1005: ';' expected.
node_modules/@ngxs/store/operators/patch.d.ts(6,70): error TS1005: ';' expected.
node_modules/@ngxs/store/operators/patch.d.ts(7,1): error TS1128: Declaration or statement expected.
```
WebStorm highlight errors with types in file `patch.d.ts`

<img width="1051" alt="Screen Shot 2019-05-09 at 16 53 21" src="https://user-images.githubusercontent.com/14221550/57459147-525ed000-727b-11e9-8f37-574755074ba9.png">

## Environment

<pre><code>
Libs:
- "@angular/core": "6.1.3",
- "@ngxs/store": "3.4.3"

For Tooling issues:
- Node version: 8.12.0  
- Yarn version: 1.9.4 
- Npm version: 6.4.1
- Typescript version: 2.7.2
- Platform: Mac  
</code></pre>

I'm using patch operator to mutate state properties.

```typescript
export function AddRole(role: Role): StateOperator<AssignRolesEditStateModel> {
    return patch<AssignRolesEditStateModel>({
        employee: patch<AssignedEmployee>({
            roles: insertItem<string>(role.title)
        })
    });
}

export function RemoveRole(role: Role): StateOperator<AssignRolesEditStateModel> {
    return patch<AssignRolesEditStateModel>({
        employee: patch<AssignedEmployee>({
            roles: removeItem<string>(title => title === role.title)
        })
    });
} 

```

**Comment by markwhitfeld** [comment]
Could you upgrade your typescript to v2.8 to see if this fixes the issue.
Restart your ide after the upgrade.
I think that TS 2.8 is a minimum required version for the `@ngxs/store/operators` sub package.

**Comment by haacki47** [comment]
@markwhitfeld yeah, issue with typescript version, I installed version `2.8.4`. 

Thanks!
