### ISSUE TITLE
Using selector in external class doesn't work in AOT

### ISSUE THREAD

**Issue by Wykks** [ngxs/store#1050]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

````
  @Select(FooSelectors.bar) bar$: Observable<boolean>;
````

I'm putting `FooSelectors.bar` in an external file (because my state is quite big), and this select simply doesn't work in AOT.

## Expected behavior

It should works in AOT

## Minimal reproduction of the problem with instructions

Try this, in AOT:
````
export class FooSelectors {
  @Selector([FooState])
  static bar(state: FooStateModel) {
    return state.bar;
  }
}
````

If you move the Selector back to the State class, it works in AOT.

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.13
- @ngxs/store version: 3.4.3

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [X] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Wykks** [comment]
Actually this happens when you use selectors in the state (Circular ref). Be it should be fine, since there's only static method...

TIL, when you use an external file for selectors, you cannot use them in actions of the (corresponding) state unless you also split actions in a other file.

**Comment by Wykks** [comment]
Actually, I don't have a clean solution for this. How do you separate action implementation from the state ?

Using selector of the state in the actions of the same state is needed when the selector do a lot of work, so I cannot just read the state with getState. I _have to_ use `selectSnapshot` in actions.

**Comment by splincode** [comment]
@Wykks give an example of the code you need

**Comment by Wykks** [comment]
Sure!

foo.selectors.ts
```
export class FooSelectors {
  @Selector([FooState])
  static bar(state: FooStateModel) { // Let's assume this selector is heavy
    return state.bar;
  }
}
```

foo.state.ts
```
export interface FooStateModel {
  bar: boolean;
}

@State<FooStateModel>({
  name: 'foo',
  defaults: {
    bar: false
  }
})
export class ConnectiveDeviceState {
  constructor(private store: Store) { }

  @Action(DoStuffAction)
  setMode(ctx: StateContext<FooStateModel >, action: DoStuffAction) {
    const bar this.store.selectSnapshot(FooSelectors.bar); // This doesn't work in AOT (but OK in JIT)
    [...]
  }
}
```

**Comment by arturovt** [comment]
@Wykks 

The problem that you've described is not reproducing. The last example that you showed:

```ts
const bar = this.store.selectSnapshot(FooSelectors.bar); // This doesn't work in AOT (but OK in JIT)
```

Cannot work in JIT because it's not compiling due to circular dependency (I just copied all code).

But
> Using selector in external class

works for me. I just put my screens here:

![image](https://user-images.githubusercontent.com/7337691/58129371-43383480-7c22-11e9-9f80-b160897af2a8.png)

![image](https://user-images.githubusercontent.com/7337691/58129390-4c290600-7c22-11e9-8e78-3972d4d20169.png)

![image](https://user-images.githubusercontent.com/7337691/58129410-54814100-7c22-11e9-85cd-c3dcc80b7a8f.png)

![image](https://user-images.githubusercontent.com/7337691/58129603-c0fc4000-7c22-11e9-972d-fbc555f20360.png)

What am I missing?

**Comment by Wykks** [comment]
Hi! Thanks for taking the time on this issue! I haven't exactly tested my minimal repro (because in my app, AOT started working as soon as I removed the selector call in the state class, and JIT was working fine). 

I'll try to make a full repro repository asap!

**Comment by arturovt** [comment]
Any progress on this?

**Comment by arturovt** [comment]
Closing it as inactive, will reopen when reproduction appears.
