### ISSUE TITLE
doc :  store.dispatch return Observable<fullState> not Observable<void>

### ISSUE THREAD

**Issue by gpeel** [ngxs/store#1083]
On page 
https://ngxs.gitbook.io/ngxs/concepts/store

The Observable that a dispatch returns has a void type, this is because there can be multiple states that listen to the same @Action, therefore it's not realistically possible to return the state from these actions since we don't know the form of them.

When testing 
    this.store.dispatch(new CRUD_ACTIONS.CreateTask(task))
      .subscribe(s => console.log(s));

In param "s" I receive the full State.

If you confirm that, the doc should be updated to state something like 

The Observable that a dispatch returns has a void any,  and contains the the full State object instance.

**Comment by splincode** [comment]
https://github.com/ngxs/store/issues/827

Observable<fullState> is deprecated
https://github.com/ngxs/store/issues/827
