### ISSUE TITLE
New features with @SelectOnce() @SelectSnapshot()

### ISSUE THREAD

**Issue by gpeel** [ngxs/store#1084]
## I'm submitting a...
[x ] Feature request

## Current behavior

AT the time we have : @Select()
And on the store we have the very convenient API : 

store.select()
store.selectOnce()
store.selectSnapshot()

## New desired behavior
It would be great to have 

@SelectOnce()
and
@SelectSnapshot()

with the same meaning

**Comment by arturovt** [comment]
We already have `@SelectSnapshot` - https://github.com/ngxs-labs/select-snapshot

`@SelectOnce` is not planned.

**Comment by splincode** [comment]
Use https://github.com/ngxs-labs/select-snapshot

**Comment by gpeel** [comment]
Thanks for the link to @SelectSnapshot()
@SelectOnce()  has also its place, 
for example in Resolver and Guard where you need to have a complete.

So why not ?
It does not seem complicated to code once @Select() is done ...

**Comment by arturovt** [comment]
@gpeel 

Not complicated. But we try not to burden the core library with unused functionality (most our users were asking for the `@SelectSnapshot`, that's why we're experimenting with it now). `@SelectOnce` doesn't seem to be beneficial IMHO.

In resolver or guard you can use `@SelectSnapshot` :relaxed:

**Comment by gpeel** [comment]
yes you are right, its not the good example.  
@SelectSnapshot is more useful.  Hope it will be integrated soon.

**Comment by Z3SA** [comment]
@arturovt @splincode What about `@SelectOnce` decorator as ref to stream of store's part with `pipe(take(1))` without `Store` inject? I think this decorator can exist as NGXS Labs project as `@SelectSnapshot` decorator.

**Comment by markwhitfeld** [comment]
@Z3SA Please could you motivate for this using some use cases that you think it would be used where neither `@Select` or `@SelectSnapshot` would be suitable? Thanks!

**Comment by Z3SA** [comment]
@markwhitfeld I suppose that @Select creates stream with unlimited lifecycle of Observable. And @SelectSnapshot returns current state of store, but there can be troubles if store or state with selector isn't ready at moment of request. So, what I should do if I need selector with only one value, not unlimited stream, and store may not be ready at this moment?

**Comment by arturovt** [comment]
@Z3SA This case that you've described is not suitable for select once. There is no such thing as "isn't ready at momemt" or "store may not be ready". Store is always ready :stuck_out_tongue_closed_eyes: . I'm explaining why. Each state has a default value. So if you've got a state with the `null` default value (`defaults: null`) then the `selectOnce` will not solve your issue, as the `selectOnce` is a sugar over `select + take 1`. You will need to use `first` with condition (`first(s => state !== null)`) or something similar. This example is just for demonstrating purposes :wink:

**Comment by Z3SA** [comment]
@arturovt alright, I understood about situation when state data not ready. But I'm told about whole state container (instance of class with @State). It's possible in NGXS?
