### ISSUE TITLE
@Selector() not working when inheriting from a parent @State

### ISSUE THREAD

**Issue by joaqcid** [ngxs/store#1108]
## I'm submitting a...
<pre><code>[ X ] Bug report</code></pre>

## Current behavior
When inheriting from a Parent @State class with a @Selector, using that selector on child @State class doesnt return the store value

## Expected behavior
Child @State should return the value of the selected value via the @Selector method in its parent class

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/ngxs-inherit-selector-issue-1108

* Step 1
* Step 2
* Step 3

## What is the motivation / use case for changing the behavior?
N/A

## Environment

<pre><code>
Libs:
N/A

Browser:
N/A
 
For Tooling issues:
N/A

Others:
N/A
</code></pre>

**Comment by joaqcid** [comment]
One thing i noticed is that if i add the parent `@State` to the `AppModule` it works, but the behavior is not the desired. In this case both parent and child state have the same state.
I wonder if i what i want to do is possible or not…

**Comment by arturovt** [comment]
I'm sorry, maybe I'm missing something, but what behavior do you expect if you don't add the `CountState` when calling `forRoot`? We can't manually add this state to the root DI providers.

**Comment by joaqcid** [comment]
The behaviour expected is to able to inherit selectors from base abstract classes, to avoid duplicated selectors, for instance for "loading" @selector

**Comment by splincode** [comment]
Yes, I noticed this problem and it needs to be solved

**Comment by arturovt** [comment]
@joaqcid 
You use a selector from the non-imported class:
```ts
@Select(CountState.count) count$: Observable<number>;
```

**Comment by joaqcid** [comment]
yeah, i think i was testing with both states, just updated it, you can see it doesnt work, even if use `ChildCountState.count`

**Comment by arturovt** [comment]
You could just write `ChildCountState` except of `CountState` cause I got confused haha :joy:

**Comment by MuhammadRizwanBashir** [comment]
@arturovt  Hi,
Is it going to be resolved? If yes then please mark it as bug or feature as you see it. So we can follow this.
Thanks

**Comment by joaqcid** [comment]
Hi!

After reading more the documentation, found i can actually do this with dynamic selectors

```
export abstract class CountState {
  static get count() {
    return createSelector([this], (state: CountStateModel) => {
      return state.count
    })
  }
}
```

Updated the stackblitz with working code

**Comment by splincode** [comment]
You can send us a pull request for updating documentation.

**Comment by splincode** [comment]
@joaqcid we can close?

**Comment by joaqcid** [comment]
yup
