### ISSUE TITLE
Reload page using NgxsLocalStoragePluginModule

### ISSUE THREAD

**Issue by mailok** [ngxs/store#111]
When I reload the page with F5, not load the saved state in localStorage, my configuration is:

```
NgxsLocalStoragePluginModule.forRoot({
      key: '@@STATE',
      storage: localStorage,
      deserialize: JSON.parse,
      serialize: JSON.stringify,
    })
```

**Comment by labs-scnm** [comment]
@mailok is my [example app](https://stackblitz.com/edit/ngxs-localstorage) (#122) represent also our issue?

**Comment by mailok** [comment]
Yes I think so

**Comment by mailok** [comment]
@labs-scnm Yes I think so

**Comment by deebloo** [comment]
ok cool since there is more info there I am going to close this in favor of that

**Comment by deebloo** [comment]
closing in favor of #122
