### ISSUE TITLE
dynamic selector with createSelector

### ISSUE THREAD

**Issue by goodbeysr** [ngxs/store#1110]
## I'm submitting a...

<pre><code>
[ ] Bug report 
</code></pre>

## Current behavior

In my application a have multiple states, when i try to use a dynamic selector it returns the whole app state.

static dynamicSelectorFromState1(type: string) {
    return createSelector([PartState1], (state: PartStateModel1) => {
      console.log(state)
      return _.get(state,'someAttr',someValue)
    });
 }

it consoles log the whole app state.

## Expected behavior
createSelector should slice the app state and return only a part of it.

 instead of logging : {
PartState1,
PartState2,
PartState3,
..
}

it should only log PartState1

## Environment

<pre><code>

Libs:
- @angular/core version: 7.3.8
- @ngxs/store version: lastest

Browser:
- [ ] Chrome (desktop) version 74.0.3729.169
 
For Tooling issues:
- Node version: 10.8.0
- Platform:  Windows

</code></pre>

**Comment by splincode** [comment]
please create stackblitz for reproduce

**Comment by goodbeysr** [comment]
here is the link below:
https://stackblitz.com/edit/angular-kmqm44

**Comment by arturovt** [comment]
@goodbeysr 

This is not a bug as you're decorating static method with `@Selector`. Remove `@Selector` decorator and it will work.
