### ISSUE TITLE
createSelector creates a memory leak

### ISSUE THREAD

**Issue by ralphbert** [ngxs/store#1116]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
I created a very simple store containing a dynamic selector (`completed`) created with the `createSelector`-function.

When I am using the selector it creates a memory leak when used like: 
`this.store.select(AppState.completed(isComplete)).subscribe...`

## Expected behavior

The dynamic selector should free all allocated resources when unsubscribed.

## Minimal reproduction of the problem with instructions

This project contains a `TodoListComponent` which subscribes to a dynamic selector within a `switchMap` depending on the desired status (incomplete/complete) of the todos:
https://stackblitz.com/edit/ngxs-memory-leak

1. Download the stackblitz project and run it on your local machine. If you run it on stackblitz you won't be able to inspect the `heap snapshot` properly.
2. This project contains a `TodoListComponent` which subscribes to a dynamic selector within a `switchMap` depending on the desired status (incomplete/complete) of the todos.
3. Start the app and directly create a `heap snapshot`.
4. Search for `TodoListComponent`. There should be 0
5. Press the `Destroy/Create todo list` once. The dynamic selector is not yet executed. Execute the garbage collector and create a `heap snapshot` again and verify that there is only one `TodoListComponent` created.
6. Press the `Destroy/Create todo list` button again. Create a `heap snapshot` again and verify that there is no `TodoListComponent` allocated.

Until here everything works as expected.
Now do the following:

7. Press `Destroy/Create todo list` and then press one of the two buttons several times: `show completed todos` or `show todos`. Each button click creates a dynamic selector with a `switchMap`, unsubscribing any previous dynamic selector.
8. Now press `Destroy/Create todo list`, execute the garbage collector and take a `heap snapshot` again. You should now see that the `TodoListComponent` is not released correctly even though all subscriptions are completed and resolved properly.

## Environment

<pre><code>
Libs:
- @angular/core version: 8.0.0
- @ngxs/store version: 3.4.3

Browser:
- [x] Chrome (desktop) version 74.0.3729.169
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.4.1  
- Platform: macOS 10.14.5 
</code></pre>

**Comment by arturovt** [comment]
This is not a memory leak as your `takeUntil` should go after `switchMap()`, not before

**Comment by ralphbert** [comment]
Sadly, this does not solve the issue

**Comment by arturovt** [comment]
Could you just shortly describe your question? Because there are 8 instructions and I don't understand which one is a real question :joy:

**Comment by ralphbert** [comment]
The TL;DR: 
When you use a dynamic selector (created with `createSelector`) it does stay in the memory, even when the component that uses it is destroyed (and the component stays in the memory too).

Use my steps to reproduce the error.

**Comment by arturovt** [comment]
Before I went through all those instructions as I'm not nearby PC, component actually should stay in memory. Angular doesn't release resources, only invokes `ngOnDestroy`. The component wouldn't stay in memory immediately only if Angular assigned instance to `null` like:
```TS
if (shouldCallNgOnDestroy) {
  instance.ngOnDestroy();
}
instance = null;
```
If you explicitly run garbage collection - it doesn't mean that it will remove the component instance from heap.
First of all, a garbage collection only removes objects when it performs a sweep.
A sweep could be performed 5 seconds or 5 minutes after that code is executed, or or even in the middle of the code being executed.
Second, V8 has a generational garbage collector, which means that not every sweep removes all of the objects.
An object that was created between the last sweep and current sweet, is generation 0. Every sweep will try to remove gen 0 objects, an object that survived 1 sweep, becomes gen 1, not every sweep will remove gen 1 objects, an object that survived 2 sweeps, becomes gen 2. Gen 2 is also called as a "super-generation" which means that objects are very old and can't be removed immediately.

**Comment by arturovt** [comment]
Closing this as this is not an issue.
I moved via all your instructions, there is no memory leak, here is my code:

![image](https://user-images.githubusercontent.com/7337691/59148855-87934500-8a16-11e9-8014-b8c230e291ae.png)

If I move `takeUntil` above `switchMap` as at your example on stackblitz - then there is a memory leak. This is a typical error of using `takeUntil`.

**Comment by ralphbert** [comment]
Alright! Thank you very much 👍
