### ISSUE TITLE
is it a best practive to dispatch action called InitXXXPage for each ngOnInit component's page ?

### ISSUE THREAD

**Issue by chaouiy** [ngxs/store#1120]

**Comment by arturovt** [comment]
@chaouiy 
Dude, could you please normally describe your question? Currently I'm not able to answer it as I don't understand what's going on in this question.

**Comment by splincode** [comment]
Please create the correct question.

**Comment by chaouiy** [comment]
Ok, I will make it more explicit.
Imagin I want to **GetArticle**, **UpdateLastVisited** and **NotifyAuthor** each time a user visits article page. Is it better to have an action called **InitArticlePage** that is dispatched in **ngOnInit** that do all logic listed above or it is better to have 3 actions and that all the three are dispatched from **ngOnInit** ?

**Comment by arturovt** [comment]
This depends on you, there is no best practice on dispatching 1 or 3 actions :wink:

**Comment by chaouiy** [comment]
@arturovt the speaker on [this video ](https://www.youtube.com/watch?v=JmnsEvoy-gY ) would not agree with you. He is telling that actions should notify about events (init event in our case) and should not decide how state is updated. this video is recomended by your offitial documentation.

**Comment by arturovt** [comment]
Dude, I don't really understand your question and how this video is related.

**Comment by chaouiy** [comment]
Please watch from 04:47. He say that the best practice is to dispatch only one action per event.

**Comment by arturovt** [comment]
The NgRx doesn't allow to dispatch multiple actions at once, but this is not related to the NGXS as it allows to dispatch N actions using just one `dispatch` method.

**Comment by chaouiy** [comment]
@arturov If that is true remove the line from documentation that says same
rules in video apply for both ngxs and ngrx

**Comment by chaouiy** [comment]
@arturov If that is true remove the line from documentation that says same rules in video apply for both ngxs and ngrx

**Comment by arturovt** [comment]
Our docs says `A great video on the topic is Good Action Hygiene by Mike Ryan It's for NgRx, but the same naming conventions apply to NGXS.` How is that related to what you're saying?

**Comment by chaouiy** [comment]
Video say : actions are events not commands. You say : actions can be both.

**Comment by arturovt** [comment]
Dude, you're lying.

You said:

> If that is true remove the line from documentation that says same
rules in video apply for both ngxs and ngrx

Our docs tell about naming convetion, not about best practices or design patterns.

> You say : actions can be both.

Where am I saying that?

**Comment by splincode** [comment]
NGXS extending CQRS pattern, it means that actions - is a command, but you can regard actions as events as well...

**Comment by chaouiy** [comment]
@splincode @arturovt so please don't recommand that video in documentation if ngxs philosophy don't agree with it. It's so misleading

**Comment by chaouiy** [comment]
@arturovt commands tell how to update state. Events only notify that a given event happened

**Comment by arturovt** [comment]
:confused: :confused: 

Looks like you don't understand what our docs tells.
![image](https://user-images.githubusercontent.com/7337691/59151998-bd4f2280-8a44-11e9-81b8-fbcbc36dba60.png)

**Comment by chaouiy** [comment]
@arturovt it is still misleadong since video talk about design patterns not only naming convention. So you agree only with 10% of the video. And please avoid such words "lying". Peace and love

**Comment by arturovt** [comment]
@splincode 

I still don't understand what's being asked, could you comment please?

**Comment by splincode** [comment]
@arturovt I think he is confused.  And he thinks that we refer to NGRX for the definition of the concept of actions.

**Comment by markwhitfeld** [comment]
@arturovt and @chaouiy please keep the tone friendly here!

The point is that you can take the approach that you feel is right for your application.
My personal preference is to represent the actions that have been taken in the application (usually by the user) as actions, but that does not preclude the idea that I would have other actions to represent internal ideas.
As a guideline, if there are multiple actions that are dispatched together in many places then I suspect that it represents some higher level concept and would recommend creating an action representing the source event (as long as I can give it a reasonable name) and then dispatch those three actions from within the handler.

We have included things in the docs that will hopefully be helpful and are not meant as being perscriptive. NGXS allows for many approaches, each of which have their merits, and therefore the choice is yours of which way to go.

**Comment by chaouiy** [comment]
@markwhitfeld Do you mean that when using ngxs we can safely violate what is said in the video except naming conventions. That means : we can reuse actions and we can subtype actions ?

**Comment by splincode** [comment]
@chaouiy yes
