### ISSUE TITLE
When using state manager with Angular, Does it mean that all component class attributes are selectors ? If no what are the guidlines to decide what to store in the store and what to store in component class attributes ?

### ISSUE THREAD

**Issue by chaouiy** [ngxs/store#1124]

**Comment by splincode** [comment]
What do you mean? Example please

**Comment by chaouiy** [comment]
I have noticed that sometimes I don't need to store information in the
store. So I store it directly in the component. My question is : are there
any guidlines to decide whthere some variable should be part of the store
or not.

**Comment by splincode** [comment]
NGXS is a state management pattern + library for Angular. Just like Redux and NgRx it is modeled after the CQRS pattern. 

https://medium.com/@fastphrase/when-to-use-redux-f0aa70b5b1e2
https://blog.usejournal.com/why-and-when-to-use-redux-b57f7dae9269
https://blog.logrocket.com/why-use-redux-reasons-with-clear-examples-d21bffd5835/
https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367
