### ISSUE TITLE
add source component to StateContext ?

### ISSUE THREAD

**Issue by chaouiy** [ngxs/store#1131]
It would be great if we can access from action function the source component that did the dispatch

**Comment by arturovt** [comment]
There is no sense to do this. IMHO this seems meaningless to me and it breaks the dependency inversion principle.

**Comment by arturovt** [comment]
And please, use our issue template.

**Comment by arturovt** [comment]
Read about the dependency inversion principle.

The point is that states are high level classes and shouldn't care about components, only components can be dependent on states, but not vice-versa.

Also this will break your lazy loading:
```TS
@Action(Increment)
increment(ctx: StateContext<number>) {
  console.log(ctx.componentThatDispatched); // instance of SomeLazyComponent
}
```

There are 2 unresolved issues:

* typings (how to know a type of the component that dispatched, so it should be `any` always?)
* if we know type - then we break lazy loading
