### ISSUE TITLE
Error: State name 'list' from UserListState already exists in TodoListState

### ISSUE THREAD

**Issue by abalad** [ngxs/store#1133]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

As in others this problem was corrected, but it came back to occur in the last version.
https://github.com/ngxs/store/issues/202
https://github.com/ngxs/store/issues/179

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/ngxs-lazy-load-dpunuu?file=package.json

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.2
- @ngxs/store version: 3.4.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 11.6.0
- Platform: Windows  

Others:

</code></pre>
![image](https://user-images.githubusercontent.com/5459282/59645760-fcb6f680-9149-11e9-9081-c073ee9dbbe0.png)

**Comment by splincode** [comment]
Sorry but it's correct behavior. Your state names must be unique, otherwise NGHS will not be able to build a dependency tree.

```ts
@State({
 name: 'todoList' // unique name
})
export class TodoListState {}
```

```ts
@State({
 name: 'userList' // unique name
})
export class UserListState {}
```

**Comment by abalad** [comment]
@splincode The state name only repeats on the child node, I'm using ChildsState. As I mentioned above, in version 3.3.4 this feature worked but it seems that it came back to occur in the last versions.

https://stackblitz.com/edit/ngxs-lazy-load-dpunuu?file=package.json

**Comment by splincode** [comment]
Sorry (( But this is new behavior and it's correct works. This is necessary to quickly determine the state in the state subtree for hmr plugin.

Solutions for you

```ts
@State({
  name: 'userList', // 
  defaults: {}
})
export class UserListState {
}

@State({
  name: 'user',
  defaults: {},
  children: [UserListState]
})
export class UserState {
}



@State({
  name: 'todoList',
  defaults: {}
})
export class TodoListState {
}

@State({
  name: 'todo',
  defaults: {},
  children: [TodoListState]
})
export class TodoState {
}
```

**Comment by abalad** [comment]
I understood. I believe that I could use a key to activate or not this feature, since HMR is only used in development time, since the state control goes to production and it makes more sense to use the trees correctly in small production names.

**Comment by splincode** [comment]
It has nothing to do with the HMR, now it's a new processing mechanism.
