### ISSUE TITLE
access to Action type when subscribe to select 

### ISSUE THREAD

**Issue by bahador-r** [ngxs/store#1134]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

how to can i access to Action Type when subscribe to one select ?

**Comment by poloagustin** [comment]
What is the reason behind this feature request?
Why would you benefit from know an action type?
The dispatched action does not have anything to do with the selection of the state. You can have several actions impacting the resulting state that you may be selecting. And it becomes even more complex when involved meta-selectors and joined selectors.

**Comment by arturovt** [comment]
What are you trying to achieven? :open_mouth:

**Comment by bhador1936** [comment]
I need based on action type, call different method.
I decide on the behavior of a user, what should be done.
if changed the state with action type One, must call methods a, b and c
and 
if changed the state with action type Two, must call methods a and d

**Comment by poloagustin** [comment]
maybe a real world example could work to help guide you in the correct direction.
First, selectors are for generating observables that can help you read data from the state and react to the changes to the state and return the latest value after each action dispatch.
My question would be, why are calling methods in your subscriptions? Your code should look something like this I believe
```
this.store.select(state => state.todos).subscribe(todos => this.todos = todos);
```
In which part are you calling methods and for what?

**Comment by bahador-r** [comment]
for example:
i have a data table with few settings (sort, filter, show or not show columns, column size and ...)
that connect to level up component, with state
structure of the state like as :
```
{
	id:{
		sort: ... ,
		filter: ... ,
		display: ... ,
		width: ... ,
	},
	name:{
		sort: ... ,
		filter: ... ,
		display: ... ,
		width: ... ,
	},
	.
	.
	.
}
```
sort, filter and show or not show columns, need to recall api and get new data.
but column size no need to get new query.
when i subscribe this store, i dont know wich key has changed.

**Comment by poloagustin** [comment]
you should not call your api on each message that comes from your selection, but in your action.
```
// app.state.ts
@Action(SortBy)
sortBy(ctx,action){
  ctx.patchState({...});
  ctx.dispatch(new GetDataFromApi());
}
@Action(FilterBy)
filterBy(ctx,action){
  ctx.patchState({...});
  ctx.dispatch(new GetDataFromApi());
}
@Action(setWidth)
setWidth(ctx,action){
  ctx.patchState({...});
  // should not call api
}
```

Now if what you want is not to repeat the dispatch on each `@Action` you can listen to the action stream in your component.

```
this.actions$.pipe(
  ofActionSucceded([SortBy, FilterBy]),
  mergeMap(()=> this.store.dispatch(new GetDataFromApi()))
);
```

**Comment by bahador-r** [comment]
> 
> 
> you should not call your api on each message that comes from your selection, but in your action.
> 
> ```
> // app.state.ts
> @Action(SortBy)
> sortBy(ctx,action){
>   ctx.patchState({...});
>   ctx.dispatch(new GetDataFromApi());
> }
> @Action(FilterBy)
> filterBy(ctx,action){
>   ctx.patchState({...});
>   ctx.dispatch(new GetDataFromApi());
> }
> @Action(setWidth)
> setWidth(ctx,action){
>   ctx.patchState({...});
>   // should not call api
> }
> ```
> 
> Now if what you want is not to repeat the dispatch on each `@Action` you can listen to the action stream in your component.
> 
> ```
> this.actions$.pipe(
>   ofActionSucceded([SortBy, FilterBy]),
>   mergeMap(()=> this.store.dispatch(new GetDataFromApi()))
> );
> ```

thank you for help guide

**Comment by splincode** [comment]
We can close this issue?

**Comment by bahador-r** [comment]
> 
> 
> We can close this issue?

yes
