### ISSUE TITLE
possibility to have selectors as objects instead of observables

### ISSUE THREAD

**Issue by chaouiy** [ngxs/store#1138]
It would be great if we can have selectors that provide ready to consume objects instead of observables, this way we don't need to subscribe each time to have selector value.

**Comment by splincode** [comment]
https://medium.com/ngxs/declarative-snapshot-selections-with-the-new-ngxs-labs-decorator-a62e05f1803d

**Comment by poloagustin** [comment]
You can get ready to consume objects with `Store.selectSnapshot`.
https://ngxs.gitbook.io/ngxs/concepts/select#snapshot-selects
