### ISSUE TITLE
Selectors should not have a specific order in a query class

### ISSUE THREAD

**Issue by t-denis** [ngxs/store#1143]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

A selector should be declared after it's dependencies in a query class.

## Expected behavior

Any developer-preferred selectors order.
Or an exception or, at least, a warning in the console that indicates that there is an issue with a hint on how to fix it.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-qczwnr?file=src/app/store/counter.query.ts

## What is the motivation / use case for changing the behavior?

Happy ngxs users

## Environment

<pre><code>
Libs:
- @angular/core version: 8.0.3
- @ngxs/store version: 3.4.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by arturovt** [comment]
@splincode @markwhitfeld any thoughts?

**Comment by arturovt** [comment]
I'm confirming this is not an issue.
![image](https://user-images.githubusercontent.com/7337691/63117251-0e7b1580-bfa4-11e9-8fce-e2a9e887fc52.png)

This is not related to the NGXS itself but rather to TypeScript decorators behavior, decorators are invoked after the class declaration, so basically you're trying to access non-decorated methods yet with `@Selector`.

![image](https://user-images.githubusercontent.com/7337691/63117436-77fb2400-bfa4-11e9-9b3b-6ba77b554ce1.png)

**Comment by t-denis** [comment]
Is there a way for library to check if the accessed method is decorated or not?
Maybe mention this behavior in a documentation?

**Comment by arturovt** [comment]
@t-denis I understand your agitation. I'm discussing that with my NGXS teammate.

**Comment by arturovt** [comment]
@t-denis I will make a PR to mention this.

**Comment by markwhitfeld** [comment]
@t-denis I have merged a PR that should fix this issue. Please could you test with the `@ngxs/store@dev` package and confirm if it is fixed for you or not.

**Comment by t-denis** [comment]
@markwhitfeld 
The issue is fixed, everything works as expected. Thanks!
