### ISSUE TITLE
🐞[BUG]: Action Handlers e.g. OfActionDispatched causing memory leaks

### ISSUE THREAD

**Issue by denu5** [ngxs/store#1149]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
I suspect the ngxs action handlers e.g. `OfActionDispatched` to cause memory leaks: In the ngxs-simple app I created a component which subscribes to OfActionDispatched / Add-Action.

I see some similarity to @arturovt 's explanation here a month ago: https://github.com/ngxs/store/issues/1116#issuecomment-499129824 - but removing the ofAction subscription seems to let the garbage collector cleanup the component as I would expect it to be.

So when you press the "toggle leak component" several times to init/destroy some instances and check the heap snapshot, the components appears as many times it was toggled. In our project this causes serious problems because the components contain maps and videos.

## Expected behavior
Doesn't stop garbage collection of removing components.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/ngxs-simple-rfggjd

* Step 1: Click "toggle leak component" several times
* Step 2: Check js heap and search for ofactionleakcomponent

![image](https://user-images.githubusercontent.com/5692193/60835635-f0134480-a1c3-11e9-9040-3d10d220f35b.png)

**Comment by splincode** [comment]
Most likely this is due to another phenomenon. Because this code also causes a memory leak.

```ts
@Component({
  selector: 'app-ofaction-leak',
  templateUrl: './ofaction-leak.component.html',
  styleUrls: ['./ofaction-leak.component.css']
})
export class OfactionLeakComponent implements OnInit, OnDestroy {

  private unsubscriber$ = new Subject<void>();
  constructor(private actions$: Actions) { }

  private subscribtion;

  ngOnDestroy(): void {
    this.subscribtion.unsubscribe();
    console.log(this.subscribtion)
  }

  ngOnInit() {
   this.subscribtion =  this.actions$.subscribe(_ => {
      this.logAction();
    });
  }

  logAction() {
    console.warn('triggered by ofActionDispatched(Add)');
  }

}
```

See

```ts
/**
 * Action stream that is emitted anytime an action is dispatched.
 *
 * You can listen to this in services to react without stores.
 */
@Injectable()
export class Actions extends Observable<any> {
  constructor(
    actions$: InternalActions,
    internalExecutionStrategy: InternalNgxsExecutionStrategy
  ) {
    super(observer => {
      actions$
        .pipe(leaveNgxs(internalExecutionStrategy))
        .subscribe(
          res => observer.next(res),
          err => observer.error(err),
          () => observer.complete()
        );
    });
  }
}
```

Maybe we do not create the Actions service correctly.

**Comment by arturovt** [comment]
@denu5 

Gonna tell you frankly - the example is really weird. I don't mean that you created a weird example, I mean that its behavior is weird :D

If I comment `this.logAction()` - then there is no memory leak :D

**Comment by tskweres** [comment]
I have noticed this memory leak as well when using ofActionDispatched in components

**Comment by tskweres** [comment]
Update, after testing - simply passing in the Actions subject into any child component causes a memory leak.

The work around is to create a global service ie: ActionService, pass it in there and create another Observable that components can subscribe to from the service
