### ISSUE TITLE
State not being applied in correct order when dispatching withing observable action

### ISSUE THREAD

**Issue by yarrgh** [ngxs/store#115]
When dispatching an action from within another action, the state doesn't get set correctly.

Consider the following:
```typescript
@Action(CreateRecipe)
  doCreateRecipe({ patchState, dispatch }: StateContext<RecipeStateModel>, { payload }) {
    patchState({
      isCreating: true
    });
    return this.recipeService.create(payload)
      .pipe(
        map(recipe => dispatch(new CreateRecipeSuccess(recipe)))
      );
  }

  @Action(CreateRecipeSuccess)
  createRecipeSuccess({ patchState, dispatch }: StateContext<RecipeStateModel>, { payload }: CreateRecipeSuccess) {
    patchState({
      isCreating: false,
      createdRecipe: payload
    });
  }
```

When I dispatch `CreateRecipe` it dispatches both actions however the state isn't set correctly. It applies the state in `CreateRecipeSuccess` and then the state in `CreateRecipe` causing the state to be overwritten.

![image](https://user-images.githubusercontent.com/1577822/37683800-53148e32-2c53-11e8-8158-971e793bab10.png)

This causes the final state to be:
```json
{
  "recipes": {
    "isCreating": true,
    "createdRecipe": null
  }
}
```

I expect the final state to have `isCreating = false` and `createdRecipe` to be an object.

**Comment by xmlking** [comment]
Upgraded to  ngxs :  2.0.0-rc.12 

I am also expecting this order : ChangeAuthMode -> AuthModeChanged -> Login -> LoginSuccess ->  Logout -> LogoutSuccess but see: 
> not sure if it is DevTool printing issue or really executed in this order. other then that , 2.0.0-rc.12  working without any issues. 

![image](https://user-images.githubusercontent.com/627951/37696207-393b94e4-2c92-11e8-983d-5f71e1f8efd5.png)

**Comment by wheredoesyourmindgo** [comment]
@yarrgh I'm curious what happen when you wrap ``` return this.recipeService.create(payload)
      .pipe(
        map(recipe => dispatch(new CreateRecipeSuccess(recipe)))
      );``` in a setTimeout call.

**Comment by deebloo** [comment]
@yarrgh hmmm. so the state order IS correct but it is being displayed incorrectly in the devtools?

**Comment by yarrgh** [comment]
Yes, but I did change from using `map()` to `tap()` to dispatch a new action. Maybe that's the reason why? 

I don't mind using `tap()` instead of `map()` except that when you dispatch the action, it gets out of order. The hack is to dispatch inside of a `setTimeout()`.

Should ngxs support returning an action,`Observable<action>`, or `Promise<action>`  and await/subscribe for the result, if necessary, and then dispatch the returned action automatically? This would mean that `dispatch()` wouldn't be needed in the `StateContext`

**Comment by deebloo** [comment]
@yarrgh are you still seeing this behavior with the latest builds?

**Comment by yarrgh** [comment]
Yes,
```
@ngxs/store: 2.0.0-rc.24
@ngxs/devtools-plugin: 2.0.0-rc.24
```

```ts
@Action(ReloadRecipes)
  doReloadRecipes({ patchState, dispatch }: StateContext<RecipeStateModel>, { payload }) {
    patchState({
      loadingRecipes: true
    });
    return this.recipeService.getAll().pipe(
      map(recipes => dispatch(new ReloadRecipesSuccess(recipes))),
    );
  }

  @Action(ReloadRecipesSuccess)
  reloadRecipesSuccess({ patchState }: StateContext<RecipeStateModel>, { payload }: ReloadRecipesSuccess) {
    patchState({ recipes: payload, loadingRecipes: false });
  }
```

![image](https://user-images.githubusercontent.com/1577822/37991195-cbcdfea4-31c5-11e8-85e5-cc62e456882d.png)

 I have to use `tap()` and wrap the dispatch inside of a `setTimeout()` to get it in the right order.

**Comment by yarrgh** [comment]
We could probably close this in favor of #139 as the actual state seems to be correct just the ordering in the devtools is wrong
