### ISSUE TITLE
NgxsStoragePluginModule does not add lazy loaded slices if forRoot() options define keys present in lazy loaded state

### ISSUE THREAD

**Issue by johngrimsey** [ngxs/store#1150]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
AppModule:
...
NgxsStoragePluginModule.forRoot({ key: ['foo.bar', 'lazy.bar'] })
...
```

Works as expected until the 'lazy' state is lazily loaded from a lazy module. Then the `lazy` slice is only populated with keys specified in the AppModule's NgxsStoragePluginModule config as above. The full `lazy` slice is not populated after the lazy module is loaded.

#### Example:

If LazyModule defines `lazy` state as

```
{
    bar: any;
    lazyStateKey: any;
}
```

Then when loading the `LazyModule`, only `bar` key is present in the `lazy` slice (as defined in plugin settings in AppModule).

## Expected behavior

Lazy loaded module's complete state should be present but with the key specified in the NgxsStoragePluginModule options being populated.

## Desired behavior

Would be good to specify keys in the lazy module, e.g.
```
LazyModule:
...
NgxsStoragePluginModule.forChild({ key: ['lazy.bar'] })
...
```

## What is the motivation / use case for changing the behavior?

Predictable usage.

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.12
- @ngxs/store version: 3.4.3

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.15.1
- Platform:  Mac

Others:

</code></pre>

**Comment by johngrimsey** [comment]
Ok I found a fix/workaround/how to do it: ensure the lazy module imports `NgxsStoragePluginModule`. 

If I've not missed something and this is how it's meant to be done would be helpful to add to the plugin's docs.

**Comment by splincode** [comment]
Please add repo for reproduce / or stackblitz example

**Comment by johngrimsey** [comment]
Sure, shall do when I can

**Comment by arturovt** [comment]
Closing until a reproduction is provided.
