### ISSUE TITLE
Need more complete documentation or example around action handlers

### ISSUE THREAD

**Issue by atgillette** [ngxs/store#1152]
I'm interested in using action handlers.  But the documentation around it is incomplete.  I'd love to see examples on how to use:

- ofActionDispatched
- ofActionSuccessful
- ofActionCanceled
- ofActionErrored
- ofActionCompleted

Thanks,

Adrian

**Comment by arturovt** [comment]
What do you mean by "incomplete"? [There is](https://ngxs.gitbook.io/ngxs/advanced/action-handlers) enough information of how 2 use them + examples.

**Comment by splincode** [comment]
Released in 3.5.0
