### ISSUE TITLE
Problem when using state composition.

### ISSUE THREAD

**Issue by DannyBoyNg** [ngxs/store#1154]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using state composition. For example I have two states: mainState and someState. Lets say someState extends mainState. Now when I call an action on mainState, it gets called twice. Resulting in two requests to the API server. Lets add another state called "anotherState". This state also extends mainState. Now when I call an action on mainState, it gets called three times, resulting in three requests to the API server.

I need someone to verify if they get the same behavior or if I'm just doing something wrong.

## Expected behavior
Calling an action from mainState should only call that action once and not multiple times when using state composition.

## Environment

<pre><code>
Libs:
- @angular/core version: 8.0.0 - 8.1.1
- @ngxs/store version: 3.4.3

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.4.0
- Platform:  Windows
</code></pre>

**Comment by splincode** [comment]
Please add stackblitz example

**Comment by DannyBoyNg** [comment]
https://stackblitz.com/edit/angular-18wz4q

**Comment by Dav1dde** [comment]
I don't know about the internals of ngxs, but the current behaviour does make sense to me.

If you dispatch a single action, how would you decide which of the 3 states gets to handle the event? NGXS does the "fair" thing and dispatches it to all states.

**Comment by DannyBoyNg** [comment]
Even though I agree with your reasoning. Why would you use state composition if one dispatch of an action, the action gets called multiple times. It kinda makes "state composition" useless.

Can anyone think of a use case where this behavior is justified? I just need @amcdnl to say that, this behavior is by design and I will close this issue.

Maybe a good idea to add a small note to the documentation describing this behavior.

**Comment by Dav1dde** [comment]
I'd be interested in an approach how to differentiate which store/state is supposed to handle the action. One thing that could work would be to extend the Action interface to also hold the store name and if not specified all stores that have action listeners for the action type would receive the action (this also does not break backwards compatibility).

**Comment by mucbits** [comment]
I'm using composition in my project with a rather complex store structure which in different parts hold the same type of data.  I want to avoid code duplicates to manipulate that structures in different locations. I've been running into the same problem, since I only want the structure in one location to be changes. My solution was to specify the location within the action and let the handler check if it is supposed to handle that action... yeah... not perfect. An better solution would be nice.

**Comment by DannyBoyNg** [comment]
That sounds like a viable temporary solution. I might just try that until there are better solutions available. Thanks!

**Comment by arturovt** [comment]
@DannyBoyNg should it be closed?

**Comment by arunredhu** [comment]
I am implementing the same use case around the application where I need to reuse the state logic across different parts of application. Actions in NGXS are similar to redux actions i.e. when you dispatch an action, redux store don't know which specific code needs to executed for store update, it just updates all the states which are using that action for update. 

In NGXS, if you use state as service i.e. [data plugin ](https://github.com/ngxs-labs/data), you actually don't have to use action implementation, you can just use state services and directly call the methods to update the state. In this implementation, we can make reusable logic as separate abstract class or state and then can extend that class to accomplish this type of use cases.

**Comment by enekonieto** [comment]
I found an article that uses composition to allow multiple instances of the same state in a very elegant way:
https://medium.com/criteo-engineering/ngxs-components-and-states-b237a15c5de0
