### ISSUE TITLE
Access parent ctx & patch state from another state

### ISSUE THREAD

**Issue by goodbeysr** [ngxs/store#1157]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x ] Feature request
[ ] Documentation issue or request
[ x ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

Let's say we have a parent state with dynamic key:

`
interface WorkspaceModel {
    config: {index: number};
    workspaces: { [key: string] : { calibration: any, plts: any } }
}

@State<\WorkspaceModel\>({
    name: 'workspace',
    default: {
        config: { index: 0},
        workspaces: {}
    }
})
export class WorkspaceState{
   ....
}
`

in my case calibration and plts are another state and to handle them i need to handle each of their action inside the same file where i did define WorkspaceState with the @Action decorator. The problem is that these sub states can have more than 30 actions each + workspace actions which means the file will have a lot of code lines.

## Expected behavior

What i want to achieve is to keep the same state but create another state files called calibration & plts, and somehow i can handle the ctx of workspace from the other state files "calibration & plts";

## What is the motivation / use case for changing the behavior?

I think it is a normal functionality to have because its part of the redux/flux architecture where in the case of NGRX I could simply call the reducer function on each part of my nested state to handle it, but in the case of decorated class each state define its ctx and u cant access to the parent context or destruct it from the whole app state so you can patch it.

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.0
- @ngxs/store version: 3.4.3

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.4.0
- Platform:  Windows
</code></pre>

**Comment by arturovt** [comment]
I'm a little bit cautious about what's going on in this topic. But I've got to mention that:
> I think it is a normal functionality to have because its part of the redux/flux architecture

No, Redux/Flux has nothing to do with parent and child states as it's a part of a specific implementation. I'm not sure if the NgRx has nested states (I just tried to google it) as you're saying that:
> I could simply call the reducer function on each part of my nested state

And it would be great if you could have structured your issue and highlight code and properties. Also always highlight decorators like `@Action` because otherwise you're mentioning a person with nickname `action` :grin: 

And no, it's not possible to access other states. States are isolated from each other, otherwise you'd get a mess and entropy. `StateContext` is created every time when any action is dispatched and its handler is invoked.

**Comment by arturovt** [comment]
Do we need to close this issue?

**Comment by goodbeysr** [comment]
Yeah . sorry for the late reply.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Artur Androsovych<mailto:notifications@github.com>
Envoyé le :mardi 8 octobre 2019 18:33
À : ngxs/store<mailto:store@noreply.github.com>
Cc : driss najih<mailto:narutoshun@live.fr>; Author<mailto:author@noreply.github.com>
Objet :Re: [ngxs/store] Access parent ctx & patch state from another state (#1157)


Do we need to close this issue?
