### ISSUE TITLE
compilation failed because of non-ansi symbols: Cannot find name 'Éµh'

### ISSUE THREAD

**Issue by kain64** [ngxs/store#1176]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
compilation  failed with error:
ERROR in ......: error TS2304: Cannot find name 'Éµh'.

## Expected behavior

compilation pass

## Minimal reproduction of the problem with instructions
windows server 2016, regional settings fo non unicode: english
code example:
```
import { ɵh, ɵr } from '@ngxs/store';
............
export declare class NgxsHooks {
    constructor(scf: ɵr, internalActions: ɵh);
    ............
}

```
ɵh converted  to  'Éµh'. 
ɵh -- from store.

## Environment

<pre><code>
Libs:
- @angular/core version: ^7.2.15
- @ngxs/store version: ^3.4.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.6.0
- Platform:  Windows

Others:
windows server 2016, regional settings fo non unicode: english
</code></pre>

**Comment by splincode** [comment]
It's joke?

**Comment by markwhitfeld** [comment]
I don't think so. This is really wierd... but I am interested to know what the NgxsHooks class does ;-)

**Comment by markwhitfeld** [comment]
@kain64 Please use the issue template provided as well as a reproduction repository.

**Comment by kain64** [comment]
> @kain64 Please use the issue template provided as well as a reproduction repository.
> Closing the issue until it meets the requirements above.

updated

**Comment by kain64** [comment]
> It's joke?

to use 2 different encoding and 2 languages in 2 symbols variable name? I think, yes.

**Comment by splincode** [comment]
I don't understand how it's related with NGXS.  What is `constructor(scf: ɵr, internalActions: ɵh)`?
Where github repo for reproduce?

**Comment by arturovt** [comment]
What is `NgxsHooks` btw?

**Comment by kain64** [comment]
> I don't understand how it's related with NGXS. What is `constructor(scf: ɵr, internalActions: ɵh)`?
> Where github repo for reproduce?
1)download package ngxs/store from npm https://www.npmjs.com/package/@ngxs/store
2)open file: node_modules\@ngxs\store\ngxs-store.d.ts
3) line 5 in version 3.5 : export { InternalActions as ɵc, OrderedSubject as ɵb } from './src/actions-stream';
in 3.4 was ɵh. now ɵc.  symbol 'ɵ'-tetta problematic for compilation, probably related to some special encoding,

**Comment by markwhitfeld** [comment]
@kain64 This is output created by the angular compiler, have you searched their issues for something similar?

**Comment by kain64** [comment]
> @kain64 This is output created by the angular compiler, have you searched their issues for something similar?

no, only here. 
ok. I see.. looks like impossible to fix. thanks for reply. I will continue investigation on my build server

**Comment by markwhitfeld** [comment]
Thanks! I'll close this for now. Please let us know if you find anything.
As an aside you could try checking out the ngxs code on your machine, running `yarn build` and copy pasting the generated `@ngxs` folder into your `node_modules` folder to see if the issue changes.

**Comment by splincode** [comment]
I think this problem if you usage non public API in your project from `@ngxs/store`
