### ISSUE TITLE
NGXS DOM update after dispatch inconsistent

### ISSUE THREAD

**Issue by rijvirajib** [ngxs/store#1191]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using a selector like so:
```
<div id="allRelateDataItems" *ngIf="relatedDataById$ | async">
  <div *ngFor="let relatedData of relatedDataById$ | async; index as i">
    Available: {{ relatedData.isAvailable }}
  </div>
</div> 

  @State<DataStateModel>({
    name: 'data',
    defaults: {
      data: {},
      relatedData: {}
  }})
  @Selector()
  static relatedDataById(state: MissionStateModel) {
    return (id: string) => {
      const relatedData = []
      state.data[id].relatedDataIds.forEach(dataId => {
        relatedData.push(state.relatedData[dataId])
      })

      return relatedData
    }
  }

  add(relatedItem) {
    this.store.dispatch(
      new AddItem(this.data[dataItem], relatedItemId))
  }

  @Action(AddItem)
  @ImmutableContext() // from ngxs-immer
  addItem( ...) {
    state.data.relatedDataIds.push(itemId)
  }
```

The DOM does not update properly - instead, it updates the datavalues but not the dom itself:
Instead of seeing my item in the `#allRelateDataItems`, it's empty.
This changes when I reload the page, the dom is working properly and all the dispatch events are also working properly. Also should note the inidivual item inside the DOM is showing the correct value `isAvailable: false` but the Selector has not updated the parent DOM element.

## Expected behavior
The dom element `#allRelateDataItems` should appear with a list of items when a new Item is added to the state via dispatch.  

## What is the motivation / use case for changing the behavior?
I have a state with two main keys. One of those main key states has an Array of keys for the second main key on my state. When I update that list of keys on the main state's object, I can't seem to update the DOM with the update via dispatch.

## Environment

<pre><code>
Libs:
@angular-devkit/architect    0.801.2 (cli-only)
@angular-devkit/core         8.0.6
@angular-devkit/schematics   8.1.2 (cli-only)
@angular/http                8.0.0-beta.10
@ngtools/webpack             8.0.6
@schematics/angular          8.1.2 (cli-only)
@schematics/update           0.801.2 (cli-only)
rxjs                         6.5.2
typescript                   3.4.5
webpack                      4.27.1

Browser:
- [ ] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by splincode** [comment]
Please add stackblitz example for reproduce

**Comment by rijvirajib** [comment]
https://stackblitz.com/github/bnmiyoyy

This is the entire project since I'm not entirely certain where the error is happening. Either in my dispatch process, or how I'm handling states..

**Comment by splincode** [comment]
Yikes! The page you requested couldn't be found.
![image](https://user-images.githubusercontent.com/12021443/62164816-c8784d80-b325-11e9-89c7-37d7f5a0b4d0.png)

**Comment by rijvirajib** [comment]
Sorry about that, linked here : https://stackblitz.com/github/rijvirajib/questgiver

**Comment by rijvirajib** [comment]
Resolved
Turns out pushing won't do it with immer and objects need to be concat and then assigned.

**Comment by rijvirajib** [comment]
Turns out it's an issue with deep objects and subscribe not being called on the right changes.
