### ISSUE TITLE
Warning: Potential Security Risk Ahead (https://ngxs.io)

### ISSUE THREAD

**Issue by JoeWorker** [ngxs/store#1207]
Browser:

- [ ] Firefox DE Latest

> ### Warning: Potential Security Risk Ahead
> 
> Firefox Developer Edition detected a potential security threat and did not continue to ngxs.io. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.
> 
> ### What can you do about it?
> 
> The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

**Comment by splincode** [comment]
@amcdnl @markwhitfeld could you check, please?

**Comment by JoeWorker** [comment]
could be a simple outdated security cert for all I know, but thought you'd be interested, and not about to test other browsers ;)

**Comment by Dav1dde** [comment]
Fine for me: 

![image](https://user-images.githubusercontent.com/255721/62647804-a4ce8c00-b951-11e9-8415-f0e88c833aff.png)

Chrome, Firefox and Edge

**Comment by splincode** [comment]
Because it's redirect to gitbook.io domain

**Comment by Dav1dde** [comment]
Weird, now I get it too and don't get redirected:
![image](https://user-images.githubusercontent.com/255721/62682387-51455800-b9bc-11e9-979d-4df2efbfb320.png)

On Linux now instead of Windows (still Chrome)

**Comment by markwhitfeld** [comment]
Ok, I think I found the issue.
If you go to http://ngxs.io then the permanent redirect kicks in.
If you go to https://ngxs.io then you get this security issue.

@JoeWorker and @Dav1dde could you confirm that you are getting the same?

**Comment by Dav1dde** [comment]
@markwhitfeld yeah, that seems to be the problem

![image](https://user-images.githubusercontent.com/255721/63018451-29149800-be99-11e9-93c3-3ff1c845f01e.png)

**Comment by splincode** [comment]
@markwhitfeld what next?

**Comment by markwhitfeld** [comment]
Ok, I got the domain transferred to me from Austin ;-)
Godaddy is properly broken when it comes to forwarding a https connection.
I was able to fix it with a direct forward to gitbook.

@JoeWorker and @Dav1dde could you confirm that it is fixed for you?

**Comment by Dav1dde** [comment]
Works for me now 👍

**Comment by splincode** [comment]
Works for me too

**Comment by markwhitfeld** [comment]
I think it is safe to close this.
