### ISSUE TITLE
Cannot freeze / Cannot assign to read only property 'state' of object '[object Object]'

### ISSUE THREAD

**Issue by gygabyte017** [ngxs/store#1212]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
I use ng-bootstrap. When I open an NgbModal, I want to save the reference NgbModalRef into the state. When I patch the state, I get "ERROR TypeError: Cannot freeze" "TypeError: Cannot assign to read only property 'state' of object '[object Object]'"

```
  @Action(OpenModalNewActivity)
  openModalNewActivity(context: StateContext<SharedStateModel>) {
    const ref = this.modalService.open(ModalNewActivityComponent);
    context.patchState({
      refModalNewActivity: ref
    });
  }
```

## Expected behavior
It should set the refModalNewActivity property in the state with the value returned by the function modalService.open.

## Minimal reproduction of the problem with instructions
Here's my state config:

```
export interface SharedStateModel {
  refModalNewActivity: NgbModalRef;
}

export class OpenModalNewActivity {
  static readonly type = '[Modal] Open Modal New Activity';
}

@State<SharedStateModel>({
  name: 'shared',
  defaults: {
    refModalNewActivity: null
  }
})
export class SharedState {
  constructor(private modalService: NgbModal) { }

  @Action(OpenModalNewActivity)
  openModalNewActivity(context: StateContext<SharedStateModel>) {
    const ref = this.modalService.open(ModalNewActivityComponent);
    context.patchState({
      refModalNewActivity: ref
    });
  }
}

// The error happens when I dispatch the action:
this.store.dispatch(new OpenModalNewActivity());
```

## What is the motivation / use case for changing the behavior?
I want to save in the state the reference to the ng-bootstrap model.

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.0
- @ngxs/store version:3.5.0

Browser:
- [X] Chrome (desktop) version 76.0.3809.87
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.4.0
- Platform:  Windows

</code></pre>

**Comment by splincode** [comment]
Please add stackblitz example for reproduce

**Comment by gygabyte017** [comment]
Here it is: https://stackblitz.com/edit/angular-du3q8g

**Comment by gygabyte017** [comment]
Trying to deal with this issue, I've found out also that if I put into the content component (ModalNewActivityComponent) a reactive form, and I open it through the action OpenModalNewActivity (as in the example), the reactive form doesn't work and the form never update the underlying model; to prove it, if I move the opening of the modal directly in the button without the action (i.e. this.modalService.open(ModalNewActivityComponent) happens directly inside the onclick instead of calling the action which does the same thing), the reactive form works with the very same component ModalNewActivityComponent.
So I believe something breaks with ngxs.

Here's a new stackblitz with this proved: https://stackblitz.com/edit/ngxs-ngbmodal-reactiveforms

Thanks you

**Comment by arturovt** [comment]
@gygabyte017 

I opened your first stackblitz example. FIrst of all action handlers are invoked outside of Angular's zone, you've to inject the `NgZone` class and do:
```ts
const ref = this.zone.run(() => this.modalService.open(ModalNewActivityComponent));
```

Thus your form value will get updated:
![image](https://user-images.githubusercontent.com/7337691/62820909-55b47100-bb74-11e9-8808-f9e677524731.png)


Second, the current behavior is obvious, as the state is `Object.freeze`d. Set the `developmentMode` to `false` and try again.

Third, what you're doing is not correct !!! You shouldn't store any class instances in states.

**Comment by gygabyte017** [comment]
Thank you very much, so no bug and my mistake. I apologize.
Now I've carefully read https://ngxs.gitbook.io/ngxs/advanced/options and I understand what you mean about Zone and the change detection.

I'm not sure about the `Object.freeze`d, setting `developmentMode` to `false` is just suppressing the error, right? If so, what is the true reason behind that error? It is related to storing the class instance in the state? What is wrong about it? Just to understand better.

Thanks again

**Comment by arturovt** [comment]
Sure, I'll try to explain.

As you may know that `Object.freeze` is meant to prevent adding/deleting/mutating properties on the object. We're using `deepFreeze` when the `developmentMode` is `true`. When it's `false` the `deepFreeze` is not used at all, so no errors are thrown.

`Cannot freeze` is not thrown by NGXS, I guess it's thrown by stackblitz, because we don't have such error message :)

`NgbModal` does a lot of initializations under the hood, you just pass the component constructor, but `ng-bootstrap` does all job for you, retrieves the component factory, component reference, store its instances in properties, so it's able to release resources in the future, when the modal window gets closed. When you save the `NgbModalRef` instance in the state, it gets freezed. `ng-bootstrap` is not able to add or mutate any property, that's why it throws `cannot assign... blah blah`.

Redux states are meant to store plain objects, but not instances.

**Comment by gygabyte017** [comment]
Crystal clear, thank you!
