### ISSUE TITLE
🐞[BUG]: Can't resolve all parameters of state 

### ISSUE THREAD

**Issue by workfel** [ngxs/store#1223]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

**!!! Before read this, i'm using Angular 8 with ivy compiler !!!**

When i have a any service on DI in the constructor of State i  have always this error . ` Can't resolve all parameters for NavigatorState: (?).`

This is my app.module
```ts
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
   .....,
    // Ngxs
    NgxsModule.forRoot([
      LayoutState,
      NavigatorState
    ], {
      developmentMode: !environment.production,
    }),
.....
```

The layoutState not have a construction with DI

```ts
@State<LayoutStateModel>({
  name: 'layout',
  defaults: defaultLayoutStateModel
})
export class LayoutState {

}
```

And the State who i am blocked

```ts
@State<NavigatorStateModel>({
  name: 'navigator',
  defaults: {
    items: []
  }
})
export class NavigatorState {

  constructor(private readonly _router: Router) {
  }

  @Action(Navigate)
  add(ctx: StateContext<NavigatorStateModel>, { payload }: Navigate) {
    this._router.navigate([payload]);
  }
}
```

If you want my `angularCompilerOptions`

```json
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableIvy": true
  }
```

<pre><code>
Libs:
- @angular/core version: 8.2.0
- @angular/compiler-cli version: 8.2.0
- @ngxs/store version: ^3.5.0-dev.master-07d305f

For Tooling issues:
- Node version: 10.16.0
- Platform: Mac

</code></pre>

**Comment by splincode** [comment]
Related: https://github.com/ngxs/store/issues/1165

**Comment by splincode** [comment]
@workfel please add repo for reproduce

**Comment by splincode** [comment]
https://github.com/ngxs/store/pull/1474

**Comment by tskweres** [comment]
How can I fix this? Using latest version of Angular and:

@ngxs/devtools-plugin": "^3.6.2",
@ngxs/store": "^3.6.2",

Still getting this error

Error: Can't resolve all parameters for AppState: (?).

**Comment by splincode** [comment]
Add Injectable decorator for your state class

**Comment by debender495** [comment]
Ivy requires to decorate all providers with the @Injectable() decorator

**Comment by debender495** [comment]
then the Ivy compatible code should look like this:
import { Injectable } from '@angular/core';
import { State } from '@ngxs/store';

@State<string[]>({
  name: 'countries',
  defaults: ['USA', 'Mexico', 'Canada']
})
@Injectable()
export class CountriesState {}

**Comment by leobororo** [comment]
After making the state class Injectable will we still use the selectors?

**Comment by splincode** [comment]
@leobororo what do you mean?

**Comment by teohirs** [comment]
@debender495 why is it necessary to add Injectable decorator if official documentation does not mentioned it: https://www.ngxs.io/concepts/state. Can you please explain or refer to the doc?

**Comment by splincode** [comment]
@teohirs Becase need update docs

**Comment by Kappy-Lobster** [comment]
@splincode That worked for me - thank you sir!
