### ISSUE TITLE
Debounce a Action

### ISSUE THREAD

**Issue by feitzi** [ngxs/store#1225]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
I want to debounce a specific action for the whole store. It is possible to debounce it during dispatching in a component described [here](https://stackoverflow.com/questions/52259936/how-to-implement-debounce-analog-for-ngxs-action).  But I want to debounce it in the whole store. 
As an example, I have an Action that sends a POST request to the server. Currently, this action is dispatched from within some other actions. Every time one of these other actions is executed, the POST action is also executed.
I want to debounce this POST action now (and just this type of action, not the other actions) to reduce requests to the server. 

Is this scenario currently possible with ngxs?

**Comment by splincode** [comment]
https://twitter.com/splincodewd/status/1111213899339231232?s=20

**Comment by feitzi** [comment]
Thanks @splincode 
Here is the code for copy/paste from your tweet

``` typescript
export function Debounce(delay: number = 300): MethodDecorator {
  return (target: any, propertyKey: string, descriptor: PropertyDescriptor) => {
    let timeout = null;
    const original = descriptor.value;
    descriptor.value = (...args) => {
      clearTimeout(timeout);
      timeout = setTimeout(() => original.apply(this, args), delay);
    };
    return descriptor;
  };
}
```

But this works just for simple examples. For my use-case, I want to return in the debounced action an Observable with the HTTP requests itself. Without the decorator, it works, but with the debounce decorator I got null exceptions etc..

Here is a sample on [Stackblitz](https://stackblitz.com/edit/ng-ngxs-playground-y6eoab). See class `counter.state.ts` method `persistCounterState`.

**Comment by splincode** [comment]
You should not use arrow function, because arrow function not save context (this).

This works with

![image](https://user-images.githubusercontent.com/12021443/62924869-b54f8e00-bdb9-11e9-99c1-f53133fdeadd.png)

And prefer 

![image](https://user-images.githubusercontent.com/12021443/62924971-f182ee80-bdb9-11e9-8368-420e61b0e3a8.png)

**Comment by arturovt** [comment]
@feitzi This is quite complicated topic I'd say. There are not best practices or well-established approaches, only trade-offs that people try to accompany. You could achieve it by using `fromEvent + auditTime`, don't forget to query your button using `ViewChild`.

**Comment by splincode** [comment]
@arturovt I think we could add an item in the documentation about throttling actions

**Comment by feitzi** [comment]
@splincode thanks for the tip 😃  👍 

but with your solution, I cannot run the example successful. 
We got now a log message, but the observable is not handled by ngxs and therefore it will not be executed. (Without the decorator ngxs handles the observable and everthing is working)
Updated [Stackblitz](https://stackblitz.com/edit/ng-ngxs-playground-8lyly9)

![](https://i.imgur.com/9RZUViU.png)

@arturovt Sorry, I didnt understand your hint. What do you exactly mean with `fromEvent` and button querying?  It is true that this approach does not match the Flux pattern, perhaps the solution to achieve my goal is a totally deferential one as the decorator. I am not sure 😕

**Comment by arturovt** [comment]
@feitzi I'm not sure if the ~~Flux~~ Redux pattern has to do something with debouncing :)

**Comment by feitzi** [comment]
@arturovt thanks, this solution could also work for my problem :)

**Comment by feitzi** [comment]
As now described in the [docs](https://www.ngxs.io/recipes/debouncing-actions), my desired behavior can be reached with the `actions$` stream.
