### ISSUE TITLE
🐞[BUG]: HMR need skip for production build

### ISSUE THREAD

**Issue by splincode** [ngxs/store#1233]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/12021443/63003485-ed6dd400-be80-11e9-8aa9-4e2d4053d906.png)

**Comment by markwhitfeld** [comment]
A better description with a repo would be great Max ;-)
Should I close this until then?

PS. I'm pretty sure I tested this when we first released the hmr plugin and it was tree shaken in the production build.

**Comment by splincode** [comment]
I will add repo for reproduce in later

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/63006458-46406b00-be87-11e9-912f-8f9c36be3e37.png)

**Comment by splincode** [comment]
WARNING in Lazy routes discovery is not enabled. Because there is neither an entryModule nor a statically analyzable bootstrap code in the main file.

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/63009394-12684400-be8d-11e9-9744-b06e7c68c1ca.png)

@markwhitfeld

```ts
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { enableProdMode, NgModuleRef } from '@angular/core';

import { environment } from './environments/environment';
import { AppModule } from './app.module';

if (environment.production) {
    enableProdMode();
}

const bootstrap: () => Promise<NgModuleRef<AppModule>> = (): Promise<NgModuleRef<AppModule>> =>
    platformBrowserDynamic().bootstrapModule(AppModule);

if (environment.hmr) {
    // improve three shaking
    import('@ngxs/hmr-plugin').then(({ hmr }) => hmr(module, bootstrap).catch((err: Error) => console.error(err)));
} else {
    bootstrap().catch((err: Error) => console.error(err));
}
```

**Comment by arturovt** [comment]
@splincode should I do a PR to update the docs?
