### ISSUE TITLE
❓[SUPPORT]:  NullInjectorError: No provider for StateFactory!

### ISSUE THREAD

**Issue by RoanKathrina** [ngxs/store#1251]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 

Slack: https://ngxs.slack.com
Stackoverflow: https://stackoverflow.com/questions/tagged/ngxs
Twitter: https://twitter.com/NgxsStore
Reddit: https://www.reddit.com/r/NGXS/

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by arturovt** [comment]
What is that?

**Comment by arturovt** [comment]
Closing until reproduction is provided.
