### ISSUE TITLE
🐞[BUG]: It looks like the migrations version is never set.

### ISSUE THREAD

**Issue by kayvanbree** [ngxs/store#1264]
### Affected Package

@ngxs/storage-plugin

### Description

The code in https://github.com/ngxs/store/blob/master/packages/storage-plugin/src/storage.plugin.ts never seems to set a version number for a migration. It gets the version number from either `state.version` or `state[options.versionKey`. 

I think the design of version management in the migrations plugin may be a bit off. I suggest taking the index of the migration as the version and checking if that version is higher than `state.version`. At the moment it will migrate if it finds the same version, and it won't migrate if the version of the state is a different one (neither higher or lower).

## 🔬 Minimal Reproduction

- Create a new application with @ngxs/store and @ngxs/storage-plugin
- Create some kind of a state
- Create a migration with version 1
  - It won't ever set version 1 as the current migration in the state.

## Environment

I looked at the code at the master branch, and it's the same as in my environment. 

<pre><code>
Libs:
"@angular/animations": "^8.2.2",
    "@angular/cdk": "^8.1.2",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/material": "^8.1.2",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@ngxs/router-plugin": "^3.5.0",
    "@ngxs/storage-plugin": "^3.5.0",
    "@ngxs/store": "^3.5.0",
    "hammerjs": "^2.0.8",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by kayvanbree** [comment]
Some more information: 

When I set the version of the first migration to 1 it won't ever run. If I set it to undefined it will run, but it will never set a version because its undefined. 

I just got one user yet so I will just push my new version without backward compatibility in the store, but this issue should be solved I think.

**Comment by arturovt** [comment]
Wouldn't you want to make a PR?

**Comment by kayvanbree** [comment]
I would like to create a PR, but first I'll have to know I am not a complete idiot by missing some obvious step. Can anybody confirm this bug?

**Comment by kayvanbree** [comment]
I saw that you recently added a comment I missed to the README:

```
NgxsStoragePluginModule.forRoot({
      migrations: [
        {
          version: 1,
          key: 'zoo',
          versionKey: 'myVersion',
          migrate: (state) => {
            return {
              newAnimals: state.animals,
              version: 2 // Important to set this to the next version!
            }
          }
        }
      ]
    })
```

Here you are migrating to version 2, but you have to give the migration version 1. Maybe the plugin could just look for any version numbers higher than the version currently in the store? 

Either way, I think it might work best to save the version number of the migration to the state, instead of setting it in the migrate function.

**Comment by kayvanbree** [comment]
Hmmm, looks like its important to put your migrations in the correct order, or else you could end up running only one migration were several are needed, rendering your application broken.

```
if (options.migrations) {
            options.migrations.forEach(strategy => {
              const versionMatch =
                strategy.version === getValue(val, strategy.versionKey || 'version');
              const keyMatch = (!strategy.key && isMaster) || strategy.key === key;
              if (versionMatch && keyMatch) {
                val = strategy.migrate(val);
                hasMigration = true;
              }
            });
          }
```

For example the following migrations would migrate only one version when initializing the store, while three migrations are needed for the application to function correctly:

```
const options = {
  key: 'counter',
  migrations: [
    {
      version: 3,
      key: 'counter',
      versionKey: 'version',
      migrate: (state: any) => {
        state = {
          counts: state.count,
          version: 4
        };
        return state;
      }
    },{
      version: 2,
      key: 'counter',
      versionKey: 'version',
      migrate: (state: any) => {
        state = {
          count: state.counts,
          version: 3
        };
        return state;
      }
    },
    {
      version: 1,
      key: 'counter',
      versionKey: 'version',
      migrate: (state: any) => {
        state = {
          counts: state.count,
          version: 2
        };
        return state;
      }
    }
  ]
};
```

At the first page load it will migrate version 1, making it version 2, after which it will run the application missing 2 migrations. If you refresh it will again ignore one of the migrations and only at a second refresh you will be fully migrated. This is not mentioned in any docs as far as I know.

**Comment by kayvanbree** [comment]
[This commit](https://github.com/kayvanbree/store/commit/ff92ece074004e40395ec1f7bbde16033521e1a8) would change it so that the version of a migration is saved to the current saved state. When the saved state doesn't have a version, it will assume it's version 0. That means you don't have to set your version in the migrate function anymore, but it also means this is a breaking change:

```
NgxsStoragePluginModule.forRoot({
          key: 'counter',
          migrations: [
            {
              version: 1, // This is saved to your state. Add a migration with a higher version and it will migrate to that.
              key: 'counter',
              versionKey: 'version',
              migrate: (state: any) => {
                state = {
                  counts: state.count
                };
                return state;
              }
            }
          ]
        })
```

**Comment by blankplanet** [comment]
Add migration for 'version undefined' to 'version 1' first. it's works for me.
```
{
  version: undefined,
    versionKey: 'version',
    migrate: (state) => {
    return {
      ...state,
      version: 1
    };
  }
}

**Comment by arturovt** [comment]
Seems like the issue is a bit stale and it also has a solution in the comment above, so closing it for now.
