### ISSUE TITLE
DevTools Replay

### ISSUE THREAD

**Issue by amcdnl** [ngxs/store#127]
Ability to replay actions w/ dev tools

**Comment by amcdnl** [comment]
Started work on this, supports jump to action and jump to state. Still needs skip action and dispatch.

**Comment by amcdnl** [comment]
Skip is not implemented but not really that possible since are actions aren't pure

**Comment by shivamd20** [comment]
> Skip is not implemented but not really that possible since are actions aren't pure
 I tend to write my actions as pure functions. 
Shouldn't there be an option for the people who still prefer to keep their states pure?
