### ISSUE TITLE
📚[DOCS]: Mention DeepFreeze in docs

### ISSUE THREAD

**Issue by ugran** [ngxs/store#1289]
Some Libraries like https://github.com/reppners/ngx-drag-drop work upon mutable objects, but in dev mode, each object saved to state is frozen on each sub-level.

There are some cases when we need objects mutable, Please mention about this deepFreeze in devMode in the docs.

I run across this in an article of Maxim Ivanov by chance after more than an hour of searching for a proper solution.

**Comment by arturovt** [comment]
[Isn't that mentioned](https://www.ngxs.io/getting-started/installation)?

> Options such as developmentMode can be passed to the module as the second argument in the forRoot method. In development mode, plugin authors can add additional runtime checks/etc to enhance the developer experience. Switching to development mode will also freeze your store using deep-freeze-strict module.

**Comment by ugran** [comment]
> [Isn't that mentioned](https://www.ngxs.io/getting-started/installation)?
> 
> > Options such as developmentMode can be passed to the module as the second argument in the forRoot method. In development mode, plugin authors can add additional runtime checks/etc to enhance the developer experience. Switching to development mode will also freeze your store using deep-freeze-strict module.

Oh, I'm sorry for the false alarm. Totally my bad...
