### ISSUE TITLE
🐞[BUG]: 

### ISSUE THREAD

**Issue by dfa1234** [ngxs/store#1291]
### Affected Package
@ngxs/store

### Is this a regression?
no

### Description /🔬 Minimal Reproduction
I figured I need to wrap my subscription in a `setTimeout` in this situation (service constructor).
Without setTimeout i only catch 'undefined' (no 'null' nor my user object, as expected)

```typescript
@Injectable({providedIn: 'root'})
export class UserService {

  public user: User;

  constructor(private store: Store) {
    setTimeout(()=>{
      this.store.select(state => state.global.user).subscribe(
        u => this.user = u
      );
    })
  }

}
```

## Environment
Libs:
- @angular/core version: 8.*
- @ngxs/store version: 3.5.0

Browser:
- [* ] Chrome (desktop)

**Comment by arturovt** [comment]
Have you read this before creating the issue? :wink: 
> **Note:** Our policy is that issues reported without a reproduction will be closed immediately and then reopened once a reproduction has been provided. Please respect the developers of this project by doing this. We give of our personal time to work on this project and would rather be spending our time fixing or enhancing the library than chasing down badly described or unreproducable issues.

**Comment by arturovt** [comment]
Closing until a reproduction provided.

**Comment by dfa1234** [comment]
yes there is a missing piece, 
(plus how I remove the label regression??)
I have time I will complete (it's not a very important issue) I will close meanwhile

**Comment by arturovt** [comment]
Just click the `X` mark

![image](https://user-images.githubusercontent.com/7337691/63953797-aee43600-ca8a-11e9-8429-9ebc311f30bd.png)

**Comment by arturovt** [comment]
I will reopen this issue if you provide some example on the stackblitz/codesandox!
