### ISSUE TITLE
🐞[BUG]: ErrorHandler not triggered when http error intercepted by HttpInterceptor

### ISSUE THREAD

**Issue by ConnorJBeck** [ngxs/store#1305]
### Affected Package
@ngxs/store

### Is this a regression?

Not that I'm aware of. However, it's been around for at least a little while, as this StackOverflow post describes the same thing from 8 months ago. https://stackoverflow.com/questions/53720909/angular-custom-error-handler-is-not-always-hit-after-errors

### Description

If you have both a custom implementation of ErrorHandler and HttpInterceptor, then make an http call inside a state class that returns an `HttpErrorResponse`, that response will be successfully intercepted by the `HttpInterceptor`, but if the error is rethrown, it is not successfully intercepted by the `ErrorHandler`.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/ngxs-simple-h1w9y6

## Environment

<pre><code>
Libs:
- @angular/core version: latest
- @ngxs/store version: latest

Browser:
- [ XX ] Chrome (desktop) version XX
- [ ?? ] Chrome (Android) version XX
- [ ?? ] Chrome (iOS) version XX
- [ ?? ] Firefox version XX
- [ ?? ] Safari (desktop) version XX
- [ ?? ] Safari (iOS) version XX
- [ ?? ] IE version XX
- [ ?? ] Edge version XX
 
For Tooling issues:
- Node version: 10.16.2
- Platform: Mac, Linux, Windows
</code></pre>

**Comment by arturovt** [comment]
If you return an observable, that it will be intercepted.
![image](https://user-images.githubusercontent.com/7337691/64210041-dbdd8200-ceaa-11e9-8414-abdd3c183a2e.png)

**Comment by arturovt** [comment]
Should we close?

**Comment by ConnorJBeck** [comment]
Ah... So I'm guessing this falls into the category of won't fix then? I updated my stackblitz a bit to show a better example of my use case, where I perform some operations in the subscribe. I suppose I could rewrite it as 

```javascript
  @Action(MakeHttpCall)
  add({ getState, setState }) {
    return this.httpClient.get('fakeUrl')
         .pipe(tap(results => {
            setState(results);
         }))
  }
```

But I just hate using tap when I can avoid it. This seems like a pretty standard pattern, is there a better way that doesn't involve the desired effect being treated like a side-effect?

**Comment by arturovt** [comment]
`tap` is considered as anti-pattern only if you're doing some manipulations with the stream value. Is it a side-effect?
```ts
const todos = [...];
from(todos).pipe(
  tap(todo => {
    console.log(`Todo with id ${todo.id} was emitted`);
  })
)
```

And what about this?
```ts
const todos = [...];
from(todos).pipe(
  tap(todo => {
    // Mutate by reference
    todo.id = null;
  })
)
```

So I cannot concur with you why you think that `tap -> setState` is treated like a side-effect. If the problem can be solved by applying the tap operator then there is no need to do extra work.

By default doing extra work is bad, so unless they can bring up an argument why that extra work SHOULD be done.

**Comment by ConnorJBeck** [comment]
My argument is simply that the `tap` operator as a whole is something I personally avoid, because by implication it is causing side effects. Using it for logging or metrics is fine, but when the desired behaviour (changing the state) is achieved through a tap, that feels weird to me. The pipe operator, as far as I'm concerned, is meant for manipulating and transforming the stream of data coming into it, while the subscribe onNext function is for taking the transformed data and applying it or using it for something. `tap` is a way of spying on that stream of transformations and creating side effects, as by design it doesn't (shouldn't) affect the stream in any way. In this example, the desired behaviour - the updating of the state - is done in the `tap` operator. It is essentially a side effect of the "main" operation of making an http call.

Anyways, it's a matter of opinion, and you're absolutely right that it would simply create more work. I won't try to change your opinion, and I'll go ahead and follow this pattern in the future. Thanks for your help.
