### ISSUE TITLE
🚀[FEATURE]: Expose StateFactory and StateContextFactory for ngxs-data plugin

### ISSUE THREAD

**Issue by splincode** [ngxs/store#1323]
### Relevant Package
 This feature request is for @ngxs-labs/data

### Description

Problem with UMD modules (Éµn as StateFactory)

![image](https://user-images.githubusercontent.com/12021443/64888521-e7cbff80-d673-11e9-9481-894485f0e1b6.png)

![image](https://user-images.githubusercontent.com/12021443/64888461-c23ef600-d673-11e9-8fc3-63f3d7ead6cf.png)

### Describe the solution you'd like

Expose StateFactory, StateContextFactory for plugins API.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by markwhitfeld** [comment]
Hi @splincode I really do not want to expose the internals of NGXS for plugins. This can compromise the fundamentals of the framework and cause instability in the plugins if we change these internals.

I will respond to your PR #1325 with a potential option here (Exposing an InjectionToken under the internals subpackage).
