### ISSUE TITLE
🚀[FEATURE]: Custom deserializer

### ISSUE THREAD

**Issue by davidmorissette** [ngxs/store#1329]
### Relevant Package

 This feature request is for @ngxs/storage-plugin

### Description
 The plugin currently uses a global deserializer which calls "JSON.parse" and returns a generic JavaScript object. When the state model is a class (instead of being an interface or a type), the current implementation does not provide a way to convert the generic object into an concrete instance.

### Describe the solution you'd like
 A new options value "serialization" should provide the ability to define a collection of key/deserializer so we can inject our own implementation:

```
NgxsStoragePluginModule.forRoot({
      serialization: [
        {
          key: 'zoo',
          onAfterDeserializer: (state) => {
            // return concrete instance of the model
          }
        }
      ]
    })
```

**Comment by arturovt** [comment]
@davidmorissette would you want to do a PR? We would be happy :)

**Comment by splincode** [comment]
@markwhitfeld @arturovt what do you think about? 

```ts
import { NgxsSerializable } from '@ngxs/storage-plugin';

class AppState implements NgxsSerializable<AppStateModel> {
  public serialize(state): string {
    return JSON.stringify(state); // or custom stringify
  }

   public deserialize(value: string): AppStateModel {
    return JSON.parse(value); // or custom serial
  }
}
```

```ts
interface NgxsSerializable<T> {
 serialize?(state: T): string;
 deserialize?(value: string): T;
}
```

**Comment by davidmorissette** [comment]
@arturovt https://github.com/ngxs/store/pull/1447
