### ISSUE TITLE
🐞[BUG]: Navigation in devtools timeline doesn't use correct class and throws error

### ISSUE THREAD

**Issue by arquadrado** [ngxs/store#1331]
### Affected Package

This issue is caused by @ngxs/devtools-plugin

### Is this a regression?
Never had used @ngxs on a project before.

### Description

I am retrieving a list of objects of certain class via selector and iterating through them in a template for loop and passing the class instance to a method in the component. In this method I use a getter method of this class to retrieve a property. The problem comes when I navigate the app state using the dev tools. Instead of the method that I just referenced receiving an instance of the class it receives a plain javascript object with only the properties so it throws an error about trying to use a function that doesn't exist. Everything is typified so missing types are not the problem.

### Reprodution
https://stackblitz.com/edit/angular-whzmnn

Try add items and then use devtools to navigate through state

## Environment

<pre><code>
Libs:
- @angular/core version: 8.1.3
- @ngxs/store version: 3.5.1

Browser:
- [x] Chrome (desktop) version 76
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.8.1
- Platform: Linux

**Comment by splincode** [comment]
@arquadrado You should not use entities to save them, you should only save ordinary objects

![image](https://user-images.githubusercontent.com/12021443/68607029-c72bf480-04c0-11ea-9635-818aa34a89ed.png)

Because then they become ordinary objects in the future
