### ISSUE TITLE
🐞[BUG]: Testing store is not working

### ISSUE THREAD

**Issue by bokzor** [ngxs/store#1337]
## 🔬 Minimal Reproduction

I tried to implement a test for a store following the documentation.
Without success...  
Now, I don't know if the documentation is outdated or if I did something wrong.

The test is in pizzas/store/pizzas-spec.ts

Repo : https://github.com/bokzor/ngxs-pizza

Stackblizt : To run the test online 
https://stackblitz.com/github/bokzor/ngxs-pizza/tree/stackblitz-tests

**Comment by gilsdav** [comment]
Issue in the code.

You need to add store name level.
Because your store is named "pizzas" it will looks like this:
```
export const INIT_STATE = {
  pizzas: {
    pizzas: [{ id: 1, name: 'Pizza1', toppings: [] }, { id: 2, name: 'Pizza2', toppings: ['Cheese'] }],
    pizzasLoading: false,
    selectedPizza: null,
    toppings: []
  } as PizzasStateModel
};
```

**Comment by arturovt** [comment]
Sorry for being pedantic but you have to provide SMALL examples, in the terms of StackOverflow this sounds like "Minimal, Reproducible Example". Also your stackblitz is not reproducible. It throws "describe is not defined".
