### ISSUE TITLE
[Question] Some features action inheritance, selector inheritance, dynamic childs, ....

### ISSUE THREAD

**Issue by APRSystem** [ngxs/store#1342]
Hello, 
We have made several modifications starting from version 3.4.0
1 Dynamic state management (add, delete state)
now you can use the function to dynamically add a new state, specifying its parent, and destroy it.
The goal was to support dynamically created components based on configuration, which allows you to build an application by defining it using configuration.
You can now dynamically add the same state class to different store locations
2. Sending actions to the state fragment.
Since you can now have two different instances of the same state class, you had to send actions to only one of these instances. This was resolved using the location parameter.
The action can be sent to a specific location within a tree fragment
3. Selecting the state fragment taking into account the location.
Currently, you can add a location parameter to @selector that indicates where the state is desired
4. inheritance of selectors
we have parent class and child store class. The selector is implemented in the parent and the child class is used for subscription
other minor modifications
5. Command and notification action. The notification may not reach the destination, while the command if it does not find the destination will display an error on the console
6. Subscription to a non-existing blind area causes a message on the console
7. Other minor modifications resulting from points 1, 2

Why these modifications were made.
Our program stores all data and components in store. In addition, we wanted to be able to run a given business module several times. This means that the store area should have module areas - lines from module 1 instance and module 2 instance. All communication with actions and selectors should take place within each business module separately. So the lines store structure is the same, they differ only in locations. This gives you the opportunity to restart the same module not using the browser tab but the internal program tab. As a result, the whole environment is loaded once and the whole works quickly and the user can easily switch between instances of business modules.

I would like to make a pull request, but I don't know if it is suitable for such a throw. the code is at: https://github.com/APRSystem/store
Please let me know if this makes sense, then I will try to update to the latest version of ngxs.
I do not know if what I wrote is clear, if not please ask.

Regards Piotr Such

**Comment by splincode** [comment]
You can always do this in your application.

```ts
import { Store } from '@ngxs/store';
// ..

export class MyStore extends Store {
 // ...
}

@NgModule({
  imports: [NgxsModule.forRoot([ ... ])],
  providers: [
    { provide: Store, useClass: MyStore  } 
  ]
})
```

**Comment by APRSystem** [comment]
ad 1) Right
I could add work methods to the inherited store, then there would be less integration into the base project,
good point :)
I will try to refactor it so
However, I do not understand what you wanted to convey in ad 2, please explain ...
Because it's probably not my case.

my case looks like this:
@Staste ({...})
export class AbstractWidetState {
@Selector () static getLoadeWidget $ (val)
    return ...
}

@Staste ({...})
export class TaskWidetState extends AbstractWidetState {
...
}

and you are in the code
myObservable $ = this.store.selectInLocation (AbstractWidetState.getLoadeWidget, locationTaskWidet)
This gives me the implementation of the selector in the base class and the ability to use it for each of the child classes

**Comment by arturovt** [comment]
There are too many changes in your repository and I cannot understand what I should look at. We can create a `ngxs-labs` repository for you where you could transfer your features.

**Comment by APRSystem** [comment]
okay
maybe at the beginning I would record a small video showing the user interface and what is happening in the store.
This will allow you to better understand your business goal, and it may turn out that you can simply do something better and smarter.
Around Wednesday I will upload a video.

**Comment by APRSystem** [comment]
Hello
I asked about this video
and we need to get back to the idea of ngxs-labs
I have not used this possibility, I assume that this is a simple project which is to be illustrative.
If there are guidelines on what to follow to make it easier for you, please send a link

best regards...

**Comment by arturovt** [comment]
Is there any progress on this?
