### ISSUE TITLE
🐞[BUG]: Store does not wait for APP_INITIALIZER

### ISSUE THREAD

**Issue by unlight** [ngxs/store#1349]
### Affected Package

The issue is caused by package @ngxs/store

### Is this a regression?

No

### Description
Store does not wait for APP_INITIALIZER.
Looks like store ignores `APP_INITIALIZER` and starts resolving injections immediately.
But some injected services can depend on `APP_INITIALIZER`.

## 🔬 Minimal Reproduction
```
git clone https://github.com/unlight/rd-angular-starter
cd rd-angular-starter
git checkout -f origin/app-initializer
npm i
npm run dev
start  http://localhost:4200
// => main.ts:13 Error: No setting found with the specified key [locale]!
ConfigService is not ready to use, loader is not yet loaded config.json
```

## Environment

<pre><code>
Libs:
- @angular/core version: 9.0.0-next.7
- @ngxs/store version: 3.5.1
 
For Tooling issues:
- Node version: 12.9
- Platform:  Windows
</code></pre>

**Comment by arturovt** [comment]
I'm not able to run this application locally as I'm onto phone. After looking at the codebase I can say that your assumption is wrong. You have to check docs to understand how Angular resolves APP_INITIALIZER token, also services cannot depend on APP_INITIALIZER as it references promise factories.

I'm also not familiar with that external package you're using ngx-config/core and its codebase. You have to transfer this repository to the stackblitz or codesandbox, this would bring more profit for reviewers.

**Comment by arturovt** [comment]
Frankly speaking I don't know what is `ngx-config/core` package used for, as I've never used it before. This is not the issue of NGXS itself because NGXS depends on the Angular's DI system and its mechanism. State class is a provider and initialized with the root module:
* `bootstrapModuleFactory`
* `resolveNgModuleDep -> AppState`
* `createProviderInstance -> AppState`

There are different workarounds. Next times please write what you'd want to achieve, e.g.:
* I want to get `locale` setting and do ...whatever...
* I want to get `locale` setting and save it to state...
* blah blah

1. 

```ts
export class AppModule implements DoBootstrap {
    constructor(private configService: ConfigService) {}

    ngDoBootstrap(appRef: ApplicationRef) {
        appRef.bootstrap(AppComponent);
        console.log(this.configService.getSettings('locale'));
    }
}
```

2.

```ts
export class AppState implements NgxsAfterBootstrap {
    constructor(private configService: ConfigService) {}

    ngxsAfterBootstrap(ctx: StateContext<AppStateModel>) {
        console.log(this.configService.getSettings('locale'));
        ctx.setState({ isInitialized: true });
    }
}
```

**Comment by splincode** [comment]
@arturovt I think we need to specify in the documentation about `Angular Bootstrap + NGXS Bootstrap`

**Comment by arturovt** [comment]
We already have an information about life cycle hooks and `ngxsAfterBootstrap`. This doesn't depend on the NGXS, this code will also throw:
```ts
@Injectable({ providedIn: 'root' })
export class Config {
  private a: number | null = null;

  setViaAppInitializer() {
    this.a = 10;
  }

  getA(): never | number {
    if (this.a === null) {
      throw new Error('A is not available!');
    }

    return this.a;
  }
}

@Injectable({ providedIn: 'root' })
class AppState {
  constructor(config: Config) {
    config.getA();
  }
}

export function appInitializerFactory(config: Config) {
  return () => {
    config.setViaAppInitializer();
    return Promise.resolve();
  };
}

@NgModule({
  imports: [BrowserModule],
  declarations: [AppComponent],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: appInitializerFactory,
      multi: true,
      deps: [Config]
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(appState: AppState) {}
}
```

**Comment by splincode** [comment]
I understand, but we could write code in a description that should be avoided

**Comment by arturovt** [comment]
Could you make a PR so we'd able to close this issue?

**Comment by arturovt** [comment]
@unlight did the code, I've showed, help you? Or is there anything else I can do for you? :)

**Comment by unlight** [comment]
@arturovt 
Thanks, but I think solution with ngDoBootstrap and other lifecycle hooks looks too complicated.
I'll try to find more simpler workaround, or rework using of ConfigService which uses `APP_INITIALIZER`.

You can close this issue as non-relevant.
