### ISSUE TITLE
❓[SUPPORT]:  Search From Different Component

### ISSUE THREAD

**Issue by jtan80813** [ngxs/store#1351]
I'm trying to figure out how will i able to search in NGXS from different component. I have my searchbar from the navbar component while i'm displaying my data from app component which is a different component. 
Please see this stackblitz link 

CLICK [HERE](https://stackblitz.com/edit/ngxs-searching-different-component?file=src/app/navbar/navbar.component.html)

Thank you!

**Comment by Thenis** [comment]
This is how I would do it
https://stackblitz.com/edit/ngxs-searching-different-component-kfraqk

**Comment by jtan80813** [comment]
Thanks Thenis. Someone solved it too in stackoverflow [https://stackblitz.com/edit/ngxs-searching-different-component-erexd2?file=src%2Fapp%2Fnavbar%2Fnavbar.component.ts](url)

**Comment by splincode** [comment]
https://stackblitz.com/edit/ngxs-searching-different-component-ei1rj4?embed=1&file=src/app/filter.pipe.ts

**Comment by splincode** [comment]
Better use pipe for this instead ngxs, because state manager for this overcomplicated for understand
