### ISSUE TITLE
🚀[FEATURE]: SSE support

### ISSUE THREAD

**Issue by ceyhunn** [ngxs/store#1364]
### Description
It would be nice to add feature sse (server sent events).  

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by arturovt** [comment]
Could you describe in more detail what you'd want to achieve?

I don't know why do we need this feature as most browsers have this feature builtin. You can just create your own service and do whatever you want there.

**Comment by splincode** [comment]
@arturovt Yes, I, too, also, agree.

**Comment by ceyhunn** [comment]
SSE differs from websocket. You have plugin to implement websocket. That is why I requested this feature.
> I  don't know why do we need this feature as most browsers have this  feature builtin. You can just create your own service and do whatever  you want there.

Websocket also can be implemented by a service.

**Comment by arturovt** [comment]
@ceyhunn 

You have to provide more details.

> It would be nice to add feature sse

is not a good description. You could create an appropriate document with such items:

* Overview
    * A short description the feature, similar to an abstract for a paper/presentation...
* User details
    * How to use this feature...
* Technical details
    * Why is this feature suitable for the NGXS, would we have states/actions etc...
* References
    * Some useful links here with good guides...

That's how we can go on. I don't have experience with SSE but I could help you with implementation.

**Comment by ceyhunn** [comment]
@arturovt , sorry for lack info.
I am explaining you:
SSE is similar to websocket, but websocket is bidirectional. SSE just listens to the event source, but can't answer to the message like websocket. I have such a situation that I don't need websocket, SSE is suitable for me. It will also helps the community.
You can also read great explanation from [here](https://www.smashingmagazine.com/2018/02/sse-websockets-data-flow-http2/), and  there is also [Angular implementation](https://medium.com/@chrisbautistaaa/server-sent-events-in-angular-node-908830cc29aa).

**Comment by arturovt** [comment]
@ceyhunn would you want to contribute and create a package?

**Comment by ceyhunn** [comment]
> So if I understand correctly SSE is a mechanism that listens to events from some endpoint (like `GET /todos`) but doesn't respond back, right?

Yes, exactly.

**Comment by ceyhunn** [comment]
> would you want to contribute and create a package?

I have a lot of work. If I have a time, surely I will contribute.
