### ISSUE TITLE
🐞[BUG]: ES3 Target compilation

### ISSUE THREAD

**Issue by AmitMY** [ngxs/store#1374]
### Affected Package
The issue is caused by @ngxs/store

### Is this a regression?
I don't know

### Description
Some platforms require ES3 compilation, unfortunately.
When setting in `tsconfig.json` the target to be `es3`, compilation fails because of action decorators.

## 🔬 Minimal Reproduction

**Note:** Our policy is that issues reported without a reproduction will be closed immediately and then reopened once a reproduction has been provided. Please respect the developers of this project by doing this. We give of our personal time to work on this project and would rather be spending our time fixing or enhancing the library than chasing down badly described or unreproducable issues.
Please delete this note once you have read it.

 https://stackblitz.com/edit/angular-2xkhyh
Note that this app works. You have to download it, and change the tsconfig target to es3.

## 🔥 Exception or Error
<pre><code>

ERROR in src/app/store/api-data/api-data.state.ts:25:3 - error TS1241: Unable to resolve signature of method decorator when called as an expression.

25   @Action(GetConnectorsAction)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/store/api-data/api-data.state.ts:34:3 - error TS1241: Unable to resolve signature of method decorator when called as an expression.

34   @Action(GetConfigAction)
     ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/store/api-data/api-data.state.ts:44:3 - error TS1241: Unable to resolve signature of method decorator when called as an expression.

44   @Action(GetSchemaAction)
     ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/store/report/report.state.ts:22:3 - error TS1241: Unable to resolve signature of method decorator when called as an expression.

22   @Action(SetConnectorAction)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/store/report/report.state.ts:29:3 - error TS1241: Unable to resolve signature of method decorator when called as an expression.

29   @Action(SetDateRangeAction)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/store/report/report.state.ts:34:3 - error TS1241: Unable to resolve signature of method decorator when called as an expression.

34   @Action(SetConfigAction)
     ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/store/report/report.state.ts:42:3 - error TS1241: Unable to resolve signature of method decorator when called as an expression.

42   @Action(SetFieldsAction)
     ~~~~~~~~~~~~~~~~~~~~~~~~
src/app/store/report/report.state.ts:69:3 - error TS1241: Unable to resolve signature of method decorator when called as an expression.

69   @Action(SetConnectorAction)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/store/report/report.state.ts:74:3 - error TS1241: Unable to resolve signature of method decorator when called as an expression.

74   @Action(SetDateRangeAction)
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/store/report/report.state.ts:80:3 - error TS1241: Unable to resolve signature of method decorator when called as an expression.

80   @Action(SetFieldsAction)
     ~~~~~~~~~~~~~~~~~~~~~~~~
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.4
- @ngxs/store version: 3.3.2
<!-- Check whether this is still an issue in the most recent Angular version -->
 
For Tooling issues:
- Node version: v10.15.0
- Platform:  Windows

Others:
    "typescript": "~3.5.3",
</code></pre>

**Comment by splincode** [comment]
ES3 not supported, use ES5 or ES2015

**Comment by AmitMY** [comment]
ES5 is not supported by Google Suite (apps script)
And I obviously can do @ts-ignore on these errors, but thats ugly.

**Comment by arturovt** [comment]
@AmitMY I'm not sure if it's our issue. I've opened a playground and saw that decorators are not supported when targetting es3 at all.

**Comment by AmitMY** [comment]
hmmm... All of the angular decorators work just fine
thanks anyway

**Comment by arturovt** [comment]
@AmitMY depends on how do you work with Angular. Is AOT/Ivy enabled by default, etc.
