### ISSUE TITLE
🐞[BUG]: State operators typing issue

### ISSUE THREAD

**Issue by bvolkj** [ngxs/store#1375]
### Affected Package

 The issue is caused by package @ngxs/3.5.1

### Is this a regression?

 No (only tested 3.5.0)

### Description

 
When using the typescript strict compiler option there are Typescript compilation Errors when using certain state operators.

## 🔬 Minimal Reproduction
As it isn't possible to edit tsconfig files in stackblitz, I created a repo to reproduce the issue
https://github.com/bvolkj/ngxs-typing/tree/master/test

As additional information, this is what I did:

- set Typescript compilerOption strict to `true`
tsconfig.json:
 ```
 {
  "compileOnSave": false,
  "compilerOptions": {
    "strict": true,
    "baseUrl": "./",
...
``` 
- create a state with an action that uses any of these state operators: removeItem, append, or insertItem. I used the following example code: https://www.ngxs.io/advanced/operators#advanced-example

## 🔥 Exception or Error
When starting the application with `ng serve` the following errors occur:
<pre><code>

src/app/modules/profile/store/zoo.state.ts:36:17 - error TS2322: Type '(existing: string[]) => string[]' is not assignable to type 'string[] | StateOperator<string[]> | undefined'.
  Type '(existing: string[]) => string[]' is not assignable to type 'StateOperator<string[]>'.
    Types of parameters 'existing' and 'existing' are incompatible.
      The type 'readonly string[]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.

36         zebras: append([payload])
                   ~~~~~~~~~~~~~~~~~

  src/app/modules/profile/store/zoo.state.ts:36:17
    36         zebras: append([payload])
                       ~~~~~~~~~~~~~~~~~
    Did you mean to call this expression?
src/app/modules/profile/store/zoo.state.ts:45:17 - error TS2322: Type '(existing: string[]) => string[]' is not assignable to type 'string[] | StateOperator<string[]> | undefined'.
  Type '(existing: string[]) => string[]' is not assignable to type 'StateOperator<string[]>'.
    Types of parameters 'existing' and 'existing' are incompatible.
      The type 'readonly string[]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.

45         pandas: removeItem<string>(name => name === payload)
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/modules/profile/store/zoo.state.ts:45:17
    45         pandas: removeItem<string>(name => name === payload)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Did you mean to call this expression?

</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.9
- @ngxs/store version: 3.5.1
- typescript: 3.5.3

 
For Tooling issues:
- Node version: v12.10.0
- Platform:  Linux

</code></pre>

**Comment by arturovt** [comment]
Closing until reproduction is provided. Sorry, but this is our policy. You can create a github repo and provide here.

**Comment by bvolkj** [comment]
I created a repo that shows the issue (I also updated the description above):
https://github.com/bvolkj/ngxs-typing/tree/master/test

**Comment by splincode** [comment]
@markwhitfeld I have some problem

![image](https://user-images.githubusercontent.com/12021443/67048185-6f59d200-f13c-11e9-9f17-2e08feb6e2c7.png)

**Comment by splincode** [comment]
@bvolkj please try `@dev` version

**Comment by bvolkj** [comment]
@splincode thanks a lot, the errors are gone now. :tada:
