### ISSUE TITLE
Actions Subscribe

### ISSUE THREAD

**Issue by mailok** [ngxs/store#138]
### Versions

```
* ngxs: 2.0.0-rc.18
* @angular/core: 5.2.9
```

### Repro steps

* Step 1: Defining Async Actions

```
@Action(SearchPeoples)
  serarchPeoples({ getState, setState }: StateContext<ParkStateModel>) {
    const state = getState();
    this.http.get<Search>('https://randomuser.me/api/?results=5').subscribe(value => {
      console.log('updating the state...');
      setState({
        ...state,
        search: value.results
      });
      console.log('status updated.');
    });
  }
```

* Step 2: Creating function to dispatch action and subscribe

```
search() {
    this.store.dispatch(new SearchPeoples()).subscribe(value => {
      console.log('The action is completed.');
    });
  }
```

* Step 3: Call function search

### Observed behavior

In the browser console displays:
![captura](https://user-images.githubusercontent.com/3769277/37792514-5aca8b64-2de2-11e8-9cac-eadf2079a40a.PNG)

### Desired behavior

I hoped log first : **updating the state...**
then : **status updated.**
and finally:  **The action is completed.**

I thought to subscribe only receive a result when the action will update the status.
It is in this way that should work or not?

**Comment by yarrgh** [comment]
The problem here is that the dispatch observable finishes before the observable inside your action since it isn't waiting for the observable inside the action.

What happens if you return the Observable from the action and instead of subscribing to it use a rxjs operator, like `tap()` to do the work inside the observable?

**Comment by mailok** [comment]
@yarrgh sorry, I did not understand, You can give me an example?

**Comment by yarrgh** [comment]
In your action:

```typescript
@Action(SearchPeoples)
  serarchPeoples({ getState, setState }: StateContext<ParkStateModel>) {
    const state = getState();
    return this.http.get<Search>('https://randomuser.me/api/?results=5').pipe(
      tap(value => {
        console.log('updating the state...');
        setState({
          ...state,
          search: value.results
        });
        console.log('status updated.');
      })
    );
  }
```

I've changed the action to return the Observable and doing the logic inside the `tap()` rxjs operator.

**Comment by mailok** [comment]
@yarrgh I get it!. But that gives another problem:

![captura](https://user-images.githubusercontent.com/3769277/37793689-c2620f06-2de5-11e8-842b-d89878758896.PNG)

**it appears that executes the action several times**

**Comment by yarrgh** [comment]
I think subscribing to the Observable returned from `dispatch()` is causing the action to be dispatched again. Looks like a bug to me. The observable should be something like a BehavoirSubject where it doesn't trigger on multiple subscriptions but only the first subscription (subscribed internally in ngxs?). 

Not sure how the action is dispatched the 3rd time though.

**Comment by mailok** [comment]
Well, it looks like a bug.

@amcdnl any suggestions?

**Comment by yarrgh** [comment]
This can be worked around by using the `shareReplay()` rxjs operator.

Example:
```typescript
@Action(SearchPeoples)
  serarchPeoples({ getState, setState }: StateContext<ParkStateModel>) {
    const state = getState();
    return this.http.get<Search>('https://randomuser.me/api/?results=5').pipe(
      tap(value => {
        console.log('updating the state...');
        setState({
          ...state,
          search: value.results
        });
        console.log('status updated.');
      }),
      shareReplay()
    );
  }
```

**Comment by mailok** [comment]
It works well!! with ``` shareReplay() ```

**Comment by deebloo** [comment]
This may be something we need to do in the lib itself

**Comment by mailok** [comment]
I tried the version  **ngxs: 2.0.0-rc.21**  and keep making multiple requests
