### ISSUE TITLE
🐞[BUG]: Closing a Angular Material SnackBar or Dialog instantiated within a NGXS State does not work

### ISSUE THREAD

**Issue by jofrly** [ngxs/store#1401]
### Affected Package
The issue is caused by package @ngxs/store I assume

### Is this a regression?

Not AFAIK

### Description

As described in https://stackoverflow.com/questions/55668123/trying-to-close-a-material-snackbar-after-being-called-in-a-ngxs-action-does-not
When you open/instantiate a Angular Material SnackBar or Dialog within a `.state.ts` file the close mechanism if the component does no longer work properly.

## 🔬 Minimal Reproduction

https://github.com/jofrly/ngxs-bug
- `npm install`
- `npm start`
- Visit `http://localhost:4200`
- Click the button
- Click the SnackBar "Okay" button within the 10 second duration to see that it won't close. After clicking the Button it won't even close after the 10 second duration expired
- Comment out the marked code within the `test.state.ts` file
- Comment in the marked code within the `app.component.ts` file and click the button again to see that now it does work as intended

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.9
- @ngxs/store version: 3.5.1

Browser:
- [x] Chrome (desktop) version 77.0.3865.90
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.13.0
- Platform: Mac

Others:
- @angular/material version: 8.2.3
</code></pre>

**Comment by splincode** [comment]
@jofrly Unfortunately or fortunately, this is not a bug. This is not an obvious Angular behavior. You can write the following code, and then everything will work:

```ts
@State<TestStateModel>({
  name: 'test',
  defaults: {
    test: null
  }
})
export class TestState {
  constructor(private snackBar: MatSnackBar, private ngZone: NgZone) {}

  @Action(LoginRequest)
  loginRequest(ctx: StateContext<TestStateModel>) {
    return of(null).pipe(
      delay(1000),
      switchMap(() => {
        return ctx.dispatch(new LoginSuccess());
      })
    );
  }

  @Action(LoginSuccess) loginSuccess() {
    this.ngZone.run(() => {
       this.snackBar.open('Test', 'Okay', {
          duration: 10000000
       });
    });
  }
}
```

Why?

- Dispatch

![image](https://user-images.githubusercontent.com/12021443/67338645-3d78af00-f532-11e9-87c9-3bdbffa11da7.png)

- NGXS uses a default strategy whereby actions are performed outside the zone

![image](https://user-images.githubusercontent.com/12021443/67338674-508b7f00-f532-11e9-9c22-37bc5df95e3d.png)

![image](https://user-images.githubusercontent.com/12021443/67338757-757ff200-f532-11e9-83ea-69cd053d39ed.png)

However, this is the main problem of Angular Material, you should always create your own templates (cdk portals) or modals inside the ngZone.

If you have a special desire, you can override the default strategy.
https://www.ngxs.io/advanced/options

![image](https://user-images.githubusercontent.com/12021443/67338951-df000080-f532-11e9-87f9-998b6c4b07bf.png)
