### ISSUE TITLE
❓[SUPPORT]: Appending New Data to Old Data   

### ISSUE THREAD

**Issue by jtan80813** [ngxs/store#1402]
I have a problem on how will be i able to append new datas since I'm making a server side scrolling. The posts is removing the old data when the new data arrives BUT i just want the new data to append and not not delete the old data in posts

> TS
 
      page = 1;

        constructor(private store: Store) {
            this.store.dispatch(new GetPostsPerPage('', this.page.toString()));
        }
    
         onScroll() {
            this.store.dispatch(new GetPostsPerPage('', (this.page += 1).toString()));
          }

> State

    

    @Action(GetPostsPerPage)
          getPostsPerPage(ctx: StateContext<PostStateModel>, { key, pageNumber }: GetPostsPerPage) {
            return this.postsService.getPostsPerPage(key, pageNumber).pipe(
              tap((result: Post[]) => {
                console.log(result);
                ctx.patchState({
                  posts: result['data'],
                });
              }),
              catchError(err => {
                console.log(err);
                return throwError(err);
              })
            );
          }

**Comment by splincode** [comment]
You can use state operator

```ts
ctx.setState((myStateModel) => ({
   ...myStateModel,
   posts: [ ...myStateModel.posts, newPos t]
}));
```

**Comment by splincode** [comment]
You can get your questions answered using other communication channels. Please see: 

Slack: https://ngxs.slack.com
Stackoverflow: https://stackoverflow.com/questions/tagged/ngxs
Twitter: https://twitter.com/NgxsStore
Reddit: https://www.reddit.com/r/NGXS/
