### ISSUE TITLE
🚀[FEATURE]: Prepopulate ngxs state in synchronous or asynchronous way

### ISSUE THREAD

**Issue by maku** [ngxs/store#1426]
### Relevant Package
This feature request is for @ngxs/store....

### Description
It should be able to prepopulate the global state (of all state classes) with 1 object. This should be possible either synchronous or asynchronous 
e.g. I would like to read the data via a http request or in case of an "electron" app from the local file system...

### Describe alternatives you've considered
As a workaround I use my own implementation of AsyncStorageEngine (@ngxs-labs/async-storage-plugin). I only implemented the "getItem" Method.
But it feels not right. e.g. on every state change the storage engine methods are called. Also I have to patch the "serialize" Method because certain state data contains objects which are not serializeable.

**Comment by splincode** [comment]
You can try workaround

```ts
import { InitialState } from '@ngxs/store/internals';

export function initializeApp1(appInitService: AppInitService) {
  return (): Promise<any> => { 
    return appInitService.fetchData().pipe(
       pipe(tap((data) => InitialState.set(data)))
    ).toPromise();
  }
}

@NgModule({
  declarations: [
    AppComponent, AboutUsComponent,HomeComponent,ContactUsComponent
  ],
  imports: [
    HttpClientModule,
    BrowserModule,
    AppRoutingModule,
  ],
  providers: [ 
    AppInitService,
    { provide: APP_INITIALIZER,useFactory: initializeApp1, deps: [AppInitService], multi: true}
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by maku** [comment]
@splincode thank you for the "workaround". Why is this internal? For me it seems like a common use case to prepopulate...

**Comment by splincode** [comment]
@markwhitfeld I think maybe you can answer this question. Currently this functionality is used only for HMR cycles.

**Comment by maku** [comment]
@markwhitfeld Could you please comment if it is "save" to use "InitialState" from "@ngxs/store/internals". Thanks...

**Comment by splincode** [comment]
@maku https://github.com/ngxs/store/blob/master/packages/store/src/store.ts#L102

One of the main problems here. We need to figure out how we are going to correctly add state.

**Comment by arturovt** [comment]
Can be closed?

**Comment by maku** [comment]
For me the problem is not solved... Is using the workaround o.k.?

**Comment by arturovt** [comment]
@maku 

Cannot say :rofl: splincode was the author of the `InitialState`, so this question is addressed to him...

**Comment by arturovt** [comment]
Thank you for submitting this feature request.
We are closing this issue due to the fact that:
- This feature is not currently planned for the future
- There has not been much support from other community members
- The use case is not broad enough to be part of the main library
You are welcome to re-open this issue with a further motivation for why this feature is essential for the core library or plugins.
If you would like to pursue the implementation of this feature we would encourage you to implement it in your own repository and share it with the community.

Thanks again
- NGXS Core Team :heart:
