### ISSUE TITLE
🚀[FEATURE]: Run a function on matched URL

### ISSUE THREAD

**Issue by chiujuanmario** [ngxs/store#1428]
Is is possible to run a function on a specific matched URL?
Like if you match "/home", you run a function `this.store.dispatch(new SampleAction())`?

Thanks

**Comment by splincode** [comment]
You can get your questions answered using other communication channels. Please see: 

Slack: https://ngxs.slack.com
Stackoverflow: https://stackoverflow.com/questions/tagged/ngxs
Twitter: https://twitter.com/NgxsStore
Reddit: https://www.reddit.com/r/NGXS/
