### ISSUE TITLE
🚀[FEATURE]: Naming change. Action -> Reaction

### ISSUE THREAD

**Issue by Webbrother** [ngxs/store#1438]
### Relevant Package
This feature request is for @ngxs/latest

### Description
At the moment when we need to change state according to some action, we should use "Action" decorator, BUT in fact, it is **not action**! Action is an object we pass to the dispatch method, but not the entity which changes the state.
Everything looks like "Action" decorator should be renamed to "Reaction" or "Reducer" (but in fact, it is not reducer because we don't use reduce method to process it).

### Describe the problem you are trying to solve
Entities misnaming.

### Describe the solution you'd like
"Action" should be renamed to "Reaction"

Current syntax:
```javascript
export class ZooState {
  @Action(FeedAnimals)
  feedAnimals(ctx: StateContext<ZooStateModel>) {
    const state = ctx.getState();
    ctx.setState({
      ...state,
      feed: !state.feed
    });
  }
}
```

My proposal:
```javascript
export class ZooState {
  @Reaction(FeedAnimals)
  feedAnimals(ctx: StateContext<ZooStateModel>) {
    const state = ctx.getState();
    ctx.setState({
      ...state,
      feed: !state.feed
    });
  }
}
```

**Comment by splincode** [comment]
If you do not like the concept, you can always do so. But this violates the basic intent and will confuse everyone as a critical change.

```ts
import { Action as Reaction } from '@ngxs/store';

export class ZooState {
  @Reaction(FeedAnimals)
  feedAnimals(ctx: StateContext<ZooStateModel>) {
    const state = ctx.getState();
    ctx.setState({
      ...state,
      feed: !state.feed
    });
  }
}
```

**Comment by Webbrother** [comment]
@splincode 
Any other arguments except that it will confuse somebody because at the moment the decorator has "Action" name? You did not answer in essence.
Don't you agree that the term "Action" has another meaning? Why you use the term "Action" for the command entity and for processing action entity?

**Comment by splincode** [comment]
@markwhitfeld @arturovt I think they can answer in more detail, or you can raise a question in the main chat

https://ngxs.slack.com

**Comment by markwhitfeld** [comment]
@Webbrother I agree that the current naming could be improved. I have always called these "action handlers" which is then confusing when you look at the naming used in the docs for custom subscriptions to the actions stream. The name `Reaction` is interesting. Potentially a name like `@Handle` could also be a decent choice. It is more familiar for command handler patters like we have here.

That being said making this change would have a very big impact. Do you have any thoughts on how a transition could be made to a different naming convention? I'm open to suggestions :+1:

**Comment by Webbrother** [comment]
@markwhitfeld I think a transition to a new naming convention could be made in some of the next major versions.
