### ISSUE TITLE
how to get value from other state in the lazy loading module / modules

### ISSUE THREAD

**Issue by tommythongnguyen** [ngxs/store#144]
I could not find the way to resolve these 2 issues:
1> I have lazy loading Product module which have PizzasState and ToppingsState, and i add both of them in to Products state which will add to the NgxsModule.forFeature(ProductState); like this
PizzasState = {
   ......
   visualizedPizza: Pizza
}
ToppingsState = {
   ......
   selectedToppingIds: number[]
}

export const ProductsState = [PizzasState, ToppingsState];
NgxsModule.forFeature(ProductsState)

Desired Behavior: 
In pizza component, i have : @Select(PizzasState.visualizedPizza) visualizedPizza: Observable<Pizza>;

I would like the visualizedPizza get update whenever the selectedToppingIds get new values.

2> The same scenario, but now  we have 2 lazies loading Module: 
         + Lazy loading   PizzasModule : PizzasState
         + Lazy loading   ToppingsModule: ToppingsState

**Comment by amcdnl** [comment]
Please refer questions to stackoverflow
