### ISSUE TITLE
🐞[BUG]: Memorized selectors are reseted if params changes

### ISSUE THREAD

**Issue by feitzi** [ngxs/store#1441]
### Affected Package
The issue is caused by package   "@ngxs/store": "^3.5.1",

### Description
If you have a lazy selector and call it with different params. Every time you change the param, the memorized value of the previous call is removed. That's a huge performance impact if you have a preselector that does some complex stuff. 

Here is an example:
https://stackblitz.com/edit/ngxs-lazyselector-issue-fix-uwfgjc

I have a selector `getSpecialAnimalComplex` that uses another select `getSpecialAnimalFn` to fetch the requested animal. So the `getSpecialAnimalFn` is a memorized selector. And everything works fine until you call that memorized function with different parameters.

In the above example, I call it first with `dog`, then again with `dog`  then with `cat` and finally again with `dog`. 
The result is, that the memorized value of the first `dog` is working for the second call. But after I query the selector with `cat` the value for `dog` is gone, and the selector needs recalculating that value.

![](https://i.imgur.com/tZeNcAn.png)

In my real-world application, this is a big performance gap. 

Can we change that to a behavior that doesn't memorize just the latest value?

**Comment by markwhitfeld** [comment]
This is by design.
When you return a lazy selector (a function returned by a selector function that will be executed later) then the returned function will be memoised. The memoization is based on only the last parameter value. Extending it to handle more than just the last value will cause an overall performance degradation because the memoization lookup will become O(n) as opposed to O(1) as it currently is.

I think that you may need to look at dynamic selectors which will allow you to create a selector at runtime that is only for cats, and another that is only for dogs. And they will have separate memoization.

**Comment by splincode** [comment]
@markwhitfeld Do we have something similar in the documentation?

**Comment by markwhitfeld** [comment]
If you really do need the lazy selector then you could implement your own memoization like this:
```TS
  @Selector([ZooState.animals])
  public  static getSpecialAnimalabc(test, animals: string[]) {
    const cache = {};
    const fn = (animalName) => {
      console.log(`Should be the single log for animal  ${animalName}`);
      return animals.filter(x => x === animalName)[0];
    };
    return (animalName) => {
      if (animalName in cache) {
        return cache[animalName];
      }
      const val = fn(animalName);
      cache[animalName] = val;
      return val;
    };
  }
```
As you can see I have made an internal memoisation strategy based on the string parameter value. This would get more complex if the parameters were objects or something else. Can you see how this could get really complicated!?
I would recommend using a memoization library if you start needing to do this.

Let me refactor what I have above to demonstrate what this could look like:
```TS
function superMemoization(fn, cache){
    return (param) => {
      if (param in cache) {
        return cache[param];
      }
      const val = fn(param);
      cache[param] = val;
      return val;
    };
}
//...
  @Selector([ZooState.animals])
  public  static getSpecialAnimalabc(test, animals: string[]) {
    const cache = {};
    return superMemoization((animalName) => {
      console.log(`Should be the single log for animal  ${animalName}`);
      return animals.filter(x => x === animalName)[0];
    }, cache);
  }
```

**Comment by feitzi** [comment]
Thanks for the very fast replies, guys :) 
I could solve my problem with dynamic selectors. But in general, it does not solve the problem if you want a more memorizable selector.
@markwhitfeld solution with own memorization is nice 👍  
For me, this is a topic for the nxgsLab. Maybe a new decorator that enables deep memorization? What is your opinion about this? 
PS:
Is the behavior regarding the last argument memorization documented?
