### ISSUE TITLE
🐞[BUG]: Prod build fails with storage migrations 

### ISSUE THREAD

**Issue by marcjulian** [ngxs/store#1449]
### Affected Package

 The issue is caused by package @ngxs/storage-plugin

### Is this a regression?

 Idk

### Description

 
Production build of angular fails with a storage migration.

## 🔬 Minimal Reproduction

 https://github.com/marcjulian/ngxs-storage-migrations

## 🔥 Exception or Error
<pre><code>ERROR in src/app/store/store.module.ts(15,20): Error during template compile of 'ɵ0'
  Function expressions are not supported in decorators
    Consider changing the function expression into an exported function.
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.3
- @ngxs/store version: 3.5.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.16.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by marcjulian** [comment]
The migration looks like this and the production build fails.

```typescript
 {
          version: 1,
          key: 'zoo',
          versionKey: 'myVersion',
          migrate: state => {
            return {
              newAnimals: state.animals,
              version: 2 // Important to set this to the next version!
            };
          }
        }
```

However, if the `migrate` function is written like this the production build works fine:

```typescript
{
          version: 1,
          key: 'zoo',
          versionKey: 'myVersion',
          migrate(state) {
            return {
              newAnimals: state.animals,
              version: 2 // Important to set this to the next version!
            };
          }
   }
```

**Comment by splincode** [comment]
Please, you can help us with PR

**Comment by marcjulian** [comment]
Do you mean updating the docs?

**Comment by splincode** [comment]
You need full investigate issue and if this is bug, so you can help us fix it

**Comment by jamajamik** [comment]
Hello after @marcjulian proposal I successfully compiled with aot. 
Nevertheless when application started with migration rule fired I  got  

> Uncaught TypeError: t.migrate is not a function.

The workaround was to define 
export function MIGRATE_BASICDATA(state) {
    console.log("Migration for ", state);
    return BasicDataModel.defaults;
}   

and 
use following in migration confituration 
{  version: 1,  
  key: 'basicData',  
 migrate: MIGRATE_BASICDATA    
...}


BTW: Is there an easy way to erase/defaults all storage content when doing app upgrade instead of configuring it per store?

**Comment by marcjulian** [comment]
<img width="524" alt="Screenshot 2019-12-13 at 07 41 04" src="https://user-images.githubusercontent.com/8985933/70775930-0d080100-1d7c-11ea-8eef-1d305534498c.png">

@jamajamik I am experiencing the same error 
> Uncaught TypeError: t.migrate is not a function.

I will try out your workaround.

**Comment by marcjulian** [comment]
@jamajamik thank you, your workaround solved the 
> Uncaught TypeError: t.migrate is not a function

**Comment by arturovt** [comment]
Ivy and newer Angular versions allow having lambdas, so closing this one as "won't do".
