### ISSUE TITLE
🐞[BUG]: Getting an error from a different library (@angular/fire) when using Router plugin

### ISSUE THREAD

**Issue by Newbie012** [ngxs/store#1450]
### Affected Package

 The issue is caused by package @ngxs/router-plugin

### Is this a regression?

 Haven't checked, first time using this plugin

### Description

 
I'm using `@angular/ccore@~9.0.0-rc2` (haven't checked other versions) and `@angular/fire@^5.3.0-rc.0`. When I import `NgxsRouterPluginModule` in my core module, I get the following error:

>ERROR Error: Uncaught (in promise): TypeError: it is not a function
TypeError: it is not a function
    at angularfire2.js:76

This error occurs when I try to navigate to a lazy loaded module.
Now, I'm not sure if this issue is related to your router plugin or with @angular/fire's package. Either way, I'm posting both packages.

## 🔬 Minimal Reproduction

I didn't find a way of creating Angular 9 in Stackblitz, so I'll understand if you would want to close this issue since it'll take some time to reproduce it.

In case it's ok with you, these are the following steps:

1. Run `ng new app` of version `~9.0.0-rc2`.
2. Add `@ngxs/store` and `@ngxs/router-plugin` - there's no need to add states
```
npm i @ngxs/store @ngxs/router-plugin @angular/fire
```
3. Add the following modules to `app.module.ts`:
```
  imports: [
    ...
    AngularFireModule.initializeApp(environment.firebase),
    NgxsModule.forRoot(),
    NgxsRouterPluginModule.forRoot(),
  ]
```
4. Run `ng g m new --routing`
5. Run `ng g c new`
6. Add the following routes::
```
app-routing.module.ts:
--
const routes: Routes = [
  {
    path: 'new',
    loadChildren: () => import('./new/new.module').then(mod => mod.NewModule)
  }
];

new-routing.module.ts:
--
const routes: Routes = [
  {
    path: '',
    component: NewComponent
  }
];
```
7.  Run `ng s`
8. Navigate to `localhost:4200/new`

## 🔥 Exception or Error
<pre><code>
ERROR Error: Uncaught (in promise): TypeError: it is not a function
TypeError: it is not a function
    at angularfire2.js:76
    at ZoneDelegate.invoke (zone-evergreen.js:365)
    at Object.onInvoke (core.js:41231)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:124)
    at zone-evergreen.js:851
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:41209)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at resolvePromise (zone-evergreen.js:793)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:41209)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: X.Y.Z
- @ngxs/store version: X.Y.Z

Browser:
- [X] Chrome (desktop) version 78
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12
- Platform:  Windows
Others:

</code></pre>

**Comment by splincode** [comment]
Try Angular 8?

**Comment by Newbie012** [comment]
@splincode It looks like if I enable Ivy then it works, so I think I'll just stick with Ivy.
