### ISSUE TITLE
🐞[BUG]: 

### ISSUE THREAD

**Issue by jtan80813** [ngxs/store#1452]
**"@ngxs/router-plugin": "^3.5.1",
 "@ngxs/storage-plugin": "^3.5.1",
 "@ngxs/store": "^3.5.1",**

I have implemented server side pagination with search. My problem is when i first go to second page, third page and so on and then when i try to search in the searchbar and then i press the back button of the browser, it suddenly return to first page. It shouldn't return directly to the first page BUT it should return first to the second page or the page where you have type the word on your searchbar.

```
`constructor(...) {
   this.route.queryParams.subscribe(params => {
      console.log(params);
      this.key = params['key'];
      this.page = params['page'];
      this.searchForm.setValue({ searchValue: this.key ? this.key : null });
      this.store.dispatch(new GetTransactionsPerPage(this.key ? this.key : '', this.page));
    });
}`
```

  ```
pageChange(newPage: string) {
    this.router.navigate([`/transactions`], {
      queryParams: { key: this.key ? this.key : null, page: newPage }
    });
  }
```

  ```
search(form: FormGroup) {
    this.router.navigate([`/transactions`], {
      queryParams: { key: form.value.searchValue }
    });
  }
```

**Comment by splincode** [comment]
Please create stackblitz reproduce

**Comment by jtan80813** [comment]
@splincode . Do you have a sample server side paginate using NGXS?

**Comment by splincode** [comment]
Or create repo for reproduce

**Comment by arturovt** [comment]
@jtan80813 Please, use our issue template and do not open issues without provided reproduction. Closing until the last is provided.
