### ISSUE TITLE
Clearer guidance regarding the observable returned by the dispatch method

### ISSUE THREAD

**Issue by markwhitfeld** [ngxs/store#146]
### Versions
```
* ngxs: 2.0-rc20
```

### Observed behavior
If my async action handler in my store returns an observable that has many items like: ```Observable.interval(1000).take(5)```
Given the dispatch method called as follows:
``` this.store.dispatch(new Add()).subscribe(()=> console.log('hit') );```
The 'hit' message would print out once after 5 seconds.

### Desired behavior
There are a few options regarding how this could act that I can think of:

- Notify the observer for each result in the result stream until it completes.
- Notify the observer once when the first result arrives and then complete the stream.
- (as-is) Notify the observer when the result stream completes and complete the stream. (Also, if the inner observable never completes then the observer will never be notified)

I think that the docs should mention how this scenario would be handled to avoid confusion.

PS. The observer is also sent the latest state but the docs state that there is no return value. This should be updated if this is correct.

**Comment by amcdnl** [comment]
@deebloo - can you take this one?

**Comment by amcdnl** [comment]
@markwhitfeld - Is this still an issue?

**Comment by ramarivera** [comment]
I would like to reopen this, or at least get some more information.
As I understand from the Redux pattern, an action could be handled by many different handlers even in different slices of state, right?
Then, would the dispatch return observable contain any value? 
if it doesnt contain any value, in the above example when would the log happen, when all action handlers have finished (taking into consideration some handlers could dispatch more actions or call async stuff)?

At least for me this is not clear in the docs
