### ISSUE TITLE
❓[SUPPORT]:  Pagination Suddenly Returns to First Page in Angular

### ISSUE THREAD

**Issue by jtan80813** [ngxs/store#1465]
I have an issue with using NGXS with my pagination. Pls see this question 

[CLICK THIS LINK](https://stackoverflow.com/questions/59071609/pagination-suddenly-returns-to-first-page-in-angular)

**Comment by arturovt** [comment]
Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 

Slack: https://ngxs.slack.com
Stackoverflow: https://stackoverflow.com/questions/tagged/ngxs
Twitter: https://twitter.com/NgxsStore
Reddit: https://www.reddit.com/r/NGXS/

**Comment by jtan80813** [comment]
@arturovt. This is not a support request. This might be a bug on ngxs. Pls reopen this issue. I have posted this already on slacks and stackoverflow.

**Comment by arturovt** [comment]
I can't reopen as the reproduction is not provided :slightly_frowning_face:

**Comment by jtan80813** [comment]
@arturovt. Do you mean the code? Ok Ill edit it

**Comment by arturovt** [comment]
No. Not the code. The reproduction is a working example (e.g. pushed on github) or _stackblitz|codesandbox_.
