### ISSUE TITLE
🐞[BUG]: Bazel support (need add integration test)

### ISSUE THREAD

**Issue by splincode** [ngxs/store#1466]
### Description

https://github.com/ngxs-labs/emitter/issues/419#issuecomment-559389777
https://github.com/ngxs/store/issues/773#issuecomment-558316732

**Comment by arturovt** [comment]
His error is not related to Bazel.

**Comment by arturovt** [comment]
I’m onto phone and can’t test it right now.

**Comment by splincode** [comment]
@arturovt I understand everything, I mean, there is a possibility that we do not have Bazel support. I want to add an integration test with Bazel.

**Comment by arturovt** [comment]
Good, go for it!
