### ISSUE TITLE
🚀[FEATURE]: Support passing type to store.reset

### ISSUE THREAD

**Issue by ahnpnl** [ngxs/store#1467]
### Relevant Package

 This feature request is for @ngxs/store

### Description
`reset` method in `Store` doesn't support passing type. Reset now is expecting always `any` type.

### Describe the problem you are trying to solve
I usually use `store.reset` in my unit test like

```
store.reset({
     animal: <default_state_value>
})
```

However, this is not type strict.

### Describe the solution you'd like
Support passing type to `reset`. For example:
```
store.reset<Animal>({
      animal: <default_state_value> // This <default_state_value> should follow type Animal
})
```

### Describe alternatives you've considered
I don't have any workarounds.

**Comment by splincode** [comment]
reset uses the `setState` which will return `void` in v4.

by @arturovt 

> Will tell you frankly I've never seen that someone had to use the `reset` method result. I don't say that other people don't do it, just meant that people in my team have never done it.
This case is very specific for your project, I guess that could be kept out of the core framework. You always can do something like:

```ts
const reset = <T = any>(state: T) => store.reset(state);
```
