### ISSUE TITLE
🚀[FEATURE]: Clearing States on Certain Action

### ISSUE THREAD

**Issue by jtan80813** [ngxs/store#1476]
Hi guys. I wanted to clear some states when i do a certain action. Is there way to do it. There's a package https://www.npmjs.com/package/ngxs-reset-plugin BUT i dont wanna add another package. Is there a way to clear specific states? Thanks

**Comment by arturovt** [comment]
Seems like you never want to follow the issue template :wink:

**Comment by jtan80813** [comment]
@arturovt. 😃

**Comment by arturovt** [comment]
@splincode I think it’s your area of knowledge 😉

**Comment by jtan80813** [comment]
@splincod. Really looking forward to it

**Comment by markwhitfeld** [comment]
@jtan80813 You can either use the package you mentioned or you can do it manually by having a copy of the state that you would like to reset it to (potentially the default state extracted to a variable) and set the state to that in response to the action of interest.

Please use the provided issue template in the future.

**Comment by jtan80813** [comment]
@markwhitfeld. I would not want to add another package. Can you provide code on how to clear state, several states for example on different state. Thanks

**Comment by jtan80813** [comment]
@markwhitfeld. Pls do not close this issue. It would be great if this feature could be added in the next update

**Comment by splincode** [comment]
@jtan80813 you can send pull request :) or edit this issue (Please use the provided issue template in the future.)
