### ISSUE TITLE
🐞[BUG]: Router build problem

### ISSUE THREAD

**Issue by splincode** [ngxs/store#1479]
🐞 bug report
Affected Package
@angular/compiler-cli

Is this a regression?
Yes

Description
The NGCC incorrectly compiles the @ngxs/router-plugin as UMD.

🔬 Minimal Reproduction
https://github.com/arturovt/ivy-ngxs-router-plugin-umd-repro

clone and install dependencies
check the postinstall script
Or open the node_modules/@ngxs/router-plugin/bundles/ngxs-router-plugin.umd file in your IDE and see the generated code at the end of the factory(....) function. This has to be something like global...modules.ngxsFeature.module.

Providing screenshot below (this is how it looks like on my PC):

image

🌍 Your Environment
Angular Version:

Angular CLI: 9.0.0-rc.4
Node: 12.11.1
OS: linux x64

Angular: 9.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.4
@angular-devkit/build-angular     0.900.0-rc.4
@angular-devkit/build-optimizer   0.900.0-rc.4
@angular-devkit/build-webpack     0.900.0-rc.4
@angular-devkit/core              9.0.0-rc.4
@angular-devkit/schematics        9.0.0-rc.4
@ngtools/webpack                  9.0.0-rc.4
@schematics/angular               9.0.0-rc.4
@schematics/update                0.900.0-rc.4
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

### Description

![image](https://user-images.githubusercontent.com/12021443/69974526-78f59880-1536-11ea-9068-bdf87db66287.png)

**Comment by arturovt** [comment]
https://github.com/angular/angular/issues/34191

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/70429667-1e09f700-1a8a-11ea-9f13-d2f2aafa2ed9.png)

**Comment by splincode** [comment]
https://github.com/angular/ngcc-validation/issues/688#issuecomment-565670960
