### ISSUE TITLE
 @ngxs/core  is 2.0.0-rc.19    where   ngxs is 2.0.0-rc.20  on npm

### ISSUE THREAD

**Issue by xmlking** [ngxs/store#148]
### Versions

```
* ngxs:
* @angular/core:
```

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior

```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by yarrgh** [comment]
@ngxs/core was renamed to @ngxs/store which is at 2.0.0-rc.20

**Comment by amcdnl** [comment]
Sorry guys, going under some project restructure . Always check the change log
