### ISSUE TITLE
the select is happening before the dispatch

### ISSUE THREAD

**Issue by smarteez17** [ngxs/store#1487]
I have the following code 

@Select(ReportingPeriodState.GetReportingPeriodId) reportingPeriodId$: Observable<number>;

 @Dispatch() // this on a button click 
   getReportingPeriodId() {
    const financialPeriodId =  this.getFinancialPeriodId().value;
    const monthId =  this.getMonthId().value;
    const yearId =  this.getYearId().value;
    return new GetReportingPeriod({financialPeriodId, monthId, yearId});
  }

whats happening is the select is happening before the dispatch and i getting back the old value and not the new one 

in the image the first value is the old value the third one is new value , The second one is what value I getting back and be added to my object 
![image](https://user-images.githubusercontent.com/35128168/70125378-6044ca00-167f-11ea-8212-561334613619.png)

**Comment by splincode** [comment]
- create stackblitz for reproduce

**Comment by arturovt** [comment]
Closing until reproduction is provided. Max or I will reopen immediately when you post a link here :wink:

**Comment by markwhitfeld** [comment]
I had a conversation with @smarteez17 and it turned out that this was an issue in his production code and not NGXS.
