### ISSUE TITLE
🚀[FEATURE]: Support @Select with dynamic selector

### ISSUE THREAD

**Issue by ahnpnl** [ngxs/store#1494]
### Relevant Package

 This feature request is for @ngxs/store

### Description
I have a service which has `Store` injected like this
```
export interface FooStateModel {
     fooData: {
          [key: number]: any
     }
}

@State<FooStateModel>({
     name: 'fooState',
})
export class FooState {
}

export class FooSelector {
     static getFooById(id: number) {
          return createSelector([ FooState ], (state: FooStateModel) => {
                return state.fooData[id];
           });
     }
}

@Injectable()
export class FooService() {
      constructor(private store: Store) {}

      getFoo$(id: number) {
           return this.store.select(FooSelector.getFooById(id));
      }
}
```

### Describe the problem you are trying to solve
Get rid of injected `Store` and use `@Select` only to get an observable of data from state using dynamic selector

### Describe the solution you'd like
```
@Injectable()
export class FooService() {
      @Select()
      getFoo$(id: number) {
           return FooSelector.getFooById(id);
      }
}
```

### Describe alternatives you've considered
**N.A.**

**Comment by splincode** [comment]
@ahnpnl https://www.ngxs.io/concepts/select#dynamic-selectors

**Comment by ahnpnl** [comment]
my `FooSelector` is a class which contains `getFooById` is a dynamic selector. The problem is I still need to inject `Store` into my `FooService` to use with dynamic selector. I want to have something similar like `@Dispatch`
```
@Dispatch()
loadData(id: number) {
     return new LoadData(id);
}
```

**Comment by markwhitfeld** [comment]
@ahnpnl unfortunately your version will lack the correct type information and could cause some issues. Decorators cannot rewrite type information.

That being said, I do think that we could come up with a reasonable solution to this.

Could you share your code for the dynamic selector too so that we have a reasonable baseline for discussion?

**Comment by ahnpnl** [comment]
Updated example codes contain `FooSelector` and `FooState`

**Comment by yadue** [comment]
@markwhitfeld it would be very helpful to have something like that, especially in complicated cases stores.

**Comment by arturovt** [comment]
Thank you for submitting this feature request.
We are closing this issue due to the fact that:
- This feature is not currently planned for the future
- We're deprecating the `@Select` decorator and no more work is going to be done on that

Thanks again
- NGXS Core Team :heart:
