### ISSUE TITLE
🚀[PROPOSAL]: Dynamic States

### ISSUE THREAD

**Issue by splincode** [ngxs/store#1500]
### Relevant Package

This feature request is for @ngxs/store

### Description

```ts
@State({
 name: 'myLazyState',
 default: { hello: 'world' }
})
export class LazyState {}
```

```ts
class MyLazyComponent {
   constructor(private store: Store) {
   }

  public ngOnInit(): void {
    import('my-lazy.state').then((LazyState) => store.createState(LazyState));
  }

}
```

**Comment by arturovt** [comment]
What would be the reason to import state this way? You can load modules and components asynchronously via `import(...).then(...)`, those modules can have bounded feature states.
