### ISSUE TITLE
🚀[FEATURE]: dynamic store

### ISSUE THREAD

**Issue by Areen3** [ngxs/store#1517]
### Relevant Package

 This feature request is for @ngxs/3.6.1

### Description
 
We have made several modifications starting from version 3.6.1
1 Dynamic state management (add, delete state)
now you can use the function to dynamically add a new state, specifying its parent, and destroy it.
The goal was to support dynamically created components based on configuration, which allows you to build an application by defining it using configuration.
You can now dynamically add the same state class to different store locations
2. Sending actions to the state fragment.
Since you can now have two different instances of the same state class, you had to send actions to only one of these instances. This was resolved using the location parameter.
The action can be sent to a specific location within a tree fragment
3. Selecting the state fragment taking into account the location.
Currently, you can add a location parameter to @selector that indicates where the state is desired
4. inheritance of selectors
we have parent class and child store class. The selector is implemented in the parent and the child class is used for subscription
other minor modifications
5. Command and notification action. The notification may not reach the destination, while the command if it does not find the destination will display an error on the console
6. Subscription to a non-existing blind area causes a message on the console
7. Other minor modifications resulting from points 1, 2

here is [source code](https://github.com/Areen3/ngxsLocation) for this modification

### Describe the problem you are trying to solve

This time I prepared a little better with this modification, the previous time you wrote that it was difficult to understand the code (it was written by another programmer, I refactorified it, I hope it will be easier)
here is a [link](https://github.com/Areen3/ngxsFactoryDocumentation/raw/master/docs/movi/buisenssExample.mp4) to a movie showing the bissnes reason for this change
and i also wrote a factory simulation here is a [movie](https://github.com/Areen3/ngxsFactoryDocumentation/raw/master/docs/movi/fsDynamicStore.mp4) what explain how it work
and here the source [code link](https://github.com/Areen3/factory-simulation)

and here you have a [screenshot](https://raw.githubusercontent.com/Areen3/ngxsFactoryDocumentation/master/docs/case/ngxs-change.png) showing in uml what I changed more or less

I will say that I care about this modification. I got into coding after a long break but I tried to make the code look similar to what is already entered.
I did not do unit tests - if it was a positive decision, I will try to add them
To understand the blinds from ngxs, I've drawn a draft version
uml of store -  link is [here](https://areen3.github.io/ngxsFactoryDocumentation/ngxs-uml/index.htm)

If there was a will, I could apply more and do some of this-looking documentation, it would be easier to understand this library.
I will say that it was quite difficult for me to get along with memoisation - I suppose that it would be useful to others.

I also noticed some modifications that could be made but I will describe them in a separate issue

if something is still missing that would be useful to understand this code, please let me know, I will try to add
with best regards Piotr

**Comment by markwhitfeld** [comment]
@Areen3 Thank you for taking the time to describe your idea so well and for the effort that you have put into making it work.

Unfortunately, it digresses very far from the simple ngxs API. One of our goals is to keep the API and the concepts of NGXS as simple as possible. Towards this end, we encourage contributors to try to implement their changes as a plugin to ngxs as opposed to modifying the core of ngxs.

While we would not be merging this into the main repository we would be happy to open up a labs project for you if you would like to implement this as a plugin.

**Comment by Areen3** [comment]
OK I understand
I can implement it as a plugin
Here I have a question is these changes possible implement as plugin?
Do I as the plugin I can add and remove story elements, handle actions and selectors with location

that's why I have a request
take a look and as if you could compare changes between branches
[my changes ](https://github.com/Areen3/ngxsLocation/tree/ngxsLocation)
and
[actula NGXS](https://github.com/Areen3/ngxsLocation/tree/master)

and more or less show the way how to start writing such a plugin

summary, I thingk, it is quite difficult to implement my changes in future versions, the plugin would be ok, but I could get some help to write it well? 
I mean potential location and possibly tips on how to write

Piotr

**Comment by Dav1dde** [comment]
Somewhat unrelated but I would love to see this as a plugin or in the core of ngxs. 

I used to use states for modal windows, but once I had to open more than one at once (or even with just one) it becomes hard to manage one global state. From what I understand this would solve this problem.

For now I had to go back to a service which was provided on the root component of the modal

**Comment by Areen3** [comment]
Hi  @markwhitfeld 
the problem I see in:
1 modification for creating a child stata (i.e. in the factory)
2 Corrections for selectors

these two fragments require interference in the core, such interference could inform the plugin that something happened

All in all, some help could be needed to outline the direction well.
I will encode it later but I don't want to do it across ngxs

**Comment by arturovt** [comment]
Thank you for submitting this feature request.
We are closing this issue due to the fact that:
- There has not been much support from other community members
- The use case is not broad enough to be part of the main library
- The proposed feature is not clear enough to be implemented
You are welcome to re-open this issue with a further motivation for why this feature is essential for the core library or plugins.
If you would like to pursue the implementation of this feature we would encourage you to implement it in your own repository and share it with the community.

Thanks again
- NGXS Core Team :heart:
