### ISSUE TITLE
🚀[FEATURE]: store.reset() without arguments should reset store to default state.

### ISSUE THREAD

**Issue by devniel** [ngxs/store#1520]
### Description
Currently, `store.reset()` requires an argument with the state that will overwrite the current state. When having multiple sub-stores and trying to reset to the default state, it's necessary to get the merge of all states (like a `combineReducers`) in some way to configure the default state and set it as an argument for the reset, this could be by-passed if internally `store.reset()` resets the store to the default state when not receiving any argument.

### Describe the problem you are trying to solve
For stores with multiple sub-stores, to avoid building the default state object when resetting the global store with `store.reset()`, specially for test cases.

```
// to avoid this:
// constructing defaultState
// defaultState = {
//   subState1: { ... },
//   subState2: { ... },
//   subState3: { ... },
//   the following statement returns an error ("Property 'NGXS_OPTIONS_META' does not exist on type 'typeof MyState'")
//   [subState4.NGXS_OPTIONS_META.name]: subState4.NGXS_OPTIONS_META.defaults,
// };
store.reset(myCombinedDefaultState);

// with this:
store.reset();
```

### Describe the solution you'd like
Maybe it's related to https://github.com/ngxs/store/issues/835#issuecomment-462650283, just handling it internally, making the `state` argument as optional and getting the default one from any internal property.

### Describe alternatives you've considered
Use https://github.com/ng-turkey/ngxs-reset-plugin, but I think that it's too much if I'm only considering resetting my states for unit testing.

**Comment by splincode** [comment]
this functionality is suitable for a plugin, if for implementation in the main core
