### ISSUE TITLE
📚[DOCS]: Doc site does not exist

### ISSUE THREAD

**Issue by scaljeri** [ngxs/store#1528]
### Description
The link to the doc site does not exist

It is http://ngxs.gitbooks.io/ngxs/ but that does not exist. I guess it should be https://www.ngxs.io/, maybe

**Comment by splincode** [comment]
I don't understand

`http://ngxs.gitbooks.io/ngxs/`
`https://www.ngxs.io/`

I go to any of these sites and everything works

**Comment by arturovt** [comment]
> I don't understand
> 
> `http://ngxs.gitbooks.io/ngxs/`
> `https://www.ngxs.io/`
> 
> I go to any of these sites and everything works

Same for me, both links work.

**Comment by scaljeri** [comment]
It seems to work again. It just failed once

![image](https://user-images.githubusercontent.com/1078741/74105131-74afb200-4b5b-11ea-90ed-677dc1c1013f.png)

Maybe a local issue!
