### ISSUE TITLE
🐞[BUG]: @Action Type checker produce TS1240 error if action processor is made as an expression

### ISSUE THREAD

**Issue by vdshb** [ngxs/store#1529]
### Affected Package
The issue is caused by package @ngxs/store:3.6.2

### Is this a regression?

Kind of. In previous version 3.5.0 this bug was not present, because there weren't type checks on actions.

### Description

I'm using several helpers to create action processors. Like this one (tries to request data from server several times when connection is weak):
```typescript
export function repeatableHttpCallAction<StateType, HttpResponse>(asyncCall: () => Observable<HttpResponse>,
                                                                   onSuccess: (stateContext: StateContext<StateType>, httpResponse: HttpResponse) => void,
                                                                   onFailure: (stateContext: StateContext<StateType>, error: HttpErrorResponse) => void,
                                                                   attempts: number = 5,
                                                                   timeout: number = 100) {
  return (stateContext: StateContext<StateType>, prolongedAction: ActionWithAttempts) => {
    let prolongedActionConstructor: any = prolongedAction.constructor;
    asyncCall()
      .subscribe(
        httpResponse => {
          onSuccess(stateContext, httpResponse);
        },
        (error: HttpErrorResponse) => {
          if (prolongedAction.attempt <= attempts) {
            setTimeout(() => stateContext.dispatch(new prolongedActionConstructor(prolongedAction.attempt + 1)), timeout);
          } else {
            onFailure(stateContext, error);
          }
        });
  };
}
```

It worked good this way at 3.5.0:

```typescript
@Action(GetNameAction)
generateDeviceToken = repeatableHttpCallAction(
  () => this.getNameCommunicator.getName(),
  ({patchState}: StateContext<NameStateModel>, response: string) => {
    patchState({
      name: response
    })
  },
  ({patchState}: StateContext<NameStateModel>) => {
    patchState({
      name: 'COMMUNICATION_ERROR'
    })
  }
)
```
But on 3.6.2 it starts produce TypeScript compilation error:
<pre><code>error TS1240: Unable to resolve signature of property decorator when called as an expression.</code></pre>

It's failing to compile at my local environment (thankfully `@ts-ignore` helps) and produce warning at stackblitz example.

I wonder if it might be fixed at ngxs/store side or it's a typescript issue.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-asxtfs?embed=1&file=src/app/logic/state.ts

## 🔥 Exception or Error
<pre><code>
error TS1240: Unable to resolve signature of property decorator when called as an expression.
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.14
- @ngxs/store version: 3.6.2
- typescript version: 3.5.3

Browser:
- [x] Chrome (desktop) version 79.0.3945.117
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v13.6.0  
- Platform:  Linux 

Others:

</code></pre>

**Comment by splincode** [comment]
This is not standard behavior using NGXS and the `Action` decorator

**Comment by splincode** [comment]
@markwhitfeld @arturovt what do you think?

**Comment by arturovt** [comment]
`Action` is a method decorator, it's not a property decorator. When you write this:
```ts
@Action(GetNameAction)
generateDeviceToken = repeatableHttpCallAction(
```
You're trying to decorate the `generateDeviceToken` property. Property decorators don't behave in the same way as method decorators since method decorators accept descriptors as the third argument.
It's similar to:
```ts
@Input()
a = 10;
```

**Comment by markwhitfeld** [comment]
@vdshb I recommend that you have a look at this and/or build on the idea:
https://github.com/ngxs-labs/attach-action

**Comment by vdshb** [comment]
@markwhitfeld Thanks, I'll take a look at this project this week.

**Comment by arturovt** [comment]
Can we close this?
