### ISSUE TITLE
🐞[BUG]: Angular 9 compile issue: ERROR in Expected named ClassDeclaration

### ISSUE THREAD

**Issue by EddyNll** [ngxs/store#1534]
### Affected Package
The issue is caused by package @ngxs/store

### Is this a regression?
Upgraded to angular 9 and had an old @ngxs/store package installed that gave multiple errors.
Trying this new package only threw this error.

### Description
Im getting the following error when trying to compile:
ERROR in Expected named ClassDeclaration: [node_modules/@ngxs/store/src/internal/internals.d.ts: FunctionDeclaration @ 68:84]

## 🔬 Minimal Reproduction
Just run with angular 9

## 🔥 Exception or Error
<pre><code>
ERROR in Expected named ClassDeclaration: [node_modules/@ngxs/store/src/internal/internals.d.ts: FunctionDeclaration @ 68:84]
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 9.0.0
- @ngxs/store version: 3.6.1

**Comment by splincode** [comment]
Please, create repo with reproduce steps

**Comment by markwhitfeld** [comment]
What version of TypeScript are you using?
Also, could you upgrade to NGXS 3.6.2 and test if you still have the error?

**Comment by EddyNll** [comment]
My typescript version is: 3.7.5.
I did also try NGXS 3.6.2, but it had the same result.

I'll try to create a reproduction

**Comment by EddyNll** [comment]
Not able to reproduce, im closing this issue.

**Comment by LeBeatle** [comment]
I have the same Issue running on Angular 13. I tried to move parts of my code into a library, and now I get this Error during compilation of my app: 
`./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Expected named ClassDeclaration: [/Users/lukas.kaeferle/Documents/Dev/somnus-frontend/node_modules/@ngxs/store/src/internal/internals.d.ts: FunctionDeclaration @ 62:87]
    at /Users/lukas.kaeferle/Documents/Dev/somnus-frontend/node_modules/@ngtools/webpack/src/ivy/loader.js:81:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9)
`
I am using 
"typescript": "4.6.3"
"@angular/compiler-cli": "13.3.4",
"@ngxs/store": "^3.7.2",
"@angular-ru/ngxs": "13.0.0",

When I remove the NGXSModule.forFeature([MyState]) from the library the Error is not thrown any more. In another lib I just moved the state out of the library and then consumed it from within the library, but this is not an option here.
