### ISSUE TITLE
🐞[BUG]: Angular 9 API constructor issue on state files

### ISSUE THREAD

**Issue by subhasheonian** [ngxs/store#1540]
### Angular version - 9

 
![angular_version](https://user-images.githubusercontent.com/58032356/74744216-dec90500-5287-11ea-952c-300bd0caf6c5.png)
 I have used angular version 9 and updated core file on my latest project/....

### State File
![state](https://user-images.githubusercontent.com/58032356/74744666-a5dd6000-5288-11ea-82bb-197833b907b2.png)

When add constructor on state file for API services but i have get the issue. you can see below screenshot for easy to understand

![bug](https://user-images.githubusercontent.com/58032356/74744898-08366080-5289-11ea-81d9-7461d96b5f4a.png)

 Please help me, how to resolve this problem.

**Comment by splincode** [comment]
https://www.ngxs.io/advanced/ivy-migration-guide

```
@Injectable()
export class StudentState {
 // ..
}
```

**Comment by subhasheonian** [comment]
Thanks. It's working
