### ISSUE TITLE
🐞[BUG]: Toastr not working on state file

### ISSUE THREAD

**Issue by subhasheonian** [ngxs/store#1541]
### Angular Version - 9
![angular_version](https://user-images.githubusercontent.com/58032356/74839661-a7239100-534b-11ea-9703-f3a52c51fee7.png)
I have used angular version 9 and updated core file on my latest project/....

### Install toastr

URL: https://www.npmjs.com/package/ngx-toastr
<pre><code>
Command : npm i ngx-toastr

</code></pre>

### Listing
![list](https://user-images.githubusercontent.com/58032356/74840889-c4595f00-534d-11ea-9000-469eedecc8d8.png)
 When click the delete button after call state file., It's proper working my code, but i want to get api response message on the listing page....

###  State File
![toastr1](https://user-images.githubusercontent.com/58032356/74840575-38dfce00-534d-11ea-8200-ed72b69300b7.png)

 you can see my screenshot for easy to understand, my api call response is simple **Success** and **error** message, so how to display message ....

 Please help me,  how to resolve this problem.

###  One more question 
Which is best between two function setState or patchState. I see your article... for information

**Comment by splincode** [comment]
try 

```ts
this.ngZone.run(() => {
 this.toastr.success('hello', 'world');
});
```

**Comment by subhasheonian** [comment]
Thanks, It's working :)
