### ISSUE TITLE
🐞[BUG]: Devtools plugin doesn't work as expected 

### ISSUE THREAD

**Issue by bboydflo** [ngxs/store#1549]
### Affected Package
```sh
"@ngxs/logger-plugin": "3.6.2",
"@ngxs/devtools-plugin": "3.6.2"
```

### Is this a regression?
I haven't tried this setup with a previous ngxs version.

### Description
Devtools plugin doesn't work as expected and see the following message:
> No store found. Make sure to follow the instructions.

Logger plugin does work as expected. I also commented out logger plugin and devtools plugin still doesn't play nice with redux devtools extension.

## 🔬 Minimal Reproduction

We cannot reproduce this on stackblitz since they use redux themselves.

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.14
- @ngxs/store version: 3.6.2

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox developer edition - version 74.0b9 (64-bit)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.13.1
- Platform:  Mac

**Comment by splincode** [comment]
Please create github repo for reproduce

**Comment by bboydflo** [comment]
> reate github repo for reprod

It will take a while but please keep this open

**Comment by bboydflo** [comment]
I think I found the issue which was related to redux devtools setup in the same page. I am migrating to ngxs and old redux setup conflicted with ngxs devtools plugin.
