### ISSUE TITLE
Feature Request / Question How to dispatch a action as soon as everything is ready

### ISSUE THREAD

**Issue by leon** [ngxs/store#155]
In my case I want to react to when the app is loaded and ready for action, and call out to firebase to check if there is a session and if not redirect to the login page.

in @ngrx you would defer an observable effect and dispatch a new action

```
import { defer } from 'rxjs/observable/defer';

@Effect()
init$: Observable<Action> = defer(() => {
    return of(new CheckSessions();
});
```

How would we do this in a good way?

**Comment by amcdnl** [comment]
There is a init action you might be able to take advantage of. Does this help?

**Comment by yarrgh** [comment]
What's the init action? I think this may answer #101 as well. Does it also work for lazy loaded states? Is this in the docs?

**Comment by leon** [comment]
After the forRoot() states have been initialized the InitState Action is dispatched.
At the moment I think this is only used to initialize the redux devtools.
It's also an internal action.

I see a couple of different ways to implement this.
either we go with the angular way and create an interface called OnInit and have the `@State` class implement that.
Then we call those methods when we know that the root state store is ready.

This way we could add more lifecycle events if we can come up with any.

```TS
@State({
  defaults:...
})
export class AuthState implements NgxsOnInit {
  ngxsOnInit(cxt: StateContext<MyState>) {
    return new GetTodos();
  }
}
```

Or we could have `InitState` Action get triggered only on the instance.

```TS
@State({
  defaults:...
})
export class AuthState {

  // Will NOT get published to the state stream, and will be called once when this state class is created
  @Action(InitState)
  ngxsOnInit(cxt: StateContext<MyState>) {
    return new GetTodos();
  }
}
```

Which one do you guys like best?

**Comment by yarrgh** [comment]
I prefer the interface approach as it keeps it simple and similar to how Angular works.

Another approach could be to introduce a new decorator. Something like `@InitStore()`

```typescript
@State({
  defaults:...
})
export class AuthState {

  @InitStore()
  initialize(cxt: StateContext<MyState>) {
    return new GetTodos();
  }
}
```

**Comment by amcdnl** [comment]
Why couldn’t you use the constructor?

I’d prefer no new decorators, they are a pain.

I think to stay consistent with angular just a special function nam and interface would be my preference

**Comment by amcdnl** [comment]
Done.

**Comment by jkossis** [comment]
Is there a way to initialize using the lifecycle hook, and have that be the default value for the state? Even after using the hook, the initial value on subscription is still the static value provided in the state class decorator. I want to try and avoid using a static value for the default.
