### ISSUE TITLE
🐞[BUG]: Incorrect definition of payload in logging

### ISSUE THREAD

**Issue by splincode** [ngxs/store#1551]
### Affected Package

 The issue is caused by package @ngxs/logger-plugin

### Description

https://github.com/ngxs/store/blob/master/packages/logger-plugin/src/action-logger.ts#L40

## 🔬 Minimal Reproduction

```ts
export class RemoveTodoAction {
  public static type: string = '@todo.removeTodo(idx)';
  constructor(public idx: number) {}
}
```

```ts
this.store.dispatch(new RemoveTodoAction( 1 ));
```

![image](https://user-images.githubusercontent.com/12021443/76709191-bd83f900-670d-11ea-8824-1a6fd0ec4b5c.png)

```ts
this.store.dispatch(new RemoveTodoAction( 0 ));
```

![image](https://user-images.githubusercontent.com/12021443/76709203-ddb3b800-670d-11ea-8881-aceddf29a3ab.png)

**Comment by markwhitfeld** [comment]
Good news, this has been addressed in NGXS v3.7 which was released last week.
( see https://dev.to/ngxs/announcing-ngxs-3-7-1kbk for release notes )

I will close this issue. Please let us know if it is not resolved.
