### ISSUE TITLE
🐞[BUG]: Angular 9.1 HMR: Injector has already been destroyed

### ISSUE THREAD

**Issue by Formaceft** [ngxs/store#1559]
### Affected Package
"@ngxs/store": "~3.6.2"
"@ngxs-labs/dispatch-decorator": "~2.1.0"

### Is this a regression?
 Yes, the previous version in which this bug was not present was: **Angular 8**

### Description
[HMR] Update failed: Error: Injector has already been destroyed.
    at R3Injector.assertNotDestroyed (http://localhost:3100/main.js:34364:19)
    at R3Injector.get (http://localhost:3100/main.js:34269:14)
    at getNgZone (http://localhost:3100/main.js:85320:42)
    at SomeService.wrapped (http://localhost:3100/main.js:85488:28)
    at SomeService.terminate (http://localhost:3100/some-module-module.js:3441:14)
    at SomeModule.ngOnDestroy (http://localhost:3100/some-module-module.js:2851:38)

All actions dispatched from ngOnDestory hook, during hrm, get this exception. This problem appeared after updating project to Angular 9.1 version.

**Comment by splincode** [comment]
create github repo for reproduce, please

**Comment by jadengis** [comment]
I think there was a change made to Angular or the CLI in 9.1 that broke the way that HMR worked before. I was using the hmr plugin for one of my projects and it suddenly stopped refreshing after the upgrade to 9.1. I did not see the errors described above.

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/83351778-92459900-a34f-11ea-96e4-5f6da2c0cc30.png)

**Comment by markwhitfeld** [comment]
Good news, NGXS v3.7 was released last week.
Bad news, we had to remove support for HMR due to lack of official Angular support for the HMR workflow, and no more options existed within our control to be able to address the issues.
( see https://dev.to/ngxs/announcing-ngxs-3-7-1kbk for release notes )

PS. There is an alternative to use the storage plugin to get a similar experience.
