### ISSUE TITLE
[Question] ngxs/store origins

### ISSUE THREAD

**Issue by MarkHerhold** [ngxs/store#156]
I'm new to redux and saw @amcdnl present `ngxs` on a recent ngAir episode. I may have missed it in the video, but someone mind sharing the motivation for this module and what differentiates it from other Angular 2+ redux libraries? Thanks!

**Comment by MarkHerhold** [comment]
Ah, here's [a blog post](https://medium.com/@amcdnl/why-another-state-management-framework-for-angular-b4b4c19ef664) by @amcdnl answering most of my questions.

**Comment by amcdnl** [comment]
:) Let me know if you have any other ?s
