### ISSUE TITLE
🐞[BUG]: Inheriting Selectors - createSelector return type

### ISSUE THREAD

**Issue by dubcdr** [ngxs/store#1564]
### Affected Package

 The issue is caused by package @ngxs/store

### Is this a regression?

 Not sure, first time looking at it

### Description

Seeing typing issues when implementing [inheriting selectors](https://www.ngxs.io/concepts/select#inheriting-selectors) with `createSelector`. Have implemented the exact method from the documentation. You can easily see the error in the stackblitz on the `base.state.ts`

The selectors actually seem to work. Just a type issue

## 🔬 Minimal Reproduction

Create a base class with selectors using `createSelector`

[Stackblitz](https://stackblitz.com/edit/ngxs-selector)

## 🔥 Exception or Error
<pre><code>
Type '(state: { entities: T[]; }) => T[]' is missing the following properties from type 'T[]': pop, push, concat, join, and 24 more.
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 9.1.1
- @ngxs/store version: 3.6.2

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:   Mac

Others:

</code></pre>

**Comment by markwhitfeld** [comment]
It was an issue in the docs. The return type of the function should not be `T[]`, but should rather return a function that given the state, returns `T[]`. I have changed the docs to use the implicit return type.
