### ISSUE TITLE
🐞[BUG]: ngxsOnChanges is not being called when ngxs form state changes

### ISSUE THREAD

**Issue by timonmasberg** [ngxs/store#1567]
### Affected Package

 The issue is related to the packages @ngxs/store and @ngxs/form-plugin

### Description

The ngxsOnChanges implemented with this [PR ](https://github.com/ngxs/store/pull/1389) is not being called when the Angular Reactive Form bound to the form state changes.
As the documentation for ngxsOnChanges suggests, subscribing to the store can be replaced with the ngxsOnChanges method. Sadly this is not the case for ngxsForms.

## 🔬 Minimal Reproduction
Please check the form.state.ts 
In the console you are able to see only the subscription on the state works as expected, the ngxsOnChanges will only be called once.
https://stackblitz.com/edit/angular-nczdzz

## Environment

<pre><code>
Libs:
- @angular/core version: 9.1.0
- @ngxs/store version: 3.6.2
- @ngxs/form-plugin version: 3.6.2

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by splincode** [comment]
Good catch

**Comment by LeParadoxHD** [comment]
Any change on this issue?

**Comment by irowbin** [comment]
Any news of this issue?

**Comment by splincode** [comment]
@LeParadoxHD @irowbin unfortunately, we do not have enough time to solve some problems, could you try to investigate this and send PR?

**Comment by arturovt** [comment]
This has been fixed as part of the [v3.7.6](https://github.com/ngxs/store/releases/tag/v3.7.6) release.
Please test this out and let us know if this is not resolved.
