### ISSUE TITLE
🐞[BUG]: Returning empty observables cancels actions

### ISSUE THREAD

**Issue by kremerd** [ngxs/store#1568]
### Affected Package
The issue is caused by package @ngxs/store.

### Is this a regression?
No.

### Description

Actions are canceled if at least one action handler listens for them that returns an Observable with the following properties:

1. It does not emit a value.
2. It completes.

In particular this applies to `EMPTY`, `of()` or `someFiniteObservable$.pipe(filter(() => false)))`.

(If all action handlers instead emit one or more values, the action is not canceled, but successful.)

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/ngxs-empty-action-handler

## Environment

<pre><code>
Libs:
- @angular/core version: 9.1.2
- @ngxs/store version: 3.6.2

Browser:
- [x] Chrome (desktop) version 81
- [x] Firefox version 75
 </code></pre>

**Comment by splincode** [comment]
@markwhitfeld what expected behavior?

**Comment by markwhitfeld** [comment]
This is a bug. This action should not come through as cancelled.

**Comment by markwhitfeld** [comment]
Good news, this has been addressed in NGXS v3.7 which was released last week.
( see https://dev.to/ngxs/announcing-ngxs-3-7-1kbk for release notes )

I will close this issue. Please let us know if it is not resolved.
