### ISSUE TITLE
🐞[BUG]: store.dispatch(...).subscribe() causes to trigger Angular ErrorHander twice.

### ISSUE THREAD

**Issue by tytskyi** [ngxs/store#1573]
### Affected Package

 The issue is caused by package @ngxs/store

### Is this a regression?

 I don't know

### Description

 Subscribing to store.dispatch(...) method causes Angular ErrorHandler more times than expected.

## 🔬 Minimal Reproduction

In the reproduction in AppComponent after 4 seconds dispatches action. Which is on purpose tries HTTP GET method on nonexistent web site. Open the console and observe that ErrorHandler logged error TWICE. 
Removing subscription logs only ONCE as expected. 
See code snippet of AppComponent. 
```
  ngOnInit() {
    setTimeout(()=> {
      // NOTE: causes 2 times triggering angular ErrorHandler
      this.store.dispatch(new MyAction()).subscribe();

      // NOTE: no problem, triggers angular ErrorHandler once
      // this.store.dispatch(new MyAction());
    }, 4000)
  }
```

 [https://stackblitz.com/edit/angular-8msqkq](https://stackblitz.com/edit/angular-8msqkq)

## Environment

<pre><code>
Libs:
- @angular/core version: 9.1.0
- @ngxs/store version: 3.6.2

Browser:
ANY
 
For Tooling issues:
- Node version: v12.16.1
- Platform:  Windows

Others:
N/A

**Comment by vmuresanu** [comment]
There was already a bug closed. It basically resumes to handle observables with catch block. Please see this comment (and original issue) - https://github.com/ngxs/store/issues/803#issuecomment-531220531

**Comment by tytskyi** [comment]
@vmuresanu thanks! It makes sense. I interpreted that it uses ErrorHandler as default mechanism, not that NGXS fires it on their side. 
Not a bug then.
