### ISSUE TITLE
❓[SUPPORT]:  Is it possible to create global selector

### ISSUE THREAD

**Issue by ozergul** [ngxs/store#1588]
Hello everyone, thanks for that plugin, I really loved it <3
I search but not found anything, I wanna know that we can we create custom selector _independent from state._

For example:
```ts
@Select(getBars([TestStat1.bar, TestState2.bar]))
```
Is it possible?

Regards.

**Comment by splincode** [comment]
https://www.ngxs.io/concepts/select#meta-selectors

```ts

export class MyGlobalSelection {
  @Selector([Zoo, ThemePark])
  static zooThemeParks(zoos, themeParks) {
    return [...zoos, ...themeParks];
  }
}

export class AppComponent {
  @Select(MyGlobalSelection.zooThemeParks) zooThemeParks$;
}
```

**Comment by ozergul** [comment]
Awesome! Thanks.
