### ISSUE TITLE
🚀[FEATURE]: Convenient dispatch

### ISSUE THREAD

**Issue by davidmorissette** [ngxs/store#1589]
### Relevant Package

This feature request is for @ngxs/store

### Description
As stated in the documentation:

> The Observable that a dispatch returns has a void type, this is because there can be multiple states that listen to the same @Action, therefore it's not realistically possible to return the state from these actions since we don't know the form of them.

In other words, "dispatch" cannot return a value since it doesn't know which states are listening to the action.

### Describe the problem you are trying to solve
1) "dispatch" tends to produce repetitive code. For instance, "selectSnapshot" is typically used when subscribing so we get a reference to a well-known impacted state.

```
this.store.dispatch(new AddAnimal(name)).subscribe(() => {
  const state = this.store.selectSnapshot(AnimalsState.animals);
});
```

2) "dispatch" can also be cumbersome when we need to obtain the return value from an Action.

```
@Select(state => state.animals) animals$: Observable<any>;

addAnimal(name: string) {
  this.store
    .dispatch(new AddAnimal(name))
    .pipe(withLatestFrom(this.animals$))
    .subscribe(([_, animals]) => {
      // do something with animals
      this.form.reset();
    });
}
```

### Describe the solution you'd like
The fact that "dispatch" returns an observable of any (void) is an opportunity to do better regarding the problems described in the previous section.

We don't know which states the action impacts, but we know which state we want to get a reference to, if any.

I propose that "dispatch" could return an object of "ActionResult" type:

```
export interface ActionResult<T> {
  state: T,
  value: any
} 
```

For instance, when implementing a State method, it would be possible to return a value:

```
@Action(AddAnimal)
addAnimal(context: StateContext<AnimalStateModel>, action: AddAnimal): Animal {
    const animal = new Animal(action.name);
    const state = ctx.getState();

    context.setState({
      animals: [...state.animals, animal]
    });

    return animal;
}
```

Then, when using "dispatch", the caller could proactively dictate the State for which he wants to get a reference to, and "dispatch" would return an ActionResult containing both the State and the return value associated to it, if any:

```
this.store.dispatch(new AddAnimal("zebra"), AnimalState.animals).subscribe(result=> {
  const state = result.state;
  const animal = result.value;
});
```

N.B. Support should also be provided the same way for async Actions.

This solution does not introduce any breaking changes since the second parameter in "dispatch" would be optional.

**Comment by splincode** [comment]
https://github.com/ngxs/store/issues/827
The value passed in the observable returned from a dispatch call should be void, matching its interface

**Comment by splincode** [comment]
@markwhitfeld can be close?

**Comment by arturovt** [comment]
@splincode I agree it can be closed. The `dispatch` should be treated as it returns `stream<void>` and we have a clear description of why this behaviour is implemented like that.
