### ISSUE TITLE
Peculair behaviour of destructuring

### ISSUE THREAD

**Issue by st-clair-clarke** [ngxs/store#159]
Hi,
I have the following:

      @Action( RsRosCoughUiUpdate )
      rsRosCoughUiUpdate( { getState, patchState }: StateContext<IRs>, payload: IFormState ) {
        console.log( `classToPlain(payload) | ${JSON.stringify( classToPlain(payload) ) }` )
        console.log('PAYLOAD', payload)
        console.log('PAYLOAD STATUS', payload.status)
        console.log('PAYLOAD STATUS', payload['status'])
        console.log( `change-before | ${JSON.stringify( payload.change ) }` )
        console.log(classToPlain(payload))
        console.log( `change-after | ${JSON.stringify( payload.change ) }` )
        
        let {change, dirty, pristine, status, target, touched, untouched} = payload
        
        console.log(change, dirty, pristine, status, target, touched, untouched)
        
        const nextState = produce( getState(), draftState => {
          let {change, dirty, pristine, status, target, touched, untouched} = payload
          console.log( `change | ${JSON.stringify( payload.change ) }` )
    //       draftState.ros.ui.cough = payload
    
          
          
    //      draftState.ros.ui.cough =    {...payload}
    //      draftState.ros.ui.cough.change = payload.change
    //      draftState.ros.ui.cough.dirty = payload.dirty
    //      draftState.ros.ui.cough.pristine = payload.pristine
    //      draftState.ros.ui.cough.status = payload.status
    //      draftState.ros.ui.cough.target = payload.target
    //      draftState.ros.ui.cough.touched = payload.touched
    //      draftState.ros.ui.cough.untouched = payload.untouched
        } )
        
        patchState( { ...getState(), ...nextState } )
      }

When the application runs, the console log is shown below:

    classToPlain(payload) | {"payload":{"change":"add","dirty":true,"pristine":false,"status":"INVALID","target":"[cough->rs-ros]cmp","touched":true,"untouched":false}}
    rs.store.ts:73 PAYLOAD RsRosCoughUiUpdate {payload: FormState}
    rs.store.ts:74 PAYLOAD STATUS undefined
    rs.store.ts:75 PAYLOAD STATUS undefined
    rs.store.ts:76 change-before | undefined
    rs.store.ts:77 {payload: {…}}payload: {change: "add", dirty: true, pristine: false, status: "INVALID", target: "[cough->rs-ros]cmp", …}__proto__: Object
    rs.store.ts:78 change-after | undefined
    rs.store.ts:82 undefined undefined undefined undefined undefined undefined undefined
    rs.store.ts:86 change | undefined

Questions:
1. Why the destructured values always undefined?
2. Why does the dot traversal of the payload object graph always undefined?

Cheers

**Comment by leon** [comment]
Hi!

That's very strange.

if you remove all your debug info and just add a `console.log(payload)`
Do you get anything then?

**Comment by st-clair-clarke** [comment]
Strange indeed!

See the graphic below 

![debug](https://user-images.githubusercontent.com/3227590/37890674-64cc5c2c-309f-11e8-8959-d367bd1e73bb.jpg)

**Comment by leon** [comment]
I see the problem now.
The second argument is not the payload it's the action.

So you need to to get the payload from the action first

```TS
@Action(RsRosCoughUiUpdate)
rsRosCoughUiUpdate( { getState, patchState }: StateContext<IRs>, action :RsRosCoughUiUpdate) {
  const payload = action.payload;
}
```

**Comment by st-clair-clarke** [comment]
Thanks and cheers!
