### ISSUE TITLE
🐞[BUG]: updateFieldValue with propertyPath setting boolean to empty javascript object

### ISSUE THREAD

**Issue by KevinCalmant** [ngxs/store#1590]
Hello, 

I was using the updateFieldValue function but i found out a strange behavior with formControl. 

This is the payload of the ngxs action  => 

{
  payload: {
    value: true,
    path: 'editRequestForms.activeForm',
    propertyPath: 'cper'
  },
  type: '[Forms] Update Form Value'
}

Sadly the cper value wasn't updated to true or false but to an empty javascript object => 

![image](https://user-images.githubusercontent.com/11736770/81313140-c054f780-9087-11ea-87e0-141c4a9f358b.png)

I don't understand why it doesn't work.

**Comment by arturovt** [comment]
Provide a minimal reproducible example, please.

> **Note:** Our policy is that issues reported without a reproduction will be closed immediately and then reopened once a reproduction has been provided. Please respect the developers of this project by doing this. We give of our personal time to work on this project and would rather be spending our time fixing or enhancing the library than chasing down badly described or unreproducable issues.

P.S. this is from the issue template.

**Comment by josh18** [comment]
It also converts strings to objects, minimal repro: https://stackblitz.com/edit/angular-ngxs-form-5317hg

I think the code assumes value is going to be an array or an object so it destructures it.

**Comment by ogalimov** [comment]
The reason can be found in line https://github.com/ngxs/store/blob/master/packages/form-plugin/src/form.plugin.ts#L31. There the value is beeing shallow copied, but only the cases object and arrays are handled, so primitives, like string are not working.

For me there are two questions here:
 1. Is therer a reason, why primitives are not handled properly?
 2. Is it really necessary to perform a shallow copy at all. Wouldn't it be the responsibility of the creator of the UpdateForrmAction?

**Comment by arturovt** [comment]
Yeah, the issue is still there. Unfortunately, I cannot say why it was implemented initially; it was many years ago. The only way to make it working properly is to add this as a fix to v4 since it's considered a breaking change.

**Comment by ogalimov** [comment]
I do not think, that testing for a primitive like described here: https://stackoverflow.com/questions/31538010/test-if-a-variable-is-a-primitive-rather-than-an-object and not doing a shallow copy for primitives, would be a breaking change

**Comment by arturovt** [comment]
We know that it’s not really working properly, I mean that the change will be breaking for projects already using the form plugin.

**Comment by ogalimov** [comment]
Now primitives are not working at all. It makes no sense to call UpdateFormValue with a primitive right now. I understand your concernes, yet I do not see a scenario, where this change would be breaking. However I am grateful, with you mantaining this project and so it will be your decision.

**Comment by markwhitfeld** [comment]
@arturovt I think that this is definitely a bug and I don't think it would be a breaking change.
If this has happened in any existing apps then I don't think that it would have been what they intended.

We could do the spread if the type is not `object` and the value is not null.

**Comment by josh18** [comment]
Would agree with ^, with the current implementation it isn't really possible to use primitives and you could continue to copy objects.

**Comment by arturovt** [comment]
No problem guys, since Mark confirmed that this is not a breaking change, we can provide a fix shortly.

**Comment by LeBeatle** [comment]
Any news on this one?

**Comment by tidusjar** [comment]
Also experiencing this issue

**Comment by markwhitfeld** [comment]
This has been fixed as part of the [v3.7.4](https://github.com/ngxs/store/releases/tag/v3.7.4) release.
Please test this out and let us know if this is not resolved.
