### ISSUE TITLE
[feature request]: Action methods accept wrong actions and patch state with their payloads

### ISSUE THREAD

**Issue by spockoyno** [ngxs/store#1601]
### Affected Package

 The issue is caused by  @ngxs/store, and possibly  @ngxs-labs/select-snapshot and @ngxs-labs/dispatch-decorator

### Is this a regression?

 Not sure.

### Description

I made an example Angular 9 Electron app. Its page 1 and 2 inputs correspond to  _DummyOneModel_ and  _DummyTwoModel_,  respectively, with either contained in _DummyStateModel_. A new value of the mat-slider on page 1  is dispatched within the payload of the _PutDummyOne_ action; similarly for page 2 and  _PutDummyTwo_. The console  outputs that both action methods on _DummyState_ receive _PutDummyOne_. I'd expect that only the method for _PutDummyOne_ would.  The second method incorrectly replaces the _dummyTwo_ field of the app's _DummyStateModel_ with the _DummyOneModel_ instance. So navigating to page 2 leads to an exception. A similar problem occurs when updating the  slider on page 2. 

## 🔬 Minimal Reproduction

 https://stackblitz.com/github/spockoyno/DoseWeb/tree/stack

Note: This being an electron desktop app, it probably won't run in stackblitz.

## 🔥 Exception or Error
<pre><code>

</code>core.js:4118 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'spec' of undefined
TypeError: Cannot read property 'spec' of undefined
    at new TwoComponent (two.component.ts:21)
    at NodeInjectorFactory.TwoComponent_Factory [as factory] (two.component.ts:41)
    at getNodeInjectable (core.js:3957)
    at instantiateRootComponent (core.js:8254)
    at createRootComponent (core.js:19266)
    at ComponentFactory.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ComponentFactory.create (core.js:23394)
    at ViewContainerRef.createComponent (core.js:10617)
    at RouterOutlet.push../node_modules/@angular/router/__ivy_ngcc__/fesm5/router.js.RouterOutlet.activateWith (router.js:5353)
    at ActivateRoutes.push../node_modules/@angular/router/__ivy_ngcc__/fesm5/router.js.ActivateRoutes.activateRoutes (router.js:2387)
    at router.js:2338
    at resolvePromise (zone.js:832)
    at resolvePromise (zone.js:784)
    at zone.js:894
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:28352)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:507)
    at invokeTask (zone.js:1671)
defaultErrorLogger @ core.js:4118
push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ErrorHandler.handleError @ core.js:4166
next @ core.js:28922
schedulerFn @ core.js:25731
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:192
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:130
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.EventEmitter.emit @ core.js:25713
(anonymous) @ core.js:28387
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:386
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:143
push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.NgZone.runOutsideAngular @ core.js:28304
onHandleError @ core.js:28387
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:390
push../node_modules/zone.js/dist/zone.js.Zone.runGuarded @ zone.js:157
_loop_1 @ zone.js:701
api.microtaskDrainDone @ zone.js:708
drainMicroTaskQueue @ zone.js:608
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:507
invokeTask @ zone.js:1671
globalZoneAwareCallback @ zone.js:1697</pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 9.1.9
- @ngxs/store version: 3.6.2

Browser:
- [x] Angular Electron Desktop 8.3.0 (presumably using Chrome 81)
 
For Tooling issues:
- Node version: 12.16.1  
- Platform:  MacOS 10.14.6 

Others:
This might not be directly relevant, but I'll say it anyway. NGXS's been a life-saver for state management in my angular apps. Hats off to the developers!

</code></pre>

**Comment by spockoyno** [comment]
The issue is not restricted to sliders but also happens with a regular material input field.

**Comment by spockoyno** [comment]
Found it! [https://stackoverflow.com/questions/59363163/ngxs-dispatch-run-all-action-for-state](url). Took light eight hours though.

Would it be possible to throw an error if an Action type is specified incorrectly?

**Comment by splincode** [comment]
Therefore, I no longer use action in the project, now I use methods directly
https://github.com/ngxs-labs/data

**Comment by spockoyno** [comment]
That's a very neat package - like half the original code. Definitely worth looking into.

**Comment by spockoyno** [comment]
Closing this as it's not an NGXS bug. But it may be useful to have a feature to prevent this; see #1603
