### ISSUE TITLE
🐞[BUG]: apply rxjs operators to @Select in component

### ISSUE THREAD

**Issue by zead1992** [ngxs/store#1602]
**Vesions:**
ngxs: 3.6.2

**Repro:**
stackblitz https://stackblitz.com/edit/angular-ivy-lux1zk

**Observed behavior**
i am trying to apply RxJS operators to observable returned by @Select in component ,
the only way is to get the selector using store.select.

**Comment by splincode** [comment]
this is the expected behavior, if you want something else, you can use select manually

I would also recommend that you look at the new plugin, which eliminates the use of selectors
https://github.com/ngxs-labs/data
