### ISSUE TITLE
🚀[FEATURE]: Throw an error if an Action's static type field is undefined.

### ISSUE THREAD

**Issue by spockoyno** [ngxs/store#1603]
### Relevant Package

 This feature request is for @ngxs/store.

### Description
 This would prevent bugs due to mistyped action definitions like 
 `export class ChangedInputs{
 static readonly type: '[Inputs] updated user inputs'
  constructor(public value: InputModel) {}
}`
which should have `type =` instead. Neither the IDE nor TypeScript flags this as error. In my case, this  caused state's action methods to catch the wrong actions and update Models with their payloads. I thought it was a bug in NGXS, see #1601, then after a few hours found a solution in  [SO question](https://stackoverflow.com/questions/59363163/ngxs-dispatch-run-all-action-for-state). Conceivably, it may take a while to realise there is a problem in the first place. 

### Describe the solution you'd like
 Seemingly the most straightforward solution is to check an action's type field and throw an error if it's undefined. Surely, a  `static readonly` field should be assigned only once at the class definition. 

### Describe alternatives you've considered
 Open a  Webstorm issue to flag this typo as error (might take years before it's implemented though). Also, consider using  [](https://github.com/ngxs-labs/data) in a future project, so such issues can't appear. It might be also helpful to mention this typo in the docs.

**Comment by splincode** [comment]
You can send PR also)

**Comment by markwhitfeld** [comment]
Good news, this has been addressed in NGXS v3.7 which was released last week.
( see https://dev.to/ngxs/announcing-ngxs-3-7-1kbk for release notes )

I will close this issue. Please let us know if it is not resolved.
