### ISSUE TITLE
dispatching action with-in action (pipe/map) triggered twice

### ISSUE THREAD

**Issue by xmlking** [ngxs/store#161]
### Versions

```
* ngxs: 2.0.0-rc.21
* @angular/core:  6.x
```

### Repro steps
dispatching action with-in action (pipe/map) triggered twice
following code ` dispatch(new LoginSuccess(profile));` getting triggered twice.
 
https://github.com/xmlking/nx-starter-kit/blob/master/libs/auth/src/auth.state.ts#L109

* Step 1
login :
https://xmlking.github.io/nx-starter-kit/home
* Step 2
look in the console logs.  `in LoginSuccess` print twice 
Redux  also show the `LoginSuccess` action twice.
* Step 3
logout

### Observed behavior
dispatching action with-in action (pipe/map) triggered twice , based on logs and redux 

### Desired behavior

Action should trigger once.

**Comment by deebloo** [comment]
I thought this was fixed I'll look into it

**Comment by deebloo** [comment]
What happens If you return dispatch instead of just calling it?

**Comment by deebloo** [comment]
@xmlking can you reproduce in the following test? 
https://github.com/ngxs/store/blob/master/packages/store/tests/dispatch.spec.ts#L48

**Comment by xmlking** [comment]
testing here :
https://stackblitz.com/edit/angular-ngxs-rxjs6-test

if you add `async` for increment2 function , it is not working (async and Observable combination)
```ts
    @Action(Increment2)
   async increment2({ getState, setState, dispatch }: StateContext<any>) {
            return new Observable(observer => {
          observer.next(dispatch(new Increment()));
          observer.complete();
        });

  }
```

**Comment by deebloo** [comment]
@xmlking what happens if you call the dispatch function outside of the .next method?

**Comment by deebloo** [comment]
fixed in master.

**Comment by DirkWolthuis** [comment]
I see my outgoing HTTP-calls fire twice, could this be the fix for that problem? 

```
@Action(SelectAvailableProduct)
	selectAvailableProducts({ getState, setState, dispatch }: StateContext<IProductConfigurationState>, { payload }: SelectAvailableProduct) {

		const findProduct = item => item.type === 'product';

		if (getState().selectedItems.find(findProduct)) {
			let selectedItemsWithoutProduct = getState().selectedItems.filter(
				item => item !== getState().selectedItems.find(findProduct)
			)
			selectedItemsWithoutProduct.push(payload)
			setState({
				...getState(),
				selectedItems: selectedItemsWithoutProduct
			})
		}
		else {
			setState({
				...getState(),
				selectedItems: [...getState().selectedItems, payload]
			})
		}

		return dispatch([new GetAvailableMaterials(), new GetAvailableFormats(), new GetAvailableColors(), new GetAvailableSides()]);
	}
```

**Comment by deebloo** [comment]
@DirkWolthuis if you are seeing an problem can you open a new issue?

**Comment by sanjeev-roughshod** [comment]
I am having the same problem. Actions dispatched from within another action triggers multiple calls.
I am using 3.0.1.
