### ISSUE TITLE
Custom Action Type name

### ISSUE THREAD

**Issue by vharadkou** [ngxs/store#162]
### Versions

```
* ngxs: 2.0.0-rc.21
* @angular/core: 5.2.9
```

### Proposal
Provide opportunity to declare Action Type in custom string format.
Only in case if no custom type is provided, generate it from class name.

![image](https://user-images.githubusercontent.com/5987672/37901105-efcb5306-30f8-11e8-87fa-b7df6ab0280b.png)

![image](https://user-images.githubusercontent.com/5987672/37901340-91c481e6-30f9-11e8-9b44-c2728acd3658.png)

**Comment by deebloo** [comment]
I think this already work. What happens if you make the type property static?

**Comment by mailok** [comment]
@vharadkou It already works that way, just have to put **static**:

```
export enum Types {
  SEARCH = '[PARK] search',
  GROW = '[PARK] grow person'
}

export class GrowPersons {
  static type = Types.GROW;

  constructor(readonly payload: string) {
  }

}

export class SearchPeoples {
  static type = Types.SEARCH;
}

```

**Comment by deebloo** [comment]
Closing as answered

**Comment by vharadkou** [comment]
Thanks.
