### ISSUE TITLE
🚀[FEATURE]: Angular 10

### ISSUE THREAD

**Issue by splincode** [ngxs/store#1630]
https://github.com/ngxs/store/blob/master/packages/store/package.json#L8

```
"peerDependencies": {
    "@angular/core": ">=6.1.0 <10.0.0",
    "rxjs": ">=6.5.5"
  },
```

**Comment by acuetoblumer** [comment]
I have the same problem, i cant migrate to Angular 10.0.0

**Comment by arturovt** [comment]
> I have the same problem, i cant migrate to Angular 10.0.0

Why?

**Comment by splincode** [comment]
https://github.com/angular/angular/issues/37926

**Comment by dimitri-bret** [comment]
Any news on this? Our team highly rely on Ngxs, so it would be amazing to work with Angular 10. I saw the PR is ready to go, do you have an idea when it will be available for all? 
Thank you for your great work!

**Comment by splincode** [comment]
some work required

- [ ] Deprecated `@ngxs/hmr-plugin`

**Comment by CesarD** [comment]
Waiting for this as well...

**Comment by ckorherr** [comment]
Same here...

**Comment by ValisStigma** [comment]
Same here, would be very much appreciated

**Comment by jayordway** [comment]
Does NGXS 3.7.x support angular 10.x yet? What is the status on this?

**Comment by LucasFrecia** [comment]
I just worked on a n ang 10 test project with ngxs, it works... i found no issues yet. https://github.com/LucasFrecia/fedex-signup

**Comment by markwhitfeld** [comment]
Angular v10 is officially supported from NGXS v3.7 ( and is confirmed as working in v3.6 ).
Support for HMR was unfortunately dropped due to lack of official Angular support for the HMR workflow.
Everything else is golden 😄 .
( see https://dev.to/ngxs/announcing-ngxs-3-7-1kbk for release notes )

**Comment by Y2zz** [comment]
Angular 11 already supports hmr, is ngxs considering following up?

**Comment by TimFoerster** [comment]
Angular 10 is supported with ngx 3.7.0
