### ISSUE TITLE
🐞[BUG]: Devtools plugin zone error with webworker

### ISSUE THREAD

**Issue by eggp** [ngxs/store#1644]
### Affected Package

@ngxs/devtools-plugin

### Is this a regression?

All version

### Description

In one of my projects I use webworkers under angular 8. For which I use `comlink` (https://github.com/GoogleChromeLabs/comlink). Sometimes I got a Promise error while using the worker in Angular serve mode. I investigated a lot to solve the problem because I always suspected it has something to do with the handling of the Angular worker or comlink. However, one thing has always been stated in the stack trace is that there was always a call from devtool.plugint.ts at the beginning of the stack trace. The error itself always came out when, because of the effect of a feature, we dispatched an Action, and subscribing to that Actions stream, the worker started at another point in the code. Unfortunately, I can't show the code and simulating an error isn't that simple either, because it didn't show up at every worker startup.

## 🔥 Exception or Error

Comlink Promise error from zonejs

## Environment

<pre><code>
Libs:
- @angular/core version: 8.2.14
- @ngxs/store version: 3.6.1
- @ngxs-labs/attach-action": 0.1.3
- @ngxs-labs/dispatch-decorator": 2.1.0
- @ngxs-labs/immer-adapter": 3.0.5
- @ngxs-labs/select-snapshot": 1.2.0
- @ngxs/devtools-plugin": 3.6.2
- @ngxs/form-plugin": 3.6.1
- @ngxs/storage-plugin": 3.6.1
Browser:
- [x] Chrome (desktop) version 83.0.4103.116 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
For Tooling issues:
- Node version: v12.13.0
- Platform: Linux
</code></pre>

### Suggestion after which the error no longer occurred:
[devtools.plugin.ts](https://github.com/ngxs/store/blob/master/packages/devtools-plugin/src/devtools.plugin.ts#L21)
Constructor replace:

<pre><code>
  constructor(
    @Inject(NGXS_DEVTOOLS_OPTIONS) private _options: NgxsDevtoolsOptions,
    private _injector: Injector,
    private ngZone: NgZone,
    @Inject(WINDOW) private windowObj: Window
  ) {
    this.ngZone.runOutsideAngular(() => {
      const globalDevtools = this.windowObj['__REDUX_DEVTOOLS_EXTENSION__'] || this.windowObj['devToolsExtension'];
      if (globalDevtools) {
        this.devtoolsExtension = globalDevtools.connect(_options) as NgxsDevtoolsExtension;
        this.devtoolsExtension.subscribe(a => this.dispatched(a));
      }
    });
  }
</code></pre>

So we really just exclude devtools messages from the zone, so we exclude incorrect zonejs subscriptions because zonejs is unnecessary here. Everything went well in the browser plugin as before. With 3 weeks of continuous daily development, after applying the patch, there was no longer a problem calling workers.

**Comment by arturovt** [comment]
This has been fixed as part of the [v3.7.4](https://github.com/ngxs/store/releases/tag/v3.7.4) release.
Please test this out and let us know if this is not resolved.
