### ISSUE TITLE
🚀[FEATURE]: Conditional action dispatching

### ISSUE THREAD

**Issue by jjsiman** [ngxs/store#1650]
### Relevant Package

 This feature request is for @ngxs/store

### Description
 Allow `undefined` in the dispatch array.

### Describe the problem you are trying to solve
 I have a long array of actions being dispatched in my store, although some of them are conditional and I would like an elegant solution to skip over those.
Similar to how Angular Schematics has the [noop() rule](https://github.com/angular/angular-devkit-schematics-builds).

### Describe the solution you'd like
Allow undefined in the dispatch array
```
ctx.dispatch([
   new MyAction(),
   myBoolVar ? MyConditionalAction() : undefined
]);
```
or a prebuilt empty action like `noop()`.
### Describe alternatives you've considered
 Currently using undefined results in the error 
`Cannot read property 'constructor' of undefined at getActionTypeFromInstance(ngxs-store.js:488)`.

My current workaround  is 
```
ctx.dispatch([
   new MyAction(),
   ...[myBoolVar ? [new MyConditionalAction] : []]
]);
```
which works well but isn't super intuitive in my mind.

**Comment by splincode** [comment]
```
class NoopAction {
  public static type = '[NOOP]';
}

ctx.dispatch([
   new MyAction(),
   myBoolVar ? MyConditionalAction() : new NoopAction()
]);
```

**Comment by jjsiman** [comment]
@splincode yeah definitely, and I can see the pros and cons of having "[NOOP]" in the devtools. In my mind `undefined` would not record any action.

**Comment by arturovt** [comment]
Seems like this might be closed. I don't think there's a reason to change the core action handling pipeline since this is easily handled:
```ts
const actions = [new MyAction()]
if (myBoolVar) actions.push(new MyActionAgain())
dispatch(actions)
```
