### ISSUE TITLE
🚀[FEATURE]: add navigation extras to route serializer

### ISSUE THREAD

**Issue by RhysOnlyBetter** [ngxs/store#1655]
### Relevant Package
This feature request is for @ngxs/router-plugin

### Description
RouterStateSerializer does not propagate NavigationExtras.

### Describe the problem you are trying to solve
I'm trying to add some additional route data via `this.store.dispatch(new Navigate(['/route'], {}, { state: { data: { folderPath: "1/2/3"}}}));`
and I can see this data logged in the [Router] Navigate payload, but it's not added to the data object in the router state data object.

### Describe the solution you'd like
It appears that the serializeRoute function doesn't return the navigation extras object. It would be great if this could be added. https://github.com/ngxs/store/blob/master/packages/router-plugin/src/serializer.ts

### Describe alternatives you've considered
I have tried to add this via my custom route serializer, but couldn't work out how.

**Comment by arturovt** [comment]
Thank you for submitting this feature request.
We are closing this issue due to the fact that:
- There has not been much support from other community members

Thanks again
- NGXS Core Team :heart:
