### ISSUE TITLE
❓[SUPPORT]:  how can i get state value from another component in ngxs

### ISSUE THREAD

**Issue by lightman0215** [ngxs/store#1658]
stackblitz example: [https://stackblitz.com/edit/angular-ivy-jvewmr?](https://stackblitz.com/edit/angular-ivy-jvewmr?)
browse [https://angular-ivy-jvewmr.stackblitz.io/worker-archive/worker-dashboard](https://angular-ivy-jvewmr.stackblitz.io/worker-archive/worker-dashboard)

common.state.ts

import { Action, Selector, State, StateContext } from '@ngxs/store';
 import { NzMessageService } from 'ng-zorro-antd';
import { PermissionDict } from '../../model/organization-authority/setting/permission-dict.model';
import { CommonService } from '../../service/common.service';
import {GetIsSuperAdminAction} from '../action/common.action';
import { map } from 'rxjs/operators';
import { Injectable } from '@angular/core';

export interface CommonStateModel {
   superAdminState: number;
}

@State<CommonStateModel>({
    name: '_CommonState',
    defaults: {
        superAdminState: null
    }
})
@Injectable()
export class CommonState {
constructor(
    private _commonService: CommonService,
  
) {}

@Selector()
public static superAdminState(state: CommonStateModel) {
    console.log(state.superAdminState + 'A');
   //is not execute
    return state.superAdminState;
}

/**
 * @param ctx
 * @param action
 */
@Action(GetIsSuperAdminAction)
GetIsSuperAdminAction(ctx: StateContext<CommonStateModel>, action: GetIsSuperAdminAction) {
    console.log(action.superAdminState);
    const state = ctx.getState();
    ctx.setState({ ...state, superAdminState: action.superAdminState });
}
}

layout.component.ts:
`onClick(){
   this._store.dispatch(new GetIsSuperAdminAction(Math.random()));
}`

worker-dashboard.component.ts
`superAdminState: Observable<number>;
this.superAdminState = this._store.select(CommonState.superAdminState);`

worker-dashboard.component.html
`{{ superAdminState | async }}`

i can't get superAdminState state value,because superAdminState display in html value is undefined,but action already changed this state value.
![avatar](https://i.stack.imgur.com/e1nX1.png)
![avatar](https://i.stack.imgur.com/Wtk1a.png)

**Comment by ccosmincc** [comment]
Hi,
 Just move this part `NgxsModule.forRoot([CommonState])` from `share.module.ts` imports section into `app.module.ts` imports section and you will achieve the expected result. For more details, you can read [here](https://angular.io/guide/ngmodule-faq#what-is-the-forroot-method).

**Comment by lightman0215** [comment]
thx,it's worked!!
