### ISSUE TITLE
Multiple calls HTTP in one action

### ISSUE THREAD

**Issue by mailok** [ngxs/store#166]
### Versions

```
* ngxs: 2.0.0-rc.21
* @angular/core: 5.2.9
```

When I define an acynchronous action, multiple calls are made.

```
@Action(SearchPeoples)
  serarchPeoples({ getState, setState }: StateContext<ParkStateModel>) {
    const state = getState();
    return this.http.get<Search>('https://randomuser.me/api/?results=5').pipe(
      tap(value => {
        console.log('updating the state...');
        setState({
          ...state,
          search: value.results
        });
        console.log('status updated.');
      })
    );
  }

```

```
search() {
    this.store.dispatch(new SearchPeoples()).subscribe(value => {
      console.log('The action is completed.');
    });
  }

```

When I dispach the action:

![a](https://user-images.githubusercontent.com/3769277/37911026-f9a704f4-30dc-11e8-8bf1-f366911acb31.PNG)

![b](https://user-images.githubusercontent.com/3769277/37911032-ff6bb9fc-30dc-11e8-8b6b-fa6b290bca13.PNG)

Two calls HTTP are made, when it should have been one.

I thought it had been solved : fix(core): fix dispatch issue #149 , but it seems that there is still the bug.

I thought it was no longer necessary to use ``` shareReplay() ``` in my action for solve this.

**Comment by amcdnl** [comment]
@deebloo - this one is haunting you!

**Comment by deebloo** [comment]
@mailok it shouldn't be. I will try to track this one down again

**Comment by deebloo** [comment]
@leon it looks like shareReplay is doing what it says lol. also @mailok there were two issues. one was the subscriber being called multiple times. that appears fixed. will try to track down this one

**Comment by deebloo** [comment]
@mailok can you reproduce in the following test? 
https://github.com/ngxs/store/blob/master/packages/store/tests/dispatch.spec.ts#L48

**Comment by mailok** [comment]
@deebloo The difference is that I am using my action in a feature module

**Comment by deebloo** [comment]
ooooo that is a good thing to point out. let me see if I can add that to the tests

**Comment by deebloo** [comment]
@mailok can you confirm if that happens when a state class is defined in the root as well?

**Comment by deebloo** [comment]
ill also try making sure there are tests for substates

**Comment by mailok** [comment]
@deebloo I just tried it alone, in the root, and behaves with the same error:

```
import {HttpClient} from '@angular/common/http';
import Search = namespace.Search;
import Result = namespace.Result;
import {shareReplay, tap} from 'rxjs/operators';
import {Action, State, StateContext} from '@ngxs/store';

export class SearchPeoples {

}

export interface AppStateModel {
  search: Result[];
}

@State<AppStateModel>({
  name: 'app',
  defaults: {
    search: []
  }
})
export class AppState {
  constructor(private http: HttpClient) {
  }


  @Action(SearchPeoples)
  serarchPeoples({getState, setState}: StateContext<AppStateModel>) {
    const state = getState();
    return this.http.get<Search>('https://randomuser.me/api/?results=5').pipe(
      tap(value => {
        console.log('updating the state...');
        setState({
          ...state,
          search: value.results
        });
        console.log('status updated.');
      })
    );
  }
}

```

```
Search() {
    this.store.dispatch(new SearchPeoples()).subscribe(value => {
      console.log('The action is completed.');
    });
  }

```
```
<button (click)="Search()">Search</button>

```

```
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    HttpClientModule,
    RouterModule.forRoot(routes),
    NgxsModule.forRoot([AppState]),
    NgxsReduxDevtoolsPluginModule.forRoot({
      disabled: false
    }),

```

**Comment by deebloo** [comment]
@mailok can you look inside your node_modules and confirm the version? Im having trouble reproducing. Could you create a staclblitz or something with a minimal reproducible example

**Comment by mailok** [comment]
@deebloo yes, This is a picture of me node_modules, and and I'm going to make an example in staclblitz

![captura](https://user-images.githubusercontent.com/3769277/37921210-26c37b60-30f7-11e8-80fc-70281a4622d5.PNG)

**Comment by deebloo** [comment]
@mailok thank you!

**Comment by deebloo** [comment]
it is also strange that it would work on 109 but not on 98? since it would be calling shareReplay on the result from _dispatchActions

**Comment by deebloo** [comment]
also if you can fix it and prove it works in a test feel free to submit a PR

**Comment by yarrgh** [comment]
I think it is from 
https://github.com/ngxs/store/blob/1d753203aad8805d38b00ff8e0dbc41031aa7102/packages/store/src/store.ts#L105

If you return an observable, I think that line will cause another subscription to be made.

**Comment by deebloo** [comment]
I just don't understand how moving the shareReplay down a level fixes teh issue. I believe that it does I just don't understand why

**Comment by deebloo** [comment]
maybe in cases when it just hits ```of()```?

**Comment by mailok** [comment]
@deebloo hi!, I made an example : https://stackblitz.com/edit/angular-sebheh , but in stackblitz works correctly, so I made a new project in my pc with angular-cli and reproduced the proyect, and behaves with the bug, I really do not know what can be

**Comment by mailok** [comment]
@deebloo  checked, a project created in stackblitz, works correctly, and the same, reproduced with a project created with angular-cli does not work correctly, makes multiple HTTP requests

**Comment by deebloo** [comment]
well that is certainly strange. looks like your stackblitz demo is using rc.22 is that the same as your local project?

**Comment by mailok** [comment]
@deebloo yes, is the same version

**Comment by deebloo** [comment]
yes that is very bizarre indeed

**Comment by deebloo** [comment]
@mailok if you export the project from stackblitz do you see the error?

**Comment by mailok** [comment]
@deebloo ya!!!, i found the problem!! is that:
```
    NgxsReduxDevtoolsPluginModule.forRoot({
      disabled: false
    })
```

**Comment by deebloo** [comment]
??? the devtools are causing the issue?

**Comment by mailok** [comment]
@deebloo when I delete it it works correctly: 
```
NgxsReduxDevtoolsPluginModule.forRoot({
      disabled: false
    })

```
when I put it, multiple requests are made

**Comment by deebloo** [comment]
cc @amcdnl

**Comment by mailok** [comment]
@deebloo look at https://stackblitz.com/edit/angular-sebheh

**Comment by deebloo** [comment]
@mailok looking now. still seeing error when I remove the devtools plugin

**Comment by mailok** [comment]
@deebloo in my case, when I delete it, the error is eliminated

**Comment by mailok** [comment]
@deebloo Well, now it's crazy lol.

**Comment by deebloo** [comment]
@mailok ah no there it is! (I was using an account without redux devolls extension installed
)

**Comment by yarrgh** [comment]
Could that be why moving the `shareReplay()` up a level works?
Does the plugin create its own subscription before `shareReplay()` is called?

**Comment by deebloo** [comment]
it is entirely possible. I am going to try some things and then submit a PR

**Comment by deebloo** [comment]
I am going to do both

**Comment by Jucian0** [comment]
https://github.com/Jucian0/authentication-ngxs-angular
