### ISSUE TITLE
Docs - Invalid link for Storage - (still points to localstorage file)

### ISSUE THREAD

**Issue by un33k** [ngxs/store#167]
[x] bug

### Versions

```
    "@ngxs/devtools-plugin": "^2.0.0-rc.22",
    "@ngxs/logger-plugin": "^2.0.0-rc.22",
    "@ngxs/storage-plugin": "^2.0.0-rc.22",
    "@ngxs/store": "^2.0.0-rc.22",
```

### Repro steps

* Click on LocalStorage in docs

### Observed behavior

localstorage.md was renamed to storage.md, but the link in summary still points to the old file.
https://github.com/ngxs/store/blob/master/docs/plugins/localstorage.md

### Desired behavior

Fixed the link and change the title to Storage.

OLD:
  ```* [Local Storage](plugins/localstorage.md)```
FIXED:
  ```*[Storage](plugins/storage.md)```

**Comment by amcdnl** [comment]
Fixed.
