### ISSUE TITLE
🚀[FEATURE]: Ability to use Store entity inside ErrorHandler

### ISSUE THREAD

**Issue by hshahdoost** [ngxs/store#1687]
### Relevant Package
This feature request is for @ngxs/....
@ngxs/store

### Description
When trying to inject `Store` entity into the global error handler, we get the following error
```
Cannot instantiate cyclic dependency! ErrorHandler
```
Seems like the `Store` entity has the global error handler as one of it's dependencies, which is normal, But there must be some workaround's to use store and specially dispatch actions in our global error handler.

**Comment by markwhitfeld** [comment]
This issue has been resolved in NGXS v3.7.2 which was released today.
Please try it out and let me know if you have any issues.
