### ISSUE TITLE
📚[DOCS]: 

### ISSUE THREAD

**Issue by tmtron** [ngxs/store#1689]
### Description

In the source code the `ctx` parameter of `ngxsOnInit()` is optional:

https://github.com/ngxs/store/blob/5280e6d7d32034af0c31abb5d5d073cc0c965326/packages/store/src/symbols.ts#L155

but according to the [docs](https://github.com/ngxs/store/blob/7c6a5d226582ecf64c1a14a9547637db7204f24b/docs/advanced/life-cycle.md#ngxsoninit) and [example code](https://github.com/ngxs/store/blob/b27bbcc603e80e24af6ca388930aec00863bcd7a/integration/app/store/todos/todo/todo.state.ts#L25) it is required

Not sure, if the documentation is wrong or the interface definition

### What's the affected URL?**
 
https://www.ngxs.io/advanced/life-cycle#ngxsoninit

**Comment by tmtron** [comment]
the same is true for `ngxsAfterBootstrap`  
https://github.com/ngxs/store/blob/5280e6d7d32034af0c31abb5d5d073cc0c965326/packages/store/src/symbols.ts#L169

doc ref: https://www.ngxs.io/advanced/life-cycle#ngxsafterbootstrap

**Comment by arturovt** [comment]
@tmtron would you want to make a PR?
