### ISSUE TITLE
🐞[BUG]: Websocket plugin is not usable on Angular 10, is this known?

### ISSUE THREAD

**Issue by jrch2k20** [ngxs/store#1690]
### Affected Package
@ngxs/Websocket
### Is this a regression?
Unknown
### Description
Any web socket connection is instantly closed and no apparent reason of why whereas any other implementation i tested included https://www.websocket.org/echo.html behave correctly.

Correct behavior is to stay open until close is called

backend is custom C++ uwebsockets implementation and as mentioned every other method i've tried include pure rxjs websockets work as intended but i really wanted to use ngxs, so any help is appreciatted.

## 🔬 Minimal Reproduction

<pre><code>
import { Injectable } from '@angular/core';
import { Store } from '@ngxs/store';

import { ConnectWebSocket, SendWebSocketMessage } from '@ngxs/websocket-plugin';
@Injectable({
  providedIn: 'root'
})
export class Test {

  constructor(private store: Store, private router: Router) {
    this.store.dispatch(new ConnectWebSocket({ url: 'wss://127.0.0.1:3000/api/session' }));
  }
</code></pre>
## 🔥 Exception or Error
<pre><code>

</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 10.2.2
- @ngxs/store version: 3.7.0

Browser:
- [ x] Chrome (desktop) version 86
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version 82
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jrch2k20** [comment]
Well, after testing a lot i realized the problem is generated when i have more than 1 connection aka 
<pre><code>
import { Injectable } from '@angular/core';
import { Store } from '@ngxs/store';

import { ConnectWebSocket, SendWebSocketMessage } from '@ngxs/websocket-plugin';
@Injectable({
  providedIn: 'root'
})
export class Test1 {

  constructor(private store: Store, private router: Router) {
    this.store.dispatch(new ConnectWebSocket({ url: 'wss://127.0.0.1:3000/api/session' }));
  }
</code></pre>

If this service is alone, all works fine and the websocket stay open waiting for data BUT if i eanble this in another service

<pre><code>
import { Injectable } from '@angular/core';
import { Store } from '@ngxs/store';

import { ConnectWebSocket, SendWebSocketMessage } from '@ngxs/websocket-plugin';
@Injectable({
  providedIn: 'root'
})
export class Test2 {

  constructor(private store: Store, private router: Router) {
    this.store.dispatch(new ConnectWebSocket({ url: 'wss://127.0.0.1:3000/api/compute' }));
  }
</code></pre>

Then both sockets immediately disconnect with error 1005

**Comment by markwhitfeld** [comment]
Do you think that you would be able to reproduce this with a stackblitz?

**Comment by jrch2k20** [comment]
Sry, have no idea how but i moved on, the issue is basically related to a bug closed some time ago and basically since ngxs is global it cannot keep track of simultaneous connections to several different web sockets, so i basically written my own class for web socket and instance them where needed and as long as i respect the ngxs store format it works transparently.
