### ISSUE TITLE
🚀[FEATURE]: Angular 11

### ISSUE THREAD

**Issue by internalsystemerror** [ngxs/store#1692]
Angular 11 has now been released and this library should look towards supporting it.

**Comment by markwhitfeld** [comment]
100% agreed! It should work out of the box because we are Ivy compatible.
Have you had any issues or is the problem just regarding the npm dependency range?

PS. We plan to cut another release this week that has Angular 11 included in the npm dependency range.

**Comment by internalsystemerror** [comment]
No issues noticed in 2 apps so far, 1 using ngxs more than the other. Although I had no issues upgrading form 9 to 10 either. Mainly just want to ensure that the tests in this repository are run against ng11 before putting these live. Thanks.

**Comment by cybercussion** [comment]
I had the same, seems fine.  I ended up having to do a 'npm outdated' and hand roll my updates.  Nuked my node_modules and did a fresh 'npm install'.

**Comment by bbarry** [comment]
`ng update @angular/core @angular/cli --force`  works fine for me updating to Angular 11 (aside from the compatibility warnings that would prevent it from running without --force). If you manually updated, review the angular changelog and the update migrations to determine if they apply to you.  Source for angular update migrations here: https://github.com/angular/angular-cli/tree/master/packages/schematics/angular/migrations

**Comment by splincode** [comment]
@miggymigz sorry, I wanted to send a comment, but pressed the wrong button. Most likely only one workaround will work now: `ng update @angular/core @angular/cli --force`

**Comment by miggymigz** [comment]
@splincode No worries. I just realized markwhitfeld already said that this week's release will include the updated dependencies. Sorry for that.

**Comment by markwhitfeld** [comment]
This is resolved with the release of v3.7.1
