### ISSUE TITLE
🚀[FEATURE]: REDUX Devtools test generation tab

### ISSUE THREAD

**Issue by MurhafSousli** [ngxs/store#1693]
### Relevant Package

**@ngxs/devtools**

### Description
 A clear and concise description of the problem or missing capability...

Why is test tab in Redux DevTools not showing? is it supported by ngxs?

if not, is it possible to add this feature?

The following screenshot is taken from a redux library (guessing ngrx)

<img width="626" alt="Screen Shot 2020-11-20 at 00 59 27" src="https://user-images.githubusercontent.com/8130692/99738812-a632b200-2acb-11eb-956e-80c7ab3fc215.png">

**Comment by arturovt** [comment]
The test tab exists.
