### ISSUE TITLE
❓[SUPPORT]:  Angular app does not start (exception on loading DispatchOutsideZoneNgxsExecutionStrategy)

### ISSUE THREAD

**Issue by alexandis** [ngxs/store#1702]
Running my Angular solution, I'm getting the following error:

> core.js:24134 Uncaught TypeError: Cannot read property 'id' of undefined
>     at registerNgModuleType (core.js:24134)

here (core.js):

```
function registerNgModuleType(ngModuleType) {
    if (ngModuleType.ɵmod.id !== null) { ... }
    ...
}
```

on `DispatchOutsideZoneNgxsExecutionStrategy` class.

Any thoughts what could be a reason?

Solution is large, I doubt I would be able to isolate it in test app. I may show some parts of code (module declarations, etc.), if it would shed some light.

**Comment by markwhitfeld** [comment]
It is really hard to debug this with the information that you have given.
Please could you modify your description to use the standard bug report template?
( found here: https://github.com/ngxs/store/issues/new?assignees=&labels=BUG%2FREGRESSION&template=--bug-report.md&title=%F0%9F%90%9E%5BBUG%5D%3A+ )

**Comment by alexandis** [comment]
It's hopeless then. Closing.
