### ISSUE TITLE
🐞[BUG]: Cannot start Angular app because of exception inside registerNgModuleType 

### ISSUE THREAD

**Issue by alexandis** [ngxs/store#1703]
### Affected Package
@ngxs/store

### Is this a regression?
No: I've added a project to my Angular app and now can't run the app because of the reported exception. I've also installed the following package that I need in this added project **ngxs-reset-plugin**: 

## 🔬 Minimal Reproduction
I'm afraid I can't create a test example, so attaching DevTools debug window:

![image](https://user-images.githubusercontent.com/6149843/100855090-79e74000-3492-11eb-9c22-4f0f148a295a.png)

The exception happens here:

![image](https://user-images.githubusercontent.com/6149843/100856261-df87fc00-3493-11eb-8c69-df2d7cca7d56.png)

## 🔥 Exception or Error
<pre><code>
core.js:24134 Uncaught TypeError: Cannot read property 'id' of undefined
    at registerNgModuleType (core.js:24134)
    at core.js:24145
    at Array.forEach (<anonymous>)
    at registerNgModuleType (core.js:24145)
    at core.js:24145
    at Array.forEach (<anonymous>)
    at registerNgModuleType (core.js:24145)
    at new NgModuleFactory$1 (core.js:24242)
    at compileNgModuleFactory__POST_R3__ (core.js:27786)
    at PlatformRef.bootstrapModule (core.js:28024)
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 11.0.2
- @ngxs/store version: 3.7.1

Browser:
- Chrome (desktop) version 87.0.4280.66 (Official Build) (64-bit)
</code></pre>

Additional info:

Don't now if it is relevant for the situtation, but I'm also getting the following warning when building any project in my app (not sure what it caused by - probably by installing **ngxs-reset-plugin**):

> (node:103512) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:103512) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
> (node:103512) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
> (node:103512) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
> (node:103512) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
> (node:103512) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency

**Comment by splincode** [comment]
I have same issue

**Comment by alexandis** [comment]
BTW, I have stashed all the changes into my app (removing new package, etc.). Left only npm_modules intact, i.e. having **ngxs-reset-plugin** installed. And the issue remains. Don't know what to do.

**Comment by alexandis** [comment]
Somehow it started to work, when I resolved other (not relevant at first glance) issues with the solution...

**Comment by armanozak** [comment]
Hi @alexandis,

We _are_ maintaining the plugin and have just seen the comment you left a few hours ago.

We would like to here about what you have changed to make it work. Could you please share the changes you made?

Thanks.

**Comment by alexandis** [comment]
Actually, I don't know what to say. Because there were a lot of changes.
Now it works with the following code:

import { NgxsResetPluginModule } from 'ngxs-reset-plugin';
- i have this in the project module which I use in my main app
import { StateReset } from 'ngxs-reset-plugin';
- i have this in the component of the project module, I export this
component (and also have this component in declaration area) and use in
main app

I dispatch the fore-mentioned component in main app component, using the
approach of ABP framework we use:
    this.store.dispatch(
      new AddReplaceableComponent({
        component: AbxNavItemsComponent,
        key: eThemeLeptonComponents.NavItems,
      }, true)
    );
Finally, I have the project module in import section of main app module

**Comment by armanozak** [comment]
Hi @alexandis,

We will take a look at it from this perspective, thanks. I’ll let you know if we find anything interesting or worth mentioning.

Have a nice day.
