### ISSUE TITLE
❓[SUPPORT]:  Strange order of action executing

### ISSUE THREAD

**Issue by karol93** [ngxs/store#1704]
Why action two is executing before the request is ended from action one?

```
@Injectable()
export class ZooState {
    constructor(private http: HttpClient) { }

    @Action(ActionOne)
    actionOne(ctx: StateContext<ZooStateModel>) {
        console.log('action one');
        return this.http.get<any>(`http://localhost:54323/api/groups`).pipe(tap((x)     
              => {
                        return ctx.dispatch(new ActionTwo())
                    }));
    }

    @Action(ActionOne)
    actionTwo(ctx: StateContext<ZooStateModel>) {
        console.log('action two');
        ctx.dispatch(new ActionThree())
    }

    @Action(ActionThree)
    actionThree(ctx: StateContext<ZooStateModel>) {
        console.log('action three');
    }
}
```

When I move HTTP request from action one to action two then it works correctly. The action tree is executing when request from action two is finished.

**Comment by markwhitfeld** [comment]
Hi @karol93 I assume that the second decorator there is supposed to refer to ActionTwo ;-)
This is most likely your issue ;-)

**Comment by karol93** [comment]
omg, what a mistake :/ thank you!

**Comment by markwhitfeld** [comment]
If that was just a typo in your issue then this may help your understanding:
You have the HTTP observable as the return value of `ActionOne`. Therefore action one will only complete once that observable completes. You are dispatching the `ActionTwo` action from within the observable, so `ActionTwo` will be dispatched before `ActionOne` ends (you are using a `tap` and not a `mergeMap`, so ActionOne's completion is not bound to the completion of `ActionTwo`). BUT, both `ActionTwo` and `ActionThree` are both synchronous, so they will actually complete before `ActionOne`.

This can also help with the understanding: https://www.ngxs.io/advanced/actions-life-cycle#asynchronous-actions-continued-fire-and-forget-vs-fire-and-wait
