### ISSUE TITLE
Subscribing to store.dispatch() causes devTools to receive action multiple times

### ISSUE THREAD

**Issue by yarrgh** [ngxs/store#171]
### Versions

```
* ngxs: 2.0.0-rc.23
* @angular/core: 5.2.9
```

### Repro steps
* Enable devTools plugin 
* Have devTools browser plugin installed and running
* Dispatch new action
* Subscribe to the `dispatch()` observable

```typescript
export class Test { }

@State({
  // ...
})
class MyState {
  @Action(Test)
  test({ patchState }: StateContext<RecipeStateModel>, action: Test) {
    patchState({ myCollections: [] });
  }
}


// ... later in the component...

this.store.dispatch(new Test()).subscribe();
```

### Observed behavior

Action shows up twice in devTools.

![image](https://user-images.githubusercontent.com/1577822/37936381-919ea5d4-3112-11e8-8113-197e61183539.png)

### Desired behavior

Action should only show up once in devTools

### Mention any other details that might be useful (optional)

This only happens when you subscribe to `store.dispatch()`. Removing the subscription causes the action to show up once.

This may be related to #170 removing `shareReplay()` from:
https://github.com/ngxs/store/blob/5a258c4f27e74d1cec1b25a6d5fa26123843f184/packages/store/src/store.ts#L98

**Comment by yarrgh** [comment]
@deebloo I guess we need `shareReplay()` at both locations to keep the plugins from receiving duplicates?

**Comment by xmlking** [comment]
i think devtools is printing twice 
Reproduce :
https://stackblitz.com/edit/angular-ngxs-rxjs6-test?file=app%2Fapp.component.ts

**Comment by deebloo** [comment]
I need to figure out how to write a test for devtools

**Comment by deebloo** [comment]
@yarrgh can you confirm adding the share replay operator both places fixes the issue. @amcdnl could you help with writing a test for devtools?

**Comment by amcdnl** [comment]
Reproduction w/ normal rx: https://stackblitz.com/edit/angular-u5h6jz

**Comment by deebloo** [comment]
@yarrgh you were right it need to be added in both places. once for the stream created by dispatching actions and the other from compose (where the plugins are integrated). There is a PR in now for a fix
