### ISSUE TITLE
Encrypt local storage data

### ISSUE THREAD

**Issue by rupeshshrestha722** [ngxs/store#1716]
How to encrypt local storage data using NgxsStoragePluginModule?

**Comment by arturovt** [comment]
Hey @rupeshshrestha722 

I don't think encryption should be part of the `NgxsStoragePlugin` functionality. You can provide your custom serialization/deserialize methods when importing the module:
```ts
@NgModule({
  imports: [
    NgxsStoragePluginModule.forRoot({
      deserialize: (state) => JSON.parse(atob(state)),
      serialize: (state) => btoa(JSON.stringify(state)),
    }),
  ],
})
export class AppModule {}
```

**Comment by rupeshshrestha722** [comment]
Thankyou @arturovt
