### ISSUE TITLE
📚[DOCS]: What is the purpose of the `type` property of an action?

### ISSUE THREAD

**Issue by scaljeri** [ngxs/store#1717]
### Description

Each action has a static property named `type`, but reading the docs I get the impression it is never used or described what its purpose is. I asked this question first on [SO](https://stackoverflow.com/questions/65658875/why-is-there-a-property-type-on-a-ngxs-action) and it was mentioned that it probably is only used internally to be able to connect the action with a state function. Although this might explain why I don't see it used anywhere, I think that some additional explanation should be in the docs why this property exists in the first place. Also, if this is true, and that property is used for identifying, why not use the action class as an identifier instead and remove that property?

**Comment by arturovt** [comment]
This is actually a classic Redux:

> An action is a plain JavaScript object that has a type field. You can think of an action as an event that describes something that happened in the application.

Not sure it's worth copy-pasting the already existing description.

More info here: https://redux.js.org/tutorials/fundamentals/part-2-concepts-data-flow
