### ISSUE TITLE
⚠️ [SECURITY]: content security policy error in fastPropGetter

### ISSUE THREAD

**Issue by bendehghan** [ngxs/store#1726]
### Description
I'm using ngxs in angular for a chrome extension. Chrome is moving to manifest v3 which limits using inline js injection with content security policy. The code here is giving us an exception:

`new Function('store', 'return ' + expr + ';');` can be used to inject malicious code using the **expr** value. The CSP detects that and justifiably fails. 

The code is here: **packages/store/src/internal/internals.ts**

<pre><code>
function fastPropGetter(paths: string[]): (x: any) => any {
  const segments = paths;
  let seg = 'store.' + segments[0];
  let i = 0;
  const l = segments.length;

  let expr = seg;
  while (++i < l) {
    expr = expr + ' && ' + (seg = seg + '.' + segments[i]);
  }

  const fn = new Function('store', 'return ' + expr + ';');

  return <(x: any) => any>fn;
}</code></pre>

## 🔬 Minimal Reproduction
The minimal setup would be complex. I can provide something if it's very necessary for understanding the issue. But I think the issue is pretty clear.

### Expected vs Actual Behavior**
I'm hoping there is a way to achieve the same code without needing inline eval. From the comments it seems like this was an optimization which I think should be reversed given the content security policy failure.

## 🔥 Exception or Error
The exception thrown by chrome is this:

`Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' ".`

## 🌍  Your Environment
Angular 11
        "@angular/cdk": "10.2.7",
        "@angular/common": "11.2.2",
        "@angular/compiler": "11.2.2",
        "@angular/core": "11.2.2",
        "@angular/forms": "11.2.2",
        "@angular/platform-browser": "11.2.2",
        "@angular/platform-browser-dynamic": "11.2.2",
        "@angular/router": "11.2.2",
        "@ngxs/logger-plugin": "3.7.1",
        "@ngxs/router-plugin": "3.7.1",
        "@ngxs/storage-plugin": "3.7.1",
        "@ngxs/store": "3.7.1",

### Browser info
Chrome manifest v3 is active in version 90. It becomes mandatory in 91 I think.

**Comment by bendehghan** [comment]
OK. I looks like there is already a property for that. I'm closing this for now unless setting that property doesn't work.

**Comment by rPetas** [comment]
> OK. I looks like there is already a property for that. I'm closing this for now unless setting that property doesn't work.

Can you expand on this?

I am having the same issue in my page.
How can i avoid this?

**Comment by maxim2mc** [comment]
The config option to solve this is 'strictContentSecurityPolicy'
