### ISSUE TITLE
📚[DOCS]: ngxs forms example error

### ISSUE THREAD

**Issue by nickpp** [ngxs/store#1733]
in this section
https://www.ngxs.io/plugins/form#updating-specific-form-properties

the example:
template: `
    <form [formGroup]="newNovelForm" ngxsForm="novels.newNovelForm" (ngSubmit)="onSubmit()">
      <input type="text" formControlName="novelName" />
      <div
        formArrayName="authors"
        *ngFor="let author of newNovelForm.get('authors').controls; index as index"
      >
        <div [formGroupName]="index">
          <input formControlName="name" />
        </div>
      </div>
      <button type="submit">Create</button>
    </form>
  `

doesnt work. 
Should be - 

template: `
    <form [formGroup]="newNovelForm" ngxsForm="novels.newNovelForm" (ngSubmit)="onSubmit()">
      <input type="text" formControlName="novelName" />
      <div
        formArrayName="authors"
        *ngFor="let author of newNovelForm.get('authors').value; index as index"
      >
        <div [formGroupName]="index">
          <input formControlName="name" />
        </div>
      </div>
      <button type="submit">Create</button>
    </form>
  `

("value" instead of "controls" in the 6 line)

**Comment by arturovt** [comment]
@nickpp would you want to make a PR to update docs?

**Comment by destus90** [comment]
@arturovt 
I have made a PR that should fix the issue.
