### ISSUE TITLE
NgxsReduxDevtoolsPluginModule: logOnly mode

### ISSUE THREAD

**Issue by vharadkou** [ngxs/store#174]
### Proposal

Implement logOnly mode for NgxsReduxDevtoolsPluginModule.
The same as StoreDevtoolsModule (ngrx/store-devtools)

**Comment by amcdnl** [comment]
Can you explain what log only is?

**Comment by tsawan** [comment]
logOnly -> boolean - connect to the Devtools Extension in log-only mode. Default is false which enables all extension features.
extension features are listed here. https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#features

**Comment by amcdnl** [comment]
I do not see `logOnly` as a option on that page.

**Comment by amcdnl** [comment]
Looks like NGRX has some custom stuff they set for this - https://github.com/ngrx/platform/blob/master/modules/store-devtools/src/instrument.ts#L83-L88

**Comment by yarrgh** [comment]
https://github.com/ngrx/platform/tree/master/docs/store-devtools

**Comment by amcdnl** [comment]
We don't use NGRX devtools, we use the redux devtools extension.

**Comment by amcdnl** [comment]
Closing and marking for future.
