### ISSUE TITLE
Observing odd behavior.

### ISSUE THREAD

**Issue by DannyBoyNg** [ngxs/store#175]
### Versions
ngxs 2.0.0.rc20
angular/cli 1.7.3
angular/core 5.2.9

### Observed behavior

When I turn off the Redux dev extension in Chrome, none of my actions get dispatched. Can someone else confirm if it is just me or is this happening to everyone. When I turn on the extension in Chrome, everything works fine again.

### Desired behavior

I would like my actions to get dispatched even when the Redux dev extension in Chrome is not enabled.

### Extra info

I deleted my node_modules folder, but it had no effect. I just installed Firefox and I observed the same issue in Firefox.
I also do not get any warnings or errors in my console.

**Comment by leon** [comment]
Please try the latest rc, there were some fixes regarding that. It may be fixed in a later rc.

**Comment by DannyBoyNg** [comment]
Thanks Leon, the issue seems to be resolved in 2.0.0.rc23
