### ISSUE TITLE
⚠️ [PERFORMANCE]: change detection with NgxsReduxDevtoolsPlugin

### ISSUE THREAD

**Issue by admir86** [ngxs/store#1758]
### Description

If the `NgxsReduxDevtoolsPluginModule` is imported the change detections runs endlessly

### Reproduction Steps**
- install the [Angular DevTools](https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh/related)
- import the module `NgxsReduxDevtoolsPluginModule.forRoot({ disabled: true })` in you app.module
- start your app and use the Angular DevTools profiler
- more than 2k change detection cycles within 5 seconds and my app contains only a title `h1`

### Expected vs Actual Behavior**

The plugin should not [connect to the devtools](https://github.com/ngxs/store/blob/66c2af79e7542e272eb037d470047d1d35383a7e/packages/devtools-plugin/src/devtools.plugin.ts#L28), if the plugin is disabled.
Maybe it should run outside angular zone?

## 📷Screenshot

![image](https://user-images.githubusercontent.com/36576424/120482873-d976c780-c3b1-11eb-9c7f-693ec6b3f2b1.png)

**Comment by markwhitfeld** [comment]
This has been fixed as part of the [v3.7.4](https://github.com/ngxs/store/releases/tag/v3.7.4) release.
Please test this out and let us know if this is not resolved.
