### ISSUE TITLE
[BUILD TOOLS]: Replace Bundlesize

### ISSUE THREAD

**Issue by markwhitfeld** [ngxs/store#1764]
### Description

Bundlesize has issues comparing PR bundle sizes to master.
Updating the bundlesize manually in PRs is a real pain, and it doesn't give a comparison to master (because of issue https://github.com/siddharthkp/bundlesize/issues/308). There must be something better!
We are probably also abusing the maxSize threshold prop by keeping it so close to the actual size and updating it all the time.

We need to investigate alternatives!

Some thoughts:
- It would be nice to commit the actual sizes to keep a history
- We really need to be able to compare a PR to master to see the change in size
- It should not interfere with PRs so much, the check and comparison is important, but fiddling values all the time is tedious
- It would be great if there was some easier way to automate the bundle size commits in PRs (potentially a commit from CI - although we would not want this to be recursive!)

We really need 2 different things...
- Report the size difference to master from a PR
- Commit a list of the current bundle sizes so that we can have a history
Maybe these could come from different tools

**Comment by markwhitfeld** [comment]
This might be an easy drop-in replacement:
https://bundlewatch.io/#/getting-started/using-bundlewatch
I think it is a fork of the other project

Bundlewatch has an action too
https://github.com/jackyef/bundlewatch-gh-action

We could use something like this to push updates back to the PR... as long as we have a way to save or retrieve the bundle sizes as a json file. I think that we could use one of the internal bundlesize apis to fetch the file details
https://github.com/marketplace/actions/git-auto-commit

**Comment by markwhitfeld** [comment]
Could be useful:
https://brennerm.github.io/posts/trigger-github-actions-on-pr-close.html

**Comment by markwhitfeld** [comment]
This looks like a great alternative that was released recently:
https://github.com/LironEr/bundlemon

**Comment by markwhitfeld** [comment]
@splincode This looks like a great alternative that was released recently:
https://github.com/LironEr/bundlemon

**Comment by splincode** [comment]
@markwhitfeld it's really interesting! what about add github action?
https://github.com/LironEr/bundlemon-github-actions

**Comment by markwhitfeld** [comment]
@splincode Yeah, it looks like great integration!

**Comment by arturovt** [comment]
@rfprod since you’re a pro at GitHub actions, would you want to take this one also?
