### ISSUE TITLE
🚀[FEATURE]: NGXS store has null root with no errors

### ISSUE THREAD

**Issue by jermylucas** [ngxs/store#1767]
### Relevant Package
This feature request is for @ngxs/store

### Description
In my app component, the NGXS store and selectors are set to a null state. The state was not being found despite no errors and proper spelling, and I when I used devtools such as Redux DevTools, I was able to see the root is null. 
![image](https://user-images.githubusercontent.com/47125917/123204700-da14f200-d475-11eb-84cd-412ecb52095c.png)

After going through my state files with a fine tooth comb, I found that inside my state I had:
```
State<MyStateModel>({
  name: 'statename',
  defaults: {
    ...
  },
  children: [...],
});
```

instead of

```
@State<MyStateModel>({
  name: 'statename',
  defaults: {
    ...
  },
  children: [...],
})
```
There was no error anywhere, only the null state selector let me know something was wrong.

It would be very valuable to warn about errors like this.

### Describe the solution you'd like
It would be helpful to possibly add a check to warn about this situation. I am not sure if it is possible to detect, but if not, at least others can find the issue.

**Comment by splincode** [comment]
Please, add `stackblitz` or `codesandbox` repro

**Comment by markwhitfeld** [comment]
@arturovt We could potentially have a dev time check (tree-shakable) that checks if the returned decorator function has been called.
This check could be scheduled to run on the next microtask. In typescript, if the decorator is used correctly (with the @ symbol) then the decorator function should have been called synchronously after the class declaration.
What do you think?

**Comment by arturovt** [comment]
Hey @markwhitfeld . Not sure if it's the functionality we'd want to have in our codebase. Honestly saying, I've never seen anyone checking if the decorator was called using the `@` symbol. I do think this is the developer's responsibility.
