### ISSUE TITLE
forRoot and forFeature canot be used together

### ISSUE THREAD

**Issue by AlgoTrader** [ngxs/store#177]
NgxsModule.forRoot and NgxsModule.forFeature cannot be used together in eagerly loaded modules.
NGRX is very different as it supports single forRoot and multiple forFeature without lazy loading.

NGRX style allows better code splitting, state can reside in multiple ng modules and every module can augment state itself, no need to create God-like app module that knows all the slices of state

**Comment by AlgoTrader** [comment]
My bad, it works as expected.

**Comment by davyvanlaere** [comment]
Im wondering, why did you initially think it didnt? Im having problems using ngxs in eagerly loaded modules ...
