### ISSUE TITLE
📚 [DISCUSSION]: rethink the design of the Storage Plugin

### ISSUE THREAD

**Issue by Carniatto** [ngxs/store#1771]
# Context

After a recent feature request (https://github.com/ngxs/store/pull/1760) to implement an async version of the storage plugin I had a look at what plugins have been developed by the community. It seems that there are quite a few plugins that have been developed that solve various different use cases, but for me, this does indicate that the core plugin is lacking in some areas.
While we generally prefer to maintain backward compatibility as much as possible, we are working on NGXS v4 and this offers the opportunity for a bit of a rethink around this plugin and to release a reworked version of this plugin.
We are looking for some members of the community that would like to be involved with this plugin and to head up the efforts to make a really awesome new version that handles a broader set of use cases.
If you would like to be involved, please join the #plugins_storage-plugin channel and indicate your intention with a :hand: emoji response to this message on the channel in Slack.

# Initial Requirements
* Connect to multiple storage engines
* Connect to Async/Observable storage engines
* Should work with Ionic? Capacitor?
* Should work with Electron?
* Feature Modules (lazy loading)
* Add extra default engines:
    * SessionStorage
    * IndexedDb (async)
    * WebSQL (async)
    * SQLite (async)
    * File
    * URL query params
    * LocalForage
    * HTTP/Rest API
* Debounce time option (similar to Electron Plugin)
* Provide Fallback storage options (similar to Ionic Plugin)
* Migration between versions of an App
* Interaction with default state

**Comment by markwhitfeld** [comment]
**Comments**
How do we configure the plugin?

Extensibility points (and their respective configuration):
- Engine?
- Converter?
- Migrator?
- Other?

Roles and responsibilities of each part
How do the extensibility points interact with Angular provided dependencies?

**Comment by markwhitfeld** [comment]
My braindump of some primary considerations:
- Support async
- Support multiple reads and writes (currently only one synchronous read at startup)
- Seems to be extensibility concepts of Engine, Converter, and Migrations
- Need to figure out how to handle default state and the load of state from storage in an asynchronous paradigm (potentially a StorageInitialised event to indicate when this is done)

**Comment by thmclellan** [comment]
Seems like a great outline. This brings up some interesting questions: 

- How to configure state-specific storage, especially for lazy-loaded stores (does this become part of the @State decorator or maybe the async storage plugin is passed to NgxsModule.forFeature()) 

- It may be useful to have an initialize storage function/hook as part of StorageEngine interface (example: HTTP REST API that requires authentication), and also some kind of state-level event to indicate when storage is initialized and state has been loaded.

**Comment by Carniatto** [comment]
Please let's continue our discussion [here](https://github.com/ngxs/store/discussions/1775).

**Comment by arturovt** [comment]
Closing since moved to a discussion.
