### ISSUE TITLE
Ngxs with Module Federation

### ISSUE THREAD

**Issue by yybarham** [ngxs/store#1776]
## I'm submitting a bug

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am trying to use ngxs module with module federation
when I use lazy laoding on module with ngxs its working fine
when working with federation them module need to work in 2 option
first as standalone which working fine
but when i use the same module inside the shell it doesnt work
the problem seem to with the injection of the store

## Expected behavior 
this module should work as standalone and inside the shell exaclly like lazy loading

## Minimal reproduction of the problem with instructions
I create a demo to demonstrate the problem
https://github.com/yybarham/ngxs-with-Federation 
which base on the following article 
https://www.angulararchitects.io/aktuelles/using-module-federation-with-monorepos-and-angular/
and then I add the ngxs module.

to simulate the problen , need to serve 2 projects shell (port 5000) & mfe1 (port 3000)
on the shell need to choose filght ( should work like flaight lazy) 

<pre><code>
Libs:
- @angular/core version: 12.0.0
- @ngxs/store version: ^3.7.2
 

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v12.22.1 
- Platform: Windows 

Others:

</code></pre>

**Comment by markwhitfeld** [comment]
Please could you try this with the `@dev` version from NPM and let us know? I think that @arturovt fixed this when he got rid of the StoreFactory singleton.

**Comment by yybarham** [comment]
I tried "^3.6.2-dev.master-eaa5d86", didn't help,

**Comment by arturovt** [comment]
> I tried "^3.6.2-dev.master-eaa5d86", didn't help,

The latest version is 3.7.2, the `@dev` version is step ahead.

**Comment by yybarham** [comment]
i didnt find @ngxs/store@3.7.2-dev, please advice

**Comment by splincode** [comment]
@arturovt @markwhitfeld very interesting

![image](https://user-images.githubusercontent.com/12021443/128593055-6bcbbb46-9748-4537-8193-ca030b7934f6.png)

**Comment by arturovt** [comment]
Whoops... @markwhitfeld any thoughts?

**Comment by splincode** [comment]
`my wife is in hospital with covid pneumonia` oh, I'm so sorry (((

`why the CI build is not publishing the dev tagged build` @arturovt do you have time for help?)

**Comment by arturovt** [comment]
Sorry Max, I’m also offline until Monday.

**Comment by splincode** [comment]
No problem, I will try check problem

**Comment by markwhitfeld** [comment]
@splincode I did a quick check as to what caused the dev publish to start failing, and reported my findings in this issue here:
https://github.com/ngxs/store/issues/1777

**Comment by markwhitfeld** [comment]
@yybarham the Dev build on NPM has been published.
Please run `npm i @ngxs/store@dev` in your project to install the dev version and test if this issue has been fixed.
PS. You will need to do a similar install for any ngxs plugins that you use.

**Comment by yybarham** [comment]
I use the following

"@ngxs/devtools-plugin": "^3.7.2-dev.master-337ab2d",
"@ngxs/logger-plugin": "^3.7.2-dev.master-337ab2d",
"@ngxs/store": "^3.7.2-dev.master-337ab2d",

didn't solve the problem

**Comment by splincode** [comment]
@yybarham 

https://github.com/yybarham/ngxs-with-Federation/blob/master/projects/mfe1/webpack.config.js#L37

add `"@ngxs/store": { singleton: true, strictVersion: true, requiredVersion: '3.7.2-dev.master-337ab2d' }` and `rxjs": { singleton: true, strictVersion: true, requiredVersion: '6.7.2' }`

**Comment by yybarham** [comment]
Error: State name 'todos' from TodoState already exists in TodoState

**Comment by matt-gold** [comment]
I think this is a duplicate [#1772](of https://github.com/ngxs/store/issues/1772),
There are some helpful comments there about the source of the issue. 

> Please could you try this with the `@dev` version from NPM and let us know? I think that @arturovt fixed this when he got rid of the StoreFactory singleton.

@arturovt do you think the change mentioned above could be relevant to the rxjs Observable class issue?

**Comment by splincode** [comment]
https://github.com/ngxs/store/issues/1772#issuecomment-901404176

**Comment by yybarham** [comment]
confirm duplication

**Comment by markwhitfeld** [comment]
@yybarham Just for reference, is this resolved with the information from the linked comment above?
> Thanks for looking into this!
I thought I had already tried sharing rxjs as a singleton, but apparently my configuration was wrong, because it is definitely working now!
> `"rxjs": { singleton: true, strictVersion: true, requiredVersion: '6.6.7' },`
>This needs to be configured in the shell as well as each micro-frontend

**Comment by yybarham** [comment]
yes

**Comment by markwhitfeld** [comment]
@yybarham I would love to get your thoughts/feedback/additions to the guide that @adrian-goe just added:
https://www.ngxs.io/v/master/recipes/module-federation
(it is only in the development docs at this time, will promote to main docs once I get your thoughts).

**Comment by yybarham** [comment]
Fine with me 
Thanks.
