### ISSUE TITLE
📚[DOCS]: Devtools Incorrect URL

### ISSUE THREAD

**Issue by bkr32** [ngxs/store#1784]
### Description
`Plugin with integration with the Redux Devtools extension.` redirects to a ad/spam site? instead of the devtools site
`http://extension.remotedev.io/`

### What's the affected URL?**
http://extension.remotedev.io/

### Reproduction Steps**
click the link

### Expected vs Actual Behavior**
should redirect to actual devtools site

## 📷Screenshot
Too explicit :/

**Comment by estrellajm** [comment]
Submitted a pull request to get this issue fixed.

https://github.com/ngxs/store/pull/1785
