### ISSUE TITLE
🚀[FEATURE]: Angular 13 support

### ISSUE THREAD

**Issue by ckorherr** [ngxs/store#1797]
### Relevant Package
@ngxs-labs/dispatch-decorator
@ngxs/devtools-plugin
@ngxs/router-plugin
@ngxs/store

### Description
Support for Angular 13

### Describe the problem you are trying to solve
Angular 13 has been released, an update is only possible if the dependency restrictions of ngxs are ignored.

### Describe the solution you'd like
Update dependency constraints and see if breaking changes are relevant.

### Describe alternatives you've considered
none

**Comment by splincode** [comment]
@markwhitfeld pinned

**Comment by splincode** [comment]
@kristofdc hello, try install beta version
https://www.npmjs.com/package/@ngxs/store/v/3.7.2-dev.master-9a7c431

**Comment by markwhitfeld** [comment]
I reopened this issue, and will close it manually once there is a new release supporting NG13 (the PR is already integrated).
A regression was picked up with the RC, which is being addressed. Expecting to release by the end of the week.

**Comment by internalsystemerror** [comment]
Testing out the latest dev version where I can for the last couple of days and no huge issues noticed so far (I've only tested very basic integrations though).

**Comment by splincode** [comment]
@internalsystemerror linked - https://github.com/ngxs/store/issues/1801

**Comment by vaceslav** [comment]
Is there any progress with this item?

**Comment by internalsystemerror** [comment]
@vaceslav As linked in the comment above yours, issue https://github.com/ngxs/store/issues/1801 is currently blocking it with https://github.com/ngxs/store/pull/1804 waiting approval/merge as a proposed fix.

**Comment by markwhitfeld** [comment]
We have just released a v3.7.3 point release that supports Angular v13! 🚀 
Closing this issue now.

PS. The blocking issues above will be reviewed and a major release will be done in the coming weeks.
