### ISSUE TITLE
Localstorage Defaults

### ISSUE THREAD

**Issue by amcdnl** [ngxs/store#180]
If I have a state with a localstorage and have it wired up. Then if I add a new property to my state, the new property isn't applied since it applies only the properties from localstorage.

**Comment by amcdnl** [comment]
I'm not sure how I'm gonna fix this at the moment since the local storage is so disconnected from the actual store. I'm gonna move this post 2.1

**Comment by amcdnl** [comment]
Fixed by migrations.

**Comment by DanielHabenicht** [comment]
@amcdnl Is there a better to add an already-defined property to the local storage? 
It feels cumbersome to write a migration for such a basic use case.
