### ISSUE TITLE
❓[SUPPORT]:  is @ngxs/form-plugin production ready ?

### ISSUE THREAD

**Issue by maxdhn** [ngxs/store#1800]
Hello,

We use ngxs in production and we are satisfied, but recently we start using ngxs/form-plugin, that's where the problems started...
We built a lot of states which dispatching inside reactive pipe, actions like `UpdateFormStatus`, `UpdateFormValue`, `UpdateFormError`, etc  and we realize that not everything is working as expected :

- https://github.com/ngxs/store/issues/1597
- https://github.com/ngxs/store/issues/1590
- https://github.com/ngxs/store/issues/1745
- https://github.com/ngxs/store/pull/1731

We don't spend time in this issue tracker because is not a part of @ngxs-labs (my bad). I think form-plugin documentation page should mention that plugin is not production ready to avoid wasting time for developer because, it's not dumby component that can be redevelop or switching easyly with another lib. As the doc says :

>  It acts as a single source of truth for your application's state, providing simple rules for predictable state mutations.

So using ngxs and all plugins (not part of @ngxs-labs) is used to build the core of your app, but it seems to be a bit complicated if we only trust the doc.

I don't see any fix for @ngxs/form-plugin in the next  release, that why I ask you if update the doc until it's working as expected, is a bad idea ?

(We also used @ngxs-labs/emitter and it work perfectly !)

Thanks for all of your works !

**Comment by arturovt** [comment]
Those issues have been triaged and fixed or closed as not reproducible. Closing this as well.
