### ISSUE TITLE
❓[SUPPORT]:  Storage plugin - state flushed on navigation end (feature or bug?)

### ISSUE THREAD

**Issue by TheCelavi** [ngxs/store#1802]
We have a state that is persisted into browser local storage using  https://github.com/ngxs/store/tree/master/packages/storage-plugin.

We noticed that state is flushed on navigation end - namely, we have, due to our business logic, state update on "setTimeout". However, browser local storage is being updated only when navigation ends (memory is fine, only flushing to browser local storage is executed on navigation). I was unable to locate why in source code of the plugin, am I missing something? Is this a feature or bug?

**Comment by arturovt** [comment]
The storage plugin has nothing to do with routing. The state is written to the storage whenever any action is dispatched and handled (w/o being errorred or canceled by another action). If you're observing `router.events` and dispatching actions during the router lifecycle, the state will be written into the storage between router hooks. But I don't know your implementation; I'm just saying how it works and that its implementation is unrelated to the router.

**Comment by TheCelavi** [comment]
Ok, understood now. We had state updated periodically, not as result of dispatched action. In order to have everything work, we just need to periodically dispatch action to update state (this was some TTL value that we are keeping alive, not a business logic state so we wanted to make it really simple). Thanks for the info, appreciated - everything is clear now.
