### ISSUE TITLE
🚀[FEATURE]: improve types of "ofAction*" functions

### ISSUE THREAD

**Issue by bbarry** [ngxs/store#1807]
### Relevant Package

 This feature request is for @ngxs/store

https://github.com/ngxs/store/blob/master/packages/store/src/operators/of-action.ts

### Description
 
The types of these methods can be significantly improved, currently

### Describe the problem you are trying to solve
 

```typescript
this.store.actions.pipe(
  ofActionSuccessful(MyAction1, MyAction2),
  tap((a/* : any */) => { });
```

type of parameter `a` here is `any`

### Describe the solution you'd like
 

```typescript
this.store.actions.pipe(
  ofActionSuccessful(MyAction1, MyAction2),
  tap((a/* : MyAction1 | MyAction2 */) => { });
```

the type of `a` can be determined by typescript...

This can be accomplished with:

```typescript
type TupleKeys<T extends any[]> = Exclude<keyof T, keyof []>;

type Constructed<T> = T extends { new (...args: any[]): infer U } ? U : T;

export function ofActionSuccessful<T extends ActionType[]>(
  ...allowedTypes: T
): OperatorFunction<ActionContext<Constructed<T[TupleKeys<T>]>>, Constructed<T[TupleKeys<T>]>> {
  // ...
}
```

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

```typescript
this.store.actions.pipe(
  ofActionSuccessful(MyAction1, MyAction2),
  // eslint-disable-next-line: @typescript-eslint/no-unsafe-argument
  tap((a: any) => { });
```

and 

```typescript
this.store.actions.pipe(
  ofActionSuccessful(MyAction1, MyAction2),
  tap((a: any) => { 
  if (a instanceof MyAction1) {
     ...
  }
  if (a instanceof MyAction2) {
    ...
  }
});
```

The vast majority of the time I only need one type here but still I have to work around the eslint rule.

Unfortunately I believe this is a breaking change...

**Comment by splincode** [comment]
Hello, you can send PR for help us

**Comment by markwhitfeld** [comment]
Great news! [v3.8.0](https://github.com/ngxs/store/releases/tag/v3.8.0) has been released and it includes a fix for this issue.
We are closing this issue, but please re-open it if the issue is not resolved.
Please leave a comment in the [v3.8.0 release discussion](https://github.com/ngxs/store/discussions/1985) if you come across any regressions with respect to your issue.
