### ISSUE TITLE
🐞[BUG]: setState returns global state instead of subState

### ISSUE THREAD

**Issue by davideappiano** [ngxs/store#1817]
I have 2 states: 
`
@State<Config>({
  name: "config",
  defaults: {
    browser: SupportedBrowsers.Chrome,
    defaultPassword: ''
  }
})
`

and 

`
@State<OrgsStateModel>({
  name: 'orgs',
  defaults: {
    version: 2,
    orgs: []
  }
})
`

When I trigger an action on the second state: 
`
@Action(OrgDelete)
  public org_delete(ctx: StateContext<OrgsStateModel>, { name }: OrgDelete): void {

    const state = ctx.setState(patch<OrgsStateModel>({
      orgs: removeItem<org_model>((org) => org.name === name)
    }));

    this.db.save(state);
  }
`

I would expect the value of `state` to be of type `OrgStateModel`. Instead it englobes both states.

**Comment by vander2675** [comment]
Stumbled upon this issue today. Is there any timeline already to when v4 will be released?

**Comment by arturovt** [comment]
Closing since this is related to v4 which is already mentioned in the main issue.
