### ISSUE TITLE
problem with synchronization between logger-plugin and devtools-plugin

### ISSUE THREAD

**Issue by mailok** [ngxs/store#183]
### Versions

```
* ngxs: 2.0.0-rc.24
* @ngxs/devtools-plugin: 2.0.0-rc.24
* @ngxs/storage-plugin: 2.0.0-rc.24
```
* Configure my plugins: 
```
 NgxsReduxDevtoolsPluginModule.forRoot({
      disabled: false
    }),
    NgxsStoragePluginModule.forRoot({
      key: '@@STATE',
      storage: StorageOption.LocalStorage,
      deserialize: JSON.parse,
      serialize: JSON.stringify
    })
```

* Dispacht a accion that belongs to de ``` NgxsModule.forRoot([AppState]) ```

```
@Action(SearchPeoples)
  serarchPeoples({getState, setState}: StateContext<AppStateModel>) {
    const state = getState();
    return this.http.get<Search>('https://randomuser.me/api/?results=5').pipe(
      tap(value => {
        setState({
          ...state,
          search: value.results
        });
      })
    );
  }
```

```
search() {
    this.store.dispatch(new SearchPeoples()).subscribe(value => {
      console.log('The action is completed.');
    });
  }
```

* Reload page

I expected that the same data would be kept in the local Storage and in Devtools.
A gif with the steps:

![bug2](https://user-images.githubusercontent.com/3769277/37979914-cdc4acfc-31b7-11e8-90cf-fbbadae2adde.gif)

**Comment by amcdnl** [comment]
I see, so the dev tools is not getting the initial data set from the localstorage.

**Comment by amcdnl** [comment]
I bet if you were to re-order how you imported the plugins, it might work. Its because the order of stuff is happening out of order. I'm not sure the best way to fix this....

**Comment by amcdnl** [comment]
@mailok - can you confirm the above?

**Comment by mailok** [comment]
@amcdnl Yes, I think it's exactly that

**Comment by amcdnl** [comment]
Ok, I'll add some docs for this.
