### ISSUE TITLE
❓[SUPPORT]:  Issue with selectors returning entire state rather than the state slice

### ISSUE THREAD

**Issue by jklotz** [ngxs/store#1833]
In src/internal/state-context-factory.ts it is noted:
```
// In doing this refactoring I noticed that there is a 'bug' where the
// application state is returned instead of this state slice.
// This has worked this way since the beginning see:
// https://github.com/ngxs/store/blame/324c667b4b7debd8eb979006c67ca0ae347d88cd/src/state-factory.ts
// This needs to be fixed, but is a 'breaking' change.
// I will do this fix in a subsequent PR and we can decide how to handle it.
```

I understand that this isn't technically a bug per say but noticed in some selectors I will get the entire application state followed by the same selector executing again against the state slice. The former makes it so the wrong value is returned from the selector and was wondering if there were plans to address the issue noted in source at some point in the future? Was also wondering why one would at times get the entire store vs. the state slice?

**Comment by YisusW** [comment]
In the Documentation i saw, you don't need to use `@Selector()` decorator when you return `createSelector` method.

please read this section:

[https://www.ngxs.io/v/master/concepts/select#dynamic-selectors](url)

**Comment by arturovt** [comment]
The example with `hasRole` is technically wrong itself.

The comment was left there long ago, which emphasizes the change might be coming in v4 (since it's a breaking). Any upcoming issues related to the selector's behavior must have a reproducible example for developers to look into the issue.
