### ISSUE TITLE
🐞[BUG]: patch() State operator not allows to set undefined value for property

### ISSUE THREAD

**Issue by Halynsky** [ngxs/store#1843]
### Affected Package
`"@ngxs/store": "3.7.3"`

### Description
`patch()` State operator not allows to set undefined value for property

## 🔬 Minimal Reproduction

<pre><code>
export interface StudyStateModel {
  loading: LoadingState;
  item: Study;
}

export class Study {
  id?: number;
  studyProtocol?: DocumentWrapper
}

  @DataAction()
  uploadStudyProtocol(file: File) {
    // code...
    this.ctx.setState(patch({loading: LoadingState.SAVING, item: patch({ studyProtocol: undefined })}))
    // code...
  }

</code></pre>

## 🔥 Exception or Error
<pre><code>
TS2345: Argument of type 'PatchOperator<{ loading: LoadingState; item: PatchOperator<{ studyProtocol: undefined; }>; }>' is not assignable to parameter of type 'StateValue<StudyStateModel>'.
</code></pre>

## Environment

<pre><code>
Libs:
- "@angular/core": "13.3.0"
- "@ngxs/store": "3.7.3"

Browser:
- [x] Chrome (desktop)  Version 101.0.4951.54 (Official Build) (64-bit)
 
For Tooling issues:
- Node version: v14.17.1
- Platform:  Windows 

</code></pre>

The goal is to set undefined the deep property of the object. Maybe there is some alternative way to do that? I just don't want to write a rude classic snipped like this:

</code></pre>

    const state = this.ctx.getState()
    this.ctx.setState({
      ...state,
      loading: LoadingState.SAVING,
      item: {
        ...state.item,
        studyProtocol: undefined
      }
    });

</code></pre>

**Comment by arturovt** [comment]
I'm closing the issue since this is an issue of `@ngxs-labs/data` package, but not `@ngxs/store` itself. I just tested patch operator within a state with a strict mode enabled and it works well.
