### ISSUE TITLE
🐞[BUG]: If a state has a handler for an action, any state that inherits from it can't handle that action

### ISSUE THREAD

**Issue by ConnorUllmann** [ngxs/store#1848]
### Affected Package
@ngxs/store

### Is this a regression?
No

### Description
If I have a state `ZooState` which has an action handler for the `Eat` action, then I use [state composition](https://www.ngxs.io/advanced/composition) to make `StLouisZooState` that inherits from `ZooState` and defines an additional action handler for the `Eat` action, that new handler will never be called.

## 🔬 Minimal Reproduction

[Stackblitz](https://stackblitz.com/edit/ngxs-simple-i5efqe?file=app/app.state.ts)

Click the "Click Me" button to trigger an action dispatch, then check the console to see what handlers were called.

In this example, when the `Eat` action is dispatched, `ZooState`'s 2 action handlers (`eat1` & `eat2`) are called, as expected, but `StLouisZooState.updateEatCount` is not. I would have expected all 3 action handlers to have been called.

If the two action handlers in `ZooState` are commented out and `Eat` is dispatched, `StLouisZooState.updateEatCount` is called correctly and `eatCount` is updated as expected.

## Environment
<pre><code>
Libs:
- @angular/core version: 11.2.14
- @ngxs/store version: 3.7.3

Browser:
- [X] Chrome (desktop) version 102.0.5005.62
- [X] Firefox version 78.7.0esr
- [X] Edge version 101.0.1210.53
</code></pre>

**Comment by arturovt** [comment]
This is not a bug because there's no reason to define different action handlers for the same action. The same action can be handled in other states, but it should be handled only once in the same state. There's also no final consistency since those 2 action handlers could've updated the state asynchronously, likely leading to a "read-write" conflict.
