### ISSUE TITLE
🐞[BUG]: TS2564: Property 'state$' has no initializer and is not definitely assigned in the constructor.

### ISSUE THREAD

**Issue by dinbtechit** [ngxs/store#1849]
### Affected Package
`Angular 12 and higher`  + `"typescript": "~4.3.5"` + `"@ngxs/store": "^3.7.3"`

### Is this a regression?
This used to work on Angular 11 and the previous version of typescript

### Description
```
TS2564: Property 'fanState$' has no initializer and is not definitely assigned in the constructor.
```

## 🔬 Minimal Reproduction

```
export class ContentComponent implements OnInit {

  . . .

  @Select(FanState.settings)
  fanState$: Observable<FanStateModel>;     <-------------- // Compile errors

   . . .
}

```

## 🔥 Exception or Error
<pre><code>
Build at: 2022-06-04T18:34:30.350Z - Hash: 94ff932c65cdc54ca64c - Time: 26761ms

Error: src/app/content/content.component.ts:25:3 - error TS2564: Property 'fanState$' has no initializer and is not definitely assigned in the constructor.

25   fanState$: Observable<FanStateModel>;
     ~~~~~~~~~


** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **

✖ Failed to compile.
<!-- ✍️-->

</code></pre>

## Environment
<pre><code>
Libs:
- "@angular/core": "~12.2.0"
- "@ngxs/store": "^3.7.3"
- "typescript": "~4.3.5"
</code></pre>

**Comment by arturovt** [comment]
https://www.ngxs.io/concepts/select#using-select-decorator-with-strictpropertyinitialization

**Comment by dinbtechit** [comment]
Work around: Current I am have to add this property in ` "strictPropertyInitialization": false` in  `tsconfig.json` to suppress the compilation error..

**tsconfig.json**
```ts
{
  "compileOnSave": false,
  "compilerOptions": {
   // . . . 
   "strictPropertyInitialization": false,
   // . . .  
}
```
