### ISSUE TITLE
Invalid documentation of the installation

### ISSUE THREAD

**Issue by mailok** [ngxs/store#188]
Fix in the documentation how to install, the core and the plugins.
It is this way: ``` npm i ngxs --S ```
and it should be: ``` npm i @ngxs/store --S ```
and the plugins:
``` npm i @ngxs/devtools-plugin --S ```
``` npm i @ngxs/logger-plugin --S ```
``` npm i @ngxs/storage-plugin --S```

**Comment by amcdnl** [comment]
Fixed that. I'm going to be redoing some of the docs for plugins so i'll address those then.
