### ISSUE TITLE
How to sync the state data saved in localstorage across all tabs using `Ngxs` state management?

### ISSUE THREAD

**Issue by mahmudabir** [ngxs/store#1894]
### Discussed in https://github.com/ngxs/store/discussions/1893

<div type='discussions-op-text'>

<sup>Originally posted by **mahmudabir** August  2, 2022</sup>
I am saving all data of the state after converting it to base64 format using `Ngxs` state management library. I can get all data across all tabs. But if I change a data in one tab it does not sync in the other tabs. To sync the data I have to refresh the tab. Is there any way to sync full state in all tabs if the state is changed in one tab?

Here is my code of `AppModule`:

```
@NgModule({
  declarations: [
    AppComponent,
    ReadComponent,
    CreateComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NgxsModule.forRoot([
      TutorialState
    ]),
    NgxsReduxDevtoolsPluginModule.forRoot(),
    NgxsLoggerPluginModule.forRoot(),
    NgxsStoragePluginModule.forRoot({
      storage: StorageOption.LocalStorage,
      serialize: (state) => btoa(JSON.stringify(state)),
      deserialize: (state) => JSON.parse(atob(state))
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```</div>

**Comment by arturovt** [comment]
We don’t support that type of functionality and it’s also not what our storage plugin is responsible for.

You can implement that functionality yourself. You basically need to listen to the storage message event. This also depends if you specify the `key` option or not. If you don’t specify the key option therefore the storage plugin saves the state under the `@@STATE` key. When you filter local storage events by this key you need to do merge `store.snapshot()` and the new state that was persisted to local storage in another tab (I’d use some deep merge from lodash, or any kind of smart merging, you can Google for such packages).

**Comment by mahmudabir** [comment]
How can I set all the state data into store on storage change where no keys were specified? Is there any functionality for that?

Can you please give an example code?
