### ISSUE TITLE
Shared States

### ISSUE THREAD

**Issue by amcdnl** [ngxs/store#190]
Lets say we have 2 stores, Items and Preferences. 

![img](https://content.screencast.com/users/amcdaniel22/folders/Snagit/media/9fc3bb5a-7ca6-4a72-831e-f139766de4c7/2018-03-28_15-00-28.png)

The preferences is a store that backed by local storage for settings in the app. The items are a list of things but they need to be sorted by the preferences sort. In concept, they are 2 different stores but in UI terms they are coupled.

A) Is this even possible? I suppose your could use a select but thats messy.
B) Is this a good idea?
C) Items now relies on preferences, so load order would need to be adjusted.

**Comment by xmlking** [comment]
it would be nice if we can have *readonly* access to whole store from any stores

**Comment by amcdnl** [comment]
@deebloo - i know you have some thoughts on this...

**Comment by deebloo** [comment]
I do. I don't think this a problem for the library to solve. I also don't know if it is feasible.

**Comment by amcdnl** [comment]
This is now much easier to do with `selectSnapshot`
