### ISSUE TITLE
🐞[BUG]: Actions Handler end up in infinite loop

### ISSUE THREAD

**Issue by yd021976** [ngxs/store#1919]
### Affected Package
@ngsx/core

### Is this a regression?

Think this is not a regression

### Description

Dispatching action in action handler (Actions Observable) end up in infinite loop

My need is to listen for a configurable bunch of actions (this OK) and update a state that track "api loading and/or app working" : I just want to avoid to dispatch action everywhere in my app code.

## 🔬 Minimal Reproduction

I've no git repo at this time, but for an exemple, the code below permit to reproduce the problem:
```
constructor(protected authService: AuthenticationService, protected storeActions: Actions) {
      
        this.subscriptionsSink.sink = this.storeActions
            .pipe(
                ofActionDispatched(AuthenticationActions.Login, AuthenticationActions.Logout))
            .subscribe((result) => {
                this.isPending$.next(true)
                this.setDispatchedAction(result.constructor.type)
            })
    }
    @Dispatch()
    private setDispatchedAction(actionName: string) {
        return new LoadingStateActions.setActionState(actionName, "dispatched")
    }
```

The call to `setDispatchedAction()` end up in infinite loop in the `subscribe` action handler. In addition, I noted that even if I restrict action handler to listen for only 2 "action type", the call to `setDispatchedAction`end up in my subscribe for action `setAction`

I haven't read in the doc that dispatching action inside "Action handler" can cause this kind of side effect.

## 🔥 Exception or Error
No error

## Environment

<pre><code>
Libs:
- @angular/core version: 14.0.1
- @ngxs/store version: 3.7.5

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX : Not tested
- [ ] Chrome (iOS) version XX : Not tested
- [X] Firefox version XX
- [X ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX : Not tested
- [ ] IE version XX : Not tested
- [ ] Edge version XX : Not tested
 
For Tooling issues:
- Node version: 18.9.0
- Platform:  Mac Monterey

**Comment by markwhitfeld** [comment]
Please could you provide a Stackblitz  reproduction of the issue? Only
include what is necessary to reproduce the issue.

**Comment by yd021976** [comment]
Hi,  i've done [a repo on stackbliz](https://angular-ivy-ytahsr.stackblitz.io). Unfortunably I can't reproduce the same behavior as describe in this issue.

In conclusion, I think there is something wrong in my original app.

**Comment by yd021976** [comment]
Hello, my bad, I was assigning same "type" name of 2 actions. So dispatching was handled twice in 2 different state in an forever loop.

**Comment by markwhitfeld** [comment]
Glad you came right. I suspected that there may have been an issue with
some actions sharing the same `type`, but it is hard to ascertain without a
repro.
It is actually very common that the problem is found while trying to create
a repro ;-)
