### ISSUE TITLE
Fire and wait pattern using Observables with HttpClient doesn't work when mfes' are being loaded using webpack

### ISSUE THREAD

**Issue by swarnadeepsaha** [ngxs/store#1921]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior  
> If you return an Observable NGXS will subscribe to the observable for you and bind the action's completion lifecycle event to the completion of the Observable.  
<sub>as mentioned in the ngxs [documentation](https://www.ngxs.io/advanced/actions-life-cycle#asynchronous-actions-continued-fire-and-forget-vs-fire-and-wait)<sub>  

When MFEs are loaded using webpack, It's not working when the handler is returned to the asynchronous work from the @Action method which involved backend HTTP call using angular's HTTP client.

[GIF - not working when mfe is loaded using webpack](https://github.com/swarnadeepsaha/webpack-mfe-angular-13/blob/master/resources/not%20working.gif)

Details of the issue [here](https://github.com/swarnadeepsaha/webpack-mfe-angular-13/blob/master/README.md#issues)

## Expected behavior  
> If you return an Observable NGXS will subscribe to the observable for you and bind the action's completion lifecycle event to the completion of the Observable.  
<sub>as mentioned in the ngxs [documentation](https://www.ngxs.io/advanced/actions-life-cycle#asynchronous-actions-continued-fire-and-forget-vs-fire-and-wait)<sub>  

Expecting this should work even when loaded/build using webpack, as it used to work earlier with
- standalone build
- partial build using ngx-build-plus  

[GIF - expected behavior when mfe is loaded using webpack](https://github.com/swarnadeepsaha/webpack-mfe-angular-13/blob/master/resources/working.gif) 

## Minimal reproduction of the problem with instructions  
[Github repo](https://github.com/swarnadeepsaha/webpack-mfe-angular-13)

* Run `npm start` from [package.json](https://github.com/swarnadeepsaha/webpack-mfe-angular-13/blob/master/package.json)
* Open [http://localhost:4200/application/host](http://localhost:4200/application/host). More [here](https://github.com/swarnadeepsaha/webpack-mfe-angular-13#run--build)
* You'll see `App1` counter is not working and there are no backend HTTP calls when you click the button.
* For `Host` and `App2` it's working fine.  

[GIF - not working when mfe is loaded using webpack](https://github.com/swarnadeepsaha/webpack-mfe-angular-13/blob/master/resources/not%20working.gif)

* If we run `App2` individually by running `npm start:app1` from [package.json](https://github.com/swarnadeepsaha/webpack-mfe-angular-13/blob/master/package.json), it works!  
[GIF - App1 works fine when loaded/run individually without using webpack](https://github.com/swarnadeepsaha/webpack-mfe-angular-13/blob/master/resources/app1-sa.gif)
* If shared libs marked in [webpack.config.json](https://github.com/swarnadeepsaha/webpack-mfe-angular-13/blob/master/app1/webpack.config.js) are removed, it works!
<pre><code>
shared: share({  
        // "@angular/core": { singleton: true, strictVersion: true, requiredVersion: 'auto' },  
        // "@angular/common": { singleton: true, strictVersion: true, requiredVersion: 'auto' },  
        // "@angular/common/http": { singleton: true, strictVersion: true, requiredVersion: 'auto' },  
        // "@angular/router": { singleton: true, strictVersion: true, requiredVersion: 'auto' },  
        ...sharedMappings.getDescriptors()  
      })  
</pre></code>   
* If we convert the http client Observable to Promise it works for both fire & wait and fire & forget pattern.
* if we don't return http client Observable handler(fire & forget) and subscribe the call inside the store, it works! [Reference](https://github.com/swarnadeepsaha/webpack-mfe-angular-13/blob/master/app1/src/store/state/count.state.ts)

## What is the motivation/use case for changing the behavior?  

[PNG - micro front end architecture using webpack module federation](https://github.com/swarnadeepsaha/webpack-mfe-angular-13/blob/master/resources/arch-daigram.png)

<pre><code>
| --  package.json  
| --  lerna.json  
| --  | -- host  
| --  | -- | -- package.json  
| --  | -- | -- src  
| --  | -- | -- | -- store
| --  | -- mfe1  
| --  | -- | -- package.json  
| --  | -- | -- src  
| --  | -- | -- | -- store  
| --  | -- mf2  
| --  | -- | -- package.json
| --  | -- mf3 
| --  | -- | -- package.json  
| --  | -- | -- src  
| --  | -- | -- | -- store
</pre></code>

In micro frontend architecture there could be mutiple UI project with it's own store instance, which can run, build & deploy individually and also can be loaded and used in the container shell or from any other ui applications. 

## Environment  

<pre><code>
Libs:
- @angular/core version: 13.3.11
- @ngxs/store version: 3.7.3

Browser:
- [x] Chrome (desktop) version 105.0.5195.102 (Official Build) (64-bit)
- [x] Chrome (iOS) version 105.0.5195.102 (Official Build) (arm64)
- [x] Firefox (desktop) version 104.0.2 (64-bit)
- [x] Firefox (iOS) version 104.0.1 (64-bit)
- [x] Safari (iOS) version 15.6.1 (17613.3.9.1.16)
- [x] Edge version 104.0.1293.70 (Official build) (arm64)
 
For Tooling issues:
- Node version: 14.15.4
- Platform:  Mac, Linux, Windows

Others:
- @angular/elements: 13.3.11
- @angular-architects/module-federation: 14.0.1
- @angular-architects/module-federation-tools: 14.3.10
- ngx-build-plus: 13.0.1
- rxjs: 7.5.0
- zone.js: 0.11.4
- typescript: 4.6.2

</code></pre>

**Comment by markwhitfeld** [comment]
None of the core team have worked on a MFE app, so this exploration is really interesting. Thank you! And thank you for the awesome effort that you went into for the repro!.

I won't have a moment to crack open the repro right now, but I do have a thought on where this could be going wrong...
In the action pipeline we do some checks for `... instanceof Observable`. See:
https://github.com/ngxs/store/blob/17a1bb8d4144b7c4d13a8e9eb7b1d3f83d3aa641/packages/store/src/internal/state-factory.ts#L254
and 
https://github.com/ngxs/store/blob/17a1bb8d4144b7c4d13a8e9eb7b1d3f83d3aa641/packages/store/src/internal/state-factory.ts#L268

I suspect that this would not work if there are different versions of `rxjs`. Have you tried adding `rxjs` to the shared libs?

Have you followed this guide?
https://www.ngxs.io/recipes/module-federation

If the guide is lacking anything then any contributions would be super welcome!

**Comment by swarnadeepsaha** [comment]
@markwhitfeld yes we have checked the guide that you have mentioned.
Our use case falls in the standalone category [https://www.ngxs.io/recipes/module-federation#stand-alone](https://www.ngxs.io/recipes/module-federation#stand-alone).

>  an entry module is needed, which must not be exported in the webpack.config.js

We have marked `ngxs` in individual ui's `app.module.ts` and haven't exported the same in the `webpack.config.js`.

It doesn't work for us.

Please let me know if there are any gaps in our understanding.

**Comment by swarnadeepsaha** [comment]
@markwhitfeld we'll try adding `rxjs` to the shared libs.

**Comment by swarnadeepsaha** [comment]
@markwhitfeld the for the suggestion.
it works with `"rxjs": { singleton: true, requiredVersion: 'auto' }`.
Here without `singleton: true` it is not working, so this configuration is important.

Can you please share the document repository link, so that I can update the guide.

But I do feel this need a correction. Other popular store library do work without this configuration in `webpack.config.js`

**Comment by markwhitfeld** [comment]
We will look into this issue.
Here is the page to which you would contribute to update the guide:
https://github.com/ngxs/store/blob/release/docs/recipes/module-federation.md
Thank you!

**Comment by markwhitfeld** [comment]
Yes, I think that we need to find a better way to detect the instance of an
observable, as I think that this is the blocker to seeing this work like
other libraries.
Here is the markdown file in the repository for that documentation page:
https://github.com/ngxs/store/blob/release/docs/recipes/module-federation.md
An update would be greatly appreciated. Thank you!

**Comment by swarnadeepsaha** [comment]
@markwhitfeld do we need to update [https://github.com/ngxs/store/blob/release/docs/recipes/module-federation.md](https://github.com/ngxs/store/blob/release/docs/recipes/module-federation.md) as the fix will be available in `v3.7.6`?

**Comment by arturovt** [comment]
This has been fixed as part of the [v3.7.6](https://github.com/ngxs/store/releases/tag/v3.7.6) release.
Please test this out and let us know if this is not resolved.

**Comment by swarnadeepsaha** [comment]
@arturovt issue is resolved. Really thankful for all the efforts.
👍 🏆  Team.
