### ISSUE TITLE
🐞[BUG]: Please make compatible to angular 15

### ISSUE THREAD

**Issue by larsilus** [ngxs/store#1937]
### Affected Package
npm WARN @ngxs/devtools-plugin@3.7.5 requires a peer of @angular/core@>=6.1.0 <15.0.0 but none is installed. You must install peer dependencies yourself.  
npm WARN @ngxs/logger-plugin@3.7.5 requires a peer of @angular/core@>=6.1.0 <15.0.0 but none is installed. You must install peer dependencies yourself.    
npm WARN @ngxs/router-plugin@3.7.5 requires a peer of @angular/core@>=6.1.0 <15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngxs/router-plugin@3.7.5 requires a peer of @angular/router@>=6.1.0 <15.0.0 but none is installed. You must install peer dependencies yourself.  
npm WARN @ngxs/store@3.7.5 requires a peer of @angular/core@>=6.1.0 <15.0.0 but none is installed. You must install peer dependencies yourself.

### Is this a regression?
No

### Description

Need to update and avoid warnings during npm install.

## 🔬 Minimal Reproduction

Upgrade your workspace to angular 15 in package.json

## 🔥 Exception or Error
<pre><code>
npm WARN @ngxs/devtools-plugin@3.7.5 requires a peer of @angular/core@>=6.1.0 <15.0.0 but none is installed. You must install peer dependencies yourself.  
npm WARN @ngxs/logger-plugin@3.7.5 requires a peer of @angular/core@>=6.1.0 <15.0.0 but none is installed. You must install peer dependencies yourself.    
npm WARN @ngxs/router-plugin@3.7.5 requires a peer of @angular/core@>=6.1.0 <15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngxs/router-plugin@3.7.5 requires a peer of @angular/router@>=6.1.0 <15.0.0 but none is installed. You must install peer dependencies yourself.  
npm WARN @ngxs/store@3.7.5 requires a peer of @angular/core@>=6.1.0 <15.0.0 but none is installed. You must install peer dependencies yourself.
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 15.0,0
- @ngxs/store version: 3.7.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: e.g. 16.13.1 
- Platform:  Windows 

Others:
</code></pre>

**Comment by markwhitfeld** [comment]
Planning to do the release later today.
I was without power yesterday and had a family member in hospital just before that.
Can you test out the `@dev` tagged release of NGXS on your codebase in the mean time for us?

**Comment by larsilus** [comment]
@markwhitfeld Yes, great works for me with. Project got fixed with
`npm install --save @ngxs/devtools-plugin@dev @ngxs/store@dev @ngxs/logger-plugin@dev @ngxs/router-plugin@dev`  
Sorry for pushing. Family is always prio 1!

**Comment by arturovt** [comment]
This has been fixed as part of the [v3.7.6](https://github.com/ngxs/store/releases/tag/v3.7.6) release.
Please test this out and let us know if this is not resolved.
