### ISSUE TITLE
2 Lazy Features only for the first loaded feature the State is initialized

### ISSUE THREAD

**Issue by svenjeppsson** [ngxs/store#194]
We have in our real project 3 feature only the first we start works correctly.
The problem is, that the state of the next called feature were not initlized.

I rebuild the problem at stackblitz.io

What do we wrong?

### Versions
```
* ngxs: 2.0.0-rc.24
* @angular/core: 5.2.8
```
### Repro steps

* open https://ngxs-localstorage-more-lazys.stackblitz.io/
* open click on "Link to LazyModul"
* click on "add one"
* click on "back"
* click on "Link to Lazy2Modul"
* click on "add one"

You can clear the application storage and begin with Lazy2Modul. 
Than the Problem come an LazyModul

### Observed behavior

```
the second called Lazy(x)State is not initialized

ng:///Lazy2Module/Lazy2Component.ngfactory.js:8 ERROR TypeError: Cannot read property 'count' of undefined
    at Lazy2State.count (lazy2.state.ts:36)
    at MapSubscriber.fn_1 (selector.ts:16)
    at MapSubscriber.memoized [as project] (memoize.ts:13)
    at MapSubscriber._next (map.ts:78)
    at MapSubscriber.Subscriber.next (Subscriber.ts:96)
    at StateStream.BehaviorSubject._subscribe (BehaviorSubject.ts:22)
    at StateStream.Observable._trySubscribe (Observable.ts:217)
    at StateStream.Subject._trySubscribe (Subject.ts:106)
    at StateStream.Observable.subscribe (Observable.ts:202)
    at MapOperator.call (map.ts:53)
```

### Desired behavior
both feature should be working and have separated counters

### Mention any other details that might be useful (optional)
Here is the code: https://stackblitz.com/edit/ngxs-localstorage-more-lazys?file=app%2Fapp.module.ts

**Comment by leon** [comment]
I was able to get it working after updating to the `2.0.0` and changing some stuff.

https://stackblitz.com/edit/ngxs-localstorage-more-lazys-nncku1

All Action class names must be unique within the app.
Since we use the name of the class as the unique identifier when dispatching and handling them.

**Comment by svenjeppsson** [comment]
Sorry for taking so long time!
You have deavtivated the storageplugin
-->   NgxsStoragePluginModule.forRoot()
When i do this in my real world project, it solves the problem, that i described in this issue. 
But we actually planed to use the storage plugin. We want to keep the state in the app.storage.

But i looks like, the problem is about handling stages in the storage with more than one lazy feature

**Comment by svenjeppsson** [comment]
I now tried the 3.0.0.beta 
https://stackblitz.com/edit/ngxs-localstorage-more-lazys-sae5sn?file=app%2Flazy2%2Flazy2.actions.ts
problem is still there

**Comment by vaags** [comment]
NgxsStoragePluginModule currently doesn't work with lazy loading it seems. Only root states are initialized. This is in version 3.0.0.beta

**Comment by svenjeppsson** [comment]
I found a workaround thats works for me.
I changed the example  for showing it: 
https://stackblitz.com/edit/ngxs-localstorage-more-lazys-sae5sn?file=app%2Flazy2%2Flazy2.state.ts

I just set a fallback-value when i call getState:
const state = sc.getState() || initialLazy2State;
or
const state = sc.getState() || initialLazyState;

This works for me. I did not find the right place to do that in the framework itself. So i could not deliver a fork with a pull request.

**Comment by killbox-code** [comment]
@svenjeppson thanks for posting this, works well for me as I had encountered the same issue.

**Comment by uberspeck** [comment]
I'm seeing more issues with the NgxsStoragePluginModule even when I use @svenjeppsson 's workaround. I [forked the stackblitz project above](https://stackblitz.com/edit/ngxs-localstorage-more-lazys-ygjkcd) and added a root app state. One of the lazy modules works, the other throws errors in the console...

`Error: undefined is not an object (evaluating 'local[k] = val[k]')`

**Comment by uberspeck** [comment]
I just updated everything in the [stackblitz demo](https://stackblitz.com/edit/ngxs-localstorage-more-lazys-ygjkcd) to latest and I'm still seeing the issue. 

![screen shot 2018-04-27 at 9 01 24 am](https://user-images.githubusercontent.com/857256/39369472-9f67d47e-49f9-11e8-9b45-b12b0104e612.png)

**Comment by splincode** [comment]
I tried 3.3.4
https://stackblitz.com/edit/ngxs-localstorage-more-lazys-bda4ox?file=app%2Fapp.module.ts

problem fixed
