### ISSUE TITLE
❓[SUPPORT]:  Is it OK to return a never ending observable in action handlers?

### ISSUE THREAD

**Issue by maa3x** [ngxs/store#1957]
Hi, I'm using Emitter from NGXS Labs which is awesome!
My base state looks like this:
```typescript
export interface StateModel<M extends Model> {
  loading: boolean;
  all: M[];
  active?: M;
  filtered: M[];
  filters: object;
  pagination?: Pagination;
  selected: M[];
  selectOptions: FormSelectOption[];
}

export function newState(name = 'BaseState') {
  class BaseState {
    displayname = name;

    static repository: Repository;

    setRepo(r: any) {
      BaseState.repository = r;
    }

    static all$() {
      return createSelector([this], (state: StateModel<Model>) => {
        return state.all;
      });
    }

    static filtered$() {
      return createSelector([this], (state: StateModel<Model>) => {
        return state.filtered;
      });
    }

    static selected$() {
      return createSelector([this], (state: StateModel<Model>) => {
        return state.selected;
      });
    }

    static active$() {
      return createSelector([this], (state: StateModel<Model>) => {
        return state.active;
      });
    }

    static filters$() {
      return createSelector([this], (state: StateModel<Model>) => {
        return state.filters;
      });
    }

    static selectOptions$() {
      return createSelector([this], (state: StateModel<Model>) => {
        return state.selectOptions;
      });
    }

    static loading$() {
      return createSelector([this], (state: StateModel<Model>) => {
        return state.loading;
      });
    }

    static pagination$() {
      return createSelector([this], (state: StateModel<Model>) => {
        return state.pagination;
      });
    }

    @Receiver({ type: `[${name}] find` })
    static find({ patchState }: StateContext<StateModel<Model>>, { payload }: EmitterAction<number>) {
      patchState({ loading: true });
      return BaseState.repository?.find(payload).pipe(tap((v) => patchState({ active: v, loading: false })));
    }

    @Receiver({ type: `[${name}] all` })
    static all({ patchState }: StateContext<StateModel<Model>>) {
      patchState({ loading: true });
      return BaseState.repository?.all().pipe(tap((v) => patchState({ all: v, loading: false })));
    }

    @Receiver({ type: `[${name}] filter` })
    static filter({ patchState }: StateContext<StateModel<Model>>, { payload }: EmitterAction<object>) {
      patchState({ loading: true, filters: payload });
      return BaseState.repository
        ?.filter(payload)
        .pipe(tap((v) => (console.log(v), patchState({ filtered: v.items, pagination: v.pagination, loading: false }))));
    }

    @Receiver({ type: `[${name}] select` })
    static select({ patchState }: StateContext<StateModel<Model>>, { payload }: EmitterAction<Model[]>) {
      patchState({ selected: payload });
    }

    @Receiver({ type: `[${name}] selectOptions` })
    static selectOptions({ patchState }: StateContext<StateModel<Model>>) {
      patchState({ loading: true });
      return BaseState.repository?.selectOptions().pipe(tap((v) => patchState({ selectOptions: v, loading: false })));
    }
  }

  return BaseState;
}
```

In the `filter` method I'm returning `BaseState.repository?.filter(payload)` which itself returns a [Dexie liveQuery](https://dexie.org/docs/liveQuery()), it will emit new values when data changes.

Currently it works fine - both State and UI gets updated.

But since state changes is not logged (both in ReduxDevTools and console using NGXS Logger) I'm wondering is this approach OK or not? does it conflict with something or cause any problems? will NGXS automatically unsubscribe from previous Observable in action handler (the liveQuery)?

And also if there is a better approach to implementing BaseState and inheriting common CRUD functionality than the one I ended up with, I will be more than happy to hear that.
Right now, my states look like this:
```typescript
@Injectable()
@State<AcademicYearsStateModel>({ name: 'AcademicYears', defaults: defaults() })
export class AcademicYearsState extends newState('AcademicYears') {
  constructor(repo: AcademicYearsRepository) {
    super();
    super.setRepo(repo);
  }
}
```

My last question is do I need to add `{providedIn: 'root'}` to the state's `Injectable` decorator or not?

Thanks.

**Comment by arturovt** [comment]
Regarding the emitter package... Unfortunately, I don't have enough time to maintain this package. But the Receiver acts as an Action listener.

The Action is a "reaction" to something being dispatched explicitly from some code place. Actions should not listen to non-complete streams. Suppose you dispatch this action again and you will subscribe to this stream the second time.

In your example I would do the following (just a quick code):
```ts
export class FilterItems {
  static type = '[...] Filter Items';
  constructor(public payload: Model[]) {}
}

export class MyState {
  @Action(FilterItems, { cancelUncompleted: true })
  filterItems(ctx, action) {
    ctx.patchState(...)
    return this.repository?.filter(action.payload).pipe(
      take(1),
      tap(....)
    )
  }
  }
}
```

Note the `cancelUncompleted`, this will cancel the `filter` and will trigger another `filter`. This guarantees the state consistency.

P.S. I'd move this question to our Slack channel, you'd get more support there.

**Comment by maa3x** [comment]
Thank you for the explanations.
I've changed my implementation a bit and now use "Action classes" instead of emit and receive.

> Note the cancelUncompleted, this will cancel the filter and will trigger another filter. This guarantees the state consistency. And it's better to re-dispatch FilterItems every time you need to re-filter the data.
> 
> Well, but actually I'm not sure if you need actions to sync the state with your "liveQuery". You may just listen to the liveQuery from outside.

What if I maintain the subscription for `liveQuery` in the repository itself and dispatch "Filter" action with updated items from there? It works but is this a good practice? What about creating Facade class that connects this two?

Also I've joined the NGXS channel on Slack, Thanks!

**Comment by arturovt** [comment]
As I said this ain't a good practice since the state should be updated as a reaction to actions being dispatched. In your example there're no actions being dispatched since the state is updated implicitly when the stream emits.

The good practice is to maintain a subscription outside of the action. The single action should not be responsible for the `liveQuery` implementation and its handling.
