### ISSUE TITLE
🐞[BUG]: Possible regression of `strictContentSecurityPolicy` in @ngxs/store

### ISSUE THREAD

**Issue by aaronfay** [ngxs/store#1964]
### Affected Package
@ngxs/store@3.7.6

### Is this a regression?
Yes, this appears to be a regression of the [flag `strictContentSecurityPolicy`](https://www.ngxs.io/advanced/options)

### Description
When adding this configuration:

```
        compatibility: {
          strictContentSecurityPolicy: true,
        },
```

... to the `ngxs` module I am still seeing unsafe JavaScript code in the distribution bundle:

```
$ grep 'new Func' ./dist/**/*.js
./dist/main.5fbc7197413830d0.js:  const fn = new Function('store', 'return ' + expr + ';');
./dist/main.5fbc7197413830d0.js:    return new Function(...args);
./dist/main.5fbc7197413830d0.js:    return new Function(...args);
./dist/main.5fbc7197413830d0.js:  // To completely mimic the behavior of calling "new Function", two more
./dist/main.5fbc7197413830d0.js:  // return new Function(...args.map(a => trustedScriptFromString(a)));
```

## 🔬 Minimal Reproduction
I have a minimal reproduction available here, with instructions in the README: https://github.com/aaronfay/ngxs-sample-app

Steps to reproduce:

```
git clone https://github.com/aaronfay/ngxs-sample-app
npm install
npm run build
grep 'new Func' ./dist/**/*.js
```

There should be no instances of `new Function()` in the `/dist/*.js` output files.

## 🔥 Exception or Error
N/A

## Environment

<pre><code>
Libs:
    "@angular/common": "^15.0.0-rc.1",
    "@angular/compiler": "^15.0.0-rc.1",
    "@angular/core": "^15.0.0-rc.1",
    "@angular/forms": "^15.0.0-rc.1",
    "@angular/platform-browser": "^15.0.0-rc.1",
    "@angular/platform-browser-dynamic": "^15.0.0-rc.1",
    "@angular/router": "^15.0.0-rc.1",
    "@ngxs/store": "^3.7.6",

Browser:
N/A
 
For Tooling issues:
- Node version: v16.13.0
- Platform:  MacOS 11.0.1

Others:
N/A
</code></pre>

**Comment by arturovt** [comment]
That's not a regression because we have had this code for years. The `new Function` is not called when the `strictContentSecurityPolicy` is enabled. What you're talking about is code tree-shaking, which isn't possible since `strictContentSecurityPolicy` is not provided during the build as a compile time constant (e.g. through the `DefinePlugin`), but as a runtime variable.
