### ISSUE TITLE
❓[SUPPORT]:  rxjs distinctUntilChanged not working as expected with ngxs

### ISSUE THREAD

**Issue by daniel-seitz** [ngxs/store#1969]
Dear NGXS Team, I'm writing because there is a **bug** between your solution and RXJS.

They say it's not their issue, hence I wonder if you should make a change.

Please see details in this ticket here:
[https://github.com/ReactiveX/rxjs/issues/7180](https://github.com/ReactiveX/rxjs/issues/7180)

Happy to assist, let me know if you have questions.
Daniel

What we're having
```
Template:
    <ng-container *ngIf="user$|async"></ng-container>

Component:
   @Select(UserState) userState$!: Observable<UserStateModel>;
   user$ = this.userState$.pipe(
       distinctUntilChanged((prev, curr) => {
          const isUserDifferent = prev.userId !== curr.userId
          const shouldContinue = isUserDifferent;
          return !shouldContinue; // negation due to: false continues
       }),
       tap(user => console.log('hooray', user)),
   );

Store
    export interface UserStateModel {
        userId: string,
    }

    @State<UserStateModel>({
       name: 'user',
       defaults: {
            userId: ''
       }
    }
```

And later somewhere

`patchState({ userId: '1' })`

later

`patchState({ userId: '2' })`

And the problem is that only the first user reaches the tap - according to rxjs: due to the state is being passed as a reference.

**Comment by mchlroy** [comment]
That's concerning, I was under the impression that patchState would create a new object to respect immutability.

It literally says it in the [docs](https://www.ngxs.io/advanced/operators#why)

> The NGXS patchState method is used to do [immutable object](https://en.wikipedia.org/wiki/Immutable_object) updates to the container state slice without the typical long-handed syntax. This is very neat and convenient because you do not have to use the getState and setState as well as the Object.assign(...) or the spread operator to update the state.


Does it fix the problem if you do this instead?

```ts
setState(patch({ userId: '2' }));
```

**Comment by arturovt** [comment]
Closing until a minimal reproducible example is provided.
