### ISSUE TITLE
NGXS ready for production?

### ISSUE THREAD

**Issue by nukuuk** [ngxs/store#199]
I very much like this approach to state management in Angular.  Is there a consensus that this resource is ready for use in production?

**Comment by waitingsong** [comment]
me too

**Comment by pmd500** [comment]
And me :)

**Comment by kylecordes** [comment]
I think the initial author @amcdnl has pointed out that this is emerged from projects he is working on.  That probably means he is using code to close to this in production, or will be.

**Comment by dminine** [comment]
I think this can be used in production and I am replacing my current products with ngxs from ngrx. This has solved a lot of things that I felt inconvenient while writing ngrx. But I want a reliable test result can be about it.

**Comment by amcdnl** [comment]
Yup, I'm using it in production on multiple projects. In our effort of 2.0, we wanted to make sure we had good test coverage and had a stable release. There is no major issues to my knowledge at this point and I've been using it in a complicated application and not had any issues. There are no breaking changes planned at the moment and in the next releases we just plan to make it even better w/ more plugins and more options.

**Comment by amcdnl** [comment]
I just added a note of this in the FAQ.

**Comment by nukuuk** [comment]
@amcdnl thank you sir for a great angular resource [donning my hat to you]
