### ISSUE TITLE
🐞[BUG]: Breaking change for 3.8.0 when using NgxsModule.forRoot()

### ISSUE THREAD

**Issue by martendV** [ngxs/store#1991]
### Affected Package
The issue is caused by the version 3.8.0 of ngxs/store

### Is this a regression?

Yes with the previous version my library was working fine.

### Description

When a library, that is using the 3.8.0 version of ngxs/store, is imported into an angular project, that is using the 3.7.6
version of ngxs/store, the project won't compile due to a typescript error, that is displayed below in the section `Exception or Error`.

In my opinion, if the behavior gets verified, 3.8.0 should be marked to have breaking changes.

## 🔬 Minimal Reproduction

Can not provide the repo, since it is private and i am not the code owner.

Reproduction:
1. Install a package that is using `@ngxs/store 3.8.0` into your angular project, that is using `@ngxs/store 3.7.6` (Both should define at least one ngxs state and define it via `NgxsModule.forRoot()`)
2. Build your angular project
3. You should get the ts compilation error below

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/19616465/229860019-0037d64a-8031-49a4-801a-2e8b9611988d.png)

## Environment

<pre><code>
Libs:

Main Project:
- @angular/core version: 15.1.5
- @ngxs/store version: 3.7.6

Imported Library:
- @angular/core version: 15.1.5
- @ngxs/store version: 3.8.0

For Tooling issues:
- Node version: 18.15.0
- Platform:  Mac - MacOS Ventura 13.2.1

</code></pre>

**Comment by arturovt** [comment]
We don't have any similar issues reported from other users. I also have multiple apps using different Angular versions and I was able to upgrade to 3.8 w/o issues. I can't divine on the provided screenshot, unfortunately.

**Comment by martendV** [comment]
> We don't have any similar issues reported from other users. I also have multiple apps using different Angular versions and I was able to upgrade to 3.8 w/o issues. I can't divine on the provided screenshot, unfortunately.

The Angular versions are not the problem. Due to dependencies of other libraries, that are also part of the whole project, the main application has to keep 3.7.6 for now. When the library version of ngxs/store is at 3.8.0 and is imported as a module of the main application the error occurs.
The solution right now is to pin the version of ngxs/store of the library to `"@ngxs/store": "3.7.6"`

**Comment by arturovt** [comment]
As I said I can’t divine what’s happening on your side w/o reproducible example provided.

**Comment by markwhitfeld** [comment]
@martendV Would it be possible to provide a reproduction in StackBlitz?

**Comment by arturovt** [comment]
Closing as not reproducible. Feel free to re-open once the reproduction is provided.
