### ISSUE TITLE
❓[SUPPORT]: Confirmation needed:  ctx.patchState() is scheduled operations

### ISSUE THREAD

**Issue by TheCelavi** [ngxs/store#2000]
It seams that ctx.patchState(): T is function which only schedules state patching and patching is executed on next micro task.

It is easy to confirm this behaviour, if 'foo' value is 'buz', then this will happen:

```
ctx.patchState({
     foo: 'bar'
});

console.log(ctx.getState().foo); // outputs 'buz'.
```

However, this will give expected result:

```
ctx.patchState({
     foo: 'bar'
});

await Promise.resolve();

console.log(ctx.getState().foo); // outputs 'buz'.
```

Current implementation absolutely makes sense, it is probably a technique for optimisation, changes are scheduled and it will be updated on next tick. However, it is not documented.

If someone could confirm this behaviour I could send a PR for documentation to add this info, it is quite useful to know and when it is not known it produces some ugly glitches and bugs.

**Comment by markwhitfeld** [comment]
@TheCelavi This is actually a bug in the v3.8.0 release.
It is fixed by PR #1995 . We will be releasing v3.8.1 soon with this fix.

**Comment by TheCelavi** [comment]
@markwhitfeld well, that is odd, in whole codebase that we have, 3 use cases are affected with this :D. Thanks, I will close this issue, there is PR and it is documented as a bug.

**Comment by felixvanleeuwen** [comment]
We also have a few use cases for this.
Getting the dev version would be a solution, but unfortunately I am limited by a npm-cache maintained by a different department.
@markwhitfeld Any ETA on the bugfix release?

**Comment by markwhitfeld** [comment]
[v3.8.1](https://github.com/ngxs/store/discussions/2019) was released yesterday!
