### ISSUE TITLE
📚[DOCS]: NGXS still at 3.7.6 on yarn.

### ISSUE THREAD

**Issue by ugran** [ngxs/store#2001]
Hello, NGXS is still at 3.7.6 version on yarn. Is it possible to update it?

**Comment by arturovt** [comment]
What do you mean on yarn?

**Comment by ugran** [comment]
v3.7.6 in yarn https://yarnpkg.com/package/@ngxs/store

v3.8 in npm
https://www.npmjs.com/package/@ngxs/store

**Comment by arturovt** [comment]
I don't know how yarnpng works since it seems like they're scheduly syncing their site with npm. The Angular package is also on 15 latest version: https://yarnpkg.com/package/@angular/core.
