### ISSUE TITLE
🚀[FEATURE]: Angular 16

### ISSUE THREAD

**Issue by raducostea** [ngxs/store#2005]
https://github.com/ngxs/store/blob/master/packages/store/package.json#L8

```
  "peerDependencies": {
    "@angular/core": ">=6.1.0 <16.0.0",
    "rxjs": ">=6.5.5"
  }
```

Any plans to support Angular 16? I tried to force upgrade but i get all kind of errors, probably to due lerna keeping both angular 15 and angular 16 to support this dependency. 

Angular 16 have some really nice feature that will be nice to use but i am currently blocked ny NGXS

**Comment by markwhitfeld** [comment]
[v3.8.1](https://github.com/ngxs/store/discussions/2019) was released yesterday with Angular 16 support!
