### ISSUE TITLE
Error: Store has already been added: [state name] - in a feature module

### ISSUE THREAD

**Issue by alvipeo** [ngxs/store#202]
I use
```
NgxsModule.forFeature([MyState])
```
in my feature module (lazy loading, with `preloadingStrategy: PreloadAllModules`), just as in the docs. And it works. But I tried to throttle performance (6x) and network connection speed in Chrome (Slow 3G) and I got the following error:

>> Error: Store has already been added: moderators
>> at _loop_1 (ngxs-store.js:187)
    at StateFactory.add (ngxs-store.js:211)
    at StateFactory.addAndReturnDefaults (ngxs-store.js:226)
    at NgxsFeatureModule.initStates (ngxs-store.js:592)
    at new NgxsFeatureModule (ngxs-store.js:587)
    at _createClass (core.js:10901)
    at _createProviderInstance$1 (core.js:10865)
    at initNgModule (core.js:10818)

What's even more, it doesn't happen every time. So no code, nothing changed, and sometimes it happens, sometimes not.

**Comment by amcdnl** [comment]
Can you make a demo on stackblitz?

**Comment by amcdnl** [comment]
@alvipeo - bump

**Comment by alvipeo** [comment]
I remember, I will do it. Sorry, very busy at the moment... But I'll do it.

**Comment by wakawaka54** [comment]
I have the same problem. It looks like it may have something to do with dispatching router.navigate on a Root Store.

Here's a stackblitz project: https://stackblitz.com/edit/angular-ngxs-lazy
And here's the hosted app: https://angular-ngxs-lazy.stackblitz.io/

You can click on "Redirect Me" and check the console for the error log.

**Comment by kamalkech** [comment]
@wakawaka54 your example not working if you try to add another module feature with his state and you will be get : Store has already been added 'name_state'

**Comment by amcdnl** [comment]
Is this still an issue in 3.0?

**Comment by alvipeo** [comment]
I haven't migrated yet. But let me do it now.

**Comment by billdwhite** [comment]
Same problem here and it's pretty much a show stopper for me].  
I've created a StackBlitz to show the problem in detail:

https://stackblitz.com/edit/ngxs-store-bug

Basically, if you load a feature module that registers a state with NGXS.forFeature(), you can never load that feature module into any other outlet, even if you have completely navigated away from the original feature module.  You will always get the error.

**Comment by billdwhite** [comment]
The state-factory is throwing the error on line 87.   I'm no expert on this, but off the top of my head, I would say that one of these should be happening:

-the feature state should be getting un-registered when the module unloads so it can be reloaded
or
-the feature state registration should be ignored if it already exists (rather than throwing an error)
or
-the feature state should be made unique if the module gets loaded into multiple outlets

**Comment by billdwhite** [comment]
As a test, I just commented out the if(has) check at state-factory:87 in my node-modules/ngxs folder and my application works fine;   I am assuming that the check is necessary so I'm hesitant to just submit a pull request that removes it;  thoughts?

**Comment by billdwhite** [comment]
bump

**Comment by splincode** [comment]
Worked with 3.3.4
https://stackblitz.com/edit/angular-ngxs-lazy-uu9xzj?file=app%2Ffeatures%2Faccount%2Fregister%2Fregister.component.ts
