### ISSUE TITLE
🚀[FEATURE]: [router-plugin] - export symbols for better extendability

### ISSUE THREAD

**Issue by jbjhjm** [ngxs/store#2030]
### Relevant Package

 This feature request is for @ngxs/router-plugin

### Description
 A clear and concise description of the problem or missing capability...
NgxsRouterPluginModule and RouterState are using private InjectionTokens.
Exporting these would help when aiming to extend RouterState with additional functionality.

### Describe the problem you are trying to solve
 Please describe the problem. If possible please substantiate it with the use cases you want to address.

I was planning to extend RouterState with custom actions and selectors.
But the way the plugin is currently set up does not allow me to do so:

* RouterState uses hard-coded injection `injector.get(NGXS_ROUTER_PLUGIN_OPTIONS, null)`
* NGXS_ROUTER_PLUGIN_OPTIONS is a private token
* only way to provide it is to use the original NgxsRouterPluginModule.
* => no way to set up an extended custom RouterState

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Exporting the contents of symbols.ts to public API will help users aiming to extend the state.

**Comment by arturovt** [comment]
> NGXS_ROUTER_PLUGIN_OPTIONS is a private token
only way to provide it is to use the original NgxsRouterPluginModule.

Why would you need another to way to provide the plugin options token since there's already the way to do this?

**Comment by jbjhjm** [comment]
> 

I guess I kinda skipped an explanation for that, sorry. Here we go:

- NGXS_ROUTER_PLUGIN_OPTIONS is un-exported, so
- NGXS_ROUTER_PLUGIN_OPTIONS can only be defined through NgxsRouterPluginModule.forRoot.
- Importing NgxsRouterPluginModule however means that RouterState will be created
- which is not what I want, because I aim to extend RouterState with custom functionality.

Approached from the other side:

- I extend RouterState with custom functionality.
- Parent constructor uses injector.get(NGXS_ROUTER_PLUGIN_OPTIONS, null).
- I cannot provide the needed NGXS_ROUTER_PLUGIN_OPTIONS manually.
- Only way to provide it is to use the NgxsRouterPluginModule, but it is bound to base RouterState.

**Comment by arturovt** [comment]
We have moved injection tokens into `@ngxs/router-plugin/internals`. See this code: https://github.com/ngxs/store/commit/22b962e17e616b5706343bda2064a2a55a0487d6#diff-2795a983a7332b924373abb6f2711937c8801c5a74f791e403bb76f0ce03b0feR3-R8 

They're exported with "barred O" symbol because they're meant to be private, but still can be used by consumers in those cases, as yours. This will be available in 3.8.2, but you can install the dev version `3.8.1-dev.master-22b962e`.

**Comment by jbjhjm** [comment]
Thanks Arturo! Appreciated! 😀
