### ISSUE TITLE
Select Raw Value

### ISSUE THREAD

**Issue by amcdnl** [ngxs/store#204]
In some cases, you need the ability to select a raw value from the store. 

In the use case below, we have a store that is backed by localstorage that contains the jwt token, we need the ability to get the RAW value from the token to pass in the request object.

```
@Injectable()
export class JWTInterceptor implements HttpInterceptor {

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
   // NEED TO GET RAW TOKEN VALUE FROM STORE
    req = req.clone({
      setHeaders: {
        Authorization: `Bearer ${token}`
      }
    });

    return next.handle(req);
  }

}
```

For this API, I'm thinking about having it only on the the store instance, so it might look like:

```
store.selectValue(v => v.token);
```

Open to suggestions for API though.

**Comment by NetanelBasal** [comment]
In this case, there is no benefit for passing a callback. I would just stick with something like:

`store.getValue(AuthState).user.token` where `store.getValue(AuthState)` should return the correct type for auto-completion. (`AuthState` in this case)

Also, mark the return value as `ReadOnly`.

**Comment by leon** [comment]
a ´HttpInterceptor` can be async :)

```TS
@Injectable()
export class JWTInterceptor implements HttpInterceptor {

  constructor(private store: Store) {}

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    this.store.select(AuthState.getToken).pipe(
      map(token => {
      	if (token) {
          // clone and modify the request
          request = request.clone({
            setHeaders: {
              Authorization: `Bearer ${token}`
            }
          });
        }
        return next.handle(request);
      })
    );
  }

}
```
But I can see the point of having a method to get the state.

Maybe we should follow the namingconvention of the router and name it `.stateSnapshot()` or `.snapshot()` to signify that it's the value at this exact moment

Input?

**Comment by NetanelBasal** [comment]
The observable approach is verbose. snapshot sounds like a good candidate.

**Comment by deebloo** [comment]
@amcdnl this is done  right?

**Comment by amcdnl** [comment]
Yup :)
