### ISSUE TITLE
📚[DOCS]: ZooState imported before it exists

### ISSUE THREAD

**Issue by peterhippocarter** [ngxs/store#2041]
### Description

On the installation page of the documentation, immediately after the `npm install`/`yarn add` step, the user is instructed to import the NgxsModule like so:

```
import { NgModule } from '@angular/core';
import { NgxsModule } from '@ngxs/store';

import { ZooState } from './examples/zoo.state';

@NgModule({
  imports: [
    NgxsModule.forRoot([ZooState], {
      developmentMode: !environment.production
    })
  ]
})
export class AppModule {}
```

Since the user has not been given details on how to create ZooState yet they will be unable to import NgxsModule in the manner specified.

## 🔬 Minimal Reproduction

Read the docs :stuck_out_tongue: :wink:.

## Expected vs Actual Behavior

It would be nice to be able to follow the installation instructions from start to finish and not have to skip ahead and make inferences to get it to work.

In a sense the coach :bus: has been put before the horses :carousel_horse:. Or, perhaps the giraffe :giraffe: before the  zoo :circus_tent:.

**Comment by arturovt** [comment]
This has been updated.
