### ISSUE TITLE
🚀[FEATURE]: Support latest angular and typescript versions (decorators arent working)

### ISSUE THREAD

**Issue by luismmdev** [ngxs/store#2047]
### Relevant Package
This feature request is for `@ngxs/store`

### Description
Support latest `angular` and `typescript` versions.

### Describe the problem you are trying to solve
We were using `angular15` and decided to use `@ngxs/store` as our redux library. After migrating to `angular16` and updating `typescript` to the latest version, we started to see the following typescript error in `@ngxs/store` `decorators`:

class decorators:
![image](https://github.com/ngxs/store/assets/6247440/988bdbf7-a652-46e5-a7e0-25b3b6c95830)

method decorators:
![image](https://github.com/ngxs/store/assets/6247440/ad7e4574-88bd-41bf-b19f-d085f45ede0a)
 

### Describe the solution you'd like
Update the current typescript version to the latest one.

### Describe alternatives you've considered
We already have our `tsconfig.json` properly configured and it has no problems with other libraries decorators (i.e angular's ones). Is there anything we are missing? Does anybody else experienced this issue and found a workaround?

Thanks in advance.

**Comment by h3x4d3c1m4l** [comment]
Try setting `target` and `module` of `tsconfig.json` to `ES2020` (instead of Angular default ES2022). This fixed the exact same issue for me.

The relevant part of the `tsconfig.json` should look like this:

```
    "target": "ES2022",
    "module": "ES2022",
    "lib": [
      "ES2022",
      "dom"
    ],
```

These are the versions I'm using btw:
- `"@angular/core": "^16.2.4"`
- `"@ngxs/store": "^3.8.1"`
- `"typescript": "^5.1.6"`

This however is not a real solution as it causes a warning to appear from Angular (that tells me to set the `target` to `ES2022` but even if I only set that one to `ES2022` it still breaks...)

**Comment by luismmdev** [comment]
Hi @h3x4d3c1m4l !

Thanks for your answer and sharing what have worked for you. Sadly, even applying those changes to the `tsconfig`, I'm still seeing the same errors.

**Comment by arturovt** [comment]
@luismmdev can you provide a minimal reproducible example?

**Comment by luismmdev** [comment]
Hi @arturovt. Sorry for the delay. I've tried creating a minimal example to reproduce the issue but everything seemed to be working as expected. Maybe there's something wrong or conflicting in our `tsconfig.json`. I'll try again whenever you guys release a new version. Thanks!

**Comment by arturovt** [comment]
I’m closing the issue for now. Feel free to reopen once you’re facing it again and at least can provide a running example, this will help to pinpoint that issue.
