### ISSUE TITLE
🐞[BUG]: Uncaught TypeError: Cannot read properties of undefined (reading 'SystemState')

### ISSUE THREAD

**Issue by qq253498229** [ngxs/store#2048]
### Affected Package

 Sorry, I do not know.

### Is this a regression?

 Sorry, I do not know.

### Description

 

Here is my code:

```typescript
  @Selector([CronState])
  static list({cronMap}: CronStateModel) {
    console.log('list', cronMap);
    return [];
  }
```

When I added monitoring for another state as shown below, I encountered an error "Uncaught TypeError: Cannot read properties of undefined (reading 'SystemState')":

```typescript
  @Selector([CronState, SystemState])
  static list({cronMap}: CronStateModel, {currentTime}: SystemStateModel) {
    console.log('list', cronMap, currentTime);
    return [];
  }
```

There are no issues when monitoring these two values individually. How can I resolve this error?

## 🔬 Minimal Reproduction

 

Here is my Git repository: git@github.com:qq253498229/ngxs-error001.git, and the file is located at `src/app/store/cron/cron.selector.ts`.

## 🔥 Exception or Error
<pre><code>

 Uncaught TypeError: Cannot read properties of undefined (reading 'SystemState')
</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 16.0.0
- @ngxs/store version: 3.8.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   v18.16.1
- NPM version: 9.5.1
- yarn version: 1.22.10
- Platform:   MacOS 13.5.1 (22G90)

Others:

WebStorm 2023.2
Build #WS-232.8660.143, built on July 21, 2023
Licensed to bin wang
Subscription is active until July 6, 2024.
Runtime version: 17.0.7+7-b1000.6 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    documentation.show.toolbar=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    Statistic (4.2.7)
    String Manipulation (9.10.0)
    org.asciidoctor.intellij.asciidoc (0.38.20)

</code></pre>

**Comment by qq253498229** [comment]
I tried changing it to this syntax, and the application can execute properly:

```typescript
  static list() {
    return createSelector([CronState, SystemState], ({cronMap}: CronStateModel, {currentTime}: SystemStateModel) => {
      console.log('list', cronMap, currentTime);
      return [];
    });
  }
```

**Comment by arturovt** [comment]
This is a circular reference issue: `system.state.ts -> cron/index.ts -> cron.selector.ts -> system/index.ts -> system.state.ts`. Consider updating your file structure and remove barrel files where they're redundant.

**Comment by qq253498229** [comment]
Oh my goodness! 

I used to encounter similar errors frequently before, and every time, I had no idea why they were happening or how to resolve them. 

Your answer helped me a lot.

**Comment by qq253498229** [comment]
@arturovt May I ask if you have any suggestions regarding the 'barrel file'? I'm not sure whether I should delete it completely, as it does seem quite useful.

**Comment by arturovt** [comment]
Barrel files are used to simplify imports for external consumers, but they're always leading to circular references if not managed carefully. It's likely always a circular reference when you face an error stating 'cannot read properties of undefined, reading some class'. You either have to import the file directly from the chain (not `cron`, but `cron/actions`), because those files are neighbors, located in 2 close folders. Or you can do a dependency inversion, i.e., dispatch `ResetConfig` outside the system state through `actions$.pipe(ofActionSuccessfull(SystemAction.ResetConfig)).subscribe(() => store.dispatch(new ResetConfig()))`.

**Comment by qq253498229** [comment]
I've deleted all `index.ts` files, and now the world is filled with peace and love.
