### ISSUE TITLE
🐞[BUG]: @Select decorator doesn't trigger value

### ISSUE THREAD

**Issue by fabisoligo** [ngxs/store#2058]
### Affected Package

The issue is caused by package @ngxs/store

### Description

`@Select` decorator doesn´t trigger ngxs state value

## 🔬 Minimal Reproduction

When listening a ngxs state value from a component using the select decorator, it doesn't work. Using the select method, it works fine

 https://stackblitz.com/edit/stackblitz-starters-yxvkub

<pre><code>
Libs:
- @angular/core version: 16.2.5
- @ngxs/store version: 3.8.1

**Comment by arturovt** [comment]
The "Select" decorator is being deprecated.
