### ISSUE TITLE
🐞[BUG]:  export 'StateContext' (imported as 'StateContext') was not found in '@ngxs/store' 

### ISSUE THREAD

**Issue by bsivapuram** [ngxs/store#2072]
### Affected Package
we are using ngxs/store version 3.8.1 in our angular application.

### Is this a regression?
No

### Description

we are updating the application to angular 16. While running the app I got the below error:
 Error: export 'StateContext' (imported as 'StateContext') was not found in '@ngxs/store' (possible exports: Action, Actions, InitState, NGXS_PLUGINS, NgxsDevelopmentModule, NgxsModule, NgxsSimpleChange, NgxsUnhandledActionsLogger, NoopNgxsExecutionStrategy, Select, Selector, SelectorOptions, State, StateStream, StateToken, Store, UpdateState, actionMatcher, createModelSelector, createPickSelector, createPropertySelectors, createSelector, ensureSelectorMetadata, ensureStoreMetadata, getActionTypeFromInstance, getSelectorMetadata, getStoreMetadata, getValue, ofAction, ofActionCanceled, ofActionCompleted, ofActionDispatched, ofActionErrored, ofActionSuccessful, setValue, ɵNgxsFeatureModule, ɵNgxsRootModule)

**Comment by arturovt** [comment]
Please, provide a minimal reproducible example.
