### ISSUE TITLE
🚀[FEATURE]: Support Angular 17

### ISSUE THREAD

**Issue by nzacca** [ngxs/store#2078]
### Relevant Package

All Ngxs packages.

### Description

Support Angular 17.

### Describe the problem you are trying to solve

Trying to update our codebase to Angular 17.

### Describe the solution you'd like

Relax the restriction in `package.json`.

### Describe alternatives you've considered

None at this time.

**Comment by CesarD** [comment]
Yes, please! It's the only package that is complaining for Angular 17.

**Comment by ggros-septeo** [comment]
Really need this to be able to update a project to Angular 17. Thanks for the work!

**Comment by shadow1349** [comment]
I would love to be able to run npm install without the --legacy-peer-deps flag.

**Comment by jase88** [comment]
Alternative to `legacy-peer-deps` is overridding dependencies in `package.json`:

```json
 "overrides": {
    "@ngxs/devtools-plugin":{
      "@angular/core": "$@angular/core"
    },
    "@ngxs/form-plugin":{
      "@angular/core": "$@angular/core",
      "@angular/forms": "$@angular/forms"
    },
    "@ngxs/logger-plugin":{
      "@angular/core": "$@angular/core"
    },
    "@ngxs/router-plugin":{
      "@angular/core": "$@angular/core",
      "@angular/router": "$@angular/router"
    },
    "@ngxs/storage-plugin":{
      "@angular/core": "$@angular/core"
    },
    "@ngxs/store": {
      "@angular/core": "$@angular/core"
    }
  }
```
$ references the version used from the direct dependency

**Comment by RHeijnen** [comment]
> Alternative to `legacy-peer-deps` is overridding dependencies in `package.json`:

> $ references the version used from the direct dependency

While alternatives to legacy-peer-deps are welcome, In my case its not acceptable to use.

NGXS is the core for my enterprise application, I would prefer not to put bandaids on something that is used by huge amounts of people everyday.

Patiently waiting...

**Comment by ggros-septeo** [comment]
Any reviewer available ? :)

**Comment by ursus-the-bear** [comment]
I tried the `$ references the version used from the direct dependency` as well but didn't work for me... would be great it I could compile without `legacy-peer-deps`. Thank you for all you hard work!

**Comment by rupekeshan** [comment]
Hello, When will the npm publish will happend?
