### ISSUE TITLE
ReferenceError: data is not defined

### ISSUE THREAD

**Issue by nukuuk** [ngxs/store#214]
I am running into the following run-time error in my effort to implement ngxs in an app I'm working on:

> ReferenceError: data is not defined
    at MapSubscriber.eval [as project] (eval at fastPropGetter (webpack-internal:///./node_modules/@ngxs/store/esm5/ngxs-store.js), <anonymous>:3:20)
    at MapSubscriber._next (webpack-internal:///./node_modules/rxjs/_esm5/operators/map.js:82)
    at MapSubscriber.Subscriber.next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:100)
    at StateStream.BehaviorSubject._subscribe (webpack-internal:///./node_modules/rxjs/_esm5/BehaviorSubject.js:34)
    at StateStream.Observable._trySubscribe (webpack-internal:///./node_modules/rxjs/_esm5/Observable.js:178)
    at StateStream.Subject._trySubscribe (webpack-internal:///./node_modules/rxjs/_esm5/Subject.js:108)
    at StateStream.Observable.subscribe (webpack-internal:///./node_modules/rxjs/_esm5/Observable.js:166)
    at MapOperator.call (webpack-internal:///./node_modules/rxjs/_esm5/operators/map.js:60)
    at AnonymousSubject.Observable.subscribe (webpack-internal:///./node_modules/rxjs/_esm5/Observable.js:163)
    at CatchOperator.call (webpack-internal:///./node_modules/rxjs/_esm5/operators/catchError.js:83)

Currently using:
* ngxs: 2.0.0
* angular/core: 5.2.3

To try to isolate the origin of this error, I have been using a "block and tackle" approach, namely, adding components and other objects to a generic app until it breaks.  The app breaks with reference to the above run-time error. 

So, for example,  THE FOLLOWING WORKS:
````
@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  @Select(HotelIdState) hotelId$: Observable<string>;
  @Select(UserDataState) userData$: Observable<UserDataStateModel>;
  @Select(HotelDataState) hotelData$: Observable<HotelDataStateModel>;
  @Select(AuthState) authentication$: Observable<AuthStateModel>;

  constructor(store: Store) {

  }
}
```` 

BUT THE FOLLOW DOES NOT WORK (throws error listed above - notice I've referenced a service called StartupService in the constructor):

```
@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  @Select(HotelIdState) hotelId$: Observable<string>;
  @Select(UserDataState) userData$: Observable<UserDataStateModel>;
  @Select(HotelDataState) hotelData$: Observable<HotelDataStateModel>;
  @Select(AuthState) authentication$: Observable<AuthStateModel>;

  constructor(store: Store, startup: StartupService) {

  }
}
```

What is StartupService?  It is an injectable service that implements a number of ngxs functions.  Here is a schematic of what it looks like:

```
> @Injectable()
export class StartupService {
  @Select(HotelIdState) hotelId$: Observable<string>;
  @Select(UserDataState) userData$: Observable<UserDataStateModel>;
  @Select(HotelDataState) hotelData$: Observable<HotelDataStateModel>;
  @Select(AuthState) authentication$: Observable<AuthStateModel>;
  constructor(
    private store: Store,
    private rezService: ReservationsService,
    private router: Router,
    private http: NkHttp,
    private nkFn: nk.NkFunctions) {
       // code here
} 
```

So the bottom line is:  I get a run-time error when my angular app attempts to reference/instantiate an injectable service that implements ngxs.  Is there a trick to using ngxs with injectable angular services?

**Comment by deebloo** [comment]
@nukuuk can you fill out the issue template? what version are you using and can you provide any code to help us troubleshoot

**Comment by nukuuk** [comment]
@deebloo yes I have updated with more info regarding the error/problem

**Comment by deebloo** [comment]
hmmmm I don't think we have ever tested Selectors in a service. I don't see why it wouldn't work but idk for sure. maybe we can reproduce in a unit test and see what the root cause is

**Comment by nukuuk** [comment]
I'm just spitballing here, but my hunch is perhaps the service is instantiated BEFORE ngxs store is instantiated hence the error saying "data is not defined"

**Comment by deebloo** [comment]
Does injecting and using the store to select stuff work?

**Comment by nukuuk** [comment]
@deebloo no, it does not.   See the repo I've submitted:  https://github.com/nukuuk/ngxs-service-example

**Comment by deebloo** [comment]
@nukuuk in my testing it is failing even when I don't inject that important-service

**Comment by deebloo** [comment]
@nukuuk if you remove the hyphen from your state name it will work

**Comment by deebloo** [comment]
@amcdnl perhaps we should add a check in the state decorator to make sure names are valid

**Comment by nukuuk** [comment]
@deebloo I think removing the hyphen may have fixed it.  am testing to confirm.  Good catch on that!

**Comment by yarrgh** [comment]
Confirmed that removing the hyphen works: https://stackblitz.com/edit/github-uujsdg?file=src%2Fapp%2Fapp.component.ts

Just curious, why are hyphens not allowed?

**Comment by deebloo** [comment]
They are not explicitly not allowed. But something internal does not like
it

**Comment by amcdnl** [comment]
@deebloo - Ya, good call. This is a priority for 2.1 I think. Should be an easy regex.

**Comment by amcdnl** [comment]
@deebloo - I think this regex might work - https://regex101.com/r/10zf95/1

`[a-zA-Z_]\w*(@?[a-zA-Z_]\w*)*$`

**Comment by nukuuk** [comment]
Thank u all for your input and assistance here.  Original error has disappeared!  Ngxs is rocking and rolling...
