### ISSUE TITLE
Question | NgxFormPluginModules ui states 

### ISSUE THREAD

**Issue by st-clair-clarke** [ngxs/store#216]
Could you please add that touched and untouched states to the Form plugin?

Also, an {option: {}} for us to add any other ui state necessary. For instance, I currently add a target UI state that identifies different instances of the same form. This target is an @Input() target property. I use this target to switch the instance of the form being currently used,

Given, the example at [https://ngxs.gitbooks.io/ngxs/plugins/form.html](https://ngxs.gitbooks.io/ngxs/plugins/form.html), this will have to be done for each form. So, each form will be a 1:1 mapping to its own store. Is this correct?

Let me know what you think. If there is an easier way to do this from my end that would be appreciated.

Cheers

**Comment by tsawan** [comment]
@amcdnl we can probably add a userData property in the state and create a corresponding action.

**Comment by amcdnl** [comment]
I'm open to suggestions!

**Comment by amcdnl** [comment]
@tsawan - Anymore thoughts?
