### ISSUE TITLE
🐞[BUG]: selectSignal cannot be called outside an injection context

### ISSUE THREAD

**Issue by haigha106** [ngxs/store#2200]
### Affected Package

 The issue is caused by package @ngxs/store

### Is this a regression?  yes

 Yes, the previous version in which this bug was not present was: 18.0.0

### Description

 selectSignal cannot be called outside an injection context in 18.1.0

## 🔬 Minimal Reproduction
    #store = inject(Store);

    someId = input.required<number>();

    ngOnInit(): void {
        this.someField= this.#store.selectSignal(SomeStore.issue(this.someId()));
    }

the above code worked in 18.0.0, in 18.1.0 it causes an exception 

a current workaround would be to use 

    #store = inject(Store);
    #injector = inject(Injector);
    ngOnInit(): void {
        const someField= this.#store.select(SomeStore.issue(this.someId()));
        this.someField = toSignal(someField, {injector: this injector})
    }

## 🔥 Exception or Error
<pre><code>

 toSignal() cannot be called from within a reactive context

</code></pre>

## Environment

<pre><code>
Libs:
- @angular/core version: 18.11
- @ngxs/store version: 18.1.0

Browser:
- [ ] Chrome (desktop) version 127

**Comment by markwhitfeld** [comment]
The fix for this has been released in v18.1.1
