### ISSUE TITLE
📚[DOCS]: Missing LICENSE file on shipped package

### ISSUE THREAD

**Issue by Frozen-byte** [ngxs/store#2225]
### Description

The LICENSE.md file is missing in the released packages and is not shipped.
This prevents SBOM generation tools from collecting evidences for Copyright or Original Licenses.

### Expected vs Actual Behavior
https://www.npmjs.com/package/@ngxs/store?activeTab=code  should list the LICENSE.md file from source.

**Comment by arturovt** [comment]
This has been fixed in 18.1.3.
