### ISSUE TITLE
🐞[BUG]: store.select finalize on catchError

### ISSUE THREAD

**Issue by vaskus** [ngxs/store#2251]
### Description

When subscribe into store select item and map into http call which fail, subscription finalize and there is no chance to call same subscription again. Working example with problem You could found on stackbliz: https://stackblitz.com/edit/stackblitz-starters-mrty2d

## 🔬 Minimal Reproduction
You can find problem on stackbliz https://stackblitz.com/edit/stackblitz-starters-mrty2d

Libs:
- @angular/core version: 18.1.0
- @ngxs/store version: 18.1.4

Browser:
- [x] Chrome (desktop)
- [x] Firefox
 
For Tooling issues:
- Node version: 22.2.0
- Platform:  Windows, Mac

**Comment by markwhitfeld** [comment]
This is not an issue with NGXS, but is working exactly as rxjs operates for the pipeline you have created.
I forked your repro and replaced the `store.select` with an rxjs `interval` call, and it exhibits the exact same behavior.
![image](https://github.com/user-attachments/assets/7952c84e-94d4-4a14-8583-209e83f5aebf)
https://stackblitz.com/edit/stackblitz-starters-cb7p4h?file=src%2Fmain.ts%3AL45
