### ISSUE TITLE
🚀[FEATURE]: Support for Angular 19

### ISSUE THREAD

**Issue by rupekeshan** [ngxs/store#2268]
### Relevant Package
This feature request is for @ngxs/store

### Description
Since Angular 19 was released on the 19. Nov, it should be supported by this package.

**Comment by AndreiZaman** [comment]
Hello, when is planned to have the support of angular 19?

**Comment by shadow1349** [comment]
Looks like the work of ready to go, it just needs a review.

**Comment by AndreiZaman** [comment]
It will be nice to have it sooner rather than later

**Comment by Sina7312** [comment]
So we will have it soon? We can't migrate to 19 because of it.

**Comment by weewoo-meow** [comment]
It's merged on master, but on npm it is still not updated.

**Comment by weewoo-meow** [comment]
> So we will have it soon? We can't migrate to 19 because of it.

Try version `18.1.6-dev.master-0ae2066`. It is bleeding-edge and you may encounter errors with the devtools package (as far as I tested it), but it would be a good start for you until the stable release appears.

**Comment by arturovt** [comment]
NGXS v19 has been released.

**Comment by shadow1349** [comment]
Thanks guys, this is awesome!
