### ISSUE TITLE
High Order Reducer Equivalent

### ISSUE THREAD

**Issue by thaoula** [ngxs/store#237]
Hi Guys,

We have a component (actually a set of components) that we reuse in several places within the application. It make several api calls and provides searching and selecting of a core entity. 

We cannot store the components state on the global state and it is too large for input / output etc. So the state management and interaction was implemented with NGRX and a high order reducer to allow the reuse of reducer logic.

Is there an equivalent or prescribed approach to achieve the effects of a High Order reducer?
https://redux.js.org/recipes/structuring-reducers/reusing-reducer-logic

Regards,
Tarek

**Comment by deebloo** [comment]
@thaoula I think you should have to use inheritance here.

**Comment by amcdnl** [comment]
@deebloo is correct. Inheritance or plugin is your answer.

**Comment by admir86** [comment]
Hi @thaoula
did you solved this problem? I'm also searching for a solution for same problem.
