### ISSUE TITLE
NgxsReduxDevtoolsPlugin NOT updating in Redux devtools with new objects

### ISSUE THREAD

**Issue by st-clair-clarke** [ngxs/store#240]
### Versions

```
"@ngxs/devtools-plugin": "^3.0.0-beta.0",
        "@ngxs/form-plugin": "^3.0.0-beta.0",
        "@ngxs/logger-plugin": "^3.0.0-beta.0",
        "@ngxs/storage-plugin": "^3.0.0-beta.0",
        "@ngxs/store": "^3.0.0-beta.0",
        "@ngxs/websocket-plugin": "^3.0.0-beta.0",
"@angular/core": "6.0.0-beta.7",
```

### Repro steps

* Step 1 | Create a store and serve the app

interface ICore {
  data: Object
}

class Core {
  data: Object = uiData
}

@State<ICore>( { name: 'core', defaults: new Core() } )
export class CoreState {
  onInit( state: StateContext<Array<any>> ) {
    console.log( 'Core State initialized' )
  }

![devtool](https://user-images.githubusercontent.com/3227590/38450691-6e135e8e-39f0-11e8-805e-c0d6bf11e066.jpg)

* Step 2 | add a new Object to the store

interface ICore {
  data: Object
  pallet: Object
}

class Core {
  data: Object = uiData
  pallet: Object = pallet
}

* Step 3 | serve the app again
@State<ICore>( { name: 'core', defaults: new Core() } )
export class CoreState {
  onInit( state: StateContext<Array<any>> ) {
    console.log( 'Core State initialized' )
  }
### Observed behavior
The pallet object is not displayed in the devtools graph

![devtool](https://user-images.githubusercontent.com/3227590/38450730-01bf3496-39f1-11e8-947f-f424582f18e3.jpg)

### Desired behavior

Both the data and pallet object should be present in the devtool

**Comment by amcdnl** [comment]
this should be fixed in 3.0
