### ISSUE TITLE
Bad RxJS imports creating a large bundle size

### ISSUE THREAD

**Issue by codediodeio** [ngxs/store#248]
Importing Rx classes with `import { something } from 'rxjs'` is causing the bundle size to explode. A picture is worth a thousand words. Sending over a PR with a fix shortly. 

![ngxs-import](https://user-images.githubusercontent.com/10172199/38462567-3f8a9da8-3a9e-11e8-958e-dec3e85ed41d.png)

**Comment by amcdnl** [comment]
I think I did this in prep for rx6, will have to undo these when that happens

**Comment by deebloo** [comment]
Yes when we upgrade we can change but for now it will cause enourmous bundles. Maybe we should create a ticket to track rxjs6 upgrade
