### ISSUE TITLE
Versions:

### ISSUE THREAD

**Issue by manjureddy7** [ngxs/store#264]
Versions:
ngxs/store -"^3.0.0-rc.0",
cli - 1.7,
angular -  5.2
@amcdnl @leon @bossqone @SebastianM @xmlking 
Getting below  Error Message during Compiling:
Error in node_modules/ngrx/store/src/of-action.d.ts (1,10): Module Project/node_modules/rxjs/rx has no exported member "Operator Function" .
Please help.

**Comment by RoraxHan** [comment]
I've met the same problem..
Is this issue solved?

**Comment by deebloo** [comment]
@RoraxHan it shoudl be fixed in the latest dev build

**Comment by amcdnl** [comment]
3.0 supports NG6
