### ISSUE TITLE
Optimistic updates with undo possibility

### ISSUE THREAD

**Issue by FallenRiteMonk** [ngxs/store#269]
I'm currently thinking about moving from ngrx to ngxs due to one of my projects getting bigger and I'm slowly loosing the overview over my state. Having just read the documentation I got the impression that this is good solid project and might make my life a bit easier.

Now I'm not sure if i just missed something reading the docs, or if this currently not possible in standard way in this library, but I was wondering if I could do optimistic updates with the possibility of undoing them in case of an error.

What I would like to do:
I have a shared todo app (server with rest api).
Upon marking a todo as done, I would like my app to immediately update its state, setting the selected todo as done, while in the background a rest request updates the todos state on the server. This would eliminate the necessity of dispalying some kind of (in my point of view annoying) loading spinner, as the app would OPTIMISTICALLY assume the state of the todo will be updated successfully on the server. Though in case of the request failing, the loca state of the app should be reverted to where the todo was not marked as done.

As far as I understood the documentation this could be achieved by creating an action that immediatly returns a new state and triggers the request. Then I would subscibe to the requests result, and in case of a error I trigger a new action which would undo the changes that where made by the first action.

Currently in my project which uses ngrx, I can simply do this revert using [ngrx-undo](https://github.com/brechtbilliet/ngrx-undo).

Now my question is, can I somehow accieve this in a more simple way (without having to dispatch a new action which manually reverts the changes), or would this be a idea for a new plugin?

**Comment by amcdnl** [comment]
Could be easily done, would look something like this: ( pseudo code )

```TS
export class TodoState {

  constructor(private todoService) {}

  @Action(AddTodo)
  addTodo({ patchState, getState }, { payload }) {
    const state = getState();
    patchState([...state, payload]);
    this.todoService.add(payload).subscribe(
      () => {},
      (err) => {
        patchState([...state]);
      });
  }
}
```

That library is interested. Wish i had more time to build that.

**Comment by FallenRiteMonk** [comment]
That looks simple xD

Just another quick question: would this still properly work if I would dispatch two addTodo actions on a slow network connection an then the first fails? In the sens would I then have a current state of [todo2] or would the patchState called by the first addTodo overwrite the addition of the second leaving me with a state of [].

**Comment by youssefsharief** [comment]
@FallenRiteMonk  Did you find any solution for this to be used in ngxs?

**Comment by FallenRiteMonk** [comment]
@youssefsharief No nothing that really fit my needs. I played around with some ideas, but they all seemed to have some kind of drawback.

**Comment by dsriniv** [comment]
Have you look at this plugin? https://www.npmjs.com/package/ngxs-history-plugin
