### ISSUE TITLE
Interfaces for Livecycle Events

### ISSUE THREAD

**Issue by Silthus** [ngxs/store#272]
I think it would be good to create a simple Interface that needs to be implemented on the state class for the livecycle events.

Implementing the interface would be more intuitive than guessing the signature of the livecycle method.

`implements NgxsOnInit`

**Comment by amcdnl** [comment]
Yup good call.

**Comment by deebloo** [comment]
@amcdnl could we also change onInit to ngxOnInit?

**Comment by amcdnl** [comment]
@deebloo im fine w/ that.
