### ISSUE TITLE
Using services in Selectors

### ISSUE THREAD

**Issue by JanMalch** [ngxs/store#273]
What would be the correct way to use an injectable service in a @Selector/@Select or this not possible?
Say I have a list of todos of multiple accounts. Now I also have a service which provides the current user ID.
How would you build a selector that always returns the todos of the current user? I can't use DI for the static function.
Would a service be available in the @Select in a component? Or do I have to select all todos and filter them in my component?
 
What's your recommended approach? Thanks for any insight!

**Comment by amcdnl** [comment]
Its not possible, decorators are pure functions with no context to the `this` object.

**Comment by CesarD** [comment]
I got into this as well, but trying to use a logger to debug and log some stuff occurring on selectors... To my surprise I can't inject the logger I needed (ngx-logger). Too bad there's no way to do this 😞
