### ISSUE TITLE
Question: How to select state from sibling feature modules

### ISSUE THREAD

**Issue by wesleygrimes** [ngxs/store#275]
I read through the issues and googled heavily and haven't been able to find discussion of this. Maybe it's an anti-pattern but in my current @ngrx setup I select from a config store in all of my other feature stores. I need to be able to do something similar in ngxs. Should I inject into the constructor of my State class an instance of the sibling state?

### Versions

```
* ngxs: 2.0.0
* @angular/core: 5.2.0
```

### Repro steps

```
@Action(SignUpRequestAction)
  async signUpRequestAction(
    sc: StateContext<AuthStateModel>,
    { payload }: SignUpRequestAction
  ) {
    sc.patchState({
      isLoading: true,
      error: null
    });

   // I need access here to a value from a sibling feature module that holds config data
  }
```

**Comment by amcdnl** [comment]
Ya, i'd say this is a anti-pattern. Parent's can't know about feature states because they could not be there. If you show a full use case, maybe someone can help you find a better way.

**Comment by wesleygrimes** [comment]
Thanks for the feedback. I think what I will do is create a service that caches the first return of the config values and then inject that service into the feature states. I had a feeling it was close to being an anti-pattern.

Thanks for the quick response!

**Comment by amcdnl** [comment]
No problem! Enjoy!
