### ISSUE TITLE
Upgrade CLI

### ISSUE THREAD

**Issue by amcdnl** [ngxs/store#277]
Upgrade the CLI and Use CLI Packager instead of ng-packagr.

**Comment by un33k** [comment]
The CLI is not ready yet. Lots of bugs. May want to hold back a while.

**Comment by un33k** [comment]
Took it for a spin, not working if lib1 depends on lib2 ... doesn't support scope yet (@scope/package).  Now that they have released 6.0.0, you may want to take it for a spin and see if with the minimal tweak, you can make it work ngxs.

**Comment by deebloo** [comment]
@un33k yeah you would have to do a setup kinda like what we have here where you define the tsconfig paths. just need to make sure that ng-packagr is given a custom tsconfig

**Comment by un33k** [comment]
@deebloo I did pass custom tsconfig with lots of combinations/permissions with no luck.  There are open bugs against the `@scope/pkg` support.  It would be nice to skip `npm link`.  I am sure the CLI folks are working hard to add support or docs. I think they had to rush an incomplete release to align themselves with ng 6.  It would be great if you find a way to make it work.

**Comment by xmlking** [comment]
on issues so far.  using angular-cli 6.0.1 
https://github.com/xmlking/ngx-filepond

**Comment by splincode** [comment]
We now updated to last version ng-packagr
