### ISSUE TITLE
Lots of bolierplate related to static type = '[Section] Action' in every action class

### ISSUE THREAD

**Issue by AlgoTrader** [ngxs/store#280]
I am porting my code to 3.x and experience adding types for every action. I would like to suggest to add a decorator to remove the type boilerplate

now
```
export class MyAction {
  static type = '[App] MyAction'
}
```

proposed
```
@Action('App') class MyAction {}
```

Personally, I feel Action decorator in state class is misleading. It is not actions there but action handlers. Action is rather object being dispatched.

**Comment by leon** [comment]
Hey!

in version 2 we didn't need the static type, but because how AOT / minifying works, the types where getting mangled and because of this we had to go back to requiring a static type field :(

So unfortunately it's a no to this...

**Comment by AlgoTrader** [comment]
Decorator can add type field
