### ISSUE TITLE
[Proposal] we can reduce boilerplate in actions

### ISSUE THREAD

**Issue by AlgoTrader** [ngxs/store#282]
I have written the decorator, that allows me to write actions like this:

```
@Action('NameSpace') class MyAction {}
```

instead of

```
class MyAction {
  static type = '[NameSpace] MyAction'
}
```

I do not propose to remove `type` field. I propose provide a decorator which will add the static `type` into actions.  

In #280 I proposed to change action declarations using decorators.  The issue was closed without discussion. The decorator is as plain as

```
function Action(ns) {
  return function(_class) {
    _class.type = `[${ns}] ${_class.name}`;
  }
}
```

**Comment by AlgoTrader** [comment]
Well, after minification, all the meaningfull names are collapsed into '[MyNamespace] t'. My solution works for dev mode, but not for prod. The same problem, that caused `static type` to appear.

It seems there are two benefits of 'static type = '[XXX] YYY'. The first is unique identifier. The second is debug helper. As to first, it is very easy to generate a unique id and put it to type but the second benefit is lost.

I can do like this

`@Action class MyAction()`

and write a decorator which sets MyAction.type = guid()

Alas, the human redable type name is lost. But no boilerplate :-)

**Comment by AlgoTrader** [comment]
Well, just another idea. 

`@ActionType() class MyAction() {}` for those who hate writing `static type`. Decorator will generate unuque id itself.

`@ActionType('[MySpace] MyAction')` class MyAction() {}` to have the `static type` meaningful

**Comment by AlgoTrader** [comment]
Finally, I tested the following actions code

```
@ActionType()
export class Authorize {}

@ActionType()
export class Authorized {}

@ActionType()
export class Logout {}
```

For me, the ActionName.type is quite useless, the minor benefit is debug comfort only.

My approach is following:

```
export function ActionType(ns = 'Default') {
  return function decorate(_class) {
    _class.type = `[${ns}] ${String(Math.random())}`;
  };
}
```

I don't care whether `type` is human redable or not, I just don't like the idea to write action name twice - one in class name and second in `static type`

**Comment by deebloo** [comment]
@AlgoTrader we specifically want it to be human readable for prod debugging purposes. We actually had an ActionToken in an earlier RC but it causes problems with some other things. I am not against the idea of a decorator though.

**Comment by deebloo** [comment]
@amcdnl what do you think about something like this? we could bring back the action token here and they would be more explicit. the name could be optional for folks who care about the name not being mangled

**Comment by deebloo** [comment]
also @AlgoTrader even if we don't include the decorator in the core lib there is no reason you can't continue to do so

**Comment by AlgoTrader** [comment]
I know I can use my own decorator. I just think decorator may provide reasonable defaults for lazy and great explicitness for those who need it.

Decorator is 100% equivalent to type. It just create that type itself. I do not beleive there is any runtime difference between 'typed' class and 'decorated' class.

I just think decorator is not that ugly

**Comment by leon** [comment]
I'm sorry I closed your issue before you hade a chance to explain.
But as deebloo says, we have already been down this path.

I think we need to tread lightly when it comes to decorators.
The magic of them can fast become quite complex. (lombok anyone?)

## not a lot to gain
```
@ActionType()
export class Authorized {}
```
vs
```
export class Authorized {
  static type = 'Authorized'
}
```

### Best solution
Before we were not using any decorators at all for the actions, which was great.
If we later down the line can get rid of the static type. Maybe TS 2.9 will introduce something, or we find a workaround.

But until then I'd rather use the static field.

**Comment by AlgoTrader** [comment]
I cannot agree the double action name, one in class name and the second in string is better.

The first variant is DRY. The second is ngrx way - not using Angular way (decorators) but adding two sources of truth

**Comment by deebloo** [comment]
It isn't two sources of truth. The type property is the source of truth.

**Comment by deebloo** [comment]
also a little context to why we made the decision. We tried generating unique names to ensure we didn't have conflicts, we got some folks complaining about minified actions not being human readable which made prod debugging more difficult. I actually agree with you that I don't care about them being human readable when minified but we saw a lot of traffic around that problem. It also adds more complexity to the core library especially when it comes to things like plugins.

I am willing to discuss more but just be aware that there is more we have consider then just the aesthetics of the class definition itself.

Thanks for taking the time and interest to share this suggestion!

**Comment by deebloo** [comment]
We could even put a small demo together and run it through our tests to see if anything t shakes out

**Comment by un33k** [comment]
One of Ngxs' mission statement is "fewer boilerplates", right?

I wonder if we could take the `name` from the Store class and combine it with the action class name.

```
class AuthLogin {}

@State<AuthState>({
  name: 'auth',
  defaults: AuthDefaultState
})
export class AuthStoreState {
}
```

```
uniqueId = `[${name.toUppercase()}]: ${klass.name}`;

// [AUTH]: AuthLogin
```

Can this be done?

**Comment by deebloo** [comment]
@un33k that still potentially creates a name collision. we had a token previously that helped us handle this but it causes other issues.

**Comment by amcdnl** [comment]
@un33k - Action's aren't always bound to names.
@AlgoTrader - I think adding a decorator is kinda like trading one evil for another except if you define them you get them in production which i think is a pretty powerful usecase for reproducing state from prod in dev.

I'm going to close this issue for now. I think the core team all agree that while this is possible its not ideal and while we don't like adding the type, it is the best solution for the time being. I encourage everyone to continue coming up with ideas though.
