### ISSUE TITLE
production build problems

### ISSUE THREAD

**Issue by AlgoTrader** [ngxs/store#284]
When I run `ng build` everything is OK. But using `ng build --prod` I get lots of warnings like those:

WARNING in ./src/app/app.component.ts
22:26-44 "export 'ofActionDispatched' was not found in '@ngxs/store'

WARNING in ./src/app/features/search-tsp/search-tsp.module.ngfactory.js
54:3405-3411 "export 'ɵh' (imported as 'i23') was not found in '@ngxs/store'

Angular 5, RxJS forward compat, ngxs 3.0.0-rc.1
The production build dos not work

**Comment by deebloo** [comment]
Can you provide us with a small example showing the error?

**Comment by AlgoTrader** [comment]
Unfortunately, it's a port of quite big project. I can try to do any research you need

**Comment by AlgoTrader** [comment]
Sorry for bothering. The universal cure 'rm -rf node_modules && npm install' fixed all the problems.
Please close
