### ISSUE TITLE
rxjs error (exported member OperatorFunction not found) in new angular project

### ISSUE THREAD

**Issue by nilsfriess** [ngxs/store#291]
### Versions
```
* ngxs: 3.0.0-rc.1
* @angular/core: 5.2.9
* rxjs: 5.5.6
```

### Repro steps

* Create new Angular Project via the angular cli
* install ngxs (`npm i --save @ngsx/store`)
* import `NgxsModule` in `app.module.ts`
* run ng serve

### Observed behavior
There seems to be a version mismatch, because ngxs tries to import `OperatorFunction` but this is not available in rxjs version 5.5.6., so it seems that version 6 of rxjs is needed.

The exact error message is the following (when running ng serve):
```
ERROR in node_modules/@ngxs/store/src/of-action.d.ts(1,10): error TS2305: Module '"/mnt/d/Programmierung/pn_datasecure/pndsm-app/node_modules/rxjs/Rx"' has no exported member 'OperatorFunction'
```

**Comment by nilsfriess** [comment]
Just saw the closed issue that adresses the same problem by adding changing version to 5.6.0-forward-compat.3

**Comment by dev9929** [comment]
remove rxjs in ngmodule  and install this: npm install rxjs@6 rxjs-compat@6 --save

**Comment by ahsinsiddique** [comment]
Also getting same issue, don't know how to fix it?

**Comment by markwhitfeld** [comment]
You probably have an old version of rxjs.
You can fix this by installing rxjs 6 or v5 compat.
Remove rxjs and install this: npm install rxjs@6 rxjs-compat@6 --save

See related issues: #270 #303 #326
