### ISSUE TITLE
Timing issue when starting a module that uses Ngxs (3.0.0-rc.1)

### ISSUE THREAD

**Issue by un33k** [ngxs/store#293]
```
[x] Possible bug
```

### Versions
```
* ngxs: 3.0.0-rc.0
* @angular/core: 6.0.0-rc.1
```

### Repro steps
* Wire up a Foobar module  (NgxsModule.forFeature([FoobarStoreState]))
* Import Foobar right after NgxsModule.forRoot([]) in the app.module.ts 
* Subscribe to the state selector in the consturctor of your FoobarService

### Observed behavior
```
Error: SelectFactory not connected to store!
    at FoobarService.createSelect (ngxs-store.js:575)
    at FoobarService.get [as _stateSub$] (ngxs-store.js:602)
    at FoobarService.push.../../libs/foobar/src/foobar.service.ts.FoobarService.constructor (foobar.service.ts:51)
    at new FoobarService (foobar.service.ts:42)
    at _createClass (core.js:9280)
    at _createProviderInstance$1 (core.js:9256)
    at initNgModule (core.js:9193)
    at new NgModuleRef_ (core.js:9908)
    at createNgModuleRef (core.js:9897)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:11728)
```

### Desired behavior
Ability to subscribe to the state via the selector without worrying about timing issues. (race condition!)

### Mention any other details that might be useful (optional)
Foobar is a singleton utility module (package, library) without any routes. Only one instance of it is pulled in and used as a core part of the app.

```typescript
  @Select(FoobarStoreState) private _stateSub$: Observable<FoobarState>;
  constructor() {
    // v------ this line is the cause of the above exception 
    this._stateSub$.pipe(takeUntil(this._unsubscribe)).subscribe(state => {
      this._state = state;
    });
  }
```

```typescript
  @Select(FoobarStoreState) private _stateSub$: Observable<FoobarState>;
  constructor() {}
  // v------ possible work around, not comfortable with timing errors as they can resurface at any `time`.
  ngOnInit() {
    this._stateSub$.pipe(takeUntil(this._unsubscribe)).subscribe(state => {
      this._state = state;
    });
  }
```

**Comment by amcdnl** [comment]
In general you should use `ngOnInit` there are some cases where constructor happens by not oninit.

**Comment by amcdnl** [comment]
Can you retest in 3.0?

**Comment by un33k** [comment]
@amcdnl Works in 3.0.  I wonder if the timing issue was addressed specifically, or I simply added more logic which shifted the time so I can't see it anymore.   I will close it for now.

**Comment by beyondsanity** [comment]
I'm experiencing the same issue using 3.0.1-dev.master-f33edbe.
It seems a timing issue as can be patched by wrapping the subscribe method in a setTimeout.

**Comment by un33k** [comment]
@beyondsanity with the timing issue, it is hard to say if this is really fixed or not.  I moved some of my code around, and that could have shifted the 'time' to my favor.  If you are using it in a component, then use `ngOnInit`, in a service, wrap it in a setTimeout as services don't have `ngOnInit`.

**Comment by beyondsanity** [comment]
@un33k  In my project now i have 2 different services with the same problem. I wrapped the code in a SetTimeout call  to make it work as you said.
The issue started happening for me when I refactored my code and moved stuff in different modules. The same code placed in a unique module used to work.

**Comment by splincode** [comment]
@sonq create a new issue
