### ISSUE TITLE
feat: Support @Selector ES6 arrow function syntax

### ISSUE THREAD

**Issue by Silthus** [ngxs/store#300]
It would be great if the `@Selector` decorator would support the ES6 arrow function syntax. That would improve the syntax of small selectors, like so:

```
  @Selector()
  static isLoggingIn(state: AuthStateModel) {
    return state.isLoggingIn;
  }

  @Selector()
  static isLoggedIn = (state: AuthStateModel) => state.isLoggedIn;
```

**Comment by deebloo** [comment]
Would be nice but Decorators do not work with arrow functions.
