### ISSUE TITLE
Docs CORS problem?

### ISSUE THREAD

**Issue by Thenis** [ngxs/store#301]
I cannot access the documentation. In the console I am getting cors errors
![image](https://user-images.githubusercontent.com/13870239/38862170-f002780e-423c-11e8-8e4a-fcecae23fca6.png)

Anybody else having this problem?

**Comment by Koen967** [comment]
Http status code 522 seems to be a Cloudflare error. Maybe you can use [this page](https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522-Connection-timed-out) to find an answer?

**Comment by leon** [comment]
It's working great here, so it's a cloudflare cache problem.
It's not got anything to do with the lib, so I'm closing this.

Just keep trying to refresh and it should start working soon :)
