### ISSUE TITLE
Module import issue.

### ISSUE THREAD

**Issue by akash-potdar7** [ngxs/store#303]
I see the following when I import :
**import { NgxsModule } from '@ngxs/store';**
in my app.module.ts

**ERROR in node_modules/@ngxs/store/src/of-action.d.ts(1,10): error TS2305: Module '"/Users/akash/angular/hello/hello/node_modules/rxjs/Rx"' has no exported member 'OperatorFunction'.**

my **"rxjs version: "rxjs": "^5.5.6".**
and **"@ngxs/store": "^3.0.0-rc.1"**

Does the problem associate with version compatibly of RxJs and @ngxs? Please help me with this.

**Comment by Koen967** [comment]
You can find the compatibility of Ngxs versions and Angular versions on the [installation page](https://ngxs.gitbook.io/ngxs/getting-started/installation) of the Ngxs docs.

**Comment by leon** [comment]
As @Koen967 pointed out, 3.0.0 is going to require angular 6 / rxjs 6 which should be released any day now.

**Comment by akash-potdar7** [comment]
So things worked, let me make sure of some aspects.

The problem was with @ngxs version, 3x would support Angular and RxJs 6 out of the box, but latest version RxJs ie., 6x is still in available.
I lowered to @ngxs2.0 version, things work like a charm.

Thank you @Koen967.
