### ISSUE TITLE
alternative for ngrx-store-freeze in ngxs

### ISSUE THREAD

**Issue by maku** [ngxs/store#304]
Is there an alternative approach to freeze the store in development (like ngrx-store-freeze for ngrx)?

**Comment by amcdnl** [comment]
Not at the moment, its on the list though.

**Comment by tdeschryver** [comment]
Is it OK if I take this one?

**Comment by amcdnl** [comment]
@tdeschryver - GO FOR IT!

**Comment by amcdnl** [comment]
Closing and marking for future.

**Comment by amcdnl** [comment]
FYI This is done. Turn on via dev flag.

**Comment by maku** [comment]
@amcdnl Great work, thank you

**Comment by Zuiago** [comment]
Good project, We all expect a long life and many contributors.
