### ISSUE TITLE
@ngxs/form-plugin model and status are empty until first field edit

### ISSUE THREAD

**Issue by AlgoTrader** [ngxs/store#307]
It is extremely unpleasant thing to have model and status undefined until first edit of any form field.

Angular form send valueChanges/statusChanges when something changed. For a newly initialized form, no valueChanges/statusChanges values sent yet, so all the model in store is completly uninitialized

It can be easyly fixed, in directive initialization there should be value/status form props read and used for state initialization

**Comment by leon** [comment]
@AlgoTrader As you say it shouldn't be hard to fix.
Do you think you could have a go at implementing it in a pull request?

**Comment by AlgoTrader** [comment]
The first state update cause two-way form and state synching. First, all data from state (if it exists) are transferred to form. The second, form model, form state and form dirty are transferred back to state.

We cannot do it in reverse order, then state data can be lost. We cannot make it one-way also.

**Comment by AlgoTrader** [comment]
I fixed the integration test

**Comment by tsawan** [comment]
not sure I am clear on this.
I am using this in my app. with form model initialized to an empty object. This is if the user opens the form in 'new' mode. If the user is editing an existing customer object, I initialize the state through a populate action and the form is shown in 'edit' mode.

**Comment by tsawan** [comment]
sorry, just noticed it's already merged in.

**Comment by LosD** [comment]
Shouldn't this have been closed with #309's merge?

(hint: If you use write e.g. `fixes #309` in the PR description or one of its commits, Github will auto-close the issue on PR merge. Also works for [other keywords](https://help.github.com/articles/closing-issues-using-keywords/))

**Comment by arturovt** [comment]
@AlgoTrader could you close the issue?

**Comment by arturovt** [comment]
As I understand the #309 PR is related to this issue. This issue should have been closed.
