### ISSUE TITLE
No displays map values into state

### ISSUE THREAD

**Issue by mailok** [ngxs/store#314]
### Versions

```
* ngxs: 3.0.0-rc.1
* @angular/core: 5.2.9
```

### Repro steps

* Define my sate model:

```
export interface SharedModel {
    logged: boolean;
    user: UserModel;
    map: Map<string, MenuItemModel>;
}

```
* define my values by default in my state

```

const myMap = new Map<string, MenuItemModel>();
myMap.set('1', { name: 'INICIO', route: 'home', active: false, role: [Role.ALL] });
myMap.set('2', { name: 'TEST', route: 'test', active: false, role: [Role.ADMIN] });

@State<SharedModel>({
    name: 'shared',
    defaults: {
        logged: false,
        user: null,
        map: myMap
    }
})

```

* Run application

### Observed behavior

``` @ngxs/devtools-plugin ``` **No displays map values**

![captura](https://user-images.githubusercontent.com/3769277/38994195-ab083928-43b3-11e8-9d76-904791adb015.PNG)

### Desired behavior

**I would like to see map values**

**Comment by deebloo** [comment]
@mailok are the values correct but just not being displayed in devtools?

**Comment by mailok** [comment]
@deebloo they are well because the ```  "@ngxs/logger-plugin"``` show the values:

![captura](https://user-images.githubusercontent.com/3769277/38995841-d8fac482-43b7-11e8-8784-9fc5675404d0.PNG)

and my Selector:

```  
@Selector()
    static getMap(state: SharedModel) {
        return state.map;
    }
```

returns the values ​​correctly

**Comment by deebloo** [comment]
ok. I don't know if we can do anything then. The display in devtools isn't up to us it is up to the devtools plugin.

**Comment by tdeschryver** [comment]
Is it OK to put a `Map` in the store tho, since this isn't serializable?
I believe this is also the reason why the devtools can't show its value.

**Comment by LosD** [comment]
I had the same issue in ngrx. That was fixed when I changed to ImmutableJS' Map instead of ES6 Map. I guess it would be the same with NGXS. A nice side-effect is not having to worry about mutability.

In newer ngrx's I think they also made a way for custom serialization, so that DevTools can show the values. Maybe NGXS has the same?

**Comment by amcdnl** [comment]
You can use a custom serializer to handle these cases. Closing this since beyond that there is nothing we can do.
