### ISSUE TITLE
selectSnapshot() not working?

### ISSUE THREAD

**Issue by uberspeck** [ngxs/store#315]
### Versions

```
* ngxs: 3.0.0-rc.1
* @angular/core: 5.2.7
```

### Repro steps

On login I save the user's data to my state. I have confirmed the data is present (currentUser in this case) and i'm also using the `@ngxs/storage-plugin` so data is persisted. However, when I use `selectSnapshot` to retrieve it nothing is returned. What am I missing???

```typescript
@Component({
  selector: 'user-dashboard',
  template: `
    <h1>User Dashboard</h1>
    <pre>{{user|json}}</pre> <!-- user doesn't display here ??? -->
  `,
  styles: []
})
export class UserDashboardComponent {
  constructor( private store: Store ) { }
  // This getter never returns anything
  public get user(): User {
    return this.store.selectSnapshot<User>((state: AppStateModel) => state.currentUser);
  }
}
```

...and my state...
```typescript
export class SetCurrentUser {
  static readonly type = '[SET] current user';
  constructor(public payload: User) {}
}

export class AppStateModel {
  currentUser: User;
}

@State<AppStateModel>({
  name: 'app',
  defaults: {
    currentUser: null
  }
})
export class AppState {
  @Action(SetCurrentUser)
  public setUser({getState, patchState}: StateContext<AppStateModel>, {payload}: SetCurrentUser) {
    patchState({
      currentUser: payload
    });
  }
}
```

### Observed behavior

- No errors in the browser console.
- Current user data *IS* present in local storage!
- User data *NEVER* displays on the page!?!?

**Comment by deebloo** [comment]
I don't think you are looking in the correct place. try logging out the plain results from select snapshot. I am betting that everything is under 'app'. remember that each state class ends up adding a property to a root object.

**Comment by deebloo** [comment]
Your type is wrong. The type of "state" isn't app state model

**Comment by uberspeck** [comment]
Thanks for the feedback! I think I have enough to clean up my mess ;)

**Comment by deebloo** [comment]
Happy to help! Let me know if you need anything else
