### ISSUE TITLE
Http Requests - CRUD example?

### ISSUE THREAD

**Issue by ThomasLohmann** [ngxs/store#323]
Hi everyone,

where should I call my http service and CRUD methods, e.g. in the state class or best practices? Otherwise is it possible to update this repository: https://github.com/ngxs/store/tree/master/integration with an http CRUD example or put one under the recipes section? It would be very helpful.

Kind regards,
Thomas

**Comment by garthmason** [comment]
@ThomasLohmann - I asked a similar question yesterday on [StackOverflow](https://stackoverflow.com/questions/49974877/ngxs-actions-state-to-load-data-from-backend), @leon's answer there might be helpful.
Cheers,
Garth

**Comment by amcdnl** [comment]
@leon Perhaps we should put this in the docs under recipes?

**Comment by ThomasLohmann** [comment]
@amcdnl but please a full CRUD example with an http service, not just Get request.

**Comment by findjonmos** [comment]
@amcdnl Can it please also be a recipe showing how to handle errors

**Comment by JosepAlacid** [comment]
It would be really really helpful...

**Comment by guillospy92** [comment]
genial estaba buscando un ejemplo de estos gracias
