### ISSUE TITLE
Error in NativeScript With NGXS

### ISSUE THREAD

**Issue by abalad** [ngxs/store#344]
There are currently some issues related to using RXJS together with NativeScript.
https://github.com/NativeScript/nativescript-angular/issues/1201
https://github.com/NativeScript/nativescript-cli/issues/3290

They refer to the direct use / import of the rxjs modules from the root rxjs.

In my application I want to use NGXS but the following error occurs:

`System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: TypeError: document.createElement is not a function
System.err: File: "file:///data/data/com.otiseg.app/files/app/tns_modules/rxjs/util/Immediate.js, line: 56, column: 68
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'ImmediateDefinition.canUseReadyStateChange', file:'file:///data/data/com.otiseg.app/files/app/tns_modules/rxjs/util/Immediate.js', line: 56, column: 69
System.err: 	Frame: function:'ImmediateDefinition', 
`

What I analyzed was that NGXS uses in some modules the import by RXJS Root which causes the error in NativeScript applications:
https://github.com/ngxs/store/blob/6df236cdd63ff8ad2b814d2ab262c71c6df59ead/packages/store/src/actions-stream.ts#L2

**Comment by deebloo** [comment]
@abalad 3.0 requires rxjs 6.0+ and that is where those imports are. can you trying adding rxjs-compat in addition?

**Comment by amcdnl** [comment]
@abalad - Can you fill out the form w/ version details?

**Comment by abalad** [comment]
@deebloo I'm using version 2.1.0 of NGXS because NativeScript has not yet updated the version of Angular to 6

**Comment by abalad** [comment]
### Versions



```
* ngxs: 2.1.0-dev.e21e7fc
* @angular/core: ~5.2.0
```

### Repro steps



* Create a default NativeScript + Angular application
* Import the `NgxsModule.forRoot ([]`) from the `AppModule`
* Perform the NativeScript application build using the `tns run android `command

### Observed behavior

```
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: System.err: System.err: Error calling module function System.err: System.err: Error calling module function System.err: System.err: Error calling module function System.err: System.err: Error calling module function System.err: System.err: Error calling module function System.err: System.err: Error calling module function System.err: System.err: Error calling module function System.err: System.err: Error calling module function System.err: System.err: Error calling module function System.err: System.err: Error calling module function System.err: System.err: Error calling module function System.err: System.err: TypeError: document.createElement is not a function System.err: File: "file:///data/data/com.otiseg.app/files/app/tns_modules/rxjs/util/Immediate.js, line: 56, column: 68 System.err: System.err: StackTrace: System.err: Frame: function:'ImmediateDefinition.canUseReadyStateChange', file:'file:///data/data/com.otiseg.app/files/app/tns_modules/rxjs/util/Immediate.js', line: 56, column: 69 System.err: Frame: function:'ImmediateDefinition',
```

### Desired behavior
Initialize an application without error

### Mention any other details that might be useful (optional)
What I analyzed was that NGXS uses in some modules the import by RXJS Root which causes the error in NativeScript applications:
https://github.com/ngxs/store/blob/6df236cdd63ff8ad2b814d2ab262c71c6df59ead/packages/store/src/actions-stream.ts#L2

**Comment by deebloo** [comment]
hmmmm so that is the module things are supposed to come from with rxjs 6

**Comment by abalad** [comment]
What did you say? The problem is that NGXS uses an import of rxjs that if used with NativeScript generates this error. NativeScript does not have access to the elementary document as it works with DOM

**Comment by deebloo** [comment]
@abalad you said that the line ` import { Observable, Subject } from 'rxjs'; ` was causing problems with nativescript. that is the correct import path for rxjs 6.0

**Comment by abalad** [comment]
@deebloo Yes I understand. But even then the syntax for import might look like this:
Because this way only the modules in question are imported.
```
import { Observable } from "rxjs/Observable";
import { Subject } from "rxjs/Subject ";
```
Instead of only

```import { Observable, Subject } from 'rxjs';```

**Comment by alibahjat** [comment]
please help https://discourse.nativescript.org/t/error-when-run-app-in-android/7021/9

**Comment by splincode** [comment]
@abalad So, this issue is outdated?

**Comment by abalad** [comment]
So I'm going to test again on a new project that I'm going to start.

**Comment by splincode** [comment]
no news
