### ISSUE TITLE
Custom @Select()

### ISSUE THREAD

**Issue by estrellajm** [ngxs/store#355]
Hi @amcdnl,

I am trying to create a custom `@Select ()` to be able to drill down a particular tree and return the values dynamically. Getting either undefined or it's not making it (executing)

### user.component.ts
```
const location = 'new york'
@Select(state => UserState.getUserLocationSlots(state, location)) slots$;
```

### user.state.ts
```
@Selector() 
static getUserLocationSlots(state: UserStateModel, location: any) {
  console.log(state);
  console.log(location); // <-- expecting 'new york', but getting undefined
}
```

**Comment by leon** [comment]
Hey @estrellajm!
Could you please post this on stackoverflow instead, we are trying to use the issue tracker for bugs only :)

**Comment by estrellajm** [comment]
Ahh yes.. Thanks for the reminder. Please close. I’ll repost to Stackoverflow

Jose

On May 3, 2018, at 8:03 AM, Leon Radley <notifications@github.com> wrote:

Hey @estrellajm!
Could you please post this on stackoverflow instead, we are trying to use the issue tracker for bugs only :)
