### ISSUE TITLE
NgxsStoragePluginModule incompatible with lazy loading when you have a root state?

### ISSUE THREAD

**Issue by uberspeck** [ngxs/store#359]
### Versions
![39369472-9f67d47e-49f9-11e8-9b45-b12b0104e612](https://user-images.githubusercontent.com/857256/39639110-90ad6a34-4f85-11e8-92ad-942601a4fe00.png)

### Repro steps
Create a project ([stackblitz example](https://stackblitz.com/edit/ngxs-localstorage-lazyload)) with a root state and lazy loaded modules w/dedicated states

### Observed behavior
At least some of the lazy loaded modules will break (but not all) with the following error: `Error: undefined is not an object (evaluating 'local[k] = val[k]')`

If you comment out the `NgxsStoragePluginModule` the issue goes away and everything works as expected.

### Mention any other details that might be useful (optional)
This is sort of a duplicate of #194. But that example has no root state and the suggested workaround doesn't seem to apply when a root state is present.

**Comment by yarrgh** [comment]
An observation: If you load your second module first, it'll work but the first won't. If you load the first module first, the second won't work. Seems as if the first lazy module to load wins while the rest loose and error.

**Comment by yarrgh** [comment]
I was able to get your example to work by removing the `defaults` property from the `@State` decorator and instead using the `ngxsOnInit()` lifecycle event to initialize the state if it doesn't exist already (from localStorage). It works... most of the time. There's intermittent issues where, I assume, it sometimes doesn't set state correctly before the components try to grab the value.

Example: https://stackblitz.com/edit/ngxs-localstorage-lazyload-epaksq

**Comment by enewbury** [comment]
Pr to fix
https://github.com/ngxs/store/pull/628

**Comment by isc30** [comment]
any update on this?
