### ISSUE TITLE
Async action processing not happening

### ISSUE THREAD

**Issue by Dercetech** [ngxs/store#361]
```
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/compiler-cli": "5.2.9",
    "@angular/core": "5.2.9",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/pro": "1.0.17",
    "@ionic/storage": "2.1.3",
    "@ngxs/devtools-plugin": "3.0.0",
    "@ngxs/store": "3.0.0-rc.1",
    "angularfire2": "^5.0.0-rc.5-next",
    "firebase": "^4.13.1",
    "ionic-angular": "3.9.2",
    "rxjs": "5.6.0-forward-compat.3"
    "@angular/cli": "^1.7.4",
    "@ionic/app-scripts": "^3.1.9",
    "redux-devtools-extension": "^2.13.2",
    "typescript": "2.5.0"
```

### Repro steps

Considering the following State (bypassing the actual call to an auth service):

```
export class AuthenticationState {
  @Selector()
  static token(state: AuthenticationStateModel) {
    return state.token;
  }

  constructor(private _authService: AuthenticationService) {}

  @Action(Login)
  login(
    { patchState }: StateContext<AuthenticationStateModel>,
    { payload }: Login
  ) {
    // return this._authService.authenticate(payload).pipe(
    console.log('sync processing');
    return of('abc').pipe(
      tap(result => {
        console.log('async processing');
        patchState({ token: result });
      }),
      catchError(err => {
        console.log('async error');
        return null;
      })
    );
  }
}
```

* dispatch a "Login" action

### Observed behavior

* see that the console log "sync processing" is output
* see that the tap's logging of "async processing" doesn't show

### Desired behavior

* like the recipe book shows in the doc, I'm to return an observable, expect the Store to subscribe to it and have the tap contents be run.

### Mention any other details that might be useful (optional)

Can't reproduce on the stackblitz example even when using the same dependencies & versions.

Is there a "known" cause to returned observables not subscribed to?

**Comment by deebloo** [comment]
hmmmm so we had a problem with this a long time ago but I haven't seen it in quite a while

**Comment by Dercetech** [comment]
I'll just branch off and remove features one by one until... well, until it works and hope to pinpoint the root cause.

**Comment by Dercetech** [comment]
Damn, impossible to reproduce on stackblitz:
https://stackblitz.com/edit/ionic-ngxs

@deebloo do you remember what caused that?

**Comment by Dercetech** [comment]
Ok, it seems to be the following check in ngxs-store.js in the invokeAction function:

                            if (result instanceof Observable) {
                                result = result.pipe(((actionMeta.options)).cancelUncompleted
                                    ? takeUntil(actions$.pipe(ofActionDispatched(action)))
                                    : map(function (r) { return r; }));
                            }

"Uncaught ReferenceError: Observable is not defined"

So it doesn't enter the if statement. Let's see why Observable isn't known...

**Comment by juliusstoerrle** [comment]
I think I'm experiencing the same bug, while trying to reproduce a different one :)
If you are interested, if it helps: https://github.com/juliusstoerrle/repro-ngxs

**Comment by Dercetech** [comment]
**UPDATE**

This seems related to https://github.com/jashkenas/backbone/issues/1288

Not backbone, but the npm behavior. I made it so that the Observable from my app is returned to ngxs-store. They both have a different version of RXJS loaded in memory. Root cause is unkown, but doing myApp.Observable === Observable in ngxs-store.js gives "false".

It's npm related, not ngxs... gotta find how to solve this "caching" (or whatever it might be) issue.
