### ISSUE TITLE
ERROR in node_modules/@ngxs/store/src/internals.d.ts(7,5)

### ISSUE THREAD

**Issue by Royal-XL** [ngxs/store#362]
### Versions

```
* ngxs: 3.0.1
* @angular/core: 5.1.0
```

### Repro steps

* Step 1: `ng serve`
* Step 2
* Step 3

### Observed behavior

```
ERROR in node_modules/@ngxs/store/src/internals.d.ts(7,5): error TS1169: A computed property name in an interface must directly refer to a built-in symbol.

```
* Running `ng serve` to start up the project, throws that error and I end up not having the project served.
* I recently noticed after editing a file, webpack re-bundles the code and serves the application, but typescript still emits the error message.

**Comment by deebloo** [comment]
@Royal-XL what version of typescript are you using?

**Comment by Royal-XL** [comment]
@deebloo here is an update on the my environment.
### package.json 
```
* typescript: ~2.4.2
```
### yarn.lock
```
typescript@~2.4.2:
  version "2.4.2"
  resolved "https://registry.yarnpkg.com/typescript/-/typescript-2.4.2.tgz#f8395f85d459276067c988aa41837a8f82870844"

typescript@~2.6.1:
  version "2.6.2"
  resolved "https://registry.yarnpkg.com/typescript/-/typescript-2.6.2.tgz#3c5b6fd7f6de0914269027f03c0946758f7673a4"
```

**Comment by mkashifwk** [comment]
Royal-XL its i clearly mentioned in NGXS doc https://ngxs.gitbook.io/ngxs/getting-started/installation, that if you are using angular 6 then use ngxs 3.x if angular 5 use ngxs 2.x

`npm install @ngxs/store@2.0.0 -s` it worked for me :)

**Comment by Royal-XL** [comment]
Thank you @mkashifwk that solved the problem. Was so excited about the library to the extent that i did not notice the first paragraph at installation.
