### ISSUE TITLE
FEATURE: @Select() Parameter

### ISSUE THREAD

**Issue by estrellajm** [ngxs/store#367]
# Feature Request

Can you please add a feature that allows for the passing of parameters into the '@Selector'?

### from component.ts
```
site = {
  location: 'new_york',
  address: '42broadway'
}
@Select(UserState.getApartments(site)) apartments$
```

### from state.ts
```
@Selector()
static getApartments(state: UserState, site: any) {
  return state.user.locations.[site.location].sites.[site.address].apartments
}
```

This would then return that slice of the state.

**Comment by piernik** [comment]
I want it too ;)
Here is mine post: https://github.com/ngxs/store/issues/195

**Comment by xban1x** [comment]
I would have a use for this as well. It is a very nice way of how to sort through an array properly without needing to replicate the code in multiple components.

**Comment by markwhitfeld** [comment]
Please see how this can be achieved in the discussion here:
https://github.com/ngxs/store/issues/386#issuecomment-390181710

**Comment by amcdnl** [comment]
Closing as duplicate.
