### ISSUE TITLE
Binding to State - is this expected behaviour?

### ISSUE THREAD

**Issue by garthmason** [ngxs/store#368]
### Versions

```
* ngxs: 3.0.1
* @angular/core: 6.0.0
```

### Repro steps

I have a state that contains a collection of items:

```
import { State, Action, StateContext } from '@ngxs/store';
import {AddItem} from './app.actions';

export interface Item { 
  id: number;
  name: string;
}

export interface AppStateModel { 
   items: Item[];
}

@State<AppStateModel>({
  name: 'app',
  defaults: {
    items: []
  }
})
export class AppState { 

  @Action(AddItem)
  addItem(ctx: StateContext<AppStateModel>, action: AddItem){
     const state = ctx.getState();

        ctx.patchState({
            items: [
                ...state.items,
                { id: action.id, name: action.name}
            ]
        });
  }

}

```
My component is subscribed to the list of items in the store, when I add a new item that is reflected in the list displayed (all fine).

### Observed behavior

I then bind that displayed item to an `input` field - when I type in that input field I seem to be modifying the state of that item, i.e. the 'View Name' display of the item is also changing.

```
<ng-container *ngIf="app$ | async as app">

Name: <input #name />
<button (click)="addItem(name.value)">Add Item </button>

<br/>
<br/>

Items List:

<div *ngFor="let item of app.items">
  View Name: <span>{{item.name}}</span>
</div>

<br/>

Items List 2 with updates:

<div *ngFor="let item of app.items">
  Update Name: <input [(ngModel)]="item.name" />
</div>

</ng-container>
```

![image](https://user-images.githubusercontent.com/19699511/39798576-a9a09c48-5393-11e8-882b-180d50e09fc2.png)

### Desired behavior

Is this expected behaviour?  I was expecting that I would not see that change reflected in the 'view only' list. 

Or is this just a case of me doing something I shouldn't be - I know I should really be dispatching that change via an action to the store like this:

`Update Name: <input [ngModel]="item.name" (ngModelChange)="updateItem(item.name)" />`

```
updateItem(value) {
   this.store.dispatch(new UpdateItemAction(value));
}

```
### Mention any other details that might be useful (optional)

See full sample repo here https://github.com/garthmason/ngxs

Thanks!

**Comment by leon** [comment]
Please ask this question on stackoverflow instead.

https://stackoverflow.com/questions/tagged/ngxs

**Comment by garthmason** [comment]
Sure, thought this might've been a bug so posted it here first - i'll raise on SO now. Thanks.

**Comment by leon** [comment]
We keep tabs on stackoverflow, so if we conclude that the question is a bug, we can add it to github later :)

**Comment by garthmason** [comment]
No problem @leon  👍
