### ISSUE TITLE
Logger - an extra "next state" is printed outside the context of logger

### ISSUE THREAD

**Issue by un33k** [ngxs/store#374]
```
[x] Bug report
```

As per attached image, we get a "prev state", a "next state" and an extra "next state" which is not even collapsible.

### Versions

```
* ngxs: 3.0.1
* @angular/core: 6.0.0
```

### Repro steps

* Enable Logger Plugin
* Trigger some state actions
* View console

### Observed behavior

![screen shot 2018-05-10 at 3 19 43 pm](https://user-images.githubusercontent.com/407537/39889714-a386834e-5466-11e8-84c2-fe6889500dd3.png)

**Comment by amcdnl** [comment]
Oh that is fun. Does it happen all the time or only certain times?

**Comment by Thenis** [comment]
@amcdnl It happens when you subscribe to dispatch. The tap operator inside the logger plugin gets executed again.

**Comment by un33k** [comment]
@amcdnl It happens all the times for my use case
@Thenis yep, that could be it as I do subscribe to dispatch in places.

**Comment by amcdnl** [comment]
SRSLY?! I thought we had fixed this. This is issue is haunting me! @markwhitfeld - Any ideas?

**Comment by Thenis** [comment]
Found the issue. The compose function needed a shareReplay operator. Made a PR https://github.com/ngxs/store/pull/436

**Comment by eranshmil** [comment]
@un33k The PR fixed your issue?
