### ISSUE TITLE
Unit testing documentation

### ISSUE THREAD

**Issue by kctang** [ngxs/store#379]
I am having some issues with the example provided on [unit test](https://ngxs.gitbook.io/ngxs/recipes/unit-testing) page. Does not work for me.

This was from the docs (does not work):
```javascript
      it('it toggles feed', () => {
        store.dispatch(new FeedAnimals());
        store.selectOnce(state => state.zoo.feed).subscribe(feed => {
          expect(feed).toBe(true);
          // NOTE: i think at least need a "done()" here (and as param for this test function)
        });
      });
```

After some tweaking of my own, I got two versions working.

1. This works for me using async/await and `toPromise()` as needed:
```javascript
      it('it toggles feed with async/await', async () => {
        // await because dispatch may take a longer time.
        await store.dispatch(new FeedAnimals()).toPromise();
        const feed = store.selectSnapshot(state => state.zoo.feed)
        expect(feed).toBe(true);
      });
```

2. A single`subscribe()` for an Observable stream and `done()` to complete the asynchronous test (I think piping from `dispatch()` is optional, should we bother?):
```javascript
  it('it toggles feed without async/await', done => {
    store.dispatch(new FeedAnimals()).pipe(
      concatMap(() => store.selectOnce(state => state.zoo.feed))
    ).subscribe(
      feed => {
        expect(feed).toBe(true)
        done()
      }
    )
  })
```

I should also mention that my Angular project uses Jest for unit testing. The configuration was roughly based on [this article](https://medium.com/@nerdic.coder/how-to-use-jest-unit-tests-with-angular-87509b500158).

Q: So, any recommendation on whether we should use "async/await with toPromise()" or a "subscribe() with done()" for these unit tests? Or you recommend some other ways?

**Comment by amcdnl** [comment]
@deebloo - Can you help?

**Comment by deebloo** [comment]
the done does matter in this case. It will depend on your actions. by default observables are actually synchronous so if your action is async you may have to add your listener BEFORE you dispatch your action

**Comment by kctang** [comment]
I think you are referring to the fact that Actions in ngxs can make state changes via sync (direct state chain, plain reducer) or async (middleware, side-effects). In the case of sync, then we can just check state after the dispatch. This is what the demo unit test code does.

However, for async, we have to do something like my example above (either approach works).

My question was to seek recommended/best practice for unit testing ngxs actions with side-effects.

I suggest update the docs with separate sections to describe testing sync actions and async actions (i am not sure if these are the right terms ) scenarios to make it clear to new users.

**Comment by garthmason** [comment]
Yep, I'd agree with @kctang it'd be good to get a few more examples here, we've been having a little trouble here understanding how we should test these scenarios.
On the whole though we are finding the library easy to use, we've got two feature teams working with NGXS for the last few weeks, overall experience is very positive 😃

**Comment by deebloo** [comment]
Ok I understand better. Now. Maybe over the weekend I'll have time to throw in some unit testing recipes or something along those lines

**Comment by amcdnl** [comment]
I added some more unit testing docs. Feel free to PR anything you find valuable.

**Comment by eranshmil** [comment]
Just to let you know, I also had this issue and updating jest to version 23 solved it.
