### ISSUE TITLE
patchState is inconvenient for patching deep objects

### ISSUE THREAD

**Issue by AlgoTrader** [ngxs/store#381]
I write a lot of boilerplate code like this

```
   const state = context.getState();
    context.patchState({
      someForm: {
        ...state.someForm,
        model: {
          ...state.someForm.model, 
          someFlag: false
        }
      }
    });
```

What I would like to have is something like this:

```
context.patchStatePath(['someForm', 'model', 'someFlag'], false)
```

There should be some helper for deep updates. For now, I write a lot of redux-style immutability stuff

**Comment by markwhitfeld** [comment]
I am working on a built-in immutability helper that will help in this regard. I'll keep you posted.

**Comment by arjunyel** [comment]
Here's an Immer with NGXS article, hope this helps! https://blog.angularindepth.com/simple-state-mutations-in-ngxs-with-immer-48b908874a5e

**Comment by AlgoTrader** [comment]
Immer is exactly what I need.

**Comment by arturovt** [comment]
@AlgoTrader 

Currently we've got a lot of features that allow to reduce boilerplate code with `...` object descruction:

* [State operators](https://ngxs.gitbook.io/ngxs/advanced/operators)
* [immer-adapter](https://github.com/ngxs-labs/immer-adapter) (compatible with NGXS)

**Comment by akopchinskiy** [comment]
@markwhitfeld 
``ts
deepMerge<T, S>(target: T, source: S): T & S {
        for (let [k, v] of Object.entries(source)) {
            if (!(k in target))
                target[k] = source[k];
            else if (v instanceof Object)
                this.deepMerge(target[k], source[k]);
            else
                target[k] = source[k];
        }

        return target as T & S;
    }
``

**Comment by mattbodman** [comment]
> Here's an Immer with NGXS article, hope this helps! https://blog.angularindepth.com/simple-state-mutations-in-ngxs-with-immer-48b908874a5e

broken link now :(

**Comment by kuncevic** [comment]
> > Here's an Immer with NGXS article, hope this helps! https://blog.angularindepth.com/simple-state-mutations-in-ngxs-with-immer-48b908874a5e
> 
> broken link now :(

That is the one https://medium.com/angular-in-depth/simple-state-mutations-in-ngxs-with-immer-48b908874a5e
