### ISSUE TITLE
Composing Selectors

### ISSUE THREAD

**Issue by bmayen** [ngxs/store#382]
This was brought up already in https://github.com/ngxs/store/issues/117. The question is, how do we create `@Selectors` composed from other `@Selectors` as is common with Reselect and in Ngrx? It was suggested we create a parent state which then uses the child state Selectors.

I was wondering if we could get a little more feedback and usage examples on this. For example, what would be the best practice if you have two lazy-loaded features and a third feature needs to select something composed from their states? Where should this "parent" state live? Under 'shared/state'?

Is there potentially a way to do this without having to create parent states for every composition you have in the app? Perhaps a `@ComposedSelector` which could handle that wiring under the hood?

**Comment by juliusstoerrle** [comment]
This is possible with the latest dev versions, see https://www.screencast.com/t/MI3XGssXCoC

**Comment by bmayen** [comment]
Well, that was easy :)

Can I assume from that screenshot that you can pass multiple states into the selector array and they will be available via additional parameters of the static function?

**Comment by juliusstoerrle** [comment]
Yes, you can.
(https://ngxs.slack.com/archives/CA0NS79MG/p1525758845000222?thread_ts=1525705717.000244&cid=CA0NS79MG)

**Comment by bmayen** [comment]
Terrific! Will go ahead and close this and look forward to its release!
