### ISSUE TITLE
WebSocket - reconnect was removed

### ISSUE THREAD

**Issue by boulix3** [ngxs/store#384]
Hello,
The reconnect function was removed from the [WebSocketSubject](https://github.com/ngxs/store/blob/master/packages/websocket-plugin/src/websocket-subject.ts) class, see #341 

The documentation and the [NgxsWebsocketPluginOptions](https://github.com/ngxs/store/blob/master/packages/websocket-plugin/src/symbols.ts) class still contain these properties : 
- reconnectInterval: Interval of which to reconnect if the client is disconnected. Default: 5000
- reconnectAttempts: Number of times before giving up on connection retries. Default: 10

Is this functionality definitely dropped (needs docs update)?

Thank you

**Comment by amcdnl** [comment]
removed from docs.
