### ISSUE TITLE
Actions subscribe called twice

### ISSUE THREAD

**Issue by perjansson** [ngxs/store#391]
### Versions

```
* ngxs: 3.0.1
* @angular/core: "6.0.2
```

### Observed behavior

I have a Service that subscribes to certain actions. After updating Angular, RXJS and NGXS the subscribe function is now called twice for each action.

```
@Injectable()
export class NotifierService {
	constructor(private actions: Actions) {
		this.actions
			.pipe(
				ofAction(
					LoginFailure,
					RequestSearchResultSuccess,
					RequestPersonSuccess,
					InputVideoUrlsInvalid,
				),
			)
			.subscribe((event: any) => {
				const { payload } = event

				switch (event.constructor) {
					case LoginFailure:
						this.notifyError(payload) <--- This notification is trigger twice since two events where received by subscribing function
						break
...
```

### Desired behavior
It should only be called once

**Comment by amcdnl** [comment]
You have to use `ofActionCompleted`, everything will get piped across this.

**Comment by perjansson** [comment]
Thx that works,

One note thought since the docs seems to not be consistent. It's be called ofActionSuccessful in advanced/action-handlers documentation but it's called ofActionCompleted​ in api/of-action documentation.

**Comment by Timon0305** [comment]
I used subscibe for showing action changing but I got action twice

  this.getStakeStatus.subscribe((res) => {
      if (res.swapStatus && res.reference === this.componentName) Popup(this);
    });

this is running twice
