### ISSUE TITLE
Actions dispatched from within another action triggers multiple calls in the inner action call

### ISSUE THREAD

**Issue by sanjeev-roughshod** [ngxs/store#395]
@Action(InitializeCoreState)
    initializeCoreState(ctx: StateContext<any>, action: InitializeCoreState) {
        ctx.dispatch(new SetConfig(action.payload)); // this action is triggered twice
    }

When I dispatch InitializeCoreState action from components/services, it calls SetConfig action twice because it is nested under the InitializeCoreState action.

**Comment by markwhitfeld** [comment]
@sanjeev-roughshod Is it possible to reproduce this with a stackblitz for us?
(You can use [this](https://stackblitz.com/edit/ngxs-simple) as a starting point if you like)

**Comment by sanjeev-roughshod** [comment]
@markwhitfeld Here's the demo 
https://stackblitz.com/edit/ngxs-simple-6fqip4
Also, please read my comment in the app.module.
I am using the NGXS 3.0.1 version.

**Comment by junraemon** [comment]
I think this happens because you extend the CountState to ParentState

**Comment by sanjeev-roughshod** [comment]
@junraemon 
It's not related to extending but rather related to declarations. See the following code snippet

**@NgModule({
  imports:      [ BrowserModule, 
  NgxsModule.forRoot([CountState, ParentState]) 
  ], // Note: If I remove ParentState from the array list, it works fine. If this is the expected behaviour then please elaborate this.
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }**


I believe this is a bug.

Can anyone from the official team comment on this please?

**Comment by leon** [comment]
The parent state should not be included in the list of states.
It's included for you when you add the CountState.

What it does behind the scenes is walk the prototype chain and add all actions that are available upp the chain.

So if you simply remove ParentState from the list, the app works as it should. (as you said).
