### ISSUE TITLE
Selecting snapshot using Selectors

### ISSUE THREAD

**Issue by piernik** [ngxs/store#402]
Is it possible to select snapshot from store using `@Select()` decorator?
If not maybe You can introduce new decorator `@SelectSnapshot()`  which is working as `@Select()` but returns snapshot not observable?

**Comment by amcdnl** [comment]
No and no plans to. It’s not really compatible with our mental model.

**Comment by piernik** [comment]
If I can :)

I think it will be very useful. Store is a source of truth so I put there my config. Config is not going to change. So snapshot feature is very useful.

I'm creating `@Selectors` for almost everything. Why? If I change store model (and I do it a log at the beggining of creating app) I simply need to only modify `@Selectors` and that's it. No need to filter my code for changed parts.

I hope You reconsider.
