### ISSUE TITLE
Module not found: Error: Can't resolve 'deep-freeze-strict' in '...../node_modules/@ngxs/store/fesm5'

### ISSUE THREAD

**Issue by gitkumi** [ngxs/store#412]
Angular version: 6.0.3
ngxs: 3.1.0
rxjs: 6.1
rxjs-compat: 6.1
typescript: 2.7.1

**Comment by mflorence99** [comment]
Likewise. I ran `npm i -S deep-freeze-strict` manually and I appear to be building and executing correctly.

**Comment by gitkumi** [comment]
Thanks. That solved my problem.

**Comment by piernik** [comment]
The same problem - solution works

**Comment by amcdnl** [comment]
Fixed in 3.1.1
