### ISSUE TITLE
[router plugin] Expose RouterStateModel

### ISSUE THREAD

**Issue by piernik** [ngxs/store#417]
I think it's good idea to expose to outer world `RouterStateModel`.
I want to define `AppStateModel` and I want to define `router` part with proper model.

Now I can import it only with `import {RouterStateModel} from '@ngxs/router-plugin/src/router.state';`

**Comment by amcdnl** [comment]
It is exposed - https://github.com/ngxs/store/blob/master/packages/router-plugin/index.ts#L2

**Comment by piernik** [comment]
It is `RouterState` - not `RouterStateModel`
