### ISSUE TITLE
[router plugin] expose most needed parts

### ISSUE THREAD

**Issue by piernik** [ngxs/store#418]
Is it possible to expose most needed parts of `RouterStateSnapshot` ?
Like `queryParams`, `params`, `data` and so on? 
It could be very helpfull.
Now it's easier to use `route: ActivatedRoute` in constructor than store itself.

Edit:
I know why it's not that easy. You pass `root` route - not current. That's why I have to dig in to get propper params, data or queryParams.

**Comment by amcdnl** [comment]
I'm not sure I understand your question.

**Comment by piernik** [comment]
You have in store only `root` route part. I hope to see `params` or `data` or `queryParams` so I could use `this.routeData = this.store.select(state => state.router.data);`

**Comment by rweng** [comment]
Maybe @piernik wants the `RouterState` to listen to all routes data changes and put the data in the state.

@piernik dunno if it helps, but I use a separate `RouteDataState` for now:

```ts
import { ActivatedRoute, NavigationEnd, Router } from '@angular/router';
import { Action, State, StateContext } from '@ngxs/store';
import { Store } from '@ngxs/store';
import { filter, map, mergeMap } from 'rxjs/operators';

export class DataChanged {
  static readonly type = '[route data] changed';
  constructor(public data: any) { }
}

@State<string>({
  name: 'routeData',
  defaults: undefined
})
export class RouteDataState {
  constructor(private router: Router, private store: Store, private _route: ActivatedRoute) {
    this.subscribeToDataChanges();
  }

  @Action(DataChanged)
  async changeRoute(context: StateContext<string>, action: DataChanged) {
    context.setState(action.data);
  }

  private subscribeToDataChanges() {
    this.router.events.pipe(
      filter(event => event instanceof NavigationEnd),
      map(() => this._route),
      map(route => {
        while (route.firstChild) { route = route.firstChild; }
        return route;
      }),
      filter(route => route.outlet === 'primary'),
      mergeMap(route => route.data)
    )
      .subscribe(d => {
        this.store.dispatch(new DataChanged(d));
      });
  }
}
```

**Comment by herkulano** [comment]
I think what @piernik wants is something like this: https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#custom-router-state-serializer

Instead of having the raw router object getting only the router url, params, etc.

@amcdnl is it possible to add a CustomRouterStateSerializer in ngxs right now? If so how?

**Comment by amcdnl** [comment]
#462 closes this, exports the sreializer so you can override via DI.
