### ISSUE TITLE
[Feature Request] Using global state in Selectors

### ISSUE THREAD

**Issue by piernik** [ngxs/store#419]
I have an real life example.

I'm using Your router plugin. I have store with entities ex: companies

	@State<CompaniesStateModel>({
	  name: 'companies',
	  defaults: {
		loaded: false,
		loading: false,
		list: [],
		entities: {},
	  }
	})
	export class CompaniesState {
	}

I want to create and `@Selector` that will fetch company details according to url path `companies/1`

	export class CompaniesDetailComponent {
		@Select(CompaniesState.details)
		company$;
	}

I believe now it is not possible. In `@Selector` You cannot pass different state that `CompaniesState` - I need `router` part.

`Selectors` are static so I cannot use `this` in it and therefore use imported `store`.
Is it possible to fix this problem to strip boilerplate?

**Comment by juliusstoerrle** [comment]
Not sure if I understood your problem correctly, but can't you use:

```
 @Selector([RouterState.state])
  static details(state: CompanieStateModel, route) {
    return state.entitities[route.params.companyId];
  }
```

**Comment by piernik** [comment]
Oh! it's working - great. Thanks
