### ISSUE TITLE
[router plugin] Own serializer

### ISSUE THREAD

**Issue by piernik** [ngxs/store#421]
I see that router plugin uses default serializer: https://github.com/ngxs/store/blob/master/packages/router-plugin/src/serializer.ts

Is it possible to make own one and provide it? Can You give an example?

Why do I need own serializer?
Default serializer uses `RouterStateSnapshot.root`. But at root there is no for example `params` attribute. I mean, there is one but it's from `root` path - not current one.

I need to use current state `params` which are very useful using `paramsInheritanceStrategy: 'always'` (https://kimsereyblog.blogspot.com/2018/02/params-inheritance-strategy-with.html)

**Comment by amcdnl** [comment]
Provide it via DI just like any other DI override.

```
 providers: [{ provide: RouterStateSerializer, useClass: DefaultRouterStateSerializer }]
```

**Comment by amcdnl** [comment]
I'm good w/ exporting it if you want to make a PR.

**Comment by arutkowski00** [comment]
#462 makes it possible 👍

**Comment by piernik** [comment]
@amcdnl when solution will be official?

**Comment by alterx** [comment]
@piernik it looks like this works already. You can do:

```
import {
  NgxsRouterPluginModule,
  RouterStateSerializer
} from "@ngxs/router-plugin";
import { CustomSerializer } from "./store/router.serializer";
```

and then 

```
@NgModule({
  ...
  providers: [{ provide: RouterStateSerializer, useClass: CustomSerializer }],
  ...
})
export class AppModule {}
```

**Comment by piernik** [comment]
I did it already with 3.2
