### ISSUE TITLE
Built-in support for compression and encryption for storage plugin

### ISSUE THREAD

**Issue by kctang** [ngxs/store#424]
While the storage plugin is awesome to get persistent state, it would be more feature complete with **built-in support** for:

- compression
- encryption

Something like this would be great:

```
NgxsStoragePluginModule.forRoot({
  key: [ ... ],
  compression: true,
  encryption: true
})
```

For now, to get compression is very easy but we need to include dependency to libraries (e.g. I used `lz-string` along with its type definition `@types/lz-string`).

```
import LZString from 'lz-string'

...
      deserialize: data => JSON.parse(LZString.decompress(data)),
      serialize: data => LZString.compress(JSON.stringify(data))
...
```

I have not done the encryption part but my client will likely need it too.

Reasons (I think these are pretty common use case, both in enterprise apps and general Internet apps):

- Encryption: If we persist state, we do not hackers to tinker with the data.
- Compression: Even when picking specific keys (and sub-keys) to persist, I am storing quite a lot of data.

**Comment by zygimantas** [comment]
I see no point of encrypting local storage because the decryption key will easily accessible (because it's in client side code on load or any other moment) and if you don't trust browser security, not much may be done.
I can't disagree on compression, there may be use cases when 5MB is not enough.

**Comment by kctang** [comment]
It is true that encryption for local storage is easily compromised. As for compression, well I guess we can reference this thread if someone needs a simple solution.

Thanks for taking the time to feedback on this! Will close this ticket. :-)

**Comment by juliusstoerrle** [comment]
Maybe you can create your own plugin with the decompression feature witch in turn registers the StoragePlugin and share it with the community. I believe taking in this feature in to the main Plugin with a specific algorithm would be too opinionated.
