### ISSUE TITLE
@ngxs/form-plugin State changes every time a form action is dispatched

### ISSUE THREAD

**Issue by maxencefrenette** [ngxs/store#429]
### Versions

```
* ngxs: 3.1.3
* @angular/core: 6.0.3
```

### Repro steps

* Load any app using @ngxs/form-plugin
* Interact with the form

### Observed behavior

The state changes after each form action, which retriggers all selectors and rerenders components that depend on them.

### Desired behavior

For performance reasons, the state should only change identity when it actually changes.

### Mention any other details that might be useful (optional)

Sorry, I didn't take the time to create a stackblitz, but this issue is visible straight from the [code](https://github.com/ngxs/store/blob/master/packages/form-plugin/src/form.plugin.ts). As you can see, when an action such as `UpdateFormDirty` is dispatched, the state is updated even if the value of the `dirty` flag didn't change. This is horrible for performance and can easily fixed. I am willing to work on a PR if needed.

**Comment by amcdnl** [comment]
If you have some ideas how to fix, feel free to PR them :)

**Comment by maxencefrenette** [comment]
I played with it for a bit and I see two solutions non mutually exclusive improvements that can be made. It's not perfect, but let's just say the way Angular handles forms is not made for a Flux achitecture :stuck_out_tongue: .

First would be adding a check on `setValue()` so that it only modifies the value if it has changed. This would make the amount of selector reevaluation go down accross the board. It may cause wierd inconsistencies though. Maybe make a `setValueIfChanged()` helper ?

Second would be to dispatch one UpdateForm action instead of dispatching multiple actions. This would also have the benefit of uncluttering the devtools. However, to do that, we would need to either modify the semantics of `UpdateForm` or make a new action type.

Toughts ?

**Comment by amcdnl** [comment]
I think option 2 sounds better. I've always wanted to do that anyways.

**Comment by xban1x** [comment]
I noticed that with async validators you keep retrigerring them.

**Comment by xban1x** [comment]
In its current form the plugin is unusable with async validators.

**Comment by markwhitfeld** [comment]
@maxencefrenette Please could you confirm that this is fixed with the v3.5.1 release and close the issue.

**Comment by markwhitfeld** [comment]
@xban1x Could you also test?

**Comment by markwhitfeld** [comment]
Closing issue. Please reopen if it is not fixed.
