### ISSUE TITLE
Subscribe to a dispatch never returns an error

### ISSUE THREAD

**Issue by ufoscout** [ngxs/store#430]
### Versions
```
* ngxs: 3.0.1
* @angular/core: 6.0.2
```

### Repro steps
I have an action that calls a loginService that perform an http call to the server:
```
  @Action(events.Login)
  login({ getState, setState }: StateContext<AuthStateModel>, {payload}: events.Login) {
    return this.loginService.login(payload).pipe(
      tap(response => {
        console.log("[ActionLogin] OK");
      }),
//      catchError(err => {
 //       console.log("[ActionLogin] error in the action");
  //      return of(err);
   //   })
     );
  }
```
In a component I dispatch the Login Action and subscribe to it:
```
  submitLogin(): void {
    this.store
      .dispatch(new Login(this.model))
      .subscribe(value => {
        console.log("Success");
        console.log(value);
      },
      err => {
        console.error('Error:', err.message);
      },
      () => {
        console.log(`We're done here!`);
      });
  }
```
### Observed behavior
When the http call fails or returns an error code, the subscription to the dispatch enters in the "success" callback and prints "Success", however, the "value" object is the error thrown by the service call.
I expected that the "error" callback was called instead of the "success" one.

Another strange behavior is that, if in the action code I uncomment the "catchError" block, then again the dispatch subscription "success" callback is called, but the "value" object is now the State instead of the error.

### Desired behavior
I expected the error callback to be called.

**Comment by juracy** [comment]
@ufoscout I believe this issue was fixed in 3.1.0 release! Update it!

**Comment by juracy** [comment]
Issue #376

**Comment by ufoscout** [comment]
@juracy 
Indeed it works as expected in 3.1.3. Nevertheless, I cannot upgrade due to #415 :(

**Comment by juliusstoerrle** [comment]
Have you tried? because in my app I did not notice any problems with change detection with the new version

**Comment by amcdnl** [comment]
Closing as its working. @ufoscout - Can you provide details why its not working for you in 415?
