### ISSUE TITLE
Data of a dispatched action

### ISSUE THREAD

**Issue by paulstelzer** [ngxs/store#433]
I have the following Action in my state class:

```
  @Action(LoginWithGoogle)
  async loginWithGoogle(ctx: StateContext<AuthStateModel>): Promise<any> {
    try {
      const provider = new firebase.auth.GoogleAuthProvider();
      const response = await this.afAuth.auth.signInWithPopup(provider);
      if (response) {
        ctx.dispatch(new LoginSuccess(response.user));
        return response;
      }
    } catch (error) {
      console.log('Error Login', error);
      ctx.dispatch(new LoginFailed(error));
    }
    return false;
  }
```

If I am now dispatch this action and subscribe to the return value, I always get the complete store state as value

    this.store.dispatch(new LoginWithGoogle()).subscribe((data) => {console.log('Data', data)})

Is this a bug or standard? My intention was to get the response as return value or false (if it fails)

**Comment by Thenis** [comment]
You are subscribing to the whole state stream. Look into action handlers https://ngxs.gitbook.io/ngxs/advanced/action-handlers

**Comment by amcdnl** [comment]
Yes, this is expected. There is no way to return the result of that data since it could be handled by multiple outlets.

**Comment by amcdnl** [comment]
I'd suggest piping a select in the dispatch subscribe.
