### ISSUE TITLE
Action not subscribing 

### ISSUE THREAD

**Issue by treveshan** [ngxs/store#434]
Hi Guys

If this is the wrong forum for this problem please direct me to the correct one.

It seems when i dis patch an action that does an async its not subscribing therfore its not hitting my API. Is this normal ? 

Below is the code 

`  @Action(GetDevicePools)
  GetDevicePools({ getState, patchState, dispatch }: StateContext<DevicePoolStateModel>, { }: GetDevicePools) {
    const state: DevicePoolStateModel = getState();
    this._devicePoolService.getAllDevicePools()
      .pipe(
        tap((devicePools: DevicePool[]) => {
          patchState({ devicePools: devicePools });
        })
      );
  }`

From component: 
`  this._store.dispatch(new GetDevicePools());
`

API service:
`
  getAllDevicePools(): Observable<DevicePool[]> {
    return this._http.get<DevicePool[]>(`${this.API_URL}/api/devicepool`).pipe(
      map(this.extractDataObject),
      map(this.transformDevicePoolFromApiIntoDevicePoolArray)
    );
  }
`
I'm using @NGXS V3.1.3 

Angular CLI: 6.0.3
Node: 8.11.2
OS: win32 x64
Angular:

@angular-devkit/architect    0.6.3
@angular-devkit/core         0.6.3
@angular-devkit/schematics   0.6.3
@schematics/angular          0.6.3
@schematics/update           0.6.3
rxjs                         6.1.0
typescript                   2.7.2

**Comment by amcdnl** [comment]
You have to subscribe to `this._devicePoolService.getAllDevicePools()`. This is the case for any observable.
