### ISSUE TITLE
Redux DevTools. Actions created from the Monitor are ignored

### ISSUE THREAD

**Issue by gsans** [ngxs/store#440]
Versions
* ngxs: 3.1.3
* angular/core: 6.0.4
* Redux DevTools: 2.15.2

Repro steps
Developing a minimal app to demonstrate ngxs I realised I couldn't dispatch actions from Redux DevTools. 
https://stackblitz.com/edit/ngxs-spinner?file=src%2Fapp%2Fapp.module.ts

Observed behavior
The Redux DevTools seems to ignore any Actions created from the Monitor. Eg:
`{
  type: '[Toggle] Hide'
}`

Desired behavior
Redux DevTools should be able to dispatch Actions created from the Monitor.

**Comment by Thenis** [comment]
Works if you dispatch the action as a JSON object

**Comment by gsans** [comment]
Did you even tried? I just did and... it doesn't work @Thenis

**Comment by Thenis** [comment]
@gsans Yes I tried it on my own project and yours. 
![image](https://user-images.githubusercontent.com/13870239/41397276-5ebd6b62-6fbc-11e8-9eee-3da83b19476b.gif)

**Comment by amcdnl** [comment]
Closing.

**Comment by gsans** [comment]
Not so quick. Still fails but now I can see the problem. It seems it doesn't accept new lines.

```
{ 
  "type": "[Toggle] Hide"
}
```

**Comment by amcdnl** [comment]
It shouldn't matter whether its multi-line or not. If thats true, then its more likely devtools than us. We are working on our own dev tools so this will be deprecated soon.

**Comment by denu5** [comment]
It's still necessary to write without new lines. Without finding this issue I would know why/how. thx @gsans
