### ISSUE TITLE
ctx.getState() returns undefined

### ISSUE THREAD

**Issue by tfiwm** [ngxs/store#442]
I have a @Action which has a simple patchState function inside 

```typescript
@Action(SetSomething)
  setSomething(ctx: StateContext<MyStateModel>, action: SetSomething) {
    const state = ctx.getState();
    ctx.patchState({
      data: {
        ...state.data,
        something: action.something
      }
    });
  }
```

i want to test this now with a unit test ->

```typescript
it('it should set something', () => {
    store.selectOnce((state: MyStateModel) => state.data.something).subscribe(something => {
      console.log('something prev', something); // -> returns the correct value which is set in beforeEach store.reset...    });
    store.dispatch(new SetSomething('some something value'));
    store.selectOnce((state: MyStateModel) => state.data.something).subscribe(something => {
      expect(something).toBe('some something value');
    });
  });
```
It crash already because it can't find data inside state because state is undefined -> ctx.getState()

### Versions

```
* ngxs: 3.1.3
* @angular/core: 6.0.1
```
### Observed behavior

ctx.getState() returns undefined

### Desired behavior

ctx.getState() returns the current state

**Comment by tfiwm** [comment]
I found the problem... so for every one who is using Store.reset() function! It is really important to add the state  'Name' scope around it!

means: if my state has the name 'myStateName' than you need to wrap it around like this:

```
store.reset({
   myStateName: OVERRIDE_DEFAULTS
})
```

Yes it is written like this in the documentation if you take the example as whole picture -> maybe it would be nice to mention it in the docu at this place more.

**Comment by michael-brade** [comment]
Really, this should be *explicitely* documented here: https://ngxs.gitbook.io/ngxs/concepts/store#reset I lost a few hours on this :(

**Comment by Justinapeldoorn** [comment]
@MitkoTschimev still saving people in 2020.  I also feel like this should be documented beter, especially here as well: https://www.ngxs.io/recipes/unit-testing#prepping-state

**Comment by MitkoTschimev** [comment]
#1614 maybe this could help?
Please review everyone if it is understandable
@Justinapeldoorn @michael-brade

**Comment by michael-brade** [comment]
@MitkoTschimev good! I would probably have written `store.reset({ stateName: MyNewState })`, similar what you wrote in your comment. Just to make it obvious on first read :-)
