### ISSUE TITLE
A Map type contained in the state is not frozen in dev mode

### ISSUE THREAD

**Issue by lyon-liao** [ngxs/store#444]
I get a state by `selectSnapshot` and I added a  additional property to the Object, The Action is pass in effect. 
```
const labelsMap = this.store.selectSnapshot(state => state.label.labelsMap)
const labels = labelsMap.get('xxx')
labels[0].checked = true
```
The state changed, look from the log tool.

**Comment by markwhitfeld** [comment]
I suspect that the Object.freeze functionality does not freeze the Map type. It is mainly focused on preventing writing to properties. Do you have the same issue if you don't use a Map but rather use an object as a hash map?

**Comment by amcdnl** [comment]
@lyon-liao - Did you turn on dev mode on the store?

**Comment by lyon-liao** [comment]
@markwhitfeld You are right. So, This issue cause of `Object.freeze functionality does not freeze the Map type`.

@amcdnl  I had turn on the dev mode, And work well most of place, except the Map type.

**Comment by markwhitfeld** [comment]
I corrected the issue name to more correctly reflect the issue.
@amcdnl Do you think that we need to do anything about freezing the Map type or is this working as intended. `Object.freeze` does not support freezing these higher order data containers, but do you think we need to? Might be a bit tricky to get right.

Also, is it recommended to use anything other than plain js structures in the state?

**Comment by amcdnl** [comment]
I would say shy away from using anything but plain js structures in the state. It will cause immutability issues, etc.
