### ISSUE TITLE
Problem with state composition

### ISSUE THREAD

**Issue by foralobo** [ngxs/store#446]
```
* ngxs: 3.1.4
* @angular/core: 6.0.1
```

Hi, I have a request for you masters...

I tried to create a simple EntityAdpter class to use the Entity feature on ngxs. It works fine:
my store has the properties "entities" and "ids".

I have a problem: when I want return a composition of the two properties 
```
  @Selector()
  static orders(state: OrdersStateModel) { 
    return [...state.ids].map(id => state.entities[id]);
  }
```
it returns correctly but everytime I call a setState() on some other state property (different from ids and entities), the observable on this Selector intercepts a new value of "orders".

I think it is the right behavior of @Selector because I'am returning a completely new array!!
I'm resolving this problem so (for brevity I hide the entitydapter class):
```
// state
@Selector()
static ids(state: OrdersStateModel) {
  return state.ids
}

@Selector()
static entities(state: OrdersStateModel) {
  return state.entities
}

...

// container

@Select(OrdersState.ids) ids$: Observable<string[]>;
@Select(OrdersState.entities) entities$: Observable<any[]>;
// on init
this.elements = this.entities$.pipe(
  withLatestFrom(this.ids$),
  map(([ent, ids]) => {
    return ids.map(id => ent[id]);
  })
);
this.elements.subscribe(data => console.log('example', data));
```
I know it is very ugly, but I'am asking, is there a more elegant mode to workaround this?
I don't know, a mode to do the "withLatestFrom" inside the state...

Thank you very much..and thank you for your work.

**Comment by foralobo** [comment]
Another possible solution is to use a child state to manage the entities operations. So we can divide the use of the two states.

I would like a decorator called @EntityState that it manages the state like an entities state.

**Comment by markwhitfeld** [comment]
You could combine those selectors using a meta selector. 
See this: https://ngxs.gitbook.io/ngxs/concepts/select#meta-selectors 
The selector would need to be defined on a non state class.

**Comment by foralobo** [comment]
I tested meta selector but it not returns values. It returns undefined (I used the example in the ngxs documentation)

**Comment by markwhitfeld** [comment]
@foralobo is it possible for you to post a Stackblitz sample?

**Comment by foralobo** [comment]
Ok It was a my error: It not worked because I was testing with an old version of store (3.0.1)
With 3.1.4 it works but it is not that i want. Every time I dispatch on the incriminated state, it send a value and my Select intercept it.

I need to do a withLatestFrom between two states properties in the state, but all this should be as a @Selector to compose a new object only if one of the two is changed.
I don't know if it is possibile.

For now I resolved making a withLatestFrom in the container (having as source two properties from @Select) or creating a separate state where I put only the properties I wand combine.

**Comment by amcdnl** [comment]
Closing per discussion.
