### ISSUE TITLE
[Question] Abandon action classes

### ISSUE THREAD

**Issue by piernik** [ngxs/store#452]
In components I don't want to use any external dependencies (no hard feelings, Your store is great:) ).
That's why I create in `state` folder `state.selectors` and `state.actions` files.
Both files are `services` that are injected to components ans uses Your store.
Example:
```
@Injectable({
  providedIn: 'root'
})
export class CoreSelectors {
  constructor(private store: Store) {
  }

  leftSidenavOpened(): Observable<boolean> {
    return this.store.select((state: AppStateModel) => state.core.leftSidenavOpened);
  }

  rightSidenavOpened(): Observable<boolean> {
    return this.store.select((state: AppStateModel) => state.core.rightSidenavOpened);
  }
}
```

```
@Injectable({
  providedIn: 'root'
})
export class CoreActions {
  constructor(private store: Store) {
  }

  toggleLeftSidenav() {
    this.store.dispatch(new CoreToggleLeftSidenav());
  }

  toggleRightSidenav() {
    this.store.dispatch(new CoreToggleRightSidenav());
  }
}
```

Thing is that I have to declare always `action classes`, which is not necessary boilerplate to me:
```
export class CoreToggleLeftSidenav {
  static readonly type = '[Core] Toggle left Sidenav';

  constructor() {
  }
}

export class CoreToggleRightSidenav {
  static readonly type = '[Core] Toggle right Sidenav';

  constructor() {
  }
}
```
Is there a solution that I could do something like this?
```
  toggleLeftSidenav() {
    this.store.dispatch({type:  '[Core] Toggle left Sidenav', payload: {}});
  }
```
How to use it in `state` files?
```
  @Action(CoreToggleLeftSidenav)
  toggleLeft(ctx: StateContext<CoreStateModel>) {
    ctx.patchState({leftSidenavOpened: !ctx.getState().leftSidenavOpened});
  }
```

**Comment by leon** [comment]
No action classes are needed.
Though you don't need an empty constructor in them.
also there is a good visual studio code extension called Angular 6 Snippets which has some great snippets for ngxs which helps when writing them.

**Comment by piernik** [comment]
I've tried something like this:
```
  @Action(null)
  toggleLeft(ctx: StateContext<CoreStateModel>) {
    ctx.patchState({leftSidenavOpened: !ctx.getState().leftSidenavOpened});
  }
```
It's not working: `TypeError: Cannot read property 'type' of null`. So You need to pass class to `@Action` decorator. Is there a workaround?
