### ISSUE TITLE
Dispatch an action on first @Select use

### ISSUE THREAD

**Issue by ufoscout** [ngxs/store#454]
Is it possible to dispatch an action when a @select is used for the first time?
The use case is to lazily fill the state (fetching some data from the server) only when the data itself is selected for the very first time and to serve it from the state if already fetched.
If already possible, would it be possible to provide in the documentation an example of how to fetch the data only once?

**Comment by markwhitfeld** [comment]
In short, no that is not possible or recommended.
I would say that a better way to handle this would be to dispatch an action requesting the load of the data from the Angular [OnInit](https://angular.io/api/core/OnInit) method to achieve the same result.
