### ISSUE TITLE
storage-plugin > Can't use duplicated key word for deeply nested key

### ISSUE THREAD

**Issue by GreenMonkeyBoy** [ngxs/store#457]
### Versions

```
* @ngxs/store: 3.1.0
* @ngxs/storage-plugin: 3.1.4
* @angular/core: 6.0.0
```

### Issue

Using a duplicated key word to save a nested object like this:

```
NgxsStoragePluginModule.forRoot({
     key: ['"items.items"]
}),
```

### Repro steps

Stackblitz: https://stackblitz.com/edit/ngxs-simple-jqtx8m

* Open the devtools
* Add an item clicking on the button
* Reload the app
* Look at the state in the store

### Observed behavior

The store does not contain the normal state anymore, but only the items array.

### Desired behavior

The store should contain the normal state including the items saved in the localstorage.

### Mention any other details that might be useful (optional)

If I change "items" key by "data" or anything else like this:
```
NgxsStoragePluginModule.forRoot({
     key: ["items.data"]
}),
```
and update items.state.ts accordingly, all is fine: https://stackblitz.com/edit/ngxs-simple-qx6gt4.

**Comment by Thenis** [comment]
I tried the stackblitz link you provided and seems to be working on my end
![image](https://user-images.githubusercontent.com/13870239/41728783-4946859c-7580-11e8-95be-a6d9e551460f.gif)
