### ISSUE TITLE
[Router Plugin] Override RouterStateSerializer with a custom serializer

### ISSUE THREAD

**Issue by herkulano** [ngxs/store#460]
The `RouterStateSerializer` is not exposed and it cannot be overridden by injecting a custom serializer as `ngrx/router-store` does: https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#custom-router-state-serializer

Adding the ability to override the `RouterStateSerializer` allows the manipulation of the router state to whatever form makes sense for each application instead of having the raw router snapshot object.

From https://github.com/ngrx/platform/blob/master/docs/router-store/api.md#custom-router-state-serializer
> During each navigation cycle, a RouterNavigationAction is dispatched with a snapshot of the state in its payload, the RouterStateSnapshot. The RouterStateSnapshot is a large complex structure, containing many pieces of information about the current state and what's rendered by the router. This can cause performance issues when used with the Store Devtools. In most cases, you may only need a piece of information from the RouterStateSnapshot. In order to pare down the RouterStateSnapshot provided during navigation, you provide a custom serializer for the snapshot to only return what you need to be added to the payload and store.
> 
> Additionally, the router state snapshot is a mutable object, which can cause issues when developing with store freeze to prevent direct state mutations. This can be avoided by using a custom serializer.

**Comment by amcdnl** [comment]
Should be an easy PR, I thought it was exposed. Can you PR this?
