### ISSUE TITLE
Feature request / Remote Redux Devtools

### ISSUE THREAD

**Issue by TomDemulierChevret** [ngxs/store#461]
The Redux Devtools plugin does work pretty well on local apps and is very handfull.
However, when developping an Ionic app and testing on device (or other situation were the app doesn't run on the local browser) we can't currently use it.

Would be possible to add another plugin (or modify the existing one) like https://github.com/zalmoxisus/remote-redux-devtools that would enable remote usage of Redux Devtools ?

Anyway, awesome work on this library !

**Comment by markwhitfeld** [comment]
Just to let you know, this is already one of the things that we will be catering for as part of the development of our own NGXS Dev Tools. Project is just kicking off.

**Comment by amcdnl** [comment]
Closing this given the above.

**Comment by somq** [comment]
@TomDemulierChevret  
In the meantime, the ws proxy trick works also for ngxs:
https://github.com/somq/ionic4-remote-devtool
