### ISSUE TITLE
🐞[BUG]: Global error handler getting called twice

### ISSUE THREAD

**Issue by leksinteractive** [ngxs/store#463]
Hi team,

It seems the global error handler is invoked twice when it first catches an error that's thrown by a state action. Any subsequent errors seem to trigger it only once though. This is the behaviour if I re-throw the error in the global error handler like so:

```
public handleError(error: any): void {
      console.log('GlobalErrorHandler', error);
      throw error;
}
```

To make things more interesting, if I don't re-throw the error, the handleError method gets invoked twice on every error (regardless of whether it's the first one or subsequent ones). Any suggestions for getting around this? Also, as in my app I do some redirection in the global error handler eg. for 401 errors, so I wouldn't want to re-throw the error in that case.

Here's a stackblitz: https://github-qfjnen-drrq77.stackblitz.io
And the editable version: https://stackblitz.com/edit/github-qfjnen-drrq77

Cheers,
Aleks

(Loosely relates to: #372)

**Comment by markwhitfeld** [comment]
**Copied from other issue conversation:**
I think that it could be to do with shareReplay (which I think has since also been added to the inner dispatch, within the compose). In PR #376 I opted for a subscribe over a catchError pipe because shareReplay only stores the last replay result of the value in the stream and not an error. Using a shareReplay over a catchError may result in the handler being executed twice.

**Comment by markwhitfeld** [comment]
@leksinteractive Do you want to have a go at reproducing this with a test? 
This scenario seems to be covered with this test: https://github.com/ngxs/store/blob/07de0badfbbd78c1de2f53f08de78445fa5f6b7d/packages/store/tests/dispatch.spec.ts#L22-L58
A repro with a test would make fixing it so much easier :wink:

**Comment by markwhitfeld** [comment]
Hmmm... this may actually have something to do with Zones

**Comment by leksinteractive** [comment]
Thanks for looking into this @markwhitfeld - I'd be happy to put together that test as soon as I find some time. Zones, I think I'm a bit out of my depth there unfortunately :)

**Comment by amcdnl** [comment]
@markwhitfeld - were u able to repo this?
