### ISSUE TITLE
Cannot read property 'SessionStorage' of undefined

### ISSUE THREAD

**Issue by kctang** [ngxs/store#480]
Hi,

When using `storage: StorageOption.SessionStorage`, I got this error:

> Cannot read property 'SessionStorage' of undefined

![image](https://user-images.githubusercontent.com/1495212/42256606-e5c16938-7f84-11e8-8fe5-9469f66fce86.png)

Looking into `StorageOption`'s enum, it says SessionStorage is 1, so I tried `storage: 1`. It works and stores in session storage.

Is this a bug or i'm using the `StorageOption` incorrectly?

Versions:

    "@ngxs/storage-plugin": "^3.1.4",
    "@ngxs/store": "^3.1.4",

**Comment by amcdnl** [comment]
This was an issue upgrading to new angular version that they have thus fixed. I think we might need to remove the `const` from the enums.
