### ISSUE TITLE
@Select decorator make Angular linter not recognize subsequent properties in template in VSCode

### ISSUE THREAD

**Issue by IlCallo** [ngxs/store#490]
### Versions

```
* ngxs: 3.1.4
* @angular/core: 6.0.7
```

### Repro steps

1. Take a component with quite a number of public properties and methods
2. Add a `@Select` decorator for a slice of the state at the top of the class, save
3. Add and remove a space somewhere in the template file, save (to force the linter to do it's work, could depend on VSCode settings)
4. Notice how all properties (except getters apparently) now shows Angular `Identifier 'XYZ' is not defined. The component declaration, template variable declarations, and element references do not contain such a member` warning (or `Unknown method 'XYZ'` for methods)
5. Move `@Select` decorated property to the end of the component, save
6. Repeat 3
7. Notice how the Angular error is not displayed anymore
8. Remove `@Select` decorated property, save
9. Repeat 3
10. Still no Angular warnings in the template

**Comment by amcdnl** [comment]
Can you make a repo of this? I've never seen this.

**Comment by IlCallo** [comment]
Same as other issues, I'll make it as soon as I can.

**Comment by IlCallo** [comment]
This hasn't happened in a while anymore, I'll close the issue

**Comment by cagcak** [comment]
is this the same issue here? I don't want open a duplicated issue:

error: Property 'todos$' is used before its initialization.
demo: https://stackblitz.com/edit/ngxs-simple-demo-undefined-stream
