### ISSUE TITLE
Harmonize return value of patchState, setState and getState

### ISSUE THREAD

**Issue by IlCallo** [ngxs/store#491]
### Versions

```
* ngxs: 3.1.4
* @angular/core: 6.0.7
```

### Observed behavior

```
<!-- Normally this includes a stack trace and some more information. -->
```
`patchState` returns the full state of the application with changes applied

### Desired behavior

`patchState` returns the slice of the application on which I'm working (as defined by `StateContext` typing) on with changes applied

### Other observations

`getState` already returns a scoped slice when invoked
`setState` instead returns the same as `patchState`

I think returning the scoped slice is the right thing to do to keep different modules decoupled.
I didn't found this behaviour described anywhere.
This would also allow to return a type from `patchState` and `setState` (Partial<T> or DeepPartial<T>)

**Comment by markwhitfeld** [comment]
I disagree. The `setState` and `patchState` are updating the state at that point in time (all relevent selectors would trigger). If they had a return value it may leave some doubt (more so with `patchState`) as to if they are assisting to produce the new state value or if they were applying the change.

I do see the merit of getting the new state after making the change but my question would be why would you need it. You should have made all the changes you intended. If you are going to make further changes then it would probably only be after some async call. You should really be getting a fresh state at that point.

**Comment by IlCallo** [comment]
Well, I guess that point of view makes sense, but right now both `setState` and `patchState` **do** return the state.
In my use case, I patch the state slice and then send the new state to the server for remote update.
If the update fails for any reason, I restore the previous state.

```
return this.preferencesService.updatePreferences(patchState(patch).preferences as AppPreferences).pipe(
    catchError(err => {
        patchState(preferencesBackup);
        throw new Error('Preferences update failed, reverting to previous value; Details: ' + err);
    }),
);
```

Of course I can do

```
patchState(patch);
return this.preferencesService.updatePreferences(getState()).pipe(
    catchError(err => {
        patchState(preferencesBackup);
        throw new Error('Preferences update failed, reverting to previous value; Details: ' + err);
    }),
);
```

In fact I'm asking for an harmonization of all methods, not to support my specific use case :)
If `setState` and `patchState` would return void, that would be fine, I'm just pointing out that now they return the full state object (not the slice I'm operating on) and this behaviour seem strange to me

**Comment by markwhitfeld** [comment]
Oh, that's very interesting. I was looking at the interface, not the actual returned data.
Interface: https://github.com/ngxs/store/blob/master/packages/store/src/symbols.ts#L25-L48
Implementation: https://github.com/ngxs/store/blob/master/packages/store/src/internal/state-context-factory.ts#L20-L59

I see the use case of getting the result of the `patchState` to be able to send to the server but that could also be achieved through calling `getState` again which would avoid any ambiguity.

I don't see the use of `setState` returning the entire app state, or any state for that matter. I agree that if it does return state it should return the current context's slice but I think void is better.

At least the interface is void, so I don't think any expectation has been set around this being any different than what is exposed by the API. It's interesting that you picked this up. Nice catch. I agree that something needs to be fixed here.

@amcdnl What was was the original intention of the values returned by `patchState` and `setState`?

**Comment by amcdnl** [comment]
I'm good w/ your suggestion @markwhitfeld . Can you make these PRs @IlCallo ?

**Comment by splincode** [comment]
return value deprecated since v4.0.0
