### ISSUE TITLE
@Select not working when used into State class

### ISSUE THREAD

**Issue by IlCallo** [ngxs/store#492]
### Versions
```
* ngxs: 3.1.4
* @angular/core: 6.0.7
```

### Repro steps

Stackblitz / Github link: https://stackblitz.com/edit/ngxs-simple-qjsbnk

### Observed behavior

I tried to use the technique described [here](https://ngxs.gitbook.io/ngxs/concepts/store#dispatching-actions) to get the state after an action took place using `withLatestFrom` (because we cannot trust the dispatch return value) but the `@Select` on the state class doesn't seem to work.
If I get the value via the `Store` service, it works as expected.

### Desired behavior

That it works, being this described as official workaround in the docs.

### Mention any other details that might be useful (optional)

Dunno if it is related on the `@Select` being on the same class of the `@Selector` or what, but I didn't found written anywhere we cannot use `@Select`s on a `@State` decorated class, so I expected it to works normally.

If this is "working as intended", it could probably be a good idea to explicitly state in the docs that this situation is not possible and suggest the workaround using `selectSnapshot` I'm using.

PS: just starting digging a bit deeper in your library, sorry for all the issues, I'm afraid more will come :P

**Comment by amcdnl** [comment]
Interesting. I'm not sure I want to encourage people to do this though. Lets say its working as intended. Will you make a PR to add this to the docs.

**Comment by markwhitfeld** [comment]
This may be to do with the order that the decorators fire in. @IlCallo if you put the `@Select` after the `@Selector` that it uses does that work?
@amcdnl If this is the case there may be something that we can do to resolve this.

**Comment by amcdnl** [comment]
Ya, you are right; its likely ordering. I just really don't think we should advertise this though. Seems like a bad idea to mix and match this w/ other states.

**Comment by IlCallo** [comment]
The decorator is before, I tried to switch order into the stackblitz but nothing changed
