### ISSUE TITLE
[Feature] @Select with no arguments should return full state

### ISSUE THREAD

**Issue by IlCallo** [ngxs/store#493]
Given how the `@Select` decorator API works, it seemed natural to me to try to use it without parameters to get the full state (the selectorOrFeature parameter is marked as optional) but I got an `undefined`.

I tried digged into the code and found that optional parameter scenario is somewhat managed but I could not figure out exactly what it's doing.
I checked again the docs and found no hint on what's the expected behaviour for this scenario.

```typescript
@Select('feature.something') // Gives deep slice
@Select('feature') // Gives feature slice
@Select('') // Expect full state
@Select() // Expect full state too, I guess?
@Select(state => state) // Current way to get full state
```

**Comment by amcdnl** [comment]
Hmmm ... interesting. I could see it, go for it if you wanna do a PR.

**Comment by IlCallo** [comment]
I don't know if I'll be able to send PRs until August, but I'll try my best :)

**Comment by markwhitfeld** [comment]
@amcdnl doesn't an empty `@Select` use the variable name to determine the state slice?
The above example would be looking for a state slice called `guess`.

**Comment by eranshmil** [comment]
https://github.com/ngxs/store/blob/master/packages/store/src/decorators/select.ts#L28
When passing no argument, the name of the property is used to define which state to fetch.

`@Select() feature: Observable<MyFeatureState>;`
It will get you the state named feature, but It's not working when dealing with a sub state.

**Comment by IlCallo** [comment]
Oh, now I understand that line of code, that's the one I was not undestanding.
So it works like this?

```typescript
@Select() public name // 'name' slice
@Select() public name$ // 'name' slice
```

Is this behaviour documented? To me, it doesn't really seem a good practice.
I can see how it's similar to `@Input`&co. behaviour, but if I refactor the state name I'll be forced to manually search and update all @Select references, while in `@Input`&co. the variable name is "the single source of truth" for that feature and renaming it will rename all others occurrences.

I can do a PR to enable the full state only when an empty string is given, but that seems ugly and wrong somehow.
Like this

```typescript
@Select('') public name // Expect full state
@Select() public name // 'name' slice
@Select() public name$ // 'name' slice
```

**Comment by eranshmil** [comment]
I created a pr to document this behavior.

I think the best approach to fetch all the state is to implement something like that:
```
import { State } from '@ngxs/store';

@Select(State) paramName$: Observable<any>;
```

Also, I think we need to add a support for sub-states using camel case parameter name.

@amcdnl 
What do you think?

**Comment by xmlking** [comment]
I am getting `undefined` first, and then real store value with following selector.
https://github.com/xmlking/ngx-starter-kit/blob/master/libs/auth/src/lib/auth.service.ts#L22 
```ts
 @Select('auth.authMode') authMode$: Observable<AuthMode>;
```
if I use ` this.store.select(AuthState.authMode)`. i get default store value as expected, instead of `undefined`. 
also discussed here: 
https://github.com/xmlking/ngx-starter-kit/issues/2#issuecomment-406783600

**Comment by arturovt** [comment]
Should it be closed? Looks like it's been open for more than 1 year and there is no progress on this. If there are any issues regarding `@Select + string` you can open a corresponding issue with reproduction. Thus we can talk business :wink:

**Comment by IlCallo** [comment]
I moved to a different framework meanwhile so I guess this can be closed.
I'll come back haunting you if I come back to Angular-land some day :P
