### ISSUE TITLE
[Discussion] Children SubStates shared between two top-level States

### ISSUE THREAD

**Issue by IlCallo** [ngxs/store#494]
This is not really a feature or bug request, nor a technical question.
Is more a "what do you think about..." thing.

My use case:
Among other parts, I'm using NGXS to keep track of the currently logged user preferences.
Other than that, I'm also keeping track of the **default** preferences for that user's role which have the same structure and is used for "reset to default" functionalities (not total, it's a reference to do a diff with single sub-objects).

Currently my code is like this

```typescript
/* State */

const preferencesSubStates = [
    Module1PreferencesState,
    Module2PreferencesState,
];

@State<AppPreferences>({
    name: 'preferences',
    children: preferencesSubStates,
})
export class PreferencesState {
    // Things
}

@State<AppPreferences>({
    name: 'rolePreferences',
    children: preferencesSubStates,
})
export class RolePreferencesState {
    // More things
}
```

```typescript
/* Module */

@NgModule({
  imports: [
    NgxsModule.forFeature([
      PreferencesState,
      RolePreferencesState,
      Module1PreferencesState,
      Module2PreferencesState,
    ]),
    NgxsStoragePluginModule.forRoot({
      key: [ 'preferences', 'rolePreferences'],
    }),
  ],
})
export class MyModule { }
```

This actually works pretty well, but then I asked myself: "preferences updates is working, but how does it know about which one of the top-level State must be used for Modules `@Select/@Selectors`?!"

Turns out the answer is the declaration order inside `NgxsModule.forFeature` (the first wins).

Would you like to enhance support for this scenario? Do think this is a proper use of your library or too much an edge case? Generally speaking, what do you think about this pattern?
Obviously I cannot use `@Select` for the second top-level state and I'm forced to use inline functions or strings, which is a pity but I can live with it.

This could be adressable with parameters on `@Select` decorators (I saw someone already proposed those), but there are probably other possibilities to support this scenario.

**Comment by markwhitfeld** [comment]
PS. with the current `@dev` version you could actually have a reasonable selector using a new construct I added last week. `createSelector` allows for the creation of a selector at run time. So you could have this as a selector:
```typescript
@State<Module1Preferences>({
    name: 'module1Pref'
})
export class Module1PreferencesState {

    @Selector()
    getPreferenceFrom(parentClass: any) {
        return createSelector([parentClass], (parent) => parent['module1Pref'] );
    }

    // Even more things
}

@Component( /* ... */)
class SomeComponent {

    @Select(Module1PreferencesState.getPreferenceFrom(RolePreferencesState))
    rolePreferencesState$: Observable<Module1Preferences>
    
    // Even more things than the things that were before
}
```

I haven't tried this but it should work theoretically.

**Comment by IlCallo** [comment]
Damn, I missed that one line.
Let that workaround aside, are interested into discussing this?
The "if ever" sounds more like a "naaah", I'll just close the issue if you prefer to not proceed in that direction.

I'll probably try some PRs on this library while I find limitations (in some months I think), I wanna just make sure that enhancements I could propose will actually have a chance of being merged, otherwise I won't even bother :)

**Comment by IlCallo** [comment]
Didn't saw the second answer, I'll give it a try.
Even because using then "extend the state with another state" can't work in my case or so it seems given that everything broke.
I think it's because all states need to have an unique name, but I need those "duplicated" states to have the same name. I could use this pattern if key and names where decoupled.

What are the "high value features" cited in the docs that substate reuse would eliminate?
I didn't saw any problems popping out with the previous implementation...

**Comment by amcdnl** [comment]
Are we good @IlCallo ?

**Comment by IlCallo** [comment]
Sorry, I started to work into another part of the application, I'll try the `createSelector` way after I finish this part (the current "buggy" way I'm using, actually works for me atm and I'm a bit in a hurry).
Also, was waiting for the release you just did :P

**Comment by amcdnl** [comment]
Gonna close this given that . ... Thanks :)
