### ISSUE TITLE
setState(state) doesn't trigger state change subscription callback

### ISSUE THREAD

**Issue by sangupta007** [ngxs/store#498]
```setState(state)``` doesn't trigger state change subscription callback.
This was indicated in [this](https://stackoverflow.com/a/50869201/5457113) StackOverflow answer.

**app.state.ts**
```
const state = context.getState();
state.permissions = action.payload;
context.setState(state);   //LineA
```
**app.compoent.ts**

```
constructor(private store: Store)
 ngOnInit() {
     this.store.subscribe(state=>console.log(state));   //LineB: this callback will not run
}
```
However if I change LineA with 
```context.setState({ ...state });```
OR
```context.patchState(state);```
Callback in LineB will run, and it will log the state

**Versions:**
```"@ngxs/store": "^3.1.4",```
```"@angular/core": "^6.0.3",```

**Comment by markwhitfeld** [comment]
Yes, this is by design. You should not make changes to the state directly but rather make a change to a copy and set that. Immutability concepts apply.
Please turn on dev mode to pick up the places in your code where you are doing the wrong thing.
