### ISSUE TITLE
Getting error while importing WebsocketMessageError

### ISSUE THREAD

**Issue by CodeSnooker** [ngxs/store#503]
### Versions

@angular: ^6.0.3 (All angular packages)
@ngxs/devtools-plugin: 3.2.0
@ngxs/logger-plugin: 3.2.0
@ngxs/router-plugin: 3.2.0
@ngxs/storage-plugin: 3.2.0
@ngxs/store: 3.2.0

### Repro steps
```
import { Injectable } from '@angular/core';
import { Store, Actions, ofActionDispatched } from '@ngxs/store';
import { WebsocketMessageError, ConnectWebSocket } from '@ngxs/websocket-plugin';
import * as Rx from 'rxjs';


@Injectable({
  providedIn: 'root'
})

export class WebSocketService {

  private subject: Rx.Subject<MessageEvent>;

  constructor(private store: Store, private actions$: Actions) {
    this.actions$
      .pipe(ofActionDispatched(WebsocketMessageError))
      .subscribe(({ payload }) => {
        console.log('Got action: ', payload);
      });
  }
  public connect() {
    this.store.dispatch(new ConnectWebSocket());
  }

}
```

### Observed behavior
Getting following error:

> module @ngxs/websocket-plugin/ngxs-websocket-plugin"' has no exported member 'WebsocketMessageError'.
> 
> import WebsocketMessageError

### Desired behavior

`WebsocketMessageError` should be able to import.

**Comment by markwhitfeld** [comment]
Looks like this needs to be added to the exports if the `public_api` of the websockets plugin. Do you want to have a go at doing a PR for this fix? It's very simple

**Comment by CodeSnooker** [comment]
@markwhitfeld let me try it over night

**Comment by xmlking** [comment]
is there an easy way to get notified after successful connect,  to do some work after successfully established connect? I have to send auth request immediately after successful connection?

**Comment by xmlking** [comment]
may we can fire more events like `WebSocketConnected`  , `WebSocketDisconnected` based on `WebSocketSubject.connectionStatus`  observable !


https://github.com/ngxs/store/blob/master/packages/websocket-plugin/src/websocket-subject.ts#L34

**Comment by CodeSnooker** [comment]
@xmlking, may be you are right. But I am thinking if plugins can be made extendable somehow then anybody can make their custom actions. Or we need to grow library as the demand kicks in.

**Comment by markwhitfeld** [comment]
@xmlking you could subscribe to the action stream and filter for the success of the correct action

**Comment by markwhitfeld** [comment]
@xmlking oh sorry, I'm mistaken, just looked at the code and what I mentioned won't work. It would need to fire the events you suggested. If it matters to you then please log a separate issue for it. Thanks!

**Comment by peternagy1332** [comment]
https://ngxs.gitbook.io/ngxs/plugins/websocket
"Here is a list of all the available actions you have: WebsocketMessageError"
I still can't import it. Could you please work on it? Thanks.

**Comment by markwhitfeld** [comment]
@peternagy1332 This is fixed in the current `@dev` npm version. Please could you try it out.
