### ISSUE TITLE
WebSocket Plugin Auth

### ISSUE THREAD

**Issue by xmlking** [ngxs/store#505]
**Feature Request:**
If WebSocket backend expect JWT token for authorization, it is commonly passed via  **query** param while initializing connection as expected by **passport** or via **query** options ( e.g., *socket.io.opts.query*)  when attempting to reconnect.

`ConnectWebSocket` or `NgxsWebsocketPluginOptions` provided by **ngxs plugin** don't have options to pass those **query** param.
it would be nice if we offer options to set **query** param.

```ts
    const socket = io('http://localhost:3000/eventbus', {query: 'token=mytoken'});
    socket.on('connect', function () {
      console.log('Connected');
      socket.emit('events', { test: 'test' });
    });
    socket.on('reconnect_attempt', function () {
      console.log('reconnect_attempt');
      socket.io.opts.query = { token: 'dddd' };
    });
    socket.on('events', function (data) {
      console.log('event', data);
    });
    socket.on('exception', function (data) {
      console.log('event', data);
    });
    socket.on('disconnect', function () {
      console.log('Disconnected');
    });
```
Someone also asked similar question here:
https://stackoverflow.com/questions/50809988/ngxs-websocket-how-to-intercept-the-connection-and-add-custom-http-header

**Comment by zeevkatz** [comment]
Faced with the same issue but the following workaround enables to authenticate the user connection in another way (using tickets):

 1. Request for a web-socket connection ticket (use `Authorization` header with your JWT).
 2. Dispatch `ConnectWebSocket` action with options which includes your web-socket url and the ticket as query param.
 3. Validate the ticket before accepting the connection handshake (in your server).

**Comment by AJ84226** [comment]
@splincode  ,  any example how to implement this   ?

working code for this : -
Request for a web-socket connection ticket (use Authorization header with your JWT).
Dispatch ConnectWebSocket action with options which includes your web-socket url and the ticket as query param.
Validate the ticket before accepting the connection handshake (in your server).   ?
