### ISSUE TITLE
expose WebSocketConnected  WebSocketDisconnected for websocket-plugin

### ISSUE THREAD

**Issue by xmlking** [ngxs/store#508]
As discussed here: https://github.com/ngxs/store/issues/503#event-1738178984
we need `WebSocketConnected`  `WebSocketDisconnected` events published to action stream  so that users can react to those events.
### usecase  
1. when WebSocket Connected successfully, we want to trigger some initialization actions like `Authentication`   ,  Data load etc.
2. when WebSocket Disconnected, we may want to re-establish connection or notify user to login etc.

**Comment by markwhitfeld** [comment]
@xmlking Do you want to work on a PR for this?

**Comment by kwalski** [comment]
I am also trying to figure out how to check the connection status of Websocket (and retry if disconnected). @xmlking  do you have any PR in progress or any ideas how to do this?

**Comment by xmlking** [comment]
sure will create a PR. would you like to name it as `socketio-plugin` ? 
I have full working minimal demo  here https://github.com/xmlking/connect4

**Comment by kwalski** [comment]
@xmlking ngxs websocket plugin uses rxjs websocket under the hood, I am curious why you used socket.io client? Was it a dependency of your backend?

**Comment by xmlking** [comment]
I am using [nestjs](https://docs.nestjs.com/websockets/gateways) as my backend which default to `socket.io` for websocket implementation. Most of node community using socket.io for WS implementation, so I have to implement this plugin.
We can back port features I added to original ws-plugin if make sense.

**Comment by splincode** [comment]
Fixed since 3.4.0
