### ISSUE TITLE
docs: domain redirects to 404

### ISSUE THREAD

**Issue by eranshmil** [ngxs/store#517]
When trying to enter the docs via http://ngxs.io it redirects to: https://ngxs.gitbook.io/ngxs/TggLZ/XKcjZ/UgMlZ/YKaNZ/WRflZ/UeSdZ/

**Comment by deebloo** [comment]
@eranshmil I am not currently seeing that. maybe it was a caching issue? could you try again and report back?

**Comment by eranshmil** [comment]
Working now, even without clearing cache. :)
