### ISSUE TITLE
[Proposal]: Shorten decorators

### ISSUE THREAD

**Issue by splincode** [ngxs/store#519]
It would be nice to have custom decorators for simplified work
https://github.com/ktsn/vuex-class

```ts
export class MyComp extends Vue {
  @State('foo') stateFoo
  @State(state => state.bar) stateBar
  @Getter('foo') getterFoo
  @Action('foo') actionFoo
  @Mutation('foo') mutationFoo
  @someModule.Getter('foo') moduleGetterFoo

  // If the argument is omitted, use the property name
  // for each state/getter/action/mutation type
  @State foo
  @Getter bar
  @Action baz
  @Mutation qux

  created () {
    this.stateFoo // -> store.state.foo
    this.stateBar // -> store.state.bar
    this.getterFoo // -> store.getters.foo
    this.actionFoo({ value: true }) // -> store.dispatch('foo', { value: true })
    this.mutationFoo({ value: true }) // -> store.commit('foo', { value: true })
    this.moduleGetterFoo // -> store.getters['path/to/module/foo']
  }
}
```

**Comment by amcdnl** [comment]
So, few things with this:

- Compressions makes infering names difficult. We had this in 1.0 but deprecated it, I think its still there actually.
- Using strings makes typing difficult. We have this in 1.0 but deprecated it but again I think its still in the code base.
- We don't have a concept of mutation vs action like vuex, its all just actions.
- I'm not sure what the `module` thing does.

**Comment by splincode** [comment]
Thank's for comment :)
