### ISSUE TITLE
Dispatching actions for global state

### ISSUE THREAD

**Issue by piernik** [ngxs/store#522]
I have store that has structure like this:

```
	entities: {
		companies: {
			[n:number]: Company
		},
		persons: {
			[n:number]: Company
		}
	},
	companies: {
		idList: number[],
		...
	},
	persons: {
		idList: number[],
		...
	}
```
Entities has their own, separate branch.

Now if I want to delete item in `companies` I dispatch `EntitiesDelete` action which should also delete id from `idList` of correct branch.

But every `@Action` is connected to it's own `StateContext`
```
@Action(EntitiesDelete)
  delete(ctx: StateContext<EntitiesStateModel>, action: EntitiesDelete) {
    const {[action.id]: removed, ...newEntities} = ctx.getState()[action.objectId];
    ctx.patchState({
      [action.objectId]: newEntities
    });
  }
```

Can I in `EntitiesState` change `CompaniesState` or `PersonsState` except of dispatching new action?
Or maybe there is a way to `dispatch` action that is not connected to certain `StateContext` but is in global state?

**Comment by piernik** [comment]
Any comment on this one? This could be very useful

**Comment by steve-todorov** [comment]
I have asked myself similar questions. The only way for now seems to be to `dispatch` a new `Action` which then does the necessary changes to the `PersonsState`. I think this approach is actually more convenient because you can see in the console logs what has happened, when it happened and what was the exact flow which caused the state(s) to change. That makes debugging a lot easier IMHO - the down side is you need to `dispatch` additional events. :)

**Comment by piernik** [comment]
Any news on this one?
I tried to do it with Plugins but, don't know why, not every services are initialled when using it.

**Comment by arturovt** [comment]
@piernik 

No, this is not possible. That would have side-effects if the `setState` function affected also the global state. Also much harder to debug.

By dispatching actions from different states gives you an opportunity to "track" the state, also you clearly know what action was dispatched, what state this action is related to. I'm not sure if this code looks "bad":

```TS
@Action(EntitiesDelete)
delete(ctx: StateContext<EntitiesStateModel>, action: EntitiesDelete) {
  const {[action.id]: removed, ...newEntities} = ctx.getState()[action.objectId];
  ctx.patchState({
    [action.objectId]: newEntities
  });

  return ctx.dispatch(new ChangeCompaniesState(...));
}
```

> Or maybe there is a way to dispatch action that is not connected to certain StateContext

`dispatch` is connected to the `StateContext`, you can any action from the action handler that will affect any another state that you want.
