### ISSUE TITLE
bug: initial state is not set when it should be

### ISSUE THREAD

**Issue by merlosy** [ngxs/store#523]
### Versions
```
* ngxs: 3.2.0
* @angular/core: 6.1.0
```

### Repro steps

- Create a Guard on a route that dispatch an action. This action is supposed to fetch data asynchronously and put it in store. The guard is resolved when data is fetched and stored
- reload this page (browser)

### Observed behavior

The state doesn't seem to be initialized before the first route is loaded. It seems to be set while the page component is instantiated. 

Chronology (from my debugged scenario): 
  1. route guard write data in store
  2. store is initialized (data is gone)
  3. reading from store -> empty

### Desired behavior

the state should be initialized before guard executes, so that when when writing to store (inside guard) it stays there

### Mention any other details that might be useful (optional)

This scenario is working with ngrx/store, as I use both in 2 different projects.

**Comment by markwhitfeld** [comment]
Is it possible to provide a Stackblitz repo for this?

**Comment by merlosy** [comment]
After some investigation, it seems that the state is set, but the selector is not working.

```ts
export class PanelStateModel {
  workingDate: Date | null;
  entities: { [key: string]: PanelDetail };
  loading: boolean;
  searchFilters: SearchFilter;
  searchResults: PaginatedList<Panel>;
  searchLoading: boolean;
}

@State<PanelStateModel>({
  name: 'panels',
  defaults: {
    workingDate: null,
    entities: {},
    loading: false,
    searchFilters: {
      extendedCode: '',
      range: '0-9'
    },
    searchLoading: false,
    searchResults: new PaginatedList([], Pagination.empty())
  }
})
export class PanelState {
...
}
```

When i use the selector to get the state, I have the whole state in the console but not in the code, it seems like the data is not up to date before ngOnInit executes.

I'll try to find some time to make a stackblitz...

**Comment by merlosy** [comment]
Here it is: 
https://stackblitz.com/edit/ngxs-simple-hnwbtb?file=app%2Fuser%2Fuser.component.ts
open the console to see the data.
Could it be related to lazy loaded module?

**Comment by merlosy** [comment]
I think I found it... `forFeature` instead of `forRoot` :1st_place_medal:
