### ISSUE TITLE
[Feature Request] Decorator based static type property initialization?

### ISSUE THREAD

**Issue by oleersoy** [ngxs/store#524]
Hi,
Just curious whether you think decorator based creation of the `static readonly type` argument makes sense for actions?

I'm just learning ngxs now, and I see that in this [coursetro tutorial (Point in time embedded)](https://youtu.be/SfiO3bDUK7Q?t=276) the author sets the type attribute like this:

```
static readonly type = '[Tutorial] Add'; 
```

If we had an `@Action` decorator we could get the class name and create the value that is used to initialize the `type` property on the Action prototype.  For example the following annotation / decorator example will console log `NgxsAction`.  
```
function Action(target: any) { 
    console.log(target.name);
}

@Action
class NgxsAction{} //

```
Thoughts?

## Constructor Generation

Another thought was that perhaps the annotation could also do more by convention.  For example if the acion is an `Add` action, then then it looks like the constructor could also be generated.

So if the class is called `AddTutorial` then deduce that the name of the model is `Tutorial` and generate the constructor like this:

```
constructor(public payload: Tutorial)
```

## StateModel Generation

It also looks like most of the code (Keep in mind I'm new so I might be missing a lot of edge cases) associated with the `@State` annotation could be generated.  For example the tutorial goes on to do this create a `TutorialStateModel` class which essentially wraps a `tutorials` array property and then we have a `@State` annotation that instruments NGXS.  Could we generate all of this based on the action?  It looks like all ends up pointing to a string `Tutorials` and the corresponding array, which is used to manage the state for Tutorial instance CRUD operations.  So it seems like that could be generated by convention?  For example it seems like the CRUD interface:
```
addTutorial(tutorial:Tutorial)
removeTutorial(tutorial:Tutorial)
...
or
addTutorial(tutorials:Array<Tutorial>)
removeTutorial(tutorials:Array<Tutorial>)
...
```

Could be automatically generated and these would work without any additional boilerplate.  If the client needed to do more advanced custom operations then they could implement that with the `@State` annotation ...

**Comment by splincode** [comment]
https://github.com/ngxs-labs/emitter
