### ISSUE TITLE
[Feature Request] Setting redux instance name

### ISSUE THREAD

**Issue by aleksandar-petrovic** [ngxs/store#525]
It would be nice if NgxsReduxDevtoolsPluginModule had property **name** for setting redux instance name.

NgRx StoreDevtoolsModule has that feature.

**Comment by juliusstoerrle** [comment]
It has:  `NgxsReduxDevtoolsPluginModule.forRoot({name: 'MyStoreName'})`

See following file for all options: https://github.com/ngxs/store/blob/4e6fd4fb7f60f00a6bd8ae6b039763c3e0d09ea1/packages/devtools-plugin/src/symbols.ts#L24
