### ISSUE TITLE
NgxsOnInit not invoked for lazy-loaded stores

### ISSUE THREAD

**Issue by BirdInTheCity** [ngxs/store#532]
### Versions
```
* ngxs: 3.2.0
* @angular/core: 6.1.0
```

### Repro steps

* Implemented `ngxsOnInit` in `ProgramState`.
* All actions and selectors work correctly for `ProgramState` store, but `NgxsOnInit` not invoked.
* In component module, removed `NgxsModule.forFeature([ProgramState]),`
* In app.module, changed `NgxsModule.forRoot([]),` to `NgxsModule.forRoot([ProgramState]),`
* `NgxsOnInit` correctly invoked.
### Observed behavior

The `ngxsOnInit` lifecycle hook does not fire for lazy-loaded stores.

### Desired behavior

`ngxsOnInit` should fire lifecycle hooks lazy-loaded stores, whenever they are initialized.

**Comment by markwhitfeld** [comment]
Is it possible to provide a stackblitz repo for this?

**Comment by steve-todorov** [comment]
State management in lazy-loaded modules work just fine for me. Maybe you should create a stackblitz indeed :)

**Comment by pdemilly** [comment]
I have an issue that is similar. I have 4 states loaded lazily. 3 of them gets initialized but not the 4th. No idea why and how to debug that. I don't do any particular in that state.

**Comment by pdemilly** [comment]
Make sure all states have a different name. I just had that problem and it was because 2 states had the same name so only one was getting initialize :(

**Comment by WayneRiesterer** [comment]
I thought that ngxsOnInit wasn't being called either, but I was relying on the Redux Devtools plugin in Firefox Developer Edition. As it turns out, my state was loaded as I wanted, but it wasn't being reflected in Redux Devtools.

I found this by console logging the state rather than relying on the developer tools.

**Comment by splincode** [comment]
@BirdInTheCity Is it possible to provide a stackblitz repo for this? you can reopen issue if the error repeats and there are examples
