### ISSUE TITLE
🚀[FEATURE]: Add test helper for @Select

### ISSUE THREAD

**Issue by wouterv** [ngxs/store#533]
## Feature Request

When I am unit testing my components that use a store, I often just want to mock the store to check whether the right dispatch methods were called.

However when the component contains @Select you'll get a errors like:

    Error: SelectFactory not connected to store!

Now we can use ugly hacks like the following to get rid of the errors:

    Object.defineProperty(component, 'active$', { writable: true });
    component.active$ = of([]);

But it would be nicer if we have the ability to have some helpers to mock the selects, or let the SelectFactory be mockable somehow.

See also: #482

**Comment by markwhitfeld** [comment]
I agree that this is very much needed.
Could you propose what you would like this testing api to look like?

**Comment by SarikaVanapalli** [comment]
Is there a way to mock @select options in an angular component with mock store? I don't see much documentation around this anywhere.

**Comment by splincode** [comment]
This problem is now considered here: ngxs-labs/ngxs-testing#4

**Comment by arturovt** [comment]
We have deprecated the select decorator since it has issues with the `SelectFactory` (it basically served as a service locator). No more work is going to be done for the select decorator.
