### ISSUE TITLE
It is necessary to put the CLI into a separate repository

### ISSUE THREAD

**Issue by splincode** [ngxs/store#535]
@amcdnl The problem is that they hurried to publish the project

Not found 404
https://www.npmjs.com/package/@ngxs/cli

Could you add me to the community, and give me the right to write?
https://github.com/ngxs/cli

Because the working project needs to be moved from here:
https://github.com/Angular-RU/ngxs-cli

**Comment by markwhitfeld** [comment]
Agreed. I think it makes sense to be in its own repo.

**Comment by splincode** [comment]
@amcdnl @markwhitfeld Are there any news about the solution of the problem?

**Comment by skanygin** [comment]
**Ohhh NOOOO!**

Better way  - sth like [this](https://github.com/ngrx/platform/blob/master/docs/schematics/README.md). Please say **NO** to different cli for each angular library.

**Comment by splincode** [comment]
@skanygin We are also working to support schematics

https://github.com/ngxs/schematics

```
$ ng add @ngxs/schematics
```

**Comment by Waterstraal** [comment]
Also, please add support for  `$ ng add @ngxs/store`.
