### ISSUE TITLE
bug (StoragePlugin): fails to check for undefined

### ISSUE THREAD

**Issue by MrCroft** [ngxs/store#536]
### Versions

```
* ngxs: 3.2.0
* @angular/core: 6.1.1
```

### Observed behavior

On init, storage plugin has [this check](https://github.com/ngxs/store/blob/master/packages/storage-plugin/src/storage.plugin.ts#L26): `if (val !== 'undefined' && val !== null) {`

### Desired behavior
It should be `if (typeof val !== 'undefined' && val !== null) {`

**Comment by markwhitfeld** [comment]
Looking forward to your PR! 😉

**Comment by eranshmil** [comment]
I guess you can close that issue now. :)

**Comment by MrCroft** [comment]
oh, right... sorry!
I didn't follow-up, I thought it would be closed automatically on merge.
closing now
