### ISSUE TITLE
ngxsOnInit is not working when importing modules in "wrong" order

### ISSUE THREAD

**Issue by hboelke** [ngxs/store#539]
### Versions
```
* ngxs: 3.2.0
* @angular/core: 6.1.0
```

### Observed behavior

The function `` ngxsOnInit `` don't get called when loading the store with  `` ngxsModule.forFeature() `` in a module that was imported before `` NgxsModule.forRoot() `` was imported.

Everything works like expected, except the `` ngxsOnInit`` function.

Importing modules that uses ngxs after `` NgxsModule.forRoot() `` solves the problem, but could cause problems if you don't know it.

**Comment by aziznatour** [comment]
@devs If this is intentional, then at the very least it should be mentioned in the official documentations

**Comment by juliusstoerrle** [comment]
Duplicate of https://github.com/ngxs/store/issues/375

**Comment by splincode** [comment]
Released in 3.5.0
