### ISSUE TITLE
[Feature Request] Remove action class concept

### ISSUE THREAD

**Issue by kyusupov33** [ngxs/store#543]
## Feature Request?
Is it possible to get rid of the concept with the action in a separate class and set the type and the payload directly in the decorator?

Something like this

```
@Action(type: string, (payload: T) => payload)
```

**Comment by splincode** [comment]
```ts
@Action({ type: '[Action type] description', action: (payload) => payload })
```

But if you set 

```ts
@Action({ action: (payload) => payload })
```

type will be auto generated by current state class

**Comment by markwhitfeld** [comment]
Hmmm... This is a very interesting idea. Did you get this idea from anywhere?
@amcdnl I would be interested to get your take on this idea (from the comment, not the issue description) with the @Dispatcher and @Dispatch

**Comment by splincode** [comment]
https://github.com/ngxs-labs/emitter
