### ISSUE TITLE
[Question] [Discussion] What is the purpose of 'any' in store select?

### ISSUE THREAD

**Issue by byronmejia** [ngxs/store#549]
Hey there,

Our team currently heavily uses ngxs for state management, and something I've noticed is: typing is not there when we are using the select function(s).

https://github.com/ngxs/store/blob/5c2f5b8475c54e830746eeb3d2bbcea616e5363d/packages/store/src/store.ts#L30

With the code base, as is, we receive the following type:

```
(method) Store.select(selector: any): Observable<any> (+1 overload)
```

<img width="611" alt="screenshot 2018-08-17 11 40 15" src="https://user-images.githubusercontent.com/11262664/44243420-53922d80-a212-11e8-902a-6ea8b210b312.png">

As the type is resolved as 'any', this actually does mean, in fact, that the selector will resolve to `anything` we want. That is dangerous as any can actually match to anything and everything. This is not the intended behavior observing the source code, from what I see.

However, deleting line 30 results in this behavior:

```
(method) Store.select<Partial<UserPreferences> | undefined>(selector:(state: any, ...states: any[]) => Partial<UserPreferences> | undefined): Observable<Partial<UserPreferences> | undefined> 
```

<img width="579" alt="screenshot 2018-08-17 11 42 34" src="https://user-images.githubusercontent.com/11262664/44243488-ae2b8980-a212-11e8-8bd2-879fde48c65e.png">

A snippet of our AuthState:
```typescript
export class AuthState {
    @Selector()
    static preferences(state: AuthStateModel): Partial<UserPreferences> | undefined {
        return state.user ? state.user.preferences : undefined;
    }
}
```

This is arguably the perfect/desired behavior that we are after, as the typescript compiler will fill the types from the given arguments, rather than explicitly passing the type via `store.select<T>() => T`;

Is this behavior already built and we might have somehow wrecked our code base, or is it appropriate to delete the 'any' typing? 

Or, thirdly, is the desired behavior to make the developer explicitly, state the type, rather than implicitly read the type via the arguments?

**Comment by markwhitfeld** [comment]
I agree that the typing could be a bit better here.
Do you want to have a go at a PR for this?

**Comment by byronmejia** [comment]
Yeah, can definitely have a go looking into it. I'll have a deeper look into the code base to see what else uses those functions, to make sure I'm not breaking anything. Got any pointers or tips?

**Comment by matulkum** [comment]
any updates?

**Comment by byronmejia** [comment]
@matulkum Here's a breakdown of what I've found so far:

# Refactoring the Store

To begin, I looked into seeing if we can get typechecking on the [`store.ts`](https://github.com/ngxs/store/blob/master/packages/store/src/store.ts)'s contents.

## Adding TypeSafety to the Store's content

We can initially create type safety via using a class parameter of `T`

```typescript
@Injectable()
export class Store<T> {
  constructor(
    private _ngZone: NgZone,
    private _stateStream: StateStream<T>,
    private _internalStateOperations: InternalStateOperations
  ) {}
```

And now, assuming `_stateStream` accepted a generic, have more predictability with how the store should look.

## Adding TypeSafety to StateStream

Since StateStream just extends a BehaviorSubject, we can assume the subject will hold the current state. However, we must also assume that the state may not be complete at all times. A `Partial<>` type would be most appropiate. This, [`state-stream.ts`](https://github.com/ngxs/store/blob/e18ecaae0238739e8f3b694e39a893f9180a94ba/packages/store/src/internal/state-stream.ts), can now look like this:

```typescript
@Injectable()
export class StateStream<T> extends BehaviorSubject<Partial<T>> {
  constructor() {
    super({});
  }
}
```

There. Now we can assume the subject will predictably be holding part of the store. This hypothesis may be incorrect, if we should be assuming the store will predictably and constantly hold the shape given by T. Would anyone be able to chime in on this?

## Increasing select function type safety

Now that we have a predictable model underneath, we can increase the power of the selectors for the store. This doesn't look much different from before, as the generics given were correct.

```typescript
select<Q>(selector: (state: T) => Q): Observable<Q> {
```

Where T is the state and Q can be anything. Preferrably we would constrain `Q` to be a type from `T`, but this isn't too important currently. With saying this, can anyone chime in on how select could have been used with a string (as currently in master).

# Final Notes

To increase development productivity, avoiding any would be the biggest start. I'm quite happy with the project sofar, but these any types have nullified the purpose of using a type system.

Why is this worth pointing out? Let's take an example from the current version:

https://github.com/ngxs/store/blob/e18ecaae0238739e8f3b694e39a893f9180a94ba/packages/store/src/store.ts#L28-L30

A union between string and any actually completes to any, disregarding type safety to begin with. There is no purpose with having the string in that type. See Microsoft/TypeScript#18568 and as stated, this is intended behavior from the compiler.

We might as well have written:

```typescript
select(selector: any): Observable<any> {
```

Which duplicates the lines as stated earlier.

If someone can clear up how selectors should run and what we should be expecting from the state, I am happy to continue with the next task, which would be to fix [`select.ts`](https://github.com/ngxs/store/blob/master/packages/store/src/decorators/select.ts).

**Comment by scott-ho** [comment]
@byronmejia could you issue a PR?
