### ISSUE TITLE
Can't use Selector decorator in Jest based test for an Angular + Capacitor environment

### ISSUE THREAD

**Issue by HoverBaum** [ngxs/store#550]
### Versions

```
* ngxs: 3.2.0
* @angular/core: 6.1.3
```

### Repro steps

Find a repo illustrating the issue at: https://github.com/HoverBaum/selector-bug

The current state of the repo is a workaround that doesn't throw bugs but has severe issues in that you can not use the `@Selector`. To see the effect please uncomment he Selector in `src/count.store.ts` and un `npm test`.

### Observed behavior

Multiple problems are observed when wanting to use NGXS in an Angulat + Capacitor project.

**unexpected token** 

After introducing the Storage component from capacitor Jest runs complain about unexpected token. TS looses the ability to process the code correctly.

This can be fixed by adding the below configuratio to the jest part of package.json as suggested in [this issue](https://github.com/ionic-team/stencil/issues/617).

```
"transformIgnorePatterns": [
  "node_modules/(?!(@capacitor)/)"
],
"transform": {
  "^.+\\.(js|ts|tsx)$": "<rootDir>/node_modules/@stencil/core/testing/jest.preprocessor.js"
}
```

**Can't initialize Classes**

Not Angular can't find all dependencies for our Class.

To get around this we introduce `@Inject(forwardRef(() => Store)) private store: Store` intro our constructor to let Angular know that the Store will be there in time.

**Value of undefined**

Now our trouble is still that using NGXSs `@Selector` returns `Cannot read property 'value' of undefined`.

Sadly he only workaround we could come up wiht is to rewrite the selector into a different format.

Please see the repos readme for further details.

### Desired behavior

Easily testable using Jest. No need for `@Inject` in constructors to allow compilation.

**Comment by markwhitfeld** [comment]
Hmmm... that jest preprocessor seems to be running tsc with blank options:
https://github.com/ionic-team/stencil/blob/master/scripts/packages/testing/jest.preprocessor.js#L73
I wonder if that is causing the issue by not specifying the defaults for angular from the tsconfig, more noteably '"experimentalDecorators": true,'
Just a shot in the dark.

**Comment by HoverBaum** [comment]
Some great ideas here 🙂 

I tried changing the preprocessor. Sadly that didn't change the `Cannot read property 'value' of undefined` output from running the tests. The place I changed was the compilation of non-tsc transpilation.

```javascript
// non-tsx
    return ts.transpile(sourceText, {
      "module": "commonjs",
      "baseUrl": "./",
      "sourceMap": true,
      "declaration": false,
      "moduleResolution": "node",
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "target": "es5",
      "include": [
        "**/*.spec.ts",
        "**/*.d.ts"
      ],
      "lib": [
        "es2017",
        "dom"
      ]
    }, filePath, []);
```

Also tried turning the **@selector** into a public method. And that fixes the issue for testing. But I am not sure how one would now use this in their modules.

Where we declare out Angular modules to have say `@Select(CountState.currentCount) count: Observable<number>;` how could we do that once the Selector is a public method. As we would need to initialize it first. With that we could only try to assign the value in the constructor of our Components. Loosing the nice semantics the decorator gives us.

Investigating the last one now.

**Comment by HoverBaum** [comment]
Since the above problems seem to originate from the usage of Capacitor plugins and their required pre-processor a feasible workaround is to encapsulate Capacitor dependencies using Injection Tokens. This way during testing we at no time need to include any files relying on the Capacitor dependencies.

We illustrated this approach in a brach of the above mentioned repo: https://github.com/HoverBaum/selector-bug/tree/solution-by-injection-token

**Comment by HoverBaum** [comment]
Tried to illustrate the general problem with Jest and Capacitor in https://github.com/HoverBaum/Capacitor-breaks-Jests-test but as it turns out the pre-processor works fine for that minimal use case.

As the problem after the pre-processor was first the Dependency Injection I am guessing that the NGXS being an import relying on Services is causing issues during testing

**Comment by splincode** [comment]
@HoverBaum is relevant?
