### ISSUE TITLE
Documentation needed for Angular HMR

### ISSUE THREAD

**Issue by matulkum** [ngxs/store#567]
How do I setup ngxs when using Hot Module Replacement (as described for example here: https://github.com/angular/angular-cli/wiki/stories-configure-hmr)?

Currently I end up with a new global NGXS instance on every update.

**Comment by splincode** [comment]
@marcus-sa I will add documentation soon

**Comment by markwhitfeld** [comment]
Thanks @splincode

**Comment by markwhitfeld** [comment]
PR merged that includes the requested documentation. Closing the issue.
@matulkum Please test and give your feedback.

**Comment by matulkum** [comment]
Unless I am missing something, the guide on ngxs.gitbook is pretty much just a copy of the recipe page from the angular-cli documentation.

Still the problem persist, that I end up with a new global NGXS instance on every reload.

**Comment by splincode** [comment]
@matulkum Did you want your state to be saved when the application is restarted? I do not think it's a good idea

**Comment by splincode** [comment]
@matulkum you need a create new issue and suggest solutions

**Comment by matulkum** [comment]
I do not have a solution.

This issue can not be open again. Otherwise I would just copy paste this issue text?

**Comment by splincode** [comment]
This issue was not formed by pattern.
https://github.com/ngxs/store/blob/master/.github/ISSUE_TEMPLATE.md

... and not clear what problem she solves

**Comment by splincode** [comment]
I think it is impossible at the moment, or send a pull request

**Comment by markwhitfeld** [comment]
Hmmm... this could be to do with the dev tools plugin... or it could be an issue with the Redux dev tools themselves. Would need an investigation.

**Comment by splincode** [comment]
@matulkum https://github.com/ngxs/store/pull/705/files

**Comment by Polyterative** [comment]
Is this possible? Being HRM a potential change in the code, maintaining the state while changing the code could corrupt the data store. Someone please correct me if I'm wrong

**Comment by splincode** [comment]
@Polyterative 

```
$ npm install @ngxs/hmr-plugin
```

https://ngxs.gitbook.io/ngxs/v/master/plugins/hmr
