### ISSUE TITLE
Selector() functions should apply distinctuntilChanged() on its returned value

### ISSUE THREAD

**Issue by matulkum** [ngxs/store#568]
## Feature Request
Currently its seems a Selector always emit when a state change occurs. Although I think it should only emit when the "selected state slice" actually changed.

Actually currently when defining a selector function, their is no chance to not emit a value if a state change occur.

I am not sure if this is some kind of anti pattern. And also if it would be implemented it might be a breaking change.

**Comment by markwhitfeld** [comment]
Selectors do apply the distinctUntilChanged operator. I suspect that it is something to do with the way that you have structured your selectors. Please could you provide a sample of a selector that is having this issue or a repro in Stackblitz. Thanks

**Comment by matulkum** [comment]
@markwhitfeld Thanks for your reply. Actually after making a stackblitz example I was realising it is actually working like you said. There seem to be a bug in my project.

Very sorry for false alarm. Please feel free to close this issue.
