### ISSUE TITLE
Still no exported `ofActionCanceled` on npm

### ISSUE THREAD

**Issue by matulkum** [ngxs/store#572]
Even though I can see it has been fixed in this repo, when I am installing @ngxs/store from npm, I still do not have an exported function `ofActionCanceled ` in _public_api.d.ts_.

package.json version from npm and GitHub is the same though (_3.2.0_)

**Comment by eranshmil** [comment]
https://github.com/ngxs/store/issues/555#issuecomment-414466812

**Comment by markwhitfeld** [comment]
@matulkum You can use the `@dev` npm build for now
