### ISSUE TITLE
Sync form-plugin with state whose path contains array.

### ISSUE THREAD

**Issue by KirillStub** [ngxs/store#581]
## Feature Request

Using `@ngxs/form-plugin`, bind form to state whose of state contains array.

### Versions

```
* ngxs: 3.2.0
* @angular/core: 5.2.0
```

### Repro steps

Try to sync `ngxsForm` to state with path `todos.todo[1].pizzaForm`. 

### Observed behavior

The state will be look like 
```
todos: {
  todo[1]: {
    pizzaForm: {} 
  }
}
```

### Desired behavior

but expected 
```
todos: {
  todo: [
    {
      ...
    },
    {
      pizzaForm: {}
    }
  ]
}
```

**Comment by markwhitfeld** [comment]
@KirillStub Can this be achieved at the moment by using the following path for the form?
`todos.todo.1.pizzaForm`

**Comment by KirillStub** [comment]
@markwhitfeld Yes, this is better way. I opened new PR that solves this issue.
