### ISSUE TITLE
npm i @ngxs/ngxs-cli -g not working

### ISSUE THREAD

**Issue by Waterstraal** [ngxs/store#583]
### Repro steps

Run `npm i @ngxs/ngxs-cli -g` 

(as per https://ngxs.gitbook.io/ngxs/plugins/cli#install)

### Observed behavior

```
npm ERR! code E404
npm ERR! 404 Not Found: @ngxs/ngxs-cli@latest
```

### Desired behavior

It should install the ngxs cli globally on my machine.

### Mention any other details that might be useful (optional)
- Windows 8
- NodeJs v8.9.4

**Comment by alejandro-heredia-coderoad-com** [comment]
Still not fond :(

**Comment by kmathy** [comment]
Because the package was not published yet, see https://github.com/ngxs/store/pull/578

**Comment by splincode** [comment]
Package is published
