### ISSUE TITLE
ngxs not able to add using angular cli

### ISSUE THREAD

**Issue by PankajPatro** [ngxs/store#591]
Created a new Angular 6 app using ng cli.
When adding ngxs/store using ng cli - ng add @ngxs/store getting this error

Package "@ngxs/store" was found but does not support schematics.

It will be great if the ngxs could be added via ng cli.

**Comment by poloagustin** [comment]
that's usually a warning, the package should be in your package.json

**Comment by PankajPatro** [comment]
I so is the case, then I think it's a non issue
