### ISSUE TITLE
@ngxs/form-plugin FormState not updated when form object is cleared

### ISSUE THREAD

**Issue by Steven-Harris** [ngxs/store#595]
This might be a dup of #260 but wanted to post this to be sure.
### Observed behavior
The Form Plugin does not update the state if the angular form object is cleared after init. 
```
  this.count$.subscribe(x => {
       this.form = new FormGroup({});
       .... (do something to recreate the form)
```

### Desired behavior
I have a form that is dynamically created based on another state. I subscribe to the other state changes and recreate my components form based on those changes.

### Versions

```
* ngxs: 3.2.0
* ngxs: 3.2.0
* @angular/core: 6.0.0
```
_I just used the angular version in the example repo._
### Repro steps

https://stackblitz.com/edit/ngxs-simple-mfsfhx

**Comment by splincode** [comment]
`@Select` usage cache
You can create a dynamic select
https://ngxs.gitbook.io/ngxs/concepts/select#dynamic-selectors

**Comment by Steven-Harris** [comment]
That's is what I am using to generate the form. But that doesn't solve the issue

**Comment by moeller142** [comment]
@Steven-Harris I am also having this issue, did you find a fix?

**Comment by Steven-Harris** [comment]
I could never pin down the root cause but it started to look more like an issue with angular's Form Groups and directives. In my original scenario, I created a new FormGroup when something changed in the state. Angular never seemed to rebind [formGroup] when I did that or at the very least thing got wonky. To get around this I had to only create the FormGroup onInit and modify the existing FormGroup on the state changes. I would addControl, updateValidators, or removeControls - etc in the change of the state. This got around this issue of angular not rebinding the new FormGroup object. Hope this helps @moeller142

**Comment by moeller142** [comment]
@Steven-Harris I think you're right.   It seems like the subscriptions in the directive are still hooked up to the old form.  The forms I am trying to dynamically build are pretty complex so I don't really want to have to use addControl, updateValidators, and removeControls to make them so I think I might just try to find a solution that does not use formGroupDirective
