### ISSUE TITLE
States across multiple tabs are not in sync but overwritten by the latest update.

### ISSUE THREAD

**Issue by goodmite** [ngxs/store#596]
Example:

I am having a chat application opened in two different tabs (Tab 1 and Tab 2). All the message are stored in store upon pressing enter.

Case 1: **State Sync is happening only after tab reload.**
In Tab 1: Type "google", press enter (which will store "google" in store)
In Tab 2: "google" doesn't appear automatically. However if I reload the tab I see "google" message in Tab 2 as well

Case 2: **States getting over written:**
In Tab 1: Type "google", press enter.
In Tab 2: Without reloading, type "facebook" and press enter.
In Tab 1: Reload. You will see only "facebook". "google" is been removed from altogether.

**Is there any plugin which will sync store across all the tabs?**

Pls let me know for any clarifications.

**Comment by splincode** [comment]
Please, create example on stackblitz for reproduce

**Comment by splincode** [comment]
Yes, it seems you have forgotten to use web-sites for getting updated data, if you tell us in the future what’s not so detailed, maybe we can help
