### ISSUE TITLE
@Select behavior inside it's own state class

### ISSUE THREAD

**Issue by somq** [ngxs/store#608]
### Versions

```
* ngxs: 3.2.0
* @angular/core:6.1.1
```

### Repro steps

https://stackblitz.com/edit/ngxs-simple-a2ymqh?file=app/app.state.ts

### Observed behavior

Using an `@Select` through an `@Selector` inside it's own state action class returns base state object instead of the slice. While `this.store.selector` (correctly?) returns the slice.

```ts
...
  @Select(CountState.getCount) countStateA$: any;
  countStateB$ = this.store.select(CountState.getCount)

  @Selector()
  static getCount(state) {
    return state;
  }
...
```

```sh
countStateA
{count: 0}

countStateB
0
```

### Desired behavior

I might be misunderstanding something, if so, please can someone explain me where I am wrong. 

But I would have thought both ways of selecting the state slice would return only the slice, and not the base state, wherever the `@Select` is (either directly in the class or anywhere else).

Is it an inconsistency or a bug, or is it by design ?

# Additional info

The same `@Select` used in a component for instance returns the slice. (see stackblitz repro)

**Comment by markwhitfeld** [comment]
This issue is caused by the order that you have declared the decorators.
It will work if you switch the order of the `@Select` and the `@Selector` declarations.

This is because the `@Selector` decorator has not applied to the method yet when the `@Select` sets up the select call.

**Comment by somq** [comment]
Thanks for your answer.
Well, I switched the `@Selector` before the `@Select` on the [stackblitz repro](https://stackblitz.com/edit/ngxs-simple-a2ymqh?file=app%2Fapp.state.ts) and I'm having the exact same result.
What am I missing?

**Comment by arturovt** [comment]
@somq 

Yeah, that's a normal behavior. Decorators are invoked after class declaration, so at this moment `getCount` is not decorated yet and returns the whole state slice like:
```TS
store.select(state => state)
```

We cannot change the default decorator behavior in TS. Just use the `select` method of the `Store` class.
