### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by odahcam** [ngxs/store#609]
Does the latest version of NGXS supports Angular 7?

`package.json` didn't help me a lot, since everything there is `devDependencies`.

**Comment by DanielHabenicht** [comment]
In my app it worked great. But ngxs didn't upgraded it peer dependencies yet, so you might get some warnings.

**Comment by markwhitfeld** [comment]
PR #610 has been merged so this will be fixed in the latest `@dev` version
