### ISSUE TITLE
NgxsStoragePlugin and NgxsRouterPlugin combo prevents deep linking

### ISSUE THREAD

**Issue by uberspeck** [ngxs/store#612]
### Versions
```
* ngxs: 3.2.0
* @angular/core: 6.1.10
```

### Repro steps
If the `NgxsStoragePlugin` and the `NgxsRouterPlugin` are both installed, any deep link (or manually entered route) is ignored and the latest router state in local storage will be used instead.

Stackblitz - https://stackblitz.com/edit/ngxs-simple-nbx8fs

* Visit [demo](https://stackblitz.com/edit/ngxs-simple-nbx8fs)
* Notice demo route is redirected to `/foo`
* Manually change to `/bar` (defined and valid route)
* Notice you're redirected back to `/foo`

### Observed behavior
Manually enter a valid route in the browser location bar and you'll be redirected to the most recent route in localStorage

### Desired behavior
Deep links/manually entered values should be honored.

**Comment by rodzappa** [comment]
The same is happening with @angular/core: 7.0.2 too.

**Comment by arturovt** [comment]
@uberspeck @rodzappa @jayordway 
Gentlemen, this might be fixed by #920. Could you please check it and say if everything is alright?

**Comment by markwhitfeld** [comment]
You would need to install the `@dev` version from npm to test. We would love your feedback before we release this fix.

**Comment by uberspeck** [comment]
@arturovt Thanks for fixing this! I can confirm it works using a fork of my original stackblitz demo. [Go here](https://stackblitz.com/edit/ngxs-simple-cbsae8) and test it using the steps I mentioned above.

**Comment by arturovt** [comment]
@uberspeck 
Thanks for your feedback, man! So can we close this?

**Comment by uberspeck** [comment]
Sorry, I should have closed it before, closed! Thanks for your hard work. This lib is awesome!

**Comment by jayordway** [comment]
I still seem to be having an issue when trying to use the NGXS Router plugin in combination with a window.location being somewhere within the code. When the routing is set by window.location there is unexpected behavior. Perhaps this is an independent problem.

**Comment by splincode** [comment]
@jayordway create a new issue with reproduce
