### ISSUE TITLE
Warnings when installing development builds

### ISSUE THREAD

**Issue by eranshmil** [ngxs/store#636]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
Warnings when installing dev builds.
```
warning " > @ngxs/devtools-plugin@3.2.0-dev.master-e7d5450" has incorrect peer dependency "@ngxs/store@3.2.0".
warning " > @ngxs/logger-plugin@3.2.0-dev.master-e7d5450" has incorrect peer dependency "@ngxs/store@3.2.0".
warning " > @ngxs/router-plugin@3.2.0-dev.master-e7d5450" has incorrect peer dependency "@ngxs/store@3.2.0".
warning " > @ngxs/storage-plugin@3.2.0-dev.master-e7d5450" has incorrect peer dependency "@ngxs/store@3.2.0".
```
I guess that's related to the [peerDependency](https://github.com/ngxs/store/blob/master/packages/logger-plugin/package.json#L8) in package.json of the packages.

## Expected behavior
Clean install without any warnings.

## Minimal reproduction of the problem with instructions

`yarn add @ngxs/{store,devtools-plugin,logger-plugin,router-plugin,storage-plugin}@dev`

## Environment

<pre><code>
Libs:
- @angular/core version: v6.1.10
- @ngxs/store version: v3.2.0-dev

 
For Tooling issues:
- Node version: v8.11.1
- Platform: Mac

Others:
- Yarn: v1.12.1
</code></pre>

**Comment by eranshmil** [comment]
After reinstalling the development builds, the packages are fine but the main package (@ngxs/store) has no new published dev build.

```json
"@ngxs/devtools-plugin": "^3.2.0-dev.master-3677b91",
"@ngxs/logger-plugin": "^3.2.0-dev.master-3677b91",
"@ngxs/router-plugin": "^3.2.0-dev.master-3677b91",
"@ngxs/storage-plugin": "^3.2.0-dev.master-3677b91",
"@ngxs/store": "^3.2.0-dev.master-fd4bd6b"
```

**Comment by markwhitfeld** [comment]
@eranshmil Is this causing a problem at all? There were no changes to store so the new version was ignored for that package.

**Comment by eranshmil** [comment]
No, everything works fine.
I just thought that the versions are always the same for the dev builds.
Issue resolved.
