### ISSUE TITLE
Typing errors in development builds

### ISSUE THREAD

**Issue by eranshmil** [ngxs/store#637]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
When trying to build/serve a project using development builds, getting the following errors and the build fails:
```bash
ERROR in node_modules/@ngxs/router-plugin/src/router.actions.d.ts(9,28): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/@ngxs/router-plugin/src/router.actions.d.ts(23,28): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/@ngxs/router-plugin/src/router.actions.d.ts(33,28): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/@ngxs/router-plugin/src/router.actions.d.ts(43,28): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/@ngxs/store/src/actions/actions.d.ts(5,28): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/@ngxs/store/src/actions/actions.d.ts(11,28): error TS1039: Initializers are not allowed in ambient contexts.
```

## Minimal reproduction of the problem with instructions
* Install development builds
```bash
yarn add @ngxs/{store,devtools-plugin,logger-plugin,router-plugin,storage-plugin}@dev
```
* Run the app
```bash
ng serve
```

## Environment

<pre><code>
Libs:
- @angular/core version: v6.1.10
- @ngxs/store version: v3.2.0-dev

 
For Tooling issues:
- Node version: v8.11.1
- Platform: Mac

Others:
- Yarn: v1.12.1
</code></pre>

**Comment by splincode** [comment]
Please can give more information?

![image](https://user-images.githubusercontent.com/12021443/47952961-cd22f780-df87-11e8-8a3f-be4bb3b87a4e.png)

I can't reproduce.

**Comment by splincode** [comment]
I see

![image](https://user-images.githubusercontent.com/12021443/47953254-4de3f280-df8c-11e8-9fe8-51c6e68bbb21.png)

**Comment by splincode** [comment]
@eranshmil So, your TypeScript version is out of date. This is not a bug. 
@markwhitfeld  But is breaking changes for v3.2.0

I tried install Typescript@2.9.2, but it did not help

![image](https://user-images.githubusercontent.com/12021443/47953448-debbcd80-df8e-11e8-9686-9c30d42b67f6.png)

Because the transition to Angular 7, TypeScript 3.1 was critical
https://github.com/ngxs/store/pull/616

**Comment by splincode** [comment]
@eranshmil 

Solution

```ts
$ ng update --all --force # for bypassing peer dependencies
$ ng serve
```

![image](https://user-images.githubusercontent.com/12021443/47953552-4c1c2e00-df90-11e8-8504-ca98befc6fb9.png)

**Comment by eranshmil** [comment]
Fixed, thanks!

**Comment by markwhitfeld** [comment]
I'll look into a fix for the issue. We should not force an upgrade of Angular

**Comment by splincode** [comment]
@markwhitfeld I think the easiest is to just release version 4.0.0, there's nothing bad about that

**Comment by markwhitfeld** [comment]
@eranshmil The `@dev` build has been published with the fix. Please could you try it out to confirm that this is fixed and close the issue if resolved.

**Comment by markwhitfeld** [comment]
@splincode I found this workaround because we don't want to drop all our users that are currently on Angular 6 in this release.

**Comment by eranshmil** [comment]
Resolved, Thanks!
