### ISSUE TITLE
Not pushing updated state when data is an Array

### ISSUE THREAD

**Issue by paulstelzer** [ngxs/store#640]
I also created a repository: https://github.com/paulstelzer/angular-testing (the relevant code is in `src/app/store/` and `src/app/todos/`

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

UPDATE: It's not a problem with the `@Selector` decorator, it seems an issue if the data is an Array

If I am using a `@Selector` Decorator and subscribe to it, it will not push the new slice of data if I use it for example in combineLatest

## Expected behavior

Stream data if a change made to the array.

## Minimal reproduction of the problem with instructions

For example, we have a ToDo State which contains an todos array. Now there are actions to push items to the array and remove items from this array (todos). On the page I have an input field to filter my ToDos where I use combineLatest to combine the latest ToDos and the input. See the following screen:

![2018-11-03_20-50-07](https://user-images.githubusercontent.com/20501666/47956797-914d5980-dfaa-11e8-9732-57aabbec3292.gif)

That's the relevant code:

```
  ngOnInit() {
    const storeToDos$ = this.store.select(ToDoState.todos);

    storeToDos$.subscribe((data) => {
      console.log('TODOS FROM SELECTOR', data);
    });

    this.store.select(state => state.todo).subscribe((data) => {
      console.log('TODOS WITH STATE', data);
    });

    this.input = new FormControl('');

    const form$: Observable<any> = this.input.valueChanges;

    this.todos$ = combineLatest(form$, storeToDos$)
      .pipe(
        map(([input, todos]) => {
          console.log('INPUT', input);

          const searchString: string = input.toLowerCase();
          todos = todos.filter(ele => ele.name.toLowerCase().includes(searchString));
          return todos;
        })
      );
  }
```

As you can see 'TODOS WITH STATE' will we pushed immidiatly, but 'TODOS FROM SELECTOR' are not. So this.todos$ will not be updated because storeToDos$ get no new items.

Is this a restriction of the `@Selector decorator` (I think its because the reference always stays the same)?

To make it working I have to use `this.store.select(state => state.todo)` as `storeToDos$`, but this is running everytime something changes in store

UPDATE:

I updated my repository and tried this:

```
    this.store.select(state => state.todo.todos).subscribe((data) => {
      console.log('TODOS WITH STATE - TRY TO GET TODOS', data);
    });
```

This isn't working too. So it's not a problem with the `@Selector`  decorator. Instead he is not pushing new values if the array has changed. I think same problem because the reference is the same. Any idea how to make it work?

**Comment by paulstelzer** [comment]
After sleeping one night about it, I got the solution ;) It's not a problem with NGXS, it's the reference of JavaScript. Easy solution:

```
    @Selector()
    static todos(state: ToDoStateModel): ToDo[] {
        return [...state.todos];
    }
```

**Comment by lohiarahul** [comment]
> @paulstelzer This is due to immutability, if the reference were changed, then the subscription would work and you would receive a new state. But since you use patchState, you just mutate the state.
> 
> ![image](https://user-images.githubusercontent.com/12021443/47961838-7965ec00-e023-11e8-81ee-6af46a03583e.png)

Doesn't work

**Comment by lohiarahul** [comment]
> After sleeping one night about it, I got the solution ;) It's not a problem with NGXS, it's the reference of JavaScript objects. Easy solution:
> 
> ```
>     @Selector()
>     static todos(state: ToDoStateModel): ToDo[] {
>         return [...state.todos];
>     }
> ```

Doesnt work

**Comment by eranshmil** [comment]
> > After sleeping one night about it, I got the solution ;) It's not a problem with NGXS, it's the reference of JavaScript objects. Easy solution:
> > ```
> >     @Selector()
> >     static todos(state: ToDoStateModel): ToDo[] {
> >         return [...state.todos];
> >     }
> > ```
> 
> Doesnt work

Please create a new issue with a small stackblitz repro, using the following template:
https://stackblitz.com/fork/ngxs-simple
