### ISSUE TITLE
Horrible performance degradation when Chrome DevTools open

### ISSUE THREAD

**Issue by twjacobsen** [ngxs/store#648]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using NGXS for managing a portion of state, browser locks up for 40-50 seconds in a special case.

## Expected behavior
No locking up, I guess

## Minimal reproduction of the problem with instructions
Unfortunately, I haven't been able to create a reproduction on StackBlitz. The code I'm working on isn't open-source, so I can't share any that either.

I can share my State, and my "fix" though, if this is any help:

```
export type ProductsStateModel = Dictionary<Product>;

@State<ProductsStateModel>({
    name: 'products',
    defaults: {}
})
export class ProductsState {
    @Selector()
    static products(products: ProductsStateModel): ProductsStateModel {
        return products;
    }

    @Action(UpdateProducts)
    updateProducts({setState}: StateContext<ProductsStateModel>, {payload}: UpdateProducts): void {
        const newProductsById: Dictionary<Product> = keyBy(payload, 'id');
        setState(newProductsById);
    }

    @Action(ResetProducts)
    resetproducts({setState}: StateContext<ProductsStateModel>): void {
        setState({});
    }
}

// Using this (nonNgxsProductsState.update instead of dispatch, nonNgxsProductsState.state instead of select) gives expected performance
class NonNgxsProductsState {
    state: BehaviorSubject<Dictionary<Product>> = new BehaviorSubject<Dictionary<Product>>(null);

    update(products: Product[]): void {
        this.state.next(keyBy(products, 'id'));
    }
}

export const nonNgxsProductsState: NonNgxsProductsState = new NonNgxsProductsState();
```

## Environment
Any OS, Chome (and Opera, so I guess V8 based browsers) - ONLY WITH INSPECTOR OPEN, **NOT** WITH THE PROFILER RUNNING

<pre><code>
Libs:
- @angular/core version: 6+
- @ngxs/store version: 3.2.0
</code></pre>

**Comment by splincode** [comment]
Add stackblitz example

**Comment by splincode** [comment]
Make a repository for a reproduce

**Comment by splincode** [comment]
@twjacobsen Please create a minimal repository with playback and steps, I suggest opening a new issue if you intend to investigate this issue.
