### ISSUE TITLE
@ngxs/form-plugin errors property does not include the validation errors

### ISSUE THREAD

**Issue by GreenMonkeyBoy** [ngxs/store#654]
## I'm submitting a...
Not sure if it's a bug or a desired behavior.

## Current behavior
The form-plugin uses the 'errors' property by default, but this property is always empty, even when the form has validation errors. Angular does not expose the FormControl errors to the parent FormGroup [(issue)](https://github.com/angular/angular/issues/10530), consequently, the errors property does not include any error. In that way, I don't think this is a bug, as soon as Angular fix the issue, the 'errors' property should works as intended.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/ngxs-form-plugin-errors-empty

## Expected behavior
However, It would be great if the form-plugin could synchronize the validation errors. For me, the 'errors' property should not be modified (for the reason seen above), but what if the state could describe the error for each FormControl?
```
form: {
    status: 'INVALID'
    dirty: true
    errors: { }
    controls: [
        {
            name: 'email',
            errors: { },
	},
        {
	    name: 'password',
	    errors: { required: true }
         }
    ]
}
```
Futhermore, in the case you send a API request from your state (like the [Authentication recipe](https://ngxs.gitbook.io/ngxs/recipes/authentication)), if the API send back an error 'duplicate email', maybe this change might allow to patch the validation errors from the state:
```
@Action(Login)
    login({ patchState }: StateContext<AuthStateModel>, { payload: { username } }: Login) {
    return this.authService.login(payload).pipe(tap((result: any) => {
        if (res.error = 'duplicate email') {
            patchState({ 
               form.controls.find(n => n.name === 'email').errors = { duplicate: true }
           })
        });
    }))
}
```

I don't know if it's possible, maybe it's not desired, too complicated or impossible, but actually if I want to synchronize the errors, I need to do it myself from the component (taking away some of the interest of the form-plugin), and handle the errors from the store looks impossible.
    
## Environment

<pre><code>
Libs:
- @angular/core version: 7.0.0
- @ngxs/store version: 3.2.0
- @ngxs/form-plugin: 3.2.0

**Comment by gvsouza** [comment]
How are you even checking for form valid status? Are you comparing status === 'VALID'? There is so much lacking in this plugin

**Comment by arturovt** [comment]
@GreenMonkeyBoy  You mentioned an issue there and it's really a blocker from the Angular's team side. We can't recursively loop via all controls and collect errors into the one aggregate object, this won't be performant. I guess this issue has to be closed until they provide this feature.
