### ISSUE TITLE
@ngxs/form-plugin value.forEach is not a function

### ISSUE THREAD

**Issue by Thenis** [ngxs/store#655]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

@ngxs/form-plugin throws an exception when the form is an FormArray.
value.forEach is not a function
## Expected behavior

It should not throw and error when the form is a FormArray

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-uve5er

## Environment

<pre><code>
Libs:
- @angular/core version: 7.0.3
- @ngxs/store version: 3.2.0
- @ngxs/form-plugin version: 3.2.0

Browser:
- [ x] Chrome (desktop) version  70.0.3538.77
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by splincode** [comment]
https://github.com/ngxs/store/pull/659

```
$ npm install @ngxs/form-plugin@dev
```
