### ISSUE TITLE
Add greenkeeper for CI

### ISSUE THREAD

**Issue by splincode** [ngxs/store#657]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Motivation

Greenkeeper helps keep your software up to date. This eliminates many security concerns and compatibility issues, and also keeps your projects fresh and maintainable. It provides a constant drip of small, isolated updates that can be easily understood, tackled and tested.

**Comment by Koslun** [comment]
Using it myself. Quite helpful.

Reminded me to add a monorepo definition for NGXS for any consumer of this library who also uses Greenkeeper. Created a PR here: https://github.com/greenkeeperio/monorepo-definitions/pull/25, feel free to review.

Didn't find a clear list for all packages but added the ones I found.

**Comment by splincode** [comment]
https://github.com/ngxs/store/pull/680
