### ISSUE TITLE
selectSnapshot does not work when the shared state is held in a lazy-loaded module

### ISSUE THREAD

**Issue by neildonkin** [ngxs/store#664]
According to the official docs it is possible to take a read-only copy of state from a different state object, using the `store.selectSnapshot()` function.  I followed this code sample in the official docs _exactly_ but it does not work:

https://ngxs.gitbook.io/ngxs/advanced/shared-state

The only differences are my modules are lazy loaded by the router and the `MyState` class in this line of code has a dependency injected into the constructor, which should not matter since I'm invoking a static function?

`const result = this.store.selectSnapshot(MyState.getValue);`

I am unable to retrieve the snapshot and I get this error:

```
core.js:12501 ERROR TypeError: Cannot set property '[my dependency service name]' of undefined
    at MyState
```

My dependency service uses the `@Injectable({ providedIn: 'root' })` decorator and is injected everywhere else without any issue.  I tried removing the `providedIn `property but it still doesn't work

I saw #502, which appears to be the same problem, however the issue is closed and the person who raised it managed to fix the error but did not include any further information.

I upgraded to ngxs store v3.3.0 but the problem still exists.

**Comment by splincode** [comment]
Please add stackblitz example for reproduce

**Comment by neildonkin** [comment]
I have tried to, but it doesn't look like StackBlitz supports lazy loading of modules.  This issue only seems to occur when state is copied from a lazy loaded module

**Comment by neildonkin** [comment]
This SB reproduces the issue, which occurs even when user eager loaded modules, so it's not caused by lazy-loading:

https://ngxs-selectsnapshot.stackblitz.io

Thanks

**Comment by splincode** [comment]
try it
![image](https://user-images.githubusercontent.com/12021443/48789775-db4e7300-ecfe-11e8-8b79-b6d337087421.png)

**Comment by splincode** [comment]
And remove providers from AppModule

**Comment by neildonkin** [comment]
I tried that and I get the same problem:

`Cannot set property 'context' of undefined`

I've updated the SB

**Comment by splincode** [comment]
Interesting ))

**Comment by markwhitfeld** [comment]
It looks like you forgot to add the PreferencesState to the NgxsModule.forRoot(...) call. I adjusted this line and it all works.
Code was:
`imports: [BrowserModule, FormsModule, NgxsModule.forRoot([AnimalState])],`
Changed to:
`imports: [BrowserModule, FormsModule, NgxsModule.forRoot([AnimalState, PreferencesState])],`

see fixed version here: https://stackblitz.com/edit/ngxs-selectsnapshot-tk7yzt?file=src/app/app.module.ts

**Comment by neildonkin** [comment]
Thanks very much, @markwhitfeld.  This fixes the issue in the eager-loaded stackblitz sample, but my project is using `forFeature()` to lazy-load state classes in feature modules.  When I add my shared state class to `forFeature()` I now get this error:

```
Child state not found: function AssessmentTemplateState(assessmentService) {
        this.assessmentService = assessmentService;
    }
```
I tried moving the shared state class from `forFeature()` to `forRoot()` in `app.module.ts`, but I still get the same error,

Do you know why this is happening?

Thanks

**Comment by splincode** [comment]
@neildonkin maybe you forgot to import for feature

**Comment by markwhitfeld** [comment]
@neildonkin Would it be possible to provide a stackblitz showing the problem you are experiencing with the lazy loaded modules?

**Comment by neildonkin** [comment]
@markwhitfeld I'm afraid I don't have time ATM.  I've managed to pass my shared state from Module A to Module B using a property on shared service, which Module B then patches into its own state object via `ngxs store`.

I don't think the issue is with `ngxs store` after all, but rather how my lazy-loaded feature modules are completely isolated from each other.  I don't have any shared state classes in my application's shared module as yet, so that's probably why I can't get this to work using `selectSnapshot`.

I _do_ believe that shared state between lazy-loaded modules is a valid use case, so if there is anything you can do with `ngxs store` to facilitate this, I think it would be extremely useful to many developers.

Thanks for your help and please feel free to close this issue.
