### ISSUE TITLE
[question] how to set root state with init data on ngxs/store is first loaded?

### ISSUE THREAD

**Issue by Bomber77** [ngxs/store#665]
I use ngxs to manage all state in my application. 
I my state tree like this:
<code>{
bizData: [{...}, {...}],
searchState: {...}
...
}</code>

I want to persist state into localstorage without **bizData**, because it have a large of data, mybe over 20MB. So, I want to only persist the compoent state. Now, I write a plugin implements <code>NgxsPlugin</code> to restrict the state and save it into localstorage in handle function. But I have no way to read it and set to store at ngxs is first loaded.

Could someone help me? 
Thanks a lot in advance.

**Comment by splincode** [comment]
write more details what you want, I do not fully understand

**Comment by guilhermechiara** [comment]
If I do not misunderstood, what you want is to persist only part of your store into local storage, right?
If so, you simply can do that selecting which property you want to store:

`
NgxsStoragePluginModule.forRoot({ key: 'auth.token' }) // store only token from AuthState
`
