### ISSUE TITLE
Arrays or maps of SubStates

### ISSUE THREAD

**Issue by kayvanbree** [ngxs/store#666]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently you can't create a SubState within an array or map. 

## Expected behavior

I would like to be able to use a Map of RowStates  in a StateModel:

```javascript
import {State} from '@ngxs/store';

export interface RowStateModel {
  id: number; // Or string
}

export interface GridStateModel {
  id: number; // Or string
  rows: Map<number, RowState>;
}

/**
 * GridCollectionStateModel has a map of GridStates,
 * where the key refers to the dataname of the GridStateModel.
 */
export interface GridCollectionStateModel {
  grids: Map<number, GridState>;
}

@State<RowStateModel>({
  name: 'row',
  defaults: {
    id: -1
  }
})
export class RowState {}

@State<GridStateModel>({
  name: 'grid',
  defaults: {
    id: -1,
    rows: new Map<number, RowState>()
  }
})
export class GridState {}

@State<GridCollectionStateModel>({
  name: 'grid-collection',
  defaults: {
    grids: new Map<number, GridState>()
  }
})
export class GridCollectionState {}
```

This should create a state that looks like this:

```json
{
  "grids": {
    "GridState_0": {
      "id": 0,
      "rows": {
        "RowState_0": {
          "id": 0
        },
        "RowState_1": {
          "id": 1
        }
      }
    },
    "GridState_1": {
      "id": 1,
      "rows": {
        "RowState_0": {
          "id": 0
        }
      }
    }
  }
}
```

## What is the motivation / use case for changing the behavior?
In my application I have a use case where I have a complex data tree which would need to have a SubState. I have a collection of grids that can be displayed at the same time. Each grid has a dataname (unique identifier), which it uses to fetch the corresponding data. On top of that, each grid has a set of hierarchical rows, for which I also could use the SubStates.

**Comment by splincode** [comment]
this is a problem, since our states must be type safe and therefore they are plain objects

**Comment by kayvanbree** [comment]
Will there ever be some kind of array/dictionary of states? Or should we just work around it using selectors and such?

**Comment by splincode** [comment]
NGXS supports arrays, objects and primitives in the defaults field

**Comment by splincode** [comment]
```ts
@State({
 name: 'myState',
 defaults: { } || [ ] || Number() || String ()
})
```

**Comment by splincode** [comment]
Also we can usage of sub States for emulate tree map

**Comment by markwhitfeld** [comment]
@kayvanbree The general recommendation for handling heirarchical data in redux is to normalise it.
This would entail flattening it inthe same way that you would design relational tables, having keys for referring to their parents.

**Comment by kayvanbree** [comment]
I'll check out a way to normalize my data. I saw some library called Normalizr that I can maybe use...

**Comment by splincode** [comment]
I moved your request to another level of support
https://github.com/ngxs-labs/entity-state/issues/12
