### ISSUE TITLE
Dispatch decorator

### ISSUE THREAD

**Issue by vovikdrg** [ngxs/store#668]
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
CUrrently to dispatch action I need to inject store and do this

addAnimal(name: string) {
    this.store.dispatch(new AddAnimal(name));
  }

## Expected behavior
@dispatch()
addAnimal = (name: string) => new AddAnimal(name)

https://github.com/angular-redux/platform/blob/master/packages/example-app/src/app/animals/animal/component.ts

**Comment by splincode** [comment]
https://github.com/ngxs-labs/emitter

**Comment by markwhitfeld** [comment]
This was already raised as a PR: #447 
See my comment here: https://github.com/ngxs/store/pull/447#issuecomment-398701133

As mentioned by @splincode you could use the emmitter library in the labs area:
https://github.com/ngxs-labs/emitter
Although it does require that you abandon actions and use the `@Emitter(...)` and `@Receiver(...)` syntax.

That being said I think that there is value to create this as a separate library (as was recommended in https://github.com/ngxs/store/pull/447#issuecomment-399762256). 
If you create a library under your github account for this we will be happy to bring it into the ngxs-labs github organisation once it is ready.
It could be called `dispatch-decorator`.
These instructions could help you creeate the library: https://medium.com/@tomsu/how-to-build-a-library-for-angular-apps-4f9b38b0ed11 
Most of the code you would need to implement is in this PR: https://github.com/ngxs/store/pull/447/files
It seems the PR author moved on once we asked for it to be moved to a separate library and it never happened.

**Comment by splincode** [comment]
https://github.com/ngxs-labs/dispatch-decorator/issues/1

**Comment by splincode** [comment]
https://github.com/ngxs-labs/dispatch
