### ISSUE TITLE
Defaults of type date results in empty object

### ISSUE THREAD

**Issue by Eja26** [ngxs/store#672]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

When creating a new state of type Date, setting the default state as a new Date results in an empty object.

## Expected behavior

I would expect the default to be a new Date object.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/ngxs-date-default-state-bug

If you check the stackblitz logs, you can see that the state is not a date object.

## Environment

<pre><code>
Libs:
- @angular/core version: 6.0.0
- @ngxs/store version: 3.1.4

Browser:
- [X] Chrome (desktop) version 72.0.3621.0
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by Eja26** [comment]
Having looked at the store factory code, it seems to be caused by the object spread used on the default object. Seems like only way around this is to have the Date value as a property on the state, rather than the Date being the state object itself.

**Comment by splincode** [comment]
Storage must not be an instance of any object.
https://stackblitz.com/edit/ngxs-date-default-state-bug-v4wju2?file=app%2Fapp.component.ts
