### ISSUE TITLE
[docs] Meaning of @@UPDATE_STATE

### ISSUE THREAD

**Issue by paulstelzer** [ngxs/store#679]
## I'm submitting a...
[x] Documentation issue or request

## Current behavior
I have lazy loaded modules in my Angular Router. if I switching from one lazy loaded module to another, there is a `"@@UPDATE_STATE"` action shown in the Redux Dev Tools (see screenshot):

![chrome_2018-11-30_10-45-35](https://user-images.githubusercontent.com/20501666/49281534-1aae5980-f48d-11e8-8544-0de7e0c12dfe.jpg)

If I subscribe to a State selector in a service (`this.store.select(UserState.currentUser).subscribe(data => console.log(data));`) he shows the data although nothing changes. So I am wondering where this `"@@UPDATE_STATE"` comes from because I cannot find anything in the documentation

**Comment by eranshmil** [comment]
This happens when a feature state is being lazy-loaded.
