### ISSUE TITLE
Host Docs anywhere but gitbook.io

### ISSUE THREAD

**Issue by alvipeo** [ngxs/store#682]
It's really annoying that whenever I move from one topic to another on https://ngxs.gitbook.io I see the blank page (only light grey bars, no text). So I need to hit refresh EVERY SINGLE TIME!

Please fix this.

**Comment by splincode** [comment]
This is a problem of your network provider, I advise you to put a VPN browser extension chrome

**Comment by alvipeo** [comment]
From all the angular-related tech you're the only ones who use gitbook.
But fine, no big deal.

**Comment by markwhitfeld** [comment]
Any alternative you can suggest?
I also get that issue when using my mobile phone

**Comment by alvipeo** [comment]
Azure has Static website hosting and it's almost at no cost - [https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website](Static website hosting).

**Comment by eranshmil** [comment]
I guess that's related to my closed issue:
https://github.com/ngxs/store/issues/517
