### ISSUE TITLE
CI improvments

### ISSUE THREAD

**Issue by splincode** [ngxs/store#685]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

Circle CI, Karma.js

## Expected behavior

Usage instead:
Travis CI, Jest

## What is the motivation / use case for changing the behavior?

easy to set up for CI

**Comment by markwhitfeld** [comment]
What we have is working but I'm not attached to it. Haven't used Travis before
I would love to have jest instead of karma though. Definite benefit in that!
If you feel the urge go for it!
