### ISSUE TITLE
The way that keep the state on HMR

### ISSUE THREAD

**Issue by junimohano** [ngxs/store#692]
Is there any way to keep state on HMR?

Always refreshes the state on HMR as it is really inconvenient.

I couldn't find any resources so far.

Impossible to create features?

**Comment by kayvanbree** [comment]
Angular already has hot module replacement right? What's the point of using it the way described in the docs?

**Comment by splincode** [comment]
`@ngxs/hmr` coming soon

**Comment by kayvanbree** [comment]
@junimohano This can be closed right?

**Comment by splincode** [comment]
No

**Comment by eranshmil** [comment]
The plugin is not published yet, because there's an issue with lazy-loaded modules.
#719
