### ISSUE TITLE
[SSR] - Action dispatch does not work properly

### ISSUE THREAD

**Issue by squelix** [ngxs/store#696]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

Angular SSR does not wait actions to finish to render.

## Expected behavior

Wait for actions to finish to render the page.

## Minimal reproduction of the problem with instructions

Any simple project with NgXs and action in NgOnInit
```typescript
ngOnInit() {
    this.store.dispatch(new AnyAction());
}
```

## What is the motivation / use case for changing the behavior?

Make the SSR working with NgXs.

## Environment

<pre><code>
Libs:
- @angular/core version: 7.1.0
- @ngxs/store version: 3.3.0

 
For Tooling issues:
- Node version: 10  
- Platform:  Mac

## Related Issues

</code></pre>
https://github.com/ngxs/store/issues/465
https://github.com/angular/universal/issues/1061

**Comment by splincode** [comment]
You can try: `npm i @ngxs/store@dev -D`
Is the problem solved?

**Comment by Gorniv** [comment]
work with @ngxs/store@dev 
https://github.com/Angular-RU/angular-universal-starter/tree/ngxs

**Comment by splincode** [comment]
it will appear in the new version 3.4.0

**Comment by squelix** [comment]
Yes it works :)
