### ISSUE TITLE
Add silent warnings

### ISSUE THREAD

**Issue by splincode** [ngxs/store#701]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

My tests 

![image](https://user-images.githubusercontent.com/12021443/49499012-f92ee280-f87d-11e8-85c5-7c550a6a4988.png)

**Comment by markwhitfeld** [comment]
@splincode Why did you close this issue?

**Comment by markwhitfeld** [comment]
I have figured out a way to detect that we are in testing mode!
