### ISSUE TITLE
feat(ofAction): ofActionCompleted

### ISSUE THREAD

**Issue by Newbie012** [ngxs/store#710]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I just want to know when an action has been ended (no matter if it's successful. errored or canceled), I need to merge all of them into one observable, and then continue. 

## Expected behavior

A method called `ofActionComplete()` which will emit after an action has been completed no matter if it was successful, errored or canceled.

## What is the motivation / use case for changing the behavior?

Short example - I have a form with a `loading` indicator. `onDispatch` will set it to true. After the action has been completed, I would like to set the `loading` indicator back to false.

## Environment

<pre><code>
Libs:
- @angular/core version: 3.3.0
- @ngxs/store version: 3.3.0

For Tooling issues:
- Node version: XX  
- Platform:

**Comment by eranshmil** [comment]
I agree that this feature should be added, but in your use case I prefer creating isLoading key in the state and using it with an async pipe.

**Comment by markwhitfeld** [comment]
@Newbie012 Yes! Thank you for raising this. It was supposed to be added in v3 but it never happened.

It should rather be called `ofActionCompleted` to match the tense of the other ofAction methods and also to avoid a conflict with the `ofActionComplete` from v2 that was renamed to `ofActionSuccessful` v3.

Would you like to have a go at doing a PR for adding `ofActionCompleted`?
You will need to also add some tests to `packages\store\tests\action.spec.ts`

**Comment by Newbie012** [comment]
@eranshmil According to the last 2 apps I built, I had to do multiple load indicators. Therefore, I moved these indicators to the component level (I made a small state-management system in my components).

@markwhitfeld As I mentioned in the PR, I agree with you. Although, I think that `AuthStatus.Completed` should be kept.
