### ISSUE TITLE
HMR not working with lazy-loaded states

### ISSUE THREAD

**Issue by eranshmil** [ngxs/store#719]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

The state is being reset after @@UPDATE_STATE action.

## Expected behavior

The state will remain the same after the reload.

## Minimal reproduction of the problem with instructions
1. Navigate to a lazy-loaded module and update the relevant state.
1. Trigger HMR.
1. The state will reset to the default values after @@UPDATE_STATE.

All the relevant information and repro could be found here: https://github.com/eranshmil/ngxs-hmr-playground

![](https://github.com/eranshmil/ngxs-hmr-playground/raw/master/assets/hmr.gif)

## Environment

<pre><code>
Libs:
- @angular/core version: 7.1.3
- @ngxs/store version: 3.3.3-dev.master-bd16c95

Browser:
- [x] Chrome (desktop) version 70.0.3538.110
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 11.3.0
- Platform:  Mac
</code></pre>

**Comment by splincode** [comment]
I will deal with this issue soon

**Comment by splincode** [comment]
@eranshmil can check again

**Comment by eranshmil** [comment]
Working now. :)
