### ISSUE TITLE
ngxs/store 3.3.3 references @angular/core/testing (which greatly increases production bundle size)

### ISSUE THREAD

**Issue by michael42** [ngxs/store#722]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[X] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

ngxs/store 3.3.3 has a reference to `@angular/core/testing`, which increases production bundle size by 92 KiB in my case (post uglify, pre compression).

## Expected behavior

ngxs/store should not reference `@angular/core/testing`, because that dependency is intended to be used only for testing.

## Minimal reproduction of the problem with instructions
Download `https://registry.npmjs.org/@ngxs/store/-/store-3.3.3.tgz` and open `package/fesm2015/ngxs-store.js`:
```
import { InjectionToken, Injectable, NgZone, Optional, SkipSelf, Inject, ErrorHandler, isDevMode, Injector, NgModule } from '@angular/core';
import { map, filter, shareReplay, exhaustMap, take, takeUntil, catchError, mergeMap, defaultIfEmpty, distinctUntilChanged } from 'rxjs/operators';
import { Observable, Subject, BehaviorSubject, of, forkJoin, empty, throwError, from } from 'rxjs';
import { TestBed } from '@angular/core/testing'; // <<<<<<<<<<

[...]
```

To compare with 3.3.2, download `https://registry.npmjs.org/@ngxs/store/-/store-3.3.2.tgz` and open `package/fesm2015/ngxs-store.js`:

```
import { InjectionToken, Injectable, NgZone, Optional, SkipSelf, Inject, ErrorHandler, isDevMode, Injector, NgModule } from '@angular/core';
import { map, filter, shareReplay, exhaustMap, take, takeUntil, catchError, mergeMap, defaultIfEmpty, distinctUntilChanged } from 'rxjs/operators';
import { Observable, Subject, BehaviorSubject, of, forkJoin, empty, throwError, from } from 'rxjs';

[...]
```

## What is the motivation / use case for changing the behavior?

It's a regression from 3.3.2.

## Environment

<pre><code>
- Node version: v10.14.1
- Platform:  Linux
- webpack: 4.28.0
- @ngtools/webpack: 7.1.3
- terser-webpack-plugin: 1.1.0
</code></pre>

**Comment by splincode** [comment]
Regression
https://github.com/ngxs/store/pull/706

**Comment by markwhitfeld** [comment]
@michael42 Could you check what the difference between the `--prod` package sizes are?

I was told by one of the Anguar In Depth writers that the best way to check if Angular is in test mode was to check for the existence of TestBed. My concern was exactly this regarding the additional dependency but I was told that after tree shaking it would have insignificant effect on bundle size.
I do have other mechanisms to use for the check (that I originally used) but then moved to this recommended approach.
(see https://twitter.com/MarkWhitfeld/status/1072060124993384449)

**Comment by michael42** [comment]
That for the quick response, it all looks sensible and plausible, so I checked my issue more in-depth.

On my custom webpack build, it seems nothing from `@angular/core/testing.js` gets tree-shaken. I tried a few things, but nothing helped. So I tested it on a freshly created empty ng cli project and initially thought everything there would be fine, because I had only referenced the Module, not the actual store. When actually using the store, the size of the otherwise empty project jumps from 174 KiB to 277 KiB. Downgrading to 3.3.2 causes the size to drop to 199 KiB.

Here's my [testing repo](https://github.com/michael42/angular-core-testing-ngxs-tree-shaking-bug/), you can switch around between master (no ngxs), ngxs-3.3.3 and ngxs-3.3.2 branches and I checked in the [output files](https://github.com/michael42/angular-core-testing-ngxs-tree-shaking-bug/tree/ngxs-3.3.2/dist).

It probably worked earlier and since then something in the angular toolchain broke this tree shaking?

**Comment by markwhitfeld** [comment]
Thanks so much for your research! This is very concerning. I'll use one of the other mechanisms I was looking at at first and do a new release
