### ISSUE TITLE
feat: substates in @Select() should resolve to their state slice instead of blindly using state name

### ISSUE THREAD

**Issue by IlCallo** [ngxs/store#728]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
From docs:
```ts
  // Reads the name of the state from the state class
  @Select(ZooState) animals$: Observable<string[]>;
```

## Expected behavior
If ZooState is a substate, it's pretty obvious you want the returned slice to be the substate slice, not a not-existent slice at root level with the name of the substate.

## What is the motivation / use case for changing the behavior?
Being able to select a substate slice just by using the substate class, instead of creating a dummy selector which just returns the `getState()`.
This can be achieved by automatically returning the `getState()` result when doing `@Select(ZooState) animals$: Observable<string[]>;`, instead of relying on the state name.

Another way could be to check the states dependency graph and build the slice from there, but I guess you are already doing that in `getState()`

This is technically a breaking change, but I think it's pretty impossible that someone actually used substates in `@Select`, because of this weird behaviour, so it can probably be changed without a major release.

Current workaround for me:
```ts
  @Selector()
  public static dummy(state: MySubStateInterface): MySubStateInterface {
    return state;
  }

  ...

  @Select(SubState.dummy) private subState$!: Observable<MySubStateInterface>;
```

## Environment

<pre><code>
Libs:
- @angular/core version: 7.1.4
- @ngxs/store version: 3.3.4
</code></pre>

**Comment by markwhitfeld** [comment]
Would it be possible to demonstrate this issue using a stackblitz repro?

**Comment by splincode** [comment]
@IlCallo Please describe the problem in more detail.

**Comment by IlCallo** [comment]
Tryed it again today only using the SubState class as selector and everything worked 🤔
Not sure which was the problem at this point, but ty anyway!

If this works right away, then I guess this line into the docs is wrong/misleading?

```ts
  // Reads the name of the state from the state class
  @Select(ZooState) animals$: Observable<string[]>;
```

Because `@Select(ZooState)` doesn't resolve into `@Select(state => state[<ZooState state name>])` as stated there, but it also takes into account the substates relations

**Comment by splincode** [comment]
I can offer the following StateFactory. Which would allow to correct such errors and could enable us to automatically create the use of selectors

my.state.ts

```ts
import { State, StateFactory } from '@ngxs/store';

@State<StateModel>({
 name: 'state',
 default: {
   a: 1,
   b: {
     c: 2,
     d: {
       e: 3
     }
   }
 }
})
export class MyState extends StateFactory<StateModel> {
}
```

my.component.ts
```ts
class MyComponent {
  @Select(MyState.state) myState$: Observable<StateModel>;
}
```

```ts
class StateFactory<T> {
  @Selector() public static state(state: T): T {
     return state;
  }
}
```

**Comment by arturovt** [comment]
@markwhitfeld should we close this?
