### ISSUE TITLE
Is it possible to create a custom action reducer system?

### ISSUE THREAD

**Issue by user753** [ngxs/store#729]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

I want to create something like this but for ngxs
https://github.com/epeli/immer-reducer
For example I have 
```
export interface ZebraFood {
  name: string;
  hay: number;
  carrots: number;
}

export interface ZooStateModel {
  zebraFood: ZebraFood[];
}

```
And instead of
```
export class FeedZebra {
  static readonly type = '[Zoo] FeedZebra';
  constructor(public zebraToFeed: ZebraFood) {}
}
​
@State<ZooStateModel>({
  name: 'zoo',
  defaults: {
    zebraFood: []
  }
})
export class ZooState {
  @Action(FeedZebra)
  feedZebra(ctx: StateContext<ZooStateModel>, action: FeedZebra) {
    const state = ctx.getState();
    ctx.setState({
      ...state,
      zebraFood: [
        ...state.zebraFood,
        // this is the new ZebraFood instance that we add to the state
        action.zebraToFeed,
      ]
    });
  }
}
```
It would be something like 
```
class ZooState extends ImmerReducer<ZooStateModel> {
    feedZebra(zebraToFeed: ZebraFood) {  
        this.draftState.zebraFood.push(zebraToFeed);
    }
}
```

**Comment by splincode** [comment]
https://github.com/ngxs-labs/immer-adapter

**Comment by user753** [comment]
@splincode No, I am not talking about use of produce, it's about reducing action boilerplate

**Comment by splincode** [comment]
@user753 The documentation gives examples, then you yourself

**Comment by markwhitfeld** [comment]
@user753 I could actually be possible...
You could try to create your own decorator that wraps the existing `Action` decorator.
Something like:
```
@Mutation(FeedZebra)
feedZebra(draft: ZooStateModel, action: FeedZebra) {
  draft.zebraFood.push(action.zebraToFeed);
}
```
_Hint: the decorator is just a function!_
