### ISSUE TITLE
docs: remove API from documentation

### ISSUE THREAD

**Issue by splincode** [ngxs/store#730]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/12021443/50474437-f5e8cb80-09d1-11e9-8fc2-98eea9bdbb52.png)

## Expected behavior

@markwhitfeld Maybe we can remove API from documentation?

**Comment by markwhitfeld** [comment]
Are you reporting the issue with the API docs where some pages are missing or are you motivating for their removal altogether? Please could you provide more information with this issue.

**Comment by splincode** [comment]
API documentation is very outdated and not updated..
I suggest not to use it, as it did not bring benefit to anyone.
