### ISSUE TITLE
Run outside ngzone

### ISSUE THREAD

**Issue by uahic** [ngxs/store#739]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

NgZone is triggered on each state update

## Expected behavior

No NgZone involvement (optionally)

## What is the motivation / use case for changing the behavior?

I am using NgXS currently only as a model/state for shapes drawn with pixi.js. So basically several arrays of points and whether it is selected or not along with an id for each shape (polygonline). Now I am experimenting whether it is performance-wise OK to update the state when dragging a shape basically with the frequency of mouse-move events (throttled by pixi.js, but still quite alot) or if I need to hold updates back until the dragging ends (which adds more local states and complexity). I've noticed that ngZone gets triggered each time an update occurs, I've tried to wrap all NgXS dispatch and subscribe calls into the runOutsideAngular call but its not working, probably there are some explicit calls in the NgXS code to run within the ngZone? or is it just RxJS itself ?

PIXI.js itself wrapped such that it runs in my application outside of ngZone which works fine

## Environment

<pre><code>
Libs:
- @angular/core version: X.Y.Z
- @ngxs/store version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 

Linux (Ubuntu 16.04)
Others:

</code></pre>

**Comment by splincode** [comment]
Please add repo or stackblitz for reproduce

**Comment by uahic** [comment]
Here is a stackblitz example 
https://stackblitz.com/edit/ngxs-simple-hgumzb

**Comment by splincode** [comment]
you are right, all events take place in the zone
https://github.com/ngxs/store/blob/master/packages/store/src/store.ts#L45

**Comment by splincode** [comment]
https://github.com/ngxs/store/blob/master/packages/store/src/operators/zone.ts

**Comment by uahic** [comment]
Hmh ok I do understand the point that the UI needs to be updated in probably most of the use cases so it makes sense but - if my usecase is not totally out of place - maybe there could be an argument or alternative select method to not enter ngZone. I cant really argue since I just started two days ago with NgXS ... or the redux pattern in general :)

**Comment by splincode** [comment]
This is a complex conceptual question that we all have to answer with the team.

**Comment by markwhitfeld** [comment]
Realted to: 
#487 - Feature request : Option to turn off 'run outside of zone' feature
#563 - Warning: Navigation triggered outside Angular zone with router-plugin

**Comment by splincode** [comment]
Today we can use `outsideZone`, this will be released in 3.4.0

**Comment by uahic** [comment]
Excellent, thanks for the effort
