### ISSUE TITLE
📚[DOCS]:  Add Angular schematics to docs

### ISSUE THREAD

**Issue by odahcam** [ngxs/store#743]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

Couldn't find them on docs, found some docs while creating this issue on GH.

## Expected behavior

Schematics documentation right on my face, this is a very important Angular feature nowdays. Maybe it could be located under "Getting started" section.

## What is the motivation / use case for changing the behavior?

Because I found docs here (https://www.npmjs.com/package/@ngxs/schematics) but not on main docs.

**Comment by Carniatto** [comment]
Thank you for your feedback @odahcam. We are working on improving and extending the schematics for NGXS. As soon as we have a official release we'll update the documentation
