### ISSUE TITLE
Add documentation for example use substate

### ISSUE THREAD

**Issue by splincode** [ngxs/store#744]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

https://stackblitz.com/edit/ngxs-simple-wt7ovz?file=app/app.state.ts

![image](https://user-images.githubusercontent.com/12021443/50724385-a3a85880-10fd-11e9-94b4-e001719cd407.png)

so that the selector is not called every time, we need to come up with a workaround, for example, substates

**Comment by arturovt** [comment]
should be closed?
