### ISSUE TITLE
Developer guide for ngxs-labs

### ISSUE THREAD

**Issue by splincode** [ngxs/store#745]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Expected behavior

we need a developer guide for ngxs labs
- linter
- test
- ci
- tsconfig path

**Comment by eranshmil** [comment]
Wouldn't it be better if we just create a boilerplate repository?

**Comment by splincode** [comment]
as an example yes
