### ISSUE TITLE
🐞[BUG]: Dispatching an empty array from an @Action() sillences all future errors

### ISSUE THREAD

**Issue by thinkingmedia** [ngxs/store#759]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

I ran into the problem of dispatching an action, and the subscribe method was not being fired. There was no error and the observable completed.

```
    this.store.dispatch(new Action()).subscribe(()=> console.log('next'));
```

The above example did not log anything to the console, and there was no error message logged. When I used callbacks for the next, error and done callbacks I noticed that only the done callback was executed.

```
    this.store.dispatch(new Action()).subscribe(
          ()=> console.log('this is not logged'),
          ()=> console.log('this is not logged'),
          ()=> console.log('done is logged')
    );
```

## Expected behavior

The subscriber should always be executed once unless there is an error. In which case, the default error handler will log it or you provide your own error handler.

```
    this.store.dispatch(new Action()).subscribe(()=> console.log('next'));
```

## Minimal reproduction of the problem with instructions

I have been able to reproduce the problem by having an action handler dispatch an empty array. Any action that is handled afterwards will have all thrown errors silenced.

Here is a link to a stackblitz that reproduces the problem (open the console and see that no error message is logged when you click the problem).

https://stackblitz.com/edit/angular-kzkt8z

Here is source that reproduces the problem:

```
import { Action, Selector, State, StateContext, Store } from '@ngxs/store';
import { Component } from '@angular/core';

export class ActionError { static type = 'error'};
export class ActionEmptyArray { static type = 'two'};

@State<{}>({
  name: 'app',
  defaults: {}
})
export class AppState {
  @Action(ActionError)
  public actionError() {
      throw new Error('should be shown in the console');
  }

  @Action(ActionEmptyArray)
  public actionTwo(ctx: StateContext<{}>) {
      return ctx.dispatch([]);
  }
}

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  public constructor(public store: Store) {}

  public click() {
    this.store.dispatch([new ActionEmptyArray(), new ActionError()])
      .subscribe(()=>{
        console.log('next');
        // ^^^ this callback is not executed
      }, (e)=>{
        console.log('error',e);
        // ^^^ the error is not logged
      },()=>{
        console.log('done');
      })
  }
}

```

## What is the motivation / use case for changing the behavior?

Silencing the error of an action and not calling the "error" callback of a subscriber creates source code that is very difficult to debug. It took me a long time to figure out what was going on.

## Environment

<pre><code>
Libs:
- @angular/core version: 7.1.3
- @ngxs/store version: 3.3.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.14.1  
- Platform:  Windows 10 

Others:

</code></pre>

**Comment by thinkingmedia** [comment]
Any progress on this issue? It does not appear to have received any attention, and is a serious defect in the library. I could attempt to open a PR to fix the issue, but I have never worked on this library before and assumed someone with more experience could have quickly fixed it.

**Comment by arturovt** [comment]
NGXS 3.6.2 has been published recently. I have upgraded NGXS version in that stackblitz example that you provided and the `error` callback is invoked.

**Comment by netwarex** [comment]
Is it possible, that with Angular 10 this still happening?
