### ISSUE TITLE
Proposal: Quick documentation in readme about why it's simpler than ngrx

### ISSUE THREAD

**Issue by gregjacobs** [ngxs/store#760]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

Pretty simple, add the following blurb that is on the docs site into the repository's readme: 

```
NGXS is a state management pattern + library for Angular. It acts as a single 
source of truth for your application's state, providing simple rules for 
predictable state mutations.

NGXS is modeled after the CQRS pattern popularly implemented in libraries 
like Redux and NGRX, but reduces boilerplate by using modern TypeScript 
features such as classes and decorators.
```

Why add this? If I hear about NGXS from someone, searching 'ngxs' on Google brings up the GitHub repository first. The only thing that I'm presented with at this point is that "NGXS is a state management pattern + library for Angular". 

I already know that _NGRX_ is very popular, so why would I investigate yet another state manager? The only other thing that I see in the readme is a list of links. My immediate feeling at this point is that I don't want to spend my time clicking through them.

Adding the above text about reducing the boilerplate of Redux and NGRX would be a major selling point of NGXS right off the bat, and likely contribute to much more adoption of the library. Maybe even adding a quick example comparison of the same slice of state written in both libraries would be helpful as well.

**Comment by deebloo** [comment]
The only thing I want to avoid is making the selling point of NGXS a knock of NGRX

**Comment by gregjacobs** [comment]
100% agree, because NGRX and the ideas behind it are excellent. But software evolves, and better patterns are found. The amount of boilerplate needed for Redux and NGRX is a problem in and of itself at this point, hence the evolution of NGRX -> NGXS. Just need to let people know that there is a better option :)

**Comment by gregjacobs** [comment]
Updated the title too to reflect this view

**Comment by splincode** [comment]
https://github.com/ngxs-labs/emitter

New pattern :)

**Comment by deebloo** [comment]
I would want to point out that there is a DIFFERENT options. I know I am being picky about wording here but I think it is important

**Comment by gregjacobs** [comment]
Well, at bare minimum, insert that little blurb of text that I mentioned earlier which already exists on the documentation site. That might do a lot right there

**Comment by markwhitfeld** [comment]
I think that there is value in doing this, although we don't really need to get into a deep comparison and we want to make it clear that there is room for each approach in the ecosystem. We would really want to be highlighting the aspects of NGXS that would be attractive if they align with your priorities.

@deebloo What would you propose as a blurb?

**Comment by splincode** [comment]
updated README.md
