### ISSUE TITLE
🚀[FEATURE]: move '@ngxs/schematics' under '@ngxs/store' so we can do 'ng add @ngxs/store' instead 'ng add @ngxs/schematics'

### ISSUE THREAD

**Issue by kuncevic** [ngxs/store#769]
The standard way of adding an angular library/package through cli schematics  is `ng add ${library-name}`.

Currently in order to do so with `@ngxs/store` you have to actually use another package name -  `@ngxs/schematics` which you always have to remember about and it is also could be confusing for some number of folks out there as usually you do `ng add ${library-name}` ref: https://github.com/ngxs/store/issues/591 

So my proposal is to move the  `@ngxs/schematics` logic under the `@ngxs/store` so `@ngxs/store` could be simply added by `ng add @ngxs/store`

**Comment by deebloo** [comment]
I think this sounds like a good idea.

**Comment by Waterstraal** [comment]
I agree. Also, `ng add` is not even mentioned in the Installation section of ngxs.io: https://ngxs.gitbook.io/ngxs/getting-started/installation

**Comment by arturovt** [comment]
Closing since the docs will be updated when we have this feature.
