### ISSUE TITLE
Class SomeClass incorrectly implements interface 'StorageEngine'...

### ISSUE THREAD

**Issue by YogliB** [ngxs/store#771]
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
When trying to implement a custom storage engine as described in the [docs](https://ngxs.gitbook.io/ngxs/plugins/storage#custom-storage-engine) I get an error :
```
Class 'IonicStorageEngine' incorrectly implements interface 'StorageEngine'.
  Type 'IonicStorageEngine' is missing the following properties from type 'StorageEngine': removeItem, clear, key
```

## Expected behavior
No error or more info in the docs.

## Minimal reproduction of the problem with instructions

```
import { NgModule } from '@angular/core';
import { IonicStorageModule } from '@ionic/storage';
import { Storage } from '@ionic/storage';
import {
  NgxsStoragePluginModule,
  STORAGE_ENGINE,
  StorageEngine,
} from '@ngxs/storage-plugin';
import { NgxsModule } from '@ngxs/store';

export class IonicStorageEngine implements StorageEngine {
  public length: number;

  constructor(private storage: Storage) {}

  public getItem(key: string): Promise<any> {
    return this.storage.get(key);
  }

  public async setItem(key: string, value: any) {
    await this.storage.set(key, value);
    this.length = await this.storage.length();
  }
}
@NgModule({
  imports: [
    NgxsModule.forRoot([]),
    NgxsStoragePluginModule.forRoot(),
    IonicStorageModule.forRoot(),
  ],
  providers: [
    {
      provide: STORAGE_ENGINE,
      useClass: IonicStorageEngine,
    },
  ],
})
export class MyModule {}
```

## What is the motivation / use case for changing the behavior?
Implementing a custom storage engine.

## Environment
Libs:
- @angular/core version: ~7.0.0
- @ngxs/store version: ^2.2.0
- @ngxs/storage-plugin: ^3.3.4
 
Others:
IDE: VS Code
Relevant plugins: TSLint

**Comment by deebloo** [comment]
Doc is def out of date there. Thanks you for reporting!

**Comment by splincode** [comment]
@markwhitfeld ping!

**Comment by markwhitfeld** [comment]
@splincode pong! 😝
The docs will need to be corrected.
@YogliB Are you willing to try a PR?

**Comment by YogliB** [comment]
@marlwhitfeld
I was going to, but I didn't understand what the 'key' method is doing, and how to implement it...

**Comment by larscom** [comment]
> @markwhitfeld
> I was going to, but I didn't understand what the 'key' method is doing, and how to implement it...
> 
> You can see it [here](https://github.com/ngxs/store/blob/master/packages/storage-plugin/src/symbols.ts#L67), what is its purpose?

was wondering exactly the same.. doesn't make sense to me

**Comment by markwhitfeld** [comment]
It really doesn't seem like a useful method. I don't think we use it, so it might be a candidate for removal.
Would that be a breaking change? It is reducing the requirement on API implementation so I think that it would actually not be a breaking change.
@ngxs/core team what do you think?

**Comment by YogliB** [comment]
@markwhitfeld Can I PR this? (With a docs update)

**Comment by homj** [comment]
@YogliB in your example above, you're using @ionic/storage to store the data, which is an async storage. I'm wondering whether your example actually works, since @ngxs/storage-plugin doesn't seem to support an async StorageEngine

**Comment by YogliB** [comment]
@homj 
It doesn't, we have the [async storage plugin](https://github.com/ngxs-labs/async-storage-plugin).

I wonder though if an async storage will works with the [data plugin](https://github.com/ngxs-labs/data).

**Comment by homj** [comment]
@YogliB thanks for the quick heads-up!
Regarding the data plugin: yeah, i just stumbled across this too and had the same question pop up in my mind.
Also: the async storage plugin seems to still have the `key(...)` method that you removed from StorageEngine. Should this plugin be updated to reflect the changed API of StorageEngine?

I'm sorry if I'm asking stupid questions, I'm really new to NGXS and currently evaluating to switch from Ngrx

**Comment by splincode** [comment]
@YogliB @homj I will add an example with asynchronous data tomorrow (ngxs-labs/data)
