### ISSUE TITLE
Error caught after dispatch is still logged

### ISSUE THREAD

**Issue by axelboc** [ngxs/store#781]
## I'm submitting a...

```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other...
```

## Current behavior

I have an action A with an action handler that throws an error (either with `throw` or RxJS' `throwError`). When I dispatch action A, then pipe it with `catchError`, the subscriber's `error` callback is not called as expected, but the error **still gets logged to the console**.

```ts
store
  .dispatch(new ActionThatThrows())
  .pipe(catchError(() => of('foo')))
  .subscribe();
```

## Expected behavior

The error should not be logged to the console, since it is properly caught.

When I remove the `dispatch` and throw the error directly, the error is not logged (as expected):

```ts
throwError(new Error('my oh my'))
  .pipe(catchError(() => of('foo')))
  .subscribe();
```

## Minimal reproduction of the problem with instructions

- https://stackblitz.com/edit/ngxs-simple-uagu8f
- Open the console and click on "Click Me".
- The error is logged, followed by `next foo` and `complete`.

## Environment

```
Libs:
- @angular/core version: 7.2.0
- @ngxs/store version: 3.3.4-dev.master-fa8d5a1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 64.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
```

**Comment by eranshmil** [comment]
This isn't related to NGXS, you should implement an ErrorHandler to catch this kind of exceptions.

**Comment by axelboc** [comment]
My point is that the `ErrorHandler` is not supposed to be called at all, since the error is supposed to have been caught with `catchError`. It works fine without the `dispatch`, which makes me think it's related to NGXS.

**Comment by eranshmil** [comment]
The observable returned from the dispatch isn't the same one as returned in the state.
Please read this comment, that might be related.
https://github.com/ngxs/store/issues/606#issuecomment-435174322

**Comment by axelboc** [comment]
I think I'm in a similar situation to this [StackOverflow user](https://stackoverflow.com/questions/50673555/can-we-handle-ngxs-action-errors-via-ofactionerrored-without-going-to-default). He's also trying to throw an error inside an action but instead of subscribing to the observable returned by `dispatch`, he makes use of the action handler `ofActionErrored()`. Like me, it seems that the action gets logged by the default `ErrorHandler` before he can catch it.

It seems that the only way for an error we know might happen to not be logged is to catch it within a state action, for instance by piping `catchError` after a webservice call in a state action:

```ts
@Action(GetAnimals)
getAnimals() {
  return this.animalsService.get().pipe(
    tap((response) => { ... }),
    catchError((err) => { ... })
  );
}
```

There are cases, however, where it makes more sense to catch the error outside of the state. In my case, I was trying to test whether an unexpected HTTP error response was properly re-thrown from a state action. By piping `catchError` after `dispatch`, I was able to catch the error and make the test pass, but the error was still being logged to the console in ugly red letters 😄. I also tried `dispatch(...).toPromise()` with a `try`/`catch` block but got the same result.

If this is by design, then I don't see how to go about testing it without mocking RxJS' `throwError` operator... As a temporary workaround, I had to provide a noop `ErrorHandler` in my tests so the error wouldn't get logged. Not a great thing to do, for obvious reasons...

**Comment by axelboc** [comment]
Following up on this, I've just come across another use case for catching errors outside of the state. I use a `LoadScript` action to load external scripts dynamically. Here's a summary of the code:

```ts
@Action(LoadScript)
loadScript(ctx: StateContext<MyStateModel>, action: LoadScript) {
  [...] // patch state
  return myObservableBasedScriptLoader(action.src).pipe(
    switchMap(() => ctx.dispatch(new LoadScriptSuccess())),
    catchError(() => ctx.dispatch(new LoadScriptFailed()))
  );
}


@Action(LoadScriptFailed)
scriptError(ctx: StateContext<MyStateModel>, action: LoadScriptFailed) {
  [...] // patch state
  return throwError(new Error('Failed to load script'));
}
```

In most cases, I want a script that fails to load to throw a big red error. However, when an analytics script fails to load, for instance, which happens often with ad blockers, I just want to log a warning to the console.

```ts
try {
  await this.store.dispatch(new LoadScript('https://my.analytics.com')).toPromise(); // note the typo
} catch (err) {
  console.warn('Unable to load my analytics');
}
```

With the code above, if I try to load the script with the wrong URL, both the `Failed to load script` error and the `Unable to load my analytics` warning are logged to the console (error first, warning second). Interestingly, the error is actually logged twice before the warning! I assume this is because of the nested `LoadScriptFailed` action.

Again, if there's a better (and as straightforward) way to implement this error handling use case, I'm all ears, but to me this seems like a limitation of NGXS that is worth resolving.

**Comment by axelboc** [comment]
Is there a specific reason for NGXS to catch errors during dispatch? By not catching the error, wouldn't Angular's `ErrorHandler` service receive the uncaught error anyway?

Basically, [this specific line](https://github.com/ngxs/store/blob/0fbf2fb1339d87c484cdfb30d5b4012ef1e6298d/packages/store/src/internal/dispatcher.ts#L47) is causing me a lot of headaches. Just today, I tried to inject the `Store` in my custom error handler service in order to send a snapshot of the store with every error, but I got a cyclic dependency error (caused, I assume, by the fact that NGXS' internal dispatcher [injects `ErrorHandler`](https://github.com/ngxs/store/blob/0fbf2fb1339d87c484cdfb30d5b4012ef1e6298d/packages/store/src/internal/dispatcher.ts#L25)).

**Comment by splincode** [comment]
@arturovt @markwhitfeld ping

**Comment by axelboc** [comment]
Any update on this by any chance?

**Comment by splincode** [comment]
@axelboc could you help send us a fix (pull request)

**Comment by axelboc** [comment]
The code seems to have changed a little since then:

```ts
result.subscribe({
  error: error =>
    this._ngxsExecutionStrategy.leave(() => this._errorHandler.handleError(error))
});
```

I would just remove the error handler and keep only `result.subscribe()`, but I didn't write the code so I'd be good to now what the intent was initially, and if the change would have any impact I'm not seeing.

**Comment by arturovt** [comment]
I've thoughtfully read you issue. Yeah, it's a bit late, I know :joy:

---

I'm really surprised that you decided to dig into the core of our library. It's not sarcasm, it's really great!

---

> I would just remove the error handler and keep only result.subscribe()

This is not possibe as this is a cornerstone. This is a breaking change. Most users provide custom error handler and track errors there (e.g. via Sentry).

---

You've got to `catchError` in your action handlers, before that piece of code `result.subscribe(...)` where we listen to the `onError` event and invoke `handleError`.
