### ISSUE TITLE
Add docs for store/operators

### ISSUE THREAD

**Issue by splincode** [ngxs/store#786]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

**Comment by arturovt** [comment]
@splincode do we close this one?
