### ISSUE TITLE
Support reload storage when another tabs

### ISSUE THREAD

**Issue by splincode** [ngxs/store#793]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

https://medium.com/@mehmetakifalp/keeping-multiple-tab-in-sync-using-ngxs-state-management-library-rxjs-and-localstorage-840c0bf615fa

**Comment by mehmetakifalp** [comment]
Hello @splincode 

I m the author of the post you've shared in description. I dont understand which feature you wants to support? 

best,

**Comment by splincode** [comment]
synchronization with fromEvent(window, 'storage')

**Comment by mehmetakifalp** [comment]
> synchronization with fromEvent(window, 'storage')

wow.. could be awesome feature, maybe some plugin?

**Comment by splincode** [comment]
https://github.com/ngxs/store/blob/master/docs/plugins/storage.md

**Comment by splincode** [comment]
Could you add this feature to the plugin with any Pull request?

**Comment by mehmetakifalp** [comment]
Of course.. I would like to help. Let me inspect storage plugin first. Is there any guide?I can follow for contribute the plugin?

**Comment by arturovt** [comment]
should we close this?

**Comment by dinbtechit** [comment]
@splincode  - I am using ngxs storage plugin, as but it doesn't sync with other tabs. How did you manage to sync your local storage with other tabs? The approach the medium post uses is a bit of a manual work. 

Just curious, Is there a simpler way to accomplish this?
