### ISSUE TITLE
Regression with action type

### ISSUE THREAD

**Issue by splincode** [ngxs/store#794]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/12021443/51796801-d7ad0000-2209-11e9-8fe1-2b493d970069.png)

## Expected behavior

@deebloo in v3.3.0
earlier I could safely use objects

**Comment by deebloo** [comment]
Fix is in master now
