### ISSUE TITLE
[Router Plugin] Feature request - router history

### ISSUE THREAD

**Issue by YogliB** [ngxs/store#795]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
Navigation history isn't stored.

## Expected behavior
A navigation stack will be stored in the Router store and a 'NavigateBack' Action will be added.

## What is the motivation / use case for changing the behavior?
Remove the need to manage the navigation stack outside the RouterStore.

</code></pre>

**Comment by arturovt** [comment]
@YogliB Why wouldn't you just use the [`Location.prototype.back`](https://angular.io/api/common/Location#back)?

**Comment by YogliB** [comment]
@arturovt 
Two reasons, first, I want routing to be handled by the store for debugging and time-traveling options.
Second is that I'm using Ionic (v4) and the routing animations don't work with `Location.prototype.back`.

**Comment by arturovt** [comment]
@YogliB 
Okay, I'm just gathering more information if we really need this feature. How would you like to see that? Just some action, as you mentioned, `NavigationBack` that can be dispatched and the user will be redirected to the previous URL, right?

**Comment by markwhitfeld** [comment]
I think that this requirement is best implemented as custom code in your app.
I suggest creating a store called `RouterHistory` that records the history by listening to the `RouterNavigation` action, and an associated `NavigationBack` action that pops the latest location off the stack and then also pops and navigates to the previous one.

**Comment by arturovt** [comment]
@markwhitfeld 
Yeah, basically the realisation is not complicated. I just thought that we would need to increase the `@ngxs/router-plugin` bundle by adding actions and business logic, that people might not need.

**Comment by arturovt** [comment]
@markwhitfeld Should we close this?

**Comment by YogliB** [comment]
Thanks for the comments 🙂

**Comment by emzet** [comment]
@arturovt I would like to implement this behavior as custom code (as was suggested), but do not really like the idea of extra state `RouterHistory` . I would like to "re-use" existing `router` state. Now it is not possible, as I try to load custom state named `router` application throws error. So the question is, is there a possibility to extend `router` state provided by this plugin, to implement various custom actions or not (because of design) ?
