### ISSUE TITLE
Action 'type' property - Additional Documentation

### ISSUE THREAD

**Issue by techy2493** [ngxs/store#812]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

Identifies Type as a property of action, and has examples showing it differing based on name.

## Expected behavior

Would like to see a more explicit definition of this type property, explaining what it is used for and that it must be globally unique. 

Some additional troubleshooting steps mentioning to double check type uniqueness if multiple actions are being invoked.

It may be useful to throw an error if two states with conflicting actions are added to the store (unless there is a useful use case for this)

## Minimal reproduction of the problem with instructions
export class SetAssignmentPrimary {
  static readonly type = '[assignment] Update assignments';
  constructor(public payload: AssignmentApplicatorPayload) {}
}
export class AddAssignmentSecondary {
  static readonly type = '[assignment] Update assignments';
  constructor(public payload: AssignmentApplicatorPayload) {}
}

Both actions will be invoked when either action is dispatched to the store.

## What is the motivation / use case for changing the behavior?

Make troubleshooting faster and easier. A more concise description of the property may prevent poor implementation ahead of time.

## Environment

<pre><code>
Libs:
- @angular/core version: X.Y.Z
- @ngxs/store version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by arturovt** [comment]
@techy2493 

I'm not aware of what's going on in this issue :relaxed: Would you like to describe more clearly what would you like to achieve?

**Comment by arturovt** [comment]
I'd like to tell you frankly, a year and a half of using NGXS - I've never had a motivation to name action types in the same way.

The main point is that actions shouldn't be treated as interchangable. Actually giving the consistent type - will give an opportunity to debug easier.

Imagine a developer comes to your project, he sees multiple actions with the same type - `'[assignment] Update assignments`, that would definitely make him confused. At some point you also get confused because you don't know what action was dispatched - set assignment or add assignment.
