### ISSUE TITLE
Selecting a slice of data from a store within a library doesn't work

### ISSUE THREAD

**Issue by kayvanbree** [ngxs/store#813]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

It is possible to use a selector from a store that has been defined in a module, but tt is impossible to use a selector from a published library. 

## Expected behavior

I would like to be able to use selectors from a published library.

If this is not a bug but intended then this can be a feature request.

Is there reasoning behind not being able so select a slice of data from a library?

## Minimal reproduction of the problem with instructions

https://github.com/kayvanbree/ngxs-library-selector-test

- Clone the repo above
- run `npm install`
- run the build:lib script
- run `npm serve`

You won't be able to get any slice of the state of a store in a library. 

## What is the motivation / use case for changing the behavior?

I am working on an application where I have a library with a store, included in an application with a store. I want to be able to select a slice of data from the application.

## Environment

```
"dependencies": {
    "@angular/animations": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "@ngxs/devtools-plugin": "^3.3.4",
    "@ngxs/store": "^3.3.4",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.11.0",
    "@angular-devkit/build-ng-packagr": "~0.11.0",
    "@angular/cli": "~7.1.4",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.2.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": ">=0.29.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
```

**Comment by kayvanbree** [comment]
I have been experimenting a bit. It seems to work if I just add the same store to the main application. Then I can use the store from the application and from the library. Will this have negative side effects?

**Comment by splincode** [comment]
Add SelectorTestModule to public API and insert your module into usage place

**Comment by kayvanbree** [comment]
Usage place?

**Comment by splincode** [comment]
Where your lazy module
