### ISSUE TITLE
Calling a static function in selector function will result in undefined value

### ISSUE THREAD

**Issue by ogix** [ngxs/store#816]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

If I call a helper static function from my selector function it does not continue afterwards and my observable emits undefined value.

## Expected behavior

I should be able to call a static function and the flow should continue.

## Minimal reproduction of the problem with instructions
```
  @Selector() 
  static pandas(state: string[]) {
    this.doNothing();
    return state.filter(s => s.indexOf('panda') > -1);
  }

  static doNothing() {}
```

## What is the motivation / use case for changing the behavior?

To be able to write complex selectors using helper functions 

## Environment

<pre><code>
Libs:
- @angular/core version: 7.1.4
- @ngxs/store version: 3.3.3

Browser:
- [x] Chrome (desktop) version 71
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by splincode** [comment]
Create stackblitz example please

**Comment by ogix** [comment]
Here you are: https://ngxs-simple-demo-9z2ckp.stackblitz.io

**Comment by arturovt** [comment]
@splincode `this` is `undefined` inside selector, just call `console.log(typeof this)`, also it's wrapped in `try-catch` thus there is no exception like `cannot read property 'doNothing' of undefined`

**Comment by arturovt** [comment]
@ogix this is related to context binding, I'll try to have a look this evening

**Comment by ogix** [comment]
ok, thanks!

**Comment by ogix** [comment]
I looked at the source code and found this.
https://github.com/ngxs/store/blob/bf13efed028ec2bbe3ca1561730237ad7f796abc/packages/store/src/utils/selector-utils.ts#L20

 Shouldn't this be written in TS syntax?
`const wrappedFn = (...args: any[]) => {`

**Comment by splincode** [comment]
https://github.com/ngxs/store/pull/818

**Comment by arturovt** [comment]
@ogix fixed man :rocket:
