### ISSUE TITLE
Logger does not close group in case of an error

### ISSUE THREAD

**Issue by karlhaas** [ngxs/store#817]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
The logger does not close the log group in case of an error which causes nested log groups in the console

## Expected behavior
The logger should close the group in case of an error using rxjs finalize

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.3
- @ngxs/store version: 3.3.4

Browser:
- [x] Chrome (desktop) version 71.0.3578.98
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by eranshmil** [comment]
I also noticed that and wrote for myself to fix that in the future. :)
Would you like to try fixing that with a PR?

**Comment by eranshmil** [comment]
I got to a point in my own application that this is just annoying, so I created a PR to fix that. #831
