### ISSUE TITLE
feat(store): Get selector from variable name

### ISSUE THREAD

**Issue by Steven-Harris** [ngxs/store#819]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

_state_
```
...
@Selector()
public static pandas({pandas}: ZooStateModel): string[] {
    return pandas; // or some complex select
}
...
```
_component_
```
@Select(ZooState.pandas)
public pandas$: Observable<string[]>;
```

## Expected behavior

```
@Select(ZooState) 
public pandas$: Observable<string[]>;
```

## What is the motivation / use case for changing the behavior?

It is a little lazy? yes. Could be nice though. I wanted to throw this out there as I think it could be doable to use the variable name to get the selector on the state. To be honest the docs makes it seem like you can already, but in practice I have not gotten it to work. Maybe this is an issue but for now I am listing this as a feature request.

**Comment by YogliB** [comment]
This should work right out of the box, read [here](https://ngxs.gitbook.io/ngxs/concepts/select).

```
import { Select } from '@ngxs/store';
import { ZooState, ZooStateModel } from './zoo.state';

@Component({ ... })
export class ZooComponent {
  // Reads the name of the state from the state class
  @Select(ZooState) animals$: Observable<string[]>;

  // Uses the pandas memoized selector to only return pandas
  @Select(ZooState.pandas) pandas$: Observable<string[]>;

  // Also accepts a function like our select method
  @Select(state => state.animals) animals$: Observable<string[]>;

  // Reads the name of the state from the parameter
  @Select() zoo$: Observable<ZooStateModel>;
}
```

**Comment by arturovt** [comment]
@Steven-Harris could you describe in more details what do you want to achieve and what problem it's solving?

**Comment by Steven-Harris** [comment]
Feel redundant to use dot notation here when the variable name could be used instead. The results in only have to specify the state in the select decorator. And then the variable name would be match to the selector in the state you're trying to use.

**Comment by splincode** [comment]
That's problem for AOT

**Comment by arturovt** [comment]
@splincode I'm just really trying to understand what problem does it solve. Actually, you anyway import state, right. So what's the problem to write `@Select(ZooState.pandas)`? This doesn't affect performance, because in case that described in this issue - we will need to do ton of `if`s.

**Comment by splincode** [comment]
@arturovt I basically do not see the point in this

**Comment by Steven-Harris** [comment]
@splincode, it is less code...

**Comment by arturovt** [comment]
@Steven-Harris sorry, maybe I missunderstand something, but is there any real code difference:
```TS
// between this
@Select(ZooState)
pandas$;
// and this
@Select(ZooState.pandas)
pandas$;
```

Also when you imperatevily specify `pandas` selector - you will not get confused and your developers too.

**Comment by splincode** [comment]
@Steven-Harris your code will confuse everyone, it does not make sense to write less code if you do not immediately understand what it does
