### ISSUE TITLE
🐞[BUG]: Redux store shows incorrect order of actions

### ISSUE THREAD

**Issue by natrayanp** [ngxs/store#839]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

app.state.ts
---------------
<pre><code>
import { State, Action, StateContext, Selector } from '@ngxs/store';
import { App } from '../models/app.models';
import { setAppDefaults, delAppDefaults, AppDefaultsSetSuccess, AppDefaultsSetFailed } from './app.actions';

export const getAppInitialState = (): App => ({
    appdefaults: {    
        entityid: '',
        countryid: ''
        },
    cart: []
});

@State<App>({
    name: 'app',
    defaults: getAppInitialState()
})
export class AppState {
    constructor() { }
 @Action(setAppDefaults)
    set(ctx: StateContext<App>, { payload }: setAppDefaults) {      
        ctx.patchState({
            appdefaults: payload
        });        
        ctx.dispatch(new AppDefaultsSetSuccess());
    }
    @Action(AppDefaultsSetSuccess)
    setSucess() {
        console.log("app defaults set successful");
    }
</code></pre>
app.component.ts
-------------------------
app.component dispatches the setappdefault action which is triggering the deault value to be set in store and post that appdefaultsetsuccess to be triggered.
<pre><code>
this.store.dispatch(new setAppDefaults(defaultval));
</code></pre>
Once the app is initialised the order in which the actions shown is incorrect.

## Expected behavior

In the redux tool i would expect to see the actions in the order of
1) setAppDefaults
2) AppDefaultsSetSuccess

However it shows in the other way (refer to the screen shot)
1) AppDefaultsSetSuccess
2) setAppDefaults

![image](https://user-images.githubusercontent.com/31285863/52710620-be0e0580-2fca-11e9-9120-1799a0612c72.png)
## Environment

<pre><code>
Libs:
 @angular/core version: 7.2.4
 @ngxs/store version: 3.3.4

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v11.9.0
- Platform:  Linux (Kubuntu)

**Comment by eranshmil** [comment]
Related to #115 and #139.

**Comment by johnwalshuk** [comment]
My example goes like this:
LoginCredentials -> api call -> http interceptor dispatches a route redirection on any 401 -> api error is thrown back to the original LoginCredential action which modifies the state to store the http error response.

But it seems that the route redirection is done last, Ive done a gif to show an example, if i step back 1 place i get the error message in the UI as expected, it seems as though because the router action is sent last it sends out some invalid/older state to my @Selects, even though the diff states its the same:

![ngxs](https://user-images.githubusercontent.com/9977602/76511902-b6c65f00-644b-11ea-835d-5c343f990d7e.gif)

any ideas?

**Comment by asdmem** [comment]
Hi guys, wrote decorator to fix this.

```typescript
import { Observable, Subject } from 'rxjs';
import { StateContext } from '@ngxs/store';

export function Async(): MethodDecorator {
  return function (
    _target: Object,
    _name: string | symbol,
    descriptor: TypedPropertyDescriptor<any>
  ): TypedPropertyDescriptor<any> {
    const orignalFn = descriptor.value as Function;

    descriptor.value = function (...args: any[]) {
      console.warn('ARGS', args);
      console.log(orignalFn);

      const context: StateContext<any> = args[0];

      const originalDispatch = context.dispatch;

      context.dispatch = function(actions: any | any[]) {
        const subject = new Subject<void>();

        window.queueMicrotask(() => originalDispatch(actions).subscribe(() => subject.next()));

        return subject.asObservable();
      }

      const result = orignalFn.call(this, ...args);

      if (result == null) {
        return result;
      }

      if (result instanceof Observable) {
        result.subscribe();
      }

      return Promise.resolve();
    };

    return descriptor;
  };
}
```
usage 
```typescript
 @Action(action)
 @Async()
 async findByFilters(ctx: Context, action: Action): Promise<void> { }
```

**Comment by splincode** [comment]
@asdmem What do you think about `AsyncAction` and send pull request?

**Comment by asdmem** [comment]
What do you guys think about this?

```typescript
export function AsyncAction(
  actions: ActionType | ActionType[],
  options?: ActionOptions
): MethodDecorator {
  const actionDecorator = Action(actions, options);

  return function (
    target: Object,
    name: string | symbol,
    descriptor: TypedPropertyDescriptor<any>
  ): TypedPropertyDescriptor<any> {
    actionDecorator(target, name, descriptor);

    const orignalFn: Function = descriptor.value;

    descriptor.value = function (context: StateContext<any>, action: any) {
      const ctor = function () {};
      ctor.type = '[ASYNC START] ' + Object.getPrototypeOf(action).constructor.type;

      const customAction = { ...action };
      Object.setPrototypeOf(customAction, ctor);

      context.dispatch(customAction);

      return orignalFn.call(this, context, action);
    };

    return descriptor;
  };
}
```

This code almost change nothing about current behaviour and add dummy action with [ASYNC START] + type action

**Comment by splincode** [comment]
@markwhitfeld @arturovt what do you think?

**Comment by arturovt** [comment]
@splincode you know better than anyone that all features we transfer to NGXS-labs. I assume that no one doesn't mind. You could create a repo for @asdmem there. Wtyd? :wink:

**Comment by arturovt** [comment]
This issue seems to be stalled and I’m not able to reproduce it for now. This also needs a minimal reproducible example. Feel free to re-open if you experience the same issue with the latest version and the reproducible example is provided.
