### ISSUE TITLE
Error ocurred while deserializing the store value, falling back to empty object.

### ISSUE THREAD

**Issue by splincode** [ngxs/store#857]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/12021443/53093457-87833e00-3528-11e9-86dc-1391e2a9c8d8.png)

**Comment by arturovt** [comment]
should we close?
