### ISSUE TITLE
logger-plugin should log payload for all variable names (not just 'payload')

### ISSUE THREAD

**Issue by pvamshi** [ngxs/store#871]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
If my Action has a structure like this 
```typescript
export class AddUser {
    readonly type = '[User page] Add user'; 
    constructor(public user: User){}   // ---> This wont appear in log 
}
```

When I dispatch the action. Logger ignores the user data . It  works only if the payload is in 'payload' param like this : 
```typescript
export class AddUser {
    readonly type = '[User page] Add user'; 
    constructor(public payload: User){} // ---> This appears in log 
}
```

## Expected behavior
Logger should log payload for any params. I guess we should even allow multiple params.

## Minimal reproduction of the problem with instructions
Rename , payload key to anything other than 'payload' and check logs. 

## What is the motivation / use case for changing the behavior?
Having custom names make it self-explanatory on what the action contains and useful while handling in store. 

Also useful in destructuring the Action. 
```ts
@Action(AddUser)
addUser(
    { getState, setState, dispatch }: StateContext<ConfigStateModel>,
    { user }: AddUser,
) {
...
}
```

## Environment

<pre><code>
Libs:
- @angular/core version: any
- @ngxs/logger-plugin version: 3.3.4

Browser:
- [ x ] Chrome (desktop) version 72
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by markwhitfeld** [comment]
The fix has been released in v3.4.3!
