### ISSUE TITLE
Updated state is correct from patchState() but not in final state.

### ISSUE THREAD

**Issue by JaronrH** [ngxs/store#874]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm not sure if this is just an issue with how I'm doing things but here it goes!  Right now, I'm trying to update a nested interface that is defined as EventType (TS Enum) -> Id (number) -> Params (any):
<pre><code>export interface NotificationsModel {
    events: {[type: string]: {[id: number]: any}};
}
</code></pre>
_When I try to patch the state, it only updates the first level._

If I pass in what essentially amounts to:
<pre><code>events: {
    testEvent: {
        1: {}
    }
}
</code></pre>
...the state only updates through the first level:
<pre><code>events: {
    testEvent: {}
}
</code></pre>

However, capturing the output of patchState, it does show the correct state!
<pre><code>notifications: 
    events: testEvent: 
        1:
             __proto__: Object
        __proto__: Object
    __proto__: Object
__proto__: Object
</code></pre>

## Expected behavior

I expected the output of patchState to be reflected in the final state.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-x2azqx

Clicking subscribe should update the state with type and id (state shown in the output) but it fails to completely update.  Output of pathState() is show in the debug console.

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.6
- @ngxs/store version: 3.3.4

Browser:
- [x] Chrome (desktop) version 72.0.3626.109 (Official Build) (64-bit)
- [x] Firefox version 65.0.1 (64-bit)

**Comment by splincode** [comment]
https://github.com/ngxs/store/issues/827

![image](https://user-images.githubusercontent.com/12021443/53757308-66c5cb80-3ecc-11e9-9cbb-c81d5fb4470d.png)

**Comment by JaronrH** [comment]
I saw that v4 would be changing the signature to void but that doesn't change the fact that the state patchState() was outputting is the correct and expected state while the final state NGXS was producing is **not** correct!

**Comment by splincode** [comment]
in fact, your code really needs refactoring

I can recommend you for now patch operators
https://medium.com/ngxs/ngxs-state-operators-8b339641b220

I do not quite understand your structure and data model, so if you want to make patches, you can try this plugin

**Comment by JaronrH** [comment]
Don't feel it is necessary to fix for me, I've designed around it already!  Was still surprised that the state was not updated which is why I threw together that nasty demo just to show the issue.

I do really like that new plugin!  That will make things much easier!
