### ISSUE TITLE
Add types to createSelector & select functions

### ISSUE THREAD

**Issue by Aracturat** [ngxs/store#875]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
I can use two ways to create selector for something: ``@Selector`` & ``createSelector.``
When I use Selector, compiler can infer result type in store.select* functions.
In the case of createSelector types are missing.

## Expected behavior
The same type inference behavior when using ``@Selector`` & ``createSelector.``

## Minimal reproduction of the problem with instructions
```ts
import { createSelector, State, Selector, Store } from '@ngxs/store';
import { Observable } from 'rxjs';
import { Injectable } from '@angular/core';

export interface TestStateModel {
  prop: string;
}

@State<TestStateModel>({
  name: 'state',
  defaults: {
    prop: null
  }
})
export class TestState {

  @Selector()
  static prop(state: TestStateModel): string {
    return state.prop;
  }
}

export const selectProp = createSelector(
  [TestState],
  (state: TestStateModel) => state.prop
);


@Injectable()
export class TestService {

  propAttributeSelector: Observable<string>;
  propCreateSelector: Observable<string>;

  wrongPropAttributeSelector: Observable<number>;
  wrongPropCreateSelector: Observable<number>;

  constructor(private store: Store) {
    this.propAttributeSelector = store.select(TestState.prop);
    this.propCreateSelector = store.select(selectProp);

    this.wrongPropAttributeSelector = store.select(TestState.prop);
    this.wrongPropCreateSelector = store.select(selectProp);
  }
}
```
![screenshot_1](https://user-images.githubusercontent.com/1833101/53548202-86bf5d00-3b63-11e9-90af-e5cecd796a9e.png)
![screenshot_2](https://user-images.githubusercontent.com/1833101/53548203-86bf5d00-3b63-11e9-92fa-ada7a51be060.png)

## What is the motivation / use case for changing the behavior?
Types check during development.

## Environment
Libs:
- @angular/core version: 7.1.0
- @ngxs/store version: 3.3.4

**Comment by eranshmil** [comment]
Should be fixed in the next release.
For now, you can use the [@dev builds](https://ngxs.gitbook.io/ngxs/getting-started/installation#development-builds).

**Comment by markwhitfeld** [comment]
And now you can use the `@latest` build... v3.4 has just been released!
