### ISSUE TITLE
State Operators: removeItem missing from node_modules

### ISSUE THREAD

**Issue by digitalcraftco** [ngxs/store#877]
## I'm submitting a...
<pre><code>
[X] Other... Please describe: missing import for new state operator.
</code></pre>

## Current behavior
Cannot import removeItem operator from : `@ngxs/store/operators`.
After inspecting the node_modules folder I don't see remove-item.d.ts. The other operators are all there. 

`error TS2305: Module '"../../../../../../node_modules/@ngxs/store/operators/ngxs-store-operators"' has no exported member 'removeItem'.`

## Expected behavior
removeItem should be an exported member. Maybe NPM package has not been updated yet?

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.7
- @ngxs/store version: 3.4.0

**Comment by arturovt** [comment]
@digitalcraftco oh, you're right, thanks for issuing that!

**Comment by arturovt** [comment]
@digitalcraftco try 3.4.1

**Comment by digitalcraftco** [comment]
@arturovt Bingo! All good now. Thanks for the quick patch.
