### ISSUE TITLE
Action is called multiple times when a module is called by multiple routes (3.4.0 issues)

### ISSUE THREAD

**Issue by junimohano** [ngxs/store#883]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
Action is called multiple times when same modules which contains a feature state are called by different routes on lazy load.

## Expected behavior
Action needs to be called only one time even though same modules which contains a feature state are called by different routes on lazy load.

NGXS 3.3.4 is fine, only 3.4.0 has a issue.

## Minimal reproduction of the problem with instructions

[https://github.com/junimohano/reproduce-ngxs-bugs](https://github.com/junimohano/reproduce-ngxs-bugs)

* Navigate to Add page
* Click Open Alert button then it will show alert message
* Navigate to Edit page
* Click Open Alert button then it will show alert message two times (should be called one time).
* Navigate to Detail page
* Click Open Alert button then it will show alert message three times (should be called one time).

It is happened if a module has a feature state which is called by different routes on lazy load.

NGXS 3.3.4 is fine but 3.4.0 has issues.

## What is the motivation / use case for changing the behavior?
I updated ngxs 3.4.0 on my company project and found a bug during QA testing.

## Environment

Libs:
- @angular/core version: 7.2.0
- @ngxs/store version: 3.4.0

Browser:
- [x] Chrome (desktop) version 72.0.3626.121
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version 11.136
- [x] Edge version 44.17763.1.0

**Comment by splincode** [comment]
@junimohano Please describe according to the issue template.

# Current behavior 

# Expected behavior

----

**Comment by junimohano** [comment]
> @junimohano Please describe according to the issue template.
> 
> # Current behavior
> # Expected behavior

Updated

**Comment by splincode** [comment]
@junimohano I fixed the bug, now I will add tests and make a pull request

we will release the fix for 3.4.1

**Comment by splincode** [comment]
@junimohano try 3.4.1

**Comment by junimohano** [comment]
@splincode works, thanks

**Comment by dzhavat** [comment]
I experienced the same problem after updating to v3.4.0. Was actually preparing a demo to submit along with a new issue but I'm happy to see that you've already fixed it :) Good work. Thanks a lot! 👏 

Thanks to @junimohano as well for reporting it.
