### ISSUE TITLE
Add logger in store for debugging

### ISSUE THREAD

**Issue by splincode** [ngxs/store#885]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

If a regression occurs, it is not clear how to fix

## Expected behavior

```ts
NgxsModule.forRoot([ ... ], {
 logLevel: NgxsLogLevel.TRACE // Default NgxsLogLevel.OFF
})
```
Shows everything that happens

**Comment by kuhnroyal** [comment]
Try https://ngxs.gitbook.io/ngxs/plugins/logger

**Comment by splincode** [comment]
You did not understand my message a little. This plugin is needed for users.

Logger is needed for internal development, so that I can always understand which calls are made before building the state graph. recently we got regression and it was hard enough to catch this problem.

**Comment by markwhitfeld** [comment]
I would like to approach solving this through introducing general extensibility hooks (you missed the conversation in the team meeting) and then this could be introduced through extension.
I'm wanting to make sure that we keep our bundle size down and adding trace stuff everywhere could add quite a bit of code not necessary for production.
Let's keep this issue open until we can solve this.
