### ISSUE TITLE
Support select lazy state from root

### ISSUE THREAD

**Issue by splincode** [ngxs/store#886]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/12021443/53683503-8c0eda00-3d12-11e9-9e4c-630e8cad0ee9.png)

If TestState is initialized after, we cannot subscribe to it right away.

**Comment by markwhitfeld** [comment]
Could you add a stackblitz to reproduce the issue?

**Comment by arturovt** [comment]
@splincode do we close this or you will add a reproduce?
