### ISSUE TITLE
Documentation Development Builds npm scripts questions

### ISSUE THREAD

**Issue by rluvaton** [ngxs/store#889]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Question
On [Documentation - Installation - Development Builds](https://ngxs.gitbook.io/ngxs/getting-started/installation#development-builds) there are these commands to install for the development
shouldn't it need to be `--save-dev` instead?
```
npm install @ngxs/store@dev --save
npm install @ngxs/logger-plugin@dev --save
```

**Comment by YogliB** [comment]
@rluvaton 
When installing npm packages, aside from choosing between installing them as regular/dev dependencies you can choose the version you want to install, for example:
```
npm install @ngxs/store@3.3.0 // Will install v3.3.0
npm install @ngxs/store@latest // Will install latest stable version (currently v3.4.1)
npm install @ngxs/store@dev // Will install latest development version (currently v3.4.1-dev.master-ab0a0cc
)
```

You can see all the version [here](https://www.npmjs.com/package/@ngxs/store?activeTab=versions).
