### ISSUE TITLE
Proposal @ngxs/store/decorators

### ISSUE THREAD

**Issue by splincode** [ngxs/store#892]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Expected behavior

Refactor decorators: `Select, Selector`

Add new decorators for Public API:

```ts
import { BindAction, Action, Dispatch } from '@ngxs/store/decorators';

@State({ .. })
export class MyState {

  @BindAction() 
  private static incrementAction(payload: number) {
   return payload;
  }

  @Dispatch()
  public increment(value: number) {
    return MyState.incrementAction(payload);
  }
 
  @Action(MyState.incrementAction)
  public incrementByState(ctx: StateContext, { payload }: BindActionType<number>) {
    ctx.setState(payload);
  }

}
```

```ts
import { BindAction, Action, Dispatch } from '@ngxs/store/decorators';

@Component({ 
  template: `
   <button (click)="state.increment()">+1</button>
  `
})
export class MyComponent {
 constructor(state: MyState) { }
}
```

**Comment by markwhitfeld** [comment]
`@BindAction` and `@Dispatch` should remain outside of the core lib in my opinion.

**Comment by splincode** [comment]
You are right
