### ISSUE TITLE
[Router plugin] - Feature request - state selector generic

### ISSUE THREAD

**Issue by beagleknight** [ngxs/store#893]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am using a custom `RouterStateSerializer` that includes `url`, `params` and `queryParams`. After upgrading from ngxs 3.3.4 to 3.4.1 both `select` and `selectSnapshot` returns a `RouterState` type like this:

```typescript
// This is an error in 3.4.1 but works fine in 3.3.4
const { queryParams } = this.store.selectSnapshot(RouterState.state);
```

The reason behind this is the current implementation of the `RouterState.state` returns a `RouterStateModel` type and by default it includes a `state` member of type `RouterStateSnapshot` that doesn't include the `queryParams`.

## Expected behavior

If I have a custom `RouterStateSerializer` that serializes the state to this:

```typescript
export interface RouterStateParams {
  url: string;
  params: Params;
  queryParams: Params;
}
```

I expect the following code to work:
```typescript
const { queryParams } = this.store.selectSnapshot(state => RouterState.state<RouterStateParams>(state));
```

## What is the motivation / use case for changing the behavior?

Using a custom `RouterStateSerializer` I don't have the advantage of the type system when selecting the router's state. The current work around is using this ugly code:

```typescript
const { queryParams } = this.store.selectSnapshot(RouterState.state) as unknown as RouterStateParams;
```

## Environment

<pre><code>
Libs:
- @angular/core version: X.Y.Z
- @ngxs/store version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by beagleknight** [comment]
I am trying to implement this myself here: https://github.com/codegram/store/tree/feat/state-selector-generic

I wrote the necessary code and an additional test but I am unable to make the test pass 😞 

```typescript
describe('with custom serializer', () => {
    it('should select custom router state ', fakeAsync(async () => {
      interface RouterStateParams {
        queryParams: Params;
      }

      class CustomRouterStateSerializer implements RouterStateSerializer<RouterStateParams> {
        serialize(state: RouterStateSnapshot): RouterStateParams {
          const {
            root: { queryParams }
          } = state;
          return { queryParams };
        }
      }

      createTestModule({
        providers: [{ provide: RouterStateSerializer, useClass: CustomRouterStateSerializer }]
      });

      const router: Router = TestBed.get(Router);
      const store: Store = TestBed.get(Store);

      await router.navigateByUrl('/testpath?foo=bar');
      tick();

      const routerState = store.selectSnapshot(state =>
        RouterState.state<RouterStateParams>(state)
      )!;
      expect(routerState.queryParams.foo).toEqual('bar');
    }));
  });
```

The error is the following:

```bash
      Error: Uncaught (in promise): TypeError: Cannot read property 'queryParams' of undefined
      TypeError: Cannot read property 'queryParams' of undefined
          at Object.<anonymous> (router-plugin/tests/router.plugin.spec.ts:109:26)
```

It looks like the custom serializer is not being used.

**Comment by beagleknight** [comment]
I managed to fix the problem with my spec and created a pull request https://github.com/ngxs/store/pull/894

I am not sure if this can be improved or not:

```typescript
store.select(state => RouterState.state<RouterStateParams>(state.router))
```

I tried this but the compiler rejects it:

```typescript
store.select(RouterState.state<RouterStateParams>)
```

**Comment by splincode** [comment]
fixed
