### ISSUE TITLE
🚀[FEATURE]: Proposal for ngxs/storage-plugin

### ISSUE THREAD

**Issue by splincode** [ngxs/store#896]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

```ts
@State({
    name: 'filter',
    defaults: new Filter()
})
export class FilterState {
 // ..
}
```

not intuitive

```ts
NgxsStoragePluginModule.forRoot({ key: [..., 'filter'] })
```

## Expected behavior

```ts
import { PersistenceState } from '@ngxs/storage-plugin';

@State({
    name: 'filter',
    defaults: new Filter()
})
@PersistenceState()
export class FilterState {
 // ..
}
```

```ts
NgxsStoragePluginModule.forRoot()
```

## Full control flow for persist state

```ts
@PersistenceState({ name: 'key' })
@PersistenceState({ name: 'key', alias: 'keyAlias' })
@PersistenceState({ name: 'key', expiredTime: 100000 // ms })

@PersistenceState({ name: 'key', storage: 'localStorage' })
@PersistenceState({ name: 'key', storage: 'sessionStorage' })
@PersistenceState({ name: 'key', storage: 'indexDB' })
```

**Comment by YogliB** [comment]
@splincode 
I have a slightly related question, why not use localForage for the plugin?
It will enable IndexedDB by default and handle fallback when needed.

**Comment by splincode** [comment]
@YogliB hello, the problem is that we want to use several kinds of storages

**Comment by splincode** [comment]
https://www.npmjs.com/package/@ngxs-labs/data

**Comment by splincode** [comment]
I use ngxs data plugin for now
