### ISSUE TITLE
Question: How do I use effects with ngxs?

### ISSUE THREAD

**Issue by goodmite** [ngxs/store#906]
Is there any example of using effects (like ngrx-effects) with this library. If yes, could you please provide the link? Thanks.

**Comment by splincode** [comment]
```( {NgRx}.reducer.ts + {NgRx}.effects.ts ) ≈ {NGXS}.state.ts```

I. NGRX

```ts
@Injectable()
export class MovieEffects {
 
  @Effect()
  loadMovies$ = this.actions$
    .pipe(
      ofType('[Movies Page] Load Movies'),
      mergeMap(() => this.moviesService.getAll()
        .pipe(
          map(movies => ({ type: '[Movies API] Movies Loaded Success', payload: movies })),
          catchError(() => EMPTY)
        ))
      )
    );
 
  constructor(
    private actions$: Actions,
    private moviesService: MoviesService
  ) {}
}
```

II. NGXS

```ts
@State({ .. })
export class MoviesState {
 
  constructor(private moviesService: MoviesService) {}

  @Action({ type: '[Movies Page] Load Movies' })
  public loadMovies(ctx: StateContext): void {
    return this.moviesService.getAll().pipe(
       map((values) => ctx.setState(values)),
       catchError(() => EMPTY)
    );
  } 
  
}
```

**Comment by goodmite** [comment]
@splincode thanks for your response. Isn't ```loadMovies``` a ```reducer```? If yes, isnt it supposed to be a pure function? Would be really great if you could explain this.

**Comment by arturovt** [comment]
@goodmite Reducers are not supposed to be pure functions. From the Redux specification - `Reducers specify how the application's state changes in response to actions sent to the store`. Redux is an architectural design pattern (more info at Dan's Abramov blog), but it has nothing to do with the single implementation, implementations can be different.

**Comment by splincode** [comment]
@goodmite 

NGRX != NGXS
NGRX != Redux (library in React)

Redux is a pattern, predictable state container. How this container will be arranged depends on the implementation.

**Comment by markwhitfeld** [comment]
@goodmite The closest thing in NGXS to NGRS Effects is Action Handlers. See the docs here:
https://ngxs.gitbook.io/ngxs/advanced/action-handlers
Note that you would have to subscribe and dispatch the resultant action.

Although this is possible it is not really the normal way to do it with NGXS.

**Comment by shivamd20** [comment]
> @goodmite
> 
> NGRX != NGXS
> NGRX != Redux (library in React)
> 
> Redux is a pattern, predictable state container. How this container will be arranged depends on the implementation.

The downside of not having pure functions as an action handler is that we cannot just replay the same actions to get the same state. 

In the first example of NGRX, you can see that if we dispatch two actions` [Movies Page] Load Movies ` and ` [Movies API] Movies Loaded Success ` then we will get the same state. But in NGXS, we can't just do it because our action handler will call the Rest Service end-point every time we dispatch an action.

**Comment by webia1** [comment]
Maybe that helps? 

**ngxs-effects**

Website: <https://github.com/vladborsh/ngxs-effects#readme>
Github: <https://github.com/vladborsh/ngxs-effects>
Npm: <https://www.npmjs.com/package/ngxs-effects>

**Comment by LucasFrecia** [comment]
@markwhitfeld check [this handy script](https://github.com/LucasFrecia/fedex-signup/blob/master/src/app/core/services/async-effects-handler.service.ts), it triggers actions based on action types and states. Usage I use it in the constructor of my .store files and it does the job well. Simple example:
```
* const dispatchedHandledActions = [FeatureArticlesGetListAction]; // load array with desired action to litsen to
 *
 * this.asyncEffectsService.setActionsEffect(
 *   dispatchedHandledActions, // effect will be triggered when this action reaches the desired state
 *   new AppShowProgressBarAction(), // Example action we want to trigger
 *   'Dispatched' // Tell setActionsEffect method in what state of the action the side effect should be triggered
 *  );
```
