### ISSUE TITLE
Proposal: improved user flow

### ISSUE THREAD

**Issue by splincode** [ngxs/store#909]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Expected behavior

```ts
@State({
 name: 'hello',
 ..
})
export class MyState {

   @Selector(MyState) public data$: Observable;
   @Context() private ctx: StateContext<string[]>;

   @BindAction()
   public addTodo(todo: string) {
    this.ctx.setState((state: string[]) => [...state, todo]);
   }

}
```

```ts
@Component({ .. })
class MyComponent {
  constructor(myState: MyState) {
  }
 
 public increment(todo: string) {
   this.myState.addTodo(ctx, todo);
 }

}
```

**Comment by poloagustin** [comment]
Doesn't this go a little bit against the structure of what a current ngxs project looks like?
All of a sudden you could end up with components having to inject all the states it needs to dispatch to instead of having a single service, the `Store` service 🤔 
It feels like you could achieve the same behavior right now having a singleton service with a state private member and each action is a method and each selector is a method that returns an observable.

```
@Injectable()
export class MyCustomStateService{
  private state = new BehaviorSubject<Todo[]>([]);
  todos(){
    return this.state;
  }
  increment(todo:Todo){
    this.state.next(this.state.concat([todo]));
  }
}
```

**Comment by deebloo** [comment]
At that point I don't see the benefit of using ngxs vs just a stateful service.

**Comment by splincode** [comment]
@poloagustin The problem is not in encapsulation, but in the boilerplate that we have when using NGXS or NGRX. That is, you need to use actions, it is not very convenient when we have a large application. 

We have a emitter plugin, but somehow faced with the fact that it is still difficult to develop.
https://github.com/ngxs-labs/emitter

**Comment by splincode** [comment]
I move this question here
https://github.com/ngxs-labs/emitter/issues/130

**Comment by markwhitfeld** [comment]
Not a fan of this approach either. It breaks state encapsulation and the decoupling that CQRS and Event Sourcing are trying to promote. Actions are a central concept in NGXS and not someting we would want to remove. They represent a clean and clear contract of communication within the system and are a valuable representation of the events within the domain.

This is why this approach is in the Emitter plugin, and not in core.

**Comment by markwhitfeld** [comment]
PS. The shared `ctx` would also cause problems for some of the things we will be doing for the debug stream. The `StateContext` represents the context for that particular `@Action` method invocation.
