### ISSUE TITLE
Server Side Pagination

### ISSUE THREAD

**Issue by jtan80813** [ngxs/store#911]
Hi! I just want to suggest to add server side pagination in your docs and also some examples.
Thanks @

**Comment by arturovt** [comment]
@jtan80813 Please use our [issue template](https://github.com/ngxs/store/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by markwhitfeld** [comment]
@jtan80813 What would you recommend that we could have that is not provided in the Angular Universal docs? https://angular.io/guide/universal

**Comment by jtan80813** [comment]
@markwhitfeld. Hi Mark.  I am sorry, but you’re mistaken server side pagination with server side rendering. What i meant is server side pagination of your data. The data is loaded per page. Please see the pic below of the json response of the server side data. Thanks Mark. 

![JSON](https://user-images.githubusercontent.com/35401535/54430075-5b409300-475d-11e9-8b36-35dcfb1e7c14.JPG)

**Comment by arturovt** [comment]
@markwhitfeld should we close this?

**Comment by splincode** [comment]
@jtan80813 As you understand, ngxs is responsible for storing the state and has nothing to do with managing the page pagination, I think it depends on your implementation.
