### ISSUE TITLE
Life-cycle events not triggered in root state

### ISSUE THREAD

**Issue by Koslun** [ngxs/store#917]
## I'm submitting a...

<pre><code>
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

1. Implement `NgxsOnInit` and `NgxsAfterBootstrap` in a state that is imported with root. In our case the state was `AuthState`:

```
 NgxsModule.forRoot(
      [
        AuthState,
        // follwed by three other states
      ],
      {
        developmentMode: !environment.production,
      }
    ),
// importing other plugins
// importing module with a NgxsModule.forFeature
```
2. Load the app

3. **Neither** life-cycle events are triggered.

## Expected behavior

Expecting life-cycle events to be triggered when loading the app at the specified timings described in the [documentation](https://ngxs.gitbook.io/ngxs/advanced/life-cycle).

This is still working in versions prior to `3.4.0` such as `3.3.4`. 

## Minimal reproduction of the problem with instructions
Was unable to reproduce in a minimal reproduction. So assuming it must be some edge-case to do with import order of NGXS modules similar to other issues: #539 and #375. The difference with this bug is that the life-cycle is called in a state initialized by `forRoot`.

Here is a more advanced version of the minimal demo that still emits life-cycle events: https://stackblitz.com/edit/ngxs-simple-k8i8y6

## What is the motivation / use case for changing the behavior?

Want to use life-cycle hooks to set authentication state.

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.7
- @ngxs/store version: 3.4.0/3.4.2
Also these plugins in-use:
```
    "@ngxs/devtools-plugin": "3.4.2",
    "@ngxs/logger-plugin": "3.4.2",
    "@ngxs/router-plugin": "3.4.2",
    "@ngxs/storage-plugin": "3.4.2",
```

Browser:
- [ x ] Chrome (desktop) version 73
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3  
- Platform:  Windows and Mac 

Others:

</code></pre>

**Comment by markwhitfeld** [comment]
I often find that if someone is unable to reproduce the issue in a stackblitz then the issue is someting they have missed in the largeness of their application.
Really interested to get to the bottom of this!
Could you do some debugging for us?
Maybe trim down your module imports one by one until the issue goes away or is at least isolated to a smaller scope.

**Comment by Koslun** [comment]
@markwhitfeld yeah, I will try to find the time to isolate this further in our own code. Hopefully later this weekend.

**Comment by sroettering** [comment]
In two of our Apps the ngxsOnInit life cycle hook is not called in feature states either. This worked with 3.4.0 (and maybe some later version too) and we are importing the feature modules in the correct order.
We are using v3.4.3 for store, devtools-plugin, form-plugin and storage-plugin.

**Comment by splincode** [comment]
https://github.com/ngxs/store/blob/master/packages/store/src/internal/lifecycle-state-manager.ts#L25

**Comment by splincode** [comment]
@sroettering 
![image](https://user-images.githubusercontent.com/12021443/54744439-0e830f00-4bd8-11e9-8ff5-a5213f039906.png)

**Comment by sroettering** [comment]
@splincode can you elaborate on how the code in your screenshot is related to the life cycle method not being called when a stored value was loaded?

**Comment by paullryan** [comment]
I got this to repeat when I had the forFeature state in the forRoot of the NgxsStoragePluginModule. When it's not in that module the ngxsOnInit calls just fine, but when it's listed in the storage plugin it doesn't. I wonder if there's something similar blocking other bootstrap patterns.

**Comment by paulstelzer** [comment]
I can confirm this issue. I am using ngxs storage and forFeature. If the State is in storage, no ngxsoninit / onbootstrap is called, but if it's not, then everything works.

**Comment by splincode** [comment]
@paulstelzer can you create example app for reproduce?

**Comment by paulstelzer** [comment]
@splincode I could create a example app to reproduce -> https://github.com/paulstelzer/ngxs-issue

Inside app.module.ts you find integratin of Ngxs and LanguageModule. LanguageModule is packed with ngpackagr (source code -> https://github.com/paulstelzer/innomobile-library/tree/master/libs/%40innomobile/language). That's the language state -> https://github.com/paulstelzer/innomobile-library/blob/master/libs/%40innomobile/language/src/lib/state/language.state.ts

As you can see inside ngxsoninit normally the default language will be set, If you serve the page for the first time instead of "HOME.TITLE" you will see the correct translated string. The second time you will see "HOME.TITLE". The reason: ngxsOnInit is not called this time

If you remove NgxsStoragePluginModule.forRoot() in app.module.ts everything is working again

**Comment by paullryan** [comment]
@splincode I made a stackblitz at https://stackblitz.com/edit/ngxs-issue-917?file=app%2Fapp.module.ts to help with troubleshooting. Just comment out the storage plugin in app module to it work as intended.

**Comment by splincode** [comment]
@paullryan 
![image](https://user-images.githubusercontent.com/12021443/55736775-abdda000-5a2c-11e9-8e61-e16d8538123f.png)

I did not notice the changes as commented out

**Comment by splincode** [comment]
Oh, I see

Before

![image](https://user-images.githubusercontent.com/12021443/55737082-3aeab800-5a2d-11e9-8e6d-bb31ef3338a8.png)

After

![image](https://user-images.githubusercontent.com/12021443/55737113-4938d400-5a2d-11e9-94a8-98ce993a181c.png)

**Comment by paulstelzer** [comment]
Any news about this @splincode ?

**Comment by splincode** [comment]
While I can not fix it, but I still hope to fix it soon

**Comment by P-de-Jong** [comment]
This issue is preventing us from upgrading 😢

**Comment by Veetaha** [comment]
Waiting for fix ☕☕☕

**Comment by splincode** [comment]
@paullryan I updated on Angular 7 and can not reproduce the error

**Comment by Veetaha** [comment]
@splincode I tried to reproduce this on `StackBlitz`, but surprisingly it works there but not on my local notebook. [Here is the link to stackblitz](https://stackblitz.com/edit/ngxs-store-lifecycle-bug-report), the code there is almost identical to mine. [Here is the code I am trying to run on my machine](https://github.com/Veetaha/ngxs-storage-plugin-lifecycle-bug).

**Comment by paulstelzer** [comment]
@splincode Just use my example -> https://github.com/ngxs/store/issues/917#issuecomment-480567098 (it's not using stackblitz) and there you can reproduce it (the example is using Angular 7)

**Comment by splincode** [comment]
@Veetaha @paulstelzer Yes, I was able to reproduce the bug, this is really a storage plugin problem.

**Comment by Veetaha** [comment]
As a temporary workaround, you may move your `ngxsOnInit()` logic to the method adorned with `@Action(UpdateState)` imported from `@ngxs/store`

**Comment by paullryan** [comment]
Interesting that it stopped being an issue on the blitz as I'm also still seeing it in projects with angular 7. So definitely still an issue. I wonder if you need to clear your localstorage for the blitz example @splincode. I've noticed if you get it to play nice by removing the storage plugin then add it back it appears to be working but that's only because it's already in the proper state.

**Comment by splincode** [comment]
@paullryan @Veetaha @paulstelzer @Koslun @P-de-Jong @sroettering @markwhitfeld 
The bug has been fixed and is awaiting approval. We plan to release version 3.5.0 as soon as possible.

**Comment by P-de-Jong** [comment]
@splincode Great! When it's released, I will upgrade and check if everything works as expected 👍

**Comment by paullryan** [comment]
Great thank you @splincode, looking forward to testing it.

**Comment by splincode** [comment]
@paullryan @Veetaha @paulstelzer @Koslun @P-de-Jong @sroettering Guys, please check out the latest changes before release!

```
$ npm install @ngxs/store@dev
```

**Comment by paulstelzer** [comment]
@splincode it's working for me - good job

**Comment by splincode** [comment]
@markwhitfeld thank's for help me

**Comment by jbjhjm** [comment]
@splincode Working fine for me thanks!

**Comment by paullryan** [comment]
LGTM

**Comment by arturovt** [comment]
Thanks @splincode for this amazing fix :tada: :tada:

**Comment by Koslun** [comment]
Working for us as well! 🎉 🎉

Thanks to all the contributors for all the hard work!

Guessing we keep the issue open until the PR is released to a stable version?

**Comment by splincode** [comment]
@Koslun yes)

**Comment by Koslun** [comment]
The fix has now been added to a stable release, version 3.5.0.
