### ISSUE TITLE
Add typings definition tests to the test suite

### ISSUE THREAD

**Issue by markwhitfeld** [ngxs/store#925]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
With virtually every PR recently that has tried to improve typings in the library recently there have been unforseen regressions (one even got through the review process that we had to fix very shortly after the v3.4.0 release).

We need to make the expectations around the public interface of the library explicit in tests because this is the area most likely to break user code if we are not careful.

## Expected behavior
We need to have a suite of tests that test the public interface of the library and includes examples of what is valid and what is invalid with regard to types. This can't be done with the normal karma/jasmine tests, so we need to use something specifically targeted to testing the typings.

Microsoft released a lib that seems to fit the bill nicely:
https://github.com/Microsoft/dtslint

Walkthrough post here: https://hackernoon.com/testing-types-an-introduction-to-dtslint-b178f9b18ac8

**Note: We need to create a comprehensive test suite in this regard before we can reasonably look at accepting any PR to improve typing.**
Not sure all that this lib offers, but it would be great if we could run these tests for all versions of ts that we support too! ... not a deal breaker, but would be nice.

**Comment by splincode** [comment]
https://medium.com/palantir/tslint-in-2019-1a144c2317a9

tslint deprecated

**Comment by markwhitfeld** [comment]
This is not related to tslint... it is dtslint, a tool for testing typings.
When you test typings you need to equally check what does and what doesn't work as part of the typings. Traditional testing approaches can't do this, hence the need for a library like the above.

**Comment by splincode** [comment]
already added
