### ISSUE TITLE
Default execution strategy is not performant with many Selecting components

### ISSUE THREAD

**Issue by pcurrivan** [ngxs/store#933]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

This is related to https://github.com/ngxs/store/issues/739
With many Selecting components, using the default execution strategy (actions run outside zone), change detection is spammed if an action calls an async function.  It looks like *each* component triggers an ApplicationRef.tick, which checks *every* component.

## Expected behavior

Change detection should not be spammed.  A single ApplicationRef.tick should be enough to update all selecting components.

## Minimal reproduction of the problem with instructions
I made a demo with a configurable number of simple counter components.  There are two actions.  One calls an async function before incrementing the counter, while the other increments synchronously.  
https://stackblitz.com/edit/angular-tv7or5?file=src%2Fapp%2Fapp.component.ts

With the default execution strategy, the time to finish the async increment action scales with the square of the number of components.  200 components takes 500ms, 800 components takes 4400ms, 1600 components takes 26000ms.  The synchronous action is always fast.
https://angular-tv7or5.stackblitz.io

With the NoopNgxsExecutionStrategy both actions are always fast.
https://angular-c6lstn.stackblitz.io

## What is the motivation / use case for changing the behavior?

Concrete use case: We have a grid consisting of a large number of components.  A related action was hanging the app for up to 30 seconds.  Taking the async call out of the action removed the issue.

It seems like our choice is to either use NoopNgxsExecutionStrategy, or remove async calls from our actions.  Is there a reason we would not want to use the NoopNgxsExecutionStrategy?

## Environment

<pre><code>
Libs:
- @angular/core version: 7.2.7
- @ngxs/store version: 3.4.0

**Comment by arturovt** [comment]
Hello, @pcurrivan
Thanks for the interesting issue! By the way, I've started investigating and came to the conclusion that it was also slow in earlier versions, before we have had these strategies.

**Comment by arturovt** [comment]
So I did a lot of investigation.

---

The first thing I did was downgrading the NGXS version just to check whether it's related to execution strategies. I observed the same behavior. So basically this is not related to execution strategies. This is related to the initial design decision of the NGXS.

---

The second thing is "why would we want to produce subscriptions in all our components?". Imagine that we have 2000 components. They've got the same prototype, let it be something like:

```html
<app-grid *ngFor="let something of (array of 2000 items)"></app-grid>
```

If we subscribe separately in each component then we'll get 2000 instances of `Subscriber|Subscription` classes that also require some memory allocation.

IMHO we could do that much better:

```ts
@Component({
  template: `
    <app-grid *ngFor="let item of (2000 items)" [grid]="grid"></app-grid>
  `
})
export class ParentComponent implements OnInit, OnDestroy {
  grid: Grid;

  private grid$ = this.store.select<Grid>(GridState.getGrid);

  private destroy$ = new Subject<void>();

  constructor(private ref: ChangeDetectorRef, private store: Store) {}

  ngOnInit(): void {
    this.grid$.pipe(takeUntil(this.destroy$)).subscribe(grid => {
      this.grid = grid;
      this.ref.markForCheck();
    });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}
```

---

I do not offer some best practice. There are no best practices, only trade-offs. This is one of the workarounds. I guess it's a bit late answer and you've already solved your problem.

---

> Is there a reason we would not want to use the NoopNgxsExecutionStrategy

With the default execution strategy action handlers are invoked outside of the Angular zone:

```ts
@Action(IncrementAsync)
increment(ctx: StateContext<number>) {
  console.log(NgZone.isInAngularZone()); // false
  return timer(0).pipe(
    tap(() => {
      ctx.setState(counter => counter += 1)
    })
  )
}
```

With the use of the `NoopNgxsExecutionStrategy` NGXS will not produce any checks inside action handlers and will invoke them inside the Angular zone, thus this will log `true`:

```ts
console.log(NgZone.isInAngularZone()); // true
```

Closing this as "not an issue". Mention me here if you've got any questions.
