### ISSUE TITLE
Auth Recipe Code Block Syntax

### ISSUE THREAD

**Issue by JoshAaronLevy** [ngxs/store#935]
## I'm submitting a...
<pre><code>
[x] Bug report  
</code></pre>

## Current behavior
Auth recipe contains code block with syntax error. Submitting PR with fix.

## What is the motivation / use case for changing the behavior?
Just an update to the awesome recipe docs on the site.

<pre><code>
Libs:
- @angular/core version: 7.2.0
- @ngxs/store version: 3.3.2
</code></pre>

**Comment by splincode** [comment]
can you properly describe the problem?
