### ISSUE TITLE
[Regression] No route snapshot provided by the Router Plugin in version 3.4.3

### ISSUE THREAD

**Issue by catchshyam** [ngxs/store#946]
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
I am using the Router Plugin and here is the selectorI have to get the active route,

>   @Selector([RouterState.state])
>     static getActiveRoute(stateModel: AppStateModel, route: RouterStateSnapshot): ActivatedRouteSnapshot {
>         console.log('Snapshot provided by the router state  ', route);
>         let state: ActivatedRouteSnapshot = route.root;
>         while (state.firstChild) {
>             state = state.firstChild;
>         }
>         return state;
>     }
> 

Until 3.4.1, I would get the route object in the console statement above. In 3.4.3, the route object injected by RouterState is undefined.

## Expected behavior
The RouterState must provide the actual snapshot.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/ngxs-router-plugin-bug
 - Launch the application and click on the hyperlink "Click me and See the console". 
 - See the debug message in the console "Snapshot provided by the router state
undefined"
 - If you change the NGXS and router plugin version to 3.4.1 in package.json, application outputs the correct object in the debug message.

## Environment

<pre><code>
Libs:
- @angular/core version: ^7.2.5
- @ngxs/store version: 3.4.3
- @ngxs/router-plugin version: 3.4.3

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by arturovt** [comment]
@catchshyam 
Hello. Yes, we're working on that.

**Comment by markwhitfeld** [comment]
This should be fixed in the latest `@dev` version.
Please could you test it out and let us know if it fixes your problem?

**Comment by arturovt** [comment]
@catchshyam 
We would really appreciate your regression feedback

**Comment by splincode** [comment]
Released in 3.5.0
