### ISSUE TITLE
Let websocket preflight be intercepted by HttpInterceptors

### ISSUE THREAD

**Issue by lamba92** [ngxs/store#947]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

## What is the motivation / use case for changing the behavior?

Websocket authentication is a widely requested feature. Letting the preflight be intercepted easily allows to adds tokens as in any http request.

**Comment by splincode** [comment]
Show me more details your proposal

**Comment by lamba92** [comment]
I'll try by explaining my use case.
I'm building an http server using [Ktor](https://ktor.io/) which serves an Angular page at `/` while serving man endpoints under `api/`, few of those are websockets. The authentication, for both on client and server, is handled by intercepting any http request which url starts with `api/` and checking if has the right header with the right token, which at the moment happens to be a Basic Auth header. 

Now, Ktor http server does not distinguishes between non-websocket-http request and http request ence the check for the header is seamless. On the other hand, Angular http client does not handle websockets, which means no `HTTP_INTERCEPTORS` will intercept and authenticate them; furthermore the only standardized auth method for websocket preflight is the Basic Auth which happens to be implemented by adding `username:password@` into the url (which is horrible at least).

Allowing to intercept your library websocket's preflight would elegantly solve this issue by leveraging the authentication to the preflight, which would be handled as any other http request.

I am no frontend expert since that's my first frontend project, but my guess is that you cannot use exactly the same `HTTP_INTERCEPTORS` provider. You may indeed could provide something like a `WS_HTTP_INTERCEPTORS` which uses the same `HttpInterceptor` interface so that once you implemented the logic in your service once you just need to use provide it once for the stock angular interceptor and once for your WS interceptor.

**Comment by ahnpnl** [comment]
I also think the same way to find a way to intercept ws request or ws response but couldn't find any documentations regarding to that in general. Since ws works differently comparing to http so probably the same concepts from http can't be applied all to ws

**Comment by lamba92** [comment]
Yeah, I googled around and found out that the WS specifications say that you should be able to add headers in the http preflight, but browsers deliberately chose not to. Lately Chrome and Opera allowed to implement Basic Auth, but that's it. 
I hope browsers will allow the possibility to customize headers soon instead of forcing to reinvent authentication through sockets.
