### ISSUE TITLE
Mock return of store.select in component unit test

### ISSUE THREAD

**Issue by AngeloETH** [ngxs/store#950]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

component.spec.ts

```
describe('MyComponent', () => {
  let store: Store;
  let component: MyComponent;
  let fixture: ComponentFixture<MyComponent>;

  @State<MyStateModel>({
    name: 'MyState',
    defaults: {
      myStates: {
        [TESTING_ID]: <SingleMyState>{
          status: 'status',
        }
      },
    }
  })
  class MyState {
    static getStatus(id: string): () => { } {
      const selector = createSelector([MyState], (state: MyStateModel) => {
           return state.MyState.myStates[TESTING_ID].status ;
     })
    }
  }
  
   beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [ MatCardModule ],
      declarations: [MyComponent ],
      providers: [ Store ],
    })
    .compileComponents();
  }));

  beforeEach(() => {
    store = TestBed.get(Store);
    const selected = MyState.getStatus(TESTING_ID);
    console.log(selected);
    fixture = TestBed.createComponent(MyComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });
  
  it('should create store', () => {
    expect(store).toBeTruthy();
  });
})
```

## Expected behavior

Expected log print 'status',  which is assigned to `state.MyState.myStates[TESTING_ID].status`.
In th ngOnInit of MyComponent, Jest executes ngOnInit and get error of following snapshot `this.store.select(MyState.getStatus(TESTING_ID)).pipe(...)`
 gets undefined of pipe. 
## What is the motivation / use case for changing the behavior?

Mocking the return observable of  `this.store.select(MyState.getStatus(TESTING_ID))` so that I can test my component

## Environment

<pre><code>
Libs:
- @angular/core version: X.Y.Z
- @ngxs/store version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.12.0  
- Platform:  

Others:

</code></pre>

**Comment by arturovt** [comment]
@AngeloETH 

Could you describe more clearly what would you like to achieve? I see that you don't return anything in the `static getStatus` method, that's why you're getting `undefined`.

**Comment by arturovt** [comment]
Closing this as inactive. Needs reproduction on the stackblitz or github repo. Currency `static getStatus` doesn't return selector that's what embarrasses me.
